facebook/AsyncDisplayKit

AsyncDisplayKit/Details/_ASDisplayView.mm
Currently we miss calling `-[super touches*]` on `_ASDisplayView` touch events. We delegate handling to the node which then forwards all touch events to the *superview*, skipping the current view. This seems to have some side effects with `UITableView` and it's cells/content views.
fixes #188
=> Call touch methods on _ASDisplayView super

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Details/_ASDisplayView.mm, AsyncDisplayKit/Private/ASDisplayNodeInternal.h
`_ASDisplayView` now forwards touch events to either super or it's node, depending on whether or not the node implements the methods.
fixes #199
=> Forward touch events to either the node or super

AsyncDisplayKit/Details/ASFlowLayoutController.mm
The cur.first may out of boundary in the case for all empty sections
=> Fix crash in Flow Controller

AsyncDisplayKit/Details/ASDataController.mm
`rowsInSection` needs to be called with the correct section index. Otherwise crashes occur in multi sectioned collection views (and I expect table views too).
=> Make ASDataController call rowsInSection with the appropriate index

AsyncDisplayKit/ASDisplayNode.h, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Private/ASDisplayNodeInternal.h, AsyncDisplayKitTests/ASDisplayNodeTests.m
ASBridgeNode is a node that that wraps a UIView that you want to embed in a view hierarchy created by ASDK. Sometimes a view can't be constructed with `-[initWithViewClass:]` but you want to use it with ASDK.
The API is meant to preserve ASDisplayNode's behavior, so you can still construct and set properties on the node on a background queue before its view is loaded; even though the view was created a priori, it is not considered to be loaded until `node.view` is accessed.
Using ASBridgeNode looks like this:
// Main queue:
UIButton *button = [UIButton buttonWithType:UIButtonTypeSystem];
[button sizeToFit];
CGRect buttonFrame = button.frame;
dispatch_async(backgroundQueue, ^{
ASDisplayNode *node = [ASBridgeNode alloc] initWithView:button];
// Use `node` as you normally would...
node.frame …
=> ASBridgeNode: wrapper around an existing UIView with ASDisplayNode semantics

AsyncDisplayKit/ASMultiplexImageNode.h, AsyncDisplayKit/ASMultiplexImageNode.mm
A hopefully better attempt at #159.
I went for the easy route and just kept track of the failed image identifier. The logic that determines which image to load next was updated to consider the failed identifier before using the last loaded identifier.
=> Let ASMultiplexImageNode skip failed image identifiers

AsyncDisplayKit/ASEditableTextNode.mm, AsyncDisplayKit/Details/ASTextNodeRenderer.mm, AsyncDisplayKit/Details/ASTextNodeTextKitHelpers.h, AsyncDisplayKit/Details/ASTextNodeTextKitHelpers.mm, AsyncDisplayKitTests/ASTextNodeWordKernerTests.mm
ARC doesn't play nicely with structs that contain references to
Objective-C objects, which causes breakage when using AsyncDisplayKit as
a dynamic framework (e.g., with CocoaPods 0.36+).  Fixes #198.
=> Convert ASTextKitComponents to an object.

AsyncDisplayKit/Details/ASRangeController.mm
=> Bail display if parent nodes raster children

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/ASControlNode.m, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKitTests/ASControlNodeTests.m
Set a build setting so that ASDK compiles "extension-safe".
We've removed calls to `-[UIApplication sharedApplication]` which is banned in extensions. Instead, we fall back on the plain ol' responder chain to handle `ASControlNode` events.
This PR also includes some basic tests to account for event propagation for control nodes, as well as minor semantics with what the actual `-[ASDisplayNode nextResponder]` (a private method) is.
fixes #98
=> Compile for extensions

AsyncDisplayKit/ASTextNode.h, AsyncDisplayKit/ASTextNode.mm, AsyncDisplayKit/Details/ASTextNodeRenderer.h, AsyncDisplayKit/Details/ASTextNodeRenderer.mm, AsyncDisplayKitTests/ASTextNodeRendererTests.m
Per #243 and #152, here's the implementation.
I'd followed the naming conventions in `ASTextNode` rather than naming the property `maximumNumberOfLines` to match the property on `NSTextContainer`.
=> Add maximumLineCount to ASTextNode

AsyncDisplayKit/ASControlNode.m
Tested with custom `ASTextNode` subclass. No targets added, but tracking events are still received upon touches.
fixes #268
=> Track control node touches

AsyncDisplayKit/ASTableViewProtocols.h
Might as well make ASTableView's support for this method explicit.
It was introduced in iOS 8 but I don't think there's a need to gate it with an `#ifdef`. It'll simply never get called on iOS 7.
=> Add -tableView:editActionsForRowAtIndexPath: to ASCommonTableViewDelegate

AsyncDisplayKit/ASControlNode.m
Summary: `weakToStrong` where the keys are NSNumbers that aren't strongly held by anyone means the events in the table get removed almost immediately. 
Test Plan: Confirm that events are not dropped from the table after they're added. 
Differential Revision: https://phabricator.fb.com/D1819759
=> Fix ASControlNode Event Dispatch Table Memory Semantics

AsyncDisplayKit/ASCollectionView.h, AsyncDisplayKit/ASTableView.h
Small adjustment to make the delegates ASTableView and ASCollectionView send back the right types.
=> Use specific types for Collection/TableView async delegate params

AsyncDisplayKit/ASMultiplexImageNode.h, AsyncDisplayKit/ASMultiplexImageNode.mm
Reverts facebook/AsyncDisplayKit#228 (cc @andyscott) — it introduced a bug where, if the best image identifier is unavailable (e.g., 404 error), ASMultiplexImageNode infinite-loops in an attempt to load it.
=> Revert "Let ASMultiplexImageNode skip failed image identifiers"

AsyncDisplayKit/ASImageNode.mm
fixes #298
Side note: should we document this behavior somewhere? I get that the change broke some builds, but should we note anywhere that `ASImageNode` is **not** opaque by default?
I ask because we document that `ASDisplayNode` is opaque [here](https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASDisplayNode.h#L452).
=> ASImageNode not opaque by default

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/ASControlNode.m, AsyncDisplayKitTests/ASControlNodeTests.m
Tested locally by adding a tap gesture to Kittens. Added unit tests to confirm that taps and gestures can work alongside each other. The unit test is limited to only testing that the target/action works since gestures are horribly un-unit-testable.
fixes #305
=> Allow all gestures through ASControlNode

AsyncDisplayKit/Details/ASDataController.mm
Per the bug report in https://github.com/facebook/AsyncDisplayKit/issues/321.
We should sort array before fetching data in batch.
=> Sort array before data fetching

AsyncDisplayKit/ASTextNode.mm
We were using the cached renderer even if the bounds differed from the constraining size as a performance optimization, and suggesting people measure instead when they need to for performance reasons, but this leads to some pretty broken layouts using simple reproduction code, as reported in https://github.com/facebook/AsyncDisplayKit/issues/89.
=> Fix text node positioning for non-left alignment

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/ASCollectionView.h, AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.h, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/Details/ASBatchContext.h, AsyncDisplayKit/Details/ASBatchContext.m, AsyncDisplayKit/Details/ASBatchContext.mm, AsyncDisplayKit/Details/ASBatchFetching.h, AsyncDisplayKit/Details/ASBatchFetching.m, AsyncDisplayKit/Details/ASLayoutController.h, AsyncDisplayKit/Details/ASScrollDirection.h, AsyncDisplayKitTests/ASBatchFetchingTests.m, examples/ASCollectionView/Sample/ViewController.m, examples/Kittens/Sample/ViewController.m
This PR introduces a new API for `ASTableView` and `ASCollectionView` to be notified when scrolling near the tail end of the available content. Notifications are limited to vertically scrolling near the bottom of `ASTableView`, and vertical and horizontal scrolling to the bottom and right, respectively, for `ASCollectionView`.
There are 2 new delegate methods for `ASTableView` and `ASCollectionView`:
- `-shouldBatchFetchForCollectionView:` returns a boolean to determine if a collection view should initiate the fetching process.
- `-collectionView:beginBatchFetchingWithContext:` is called when near the end of content.
`ASTableView`'s APIs are identical and differ only by classes and naming conventions.
The `ASBatchContext` object passed to `-collectionView:beginBatchFetchingWithContext:` …
=> Batch Fetching API

AsyncDisplayKit/Details/_ASDisplayView.mm
Summary:
What it says on the tin. This allows Nodes to effectively participate in the responder chain.
Caveat: see note in implementation below. Would have been nice to use `-targetForAction:withSender:` the way the docs imply you can, but alas.
Test Plan: Observe a node in the responder chain get invoked to handle an action it implements.
Differential Revision: https://phabricator.fb.com/D1894023
=> Support Forwarding Responder-Chain Actions to Node from its View

AsyncDisplayKit/Details/ASRangeController.mm, AsyncDisplayKit/Details/ASRangeHandlerRender.mm
This brings back the concept of a window store for nodes that are in the working range (reverting #127). It turns out that due to the system architecture if there are nodes who fetch remote content (e.g. `ASNetworkImageNode`), calls to `-display` will occur before fetching has been completed. The next chance the nodes have to decode and display content is then when they are actually on the screen, thus defeating the purpose of a working range.
With the reintroduction of the working range window, nodes are "stored" in the window and when content is finished being fetched, CA triggers `-display` since they are part of a view hierarchy.
This can be tested in the Kittens project by insuring that before `ASRangeController` adds a node to [a visible …
=> Working range window

AsyncDisplayKit/ASCollectionView.h, AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.h, AsyncDisplayKit/ASTableView.mm
Fixes #349.
(It's inelegant to require consumers to set an `asyncDelegate` even if it implements no methods; we could set a placeholder NSObject delegate ourselves, but in the case that an `asyncDelegate` is immediately set, we could conceivably run into race conditions in the accessibility subsystem.  This pull request is goofy, but probably the safest option for now.)
=> Remove the nil-asyncDelegate proxy.

AsyncDisplayKit/Details/ASRangeController.mm
In testing, I found that its possible for a node to skip the working range and go straight into the visible range. Typically this can happen if you scroll way to the bottom of a large collection and tap the status bar to go to the top. What happens is that the node was set to suspend display, but it was never enabled again. Thus the node is suspended until it enters the working range again.
=> Enable nodes entering the visible range to display

.travis.yml, build.sh, examples/ASCollectionView/Sample.xcodeproj/xcshareddata/xcschemes/Sample.xcscheme, examples/EditableText/Sample.xcodeproj/xcshareddata/xcschemes/Sample.xcscheme, examples/Kittens/Sample.xcodeproj/xcshareddata/xcschemes/Sample.xcscheme, examples/Multiplex/Sample.xcodeproj/xcshareddata/xcschemes/Sample.xcscheme, examples/Placeholders/Sample.xcodeproj/xcshareddata/xcschemes/Sample.xcscheme, examples/Swift/Sample.xcodeproj/xcshareddata/xcschemes/Sample.xcscheme
In addition to building & testing AsyncDisplayKit, this new build script
can ensure that all example projects still compile.  This will prevent
breaking API changes from landing without updating sample projects that
use them.  It's also extensible, so we can add additional integration
tests in future (e.g., non-CocoaPods framework integration).
=> [travis] New build script.

AsyncDisplayKit/ASTextNode.mm
Apply the fix from #329 to `-setFrame:`.  Fixes #89.
=> Fix ASTextNode positioning for non-left alignment, part deux.

AsyncDisplayKit/ASImageNode.h, AsyncDisplayKit/ASImageNode.mm
ASImageNodeTint is inflexible (your options are "no tint" and "use
`[UIColor grayColor]`") and needlessly complicates the ASImageNode
implementation.  Use ASImageNodeTintColorModificationBlock() instead.
Closes #383.
=> Remove ASImageNode's tint property.

AsyncDisplayKit/ASImageNode.mm
Speculative fix for #380.  Calling `-[ASImageNode setImage:]` on a
background queue will take the image lock, then trampoline to the main
queue to invalidate calculatedSize and set needsDisplay without
releasing the lock.  Any other method call that takes the image lock on
the main queue can block on the trampoline completing -- deadlock.
Note that the trampoline is itself a clowny workaround for thread
affinity (#134) and should be removed.  With this patch applied,
ASImageNode's `-setImage:` and `-calculateSizeThatFits:` can still race:
1.  -setImage changes _image, then trampolines to main
2.  -calculateSizeThatFits measures _image
3.  trampoline completes, invalidates calculated size
4.  ???
5.  ~~profit!~~ :boom:
=> Fix ASImageNode -measure: / -setImage: deadlock.

AsyncDisplayKit/ASTextNode.h, AsyncDisplayKit/ASTextNode.mm
Allows for long presses to be recognized as discrete actions without also triggering normal tap handling
=> Adds property for long press touch cancellation

AsyncDisplayKitTests/ASTextNodeWordKernerTests.mm
=> s/assign/strong/ on an object-typed ivar

examples/Kittens/Sample/ViewController.m
New kittens were being added before the last kitten instead of after it
because we weren't taking into account the first (header) row.
=> Add new kittens after last row

AsyncDisplayKit/ASControlNode.m
- addTarget:action:forControlEvents: should not retain the target. If it does
then there is a very high likelihood of a retain cycle.
=> Don’t retain an action’s target in ASControlNode

AsyncDisplayKit/ASCollectionView.h, AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.h, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/Details/ASDataController.h, AsyncDisplayKit/Details/ASDataController.mm
This PR adds an optional completion handler that is executed (on the main thread) once the async phase of `reloadData` has completed. This is a useful place to add code that needs to work with the rows & sections once they are live in the `ASTableView`/`ASCollectionView`. In my case I've used this to position my `ASTableView` using `scrollToRowAtIndexPath:atScrollPosition:animated:` 
There may be a better way to do this that I've missed. If so, I'd love to know about it. Thanks!!!
=> Add (optional) completion handler for ASTableView and AsCollectionView reloadData

AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.mm
change the order we tear things down in `setAsyncDelegate`/`setDataSource` to avoid a random crash in `UIScrollViewAccessibility` or an `NSProxy` exception. I'm not sure exactly why, but it appears the `UIScrollView` will sometimes attempt to call the delegate while it is being nilled out. Previous code was deallocing the proxy before clearing `super.delegate`. 
This can manifest as a null ref in `UIScrollViewAccessibility` or as an illegal call to `NSProx`y, depending on exactly the order things happen.
**Update:** I've made some additional changes that help solve this problem, but it's important to manually nil `asyncDelegate` (and `asyncDataSource`) to avoid crashes. If you depend on ARC bad things will happen currently and I'm not sure exactly how to handle it. Root cause is that it's …
=> Fix a crash in setAsyncDelegate: that happens randomly (UIScrollViewAccessibility or NSProxy)

AsyncDisplayKit/ASTextNode.h, AsyncDisplayKit/ASTextNode.mm, AsyncDisplayKit/Details/ASTextNodeRenderer.h, AsyncDisplayKit/Details/ASTextNodeRenderer.mm, AsyncDisplayKitTests/ASTextNodeRendererTests.m, AsyncDisplayKitTests/ASTextNodeTests.m
expose NSTextContainer's exclusionPaths property on ASTextNode to be able to exclude view areas from typesetting.
This was already discussed in #394.
I do not see were exclusion paths are used internally. A comment on `[ASTextNodeRenderer _calculateCharacterIndexBeforeTruncationMessage]` claims that, but I don't see that anywhere in code. Perhaps the comment is outdated?
=> ASTextNode expose exclusion paths

AsyncDisplayKit/Details/ASDataController.mm
For reasons I don't fully understand, this avoids a retain cycle with the currently displayed cells.
This is an alternate implementation of "[Ensure all nodes are dealloc'd in ASDataController teardown #409](https://github.com/facebook/AsyncDisplayKit/pull/409)" that works with multiple sections and IMO should supersede that one. (Thanks @barfoon for working this out in the first place. I was quite mystified until I saw his PR.)
In our application, this fix reduced AsyncDisplayKit's retained memory significantly. (There are still other issues I haven't tracked down, but this one is the biggest by far.)
=> ASDataController dealloc, ensure cell nodes are not in a superview

AsyncDisplayKit/ASTableView.mm
This code moves the initialization code to a shared method and uses it to initialize correctly in `-initWithCoder:` so it can be used in a xib or  storyboard. Note that when initializing this way `asyncDataFetching` is defaulted to NO, so it's not possible to use asyncDataFetching in this configuration. (We could do this by making `asyncDataFetching` an `IBInspectable` property but that was a bit more refactoring than I'm comfortable with at the moment.)
It might be worth double-checking `ASCollectionView` to see if it could benefit form a similar refactor. (Next time I'm in that code I'll take a look if someone else doesn't.)
=> Allow ASTableView to be loaded in a xib/storyboard

AsyncDisplayKit/ASImageNode.mm
I’m not confident why the original implementation doesn’t work, but
this version is stylistically cleaner regardless.  Resolves task #450.
=> Set line width on path instead of context.

AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.mm
Calling `[super insertRowsAtIndexPaths:withRowAnimation:]` and its `delete`/`sections` counterparts with `UITableViewRowAnimationNone` seems to do nothing to prevent the cascading animations when data changes in the table view. Using other options like `UITableViewRowAnimationFade` and `UITableViewRowAnimationRight` change the animation completely. With the `UITableViewRowAnimationNone` option not functioning, I have turned off animations during the default insertion/deletion calls.
This fixes #292.
=> Prevent UITableView insertion/deletion animations by default

AsyncDisplayKit/ASTableView.mm
Root cause is because we assume `UITableView`'s `indexPathsForVisibleRows` returns the new item to be displayed immediately after `tableView:willDisplayCell:forRowAtIndexPath:` is called. This is not always true, especially when we are scrolling programmatically. Fix is to track this "pending" visible index path and return it along with the `UITableView`'s `indexPathsForVisibleRows` in `rangeControllerVisibleNodeIndexPaths:`.
=> Bug Fix - ASTableView sometimes fails to render cell contents when scrolling programmatically.

AsyncDisplayKit/ASDisplayNode+Subclasses.h, AsyncDisplayKit/ASDisplayNode.mm
Some fixes to the placeholder API:
* The ```_pendingDisplayNodes``` object was never initialized.
* Placeholder opacity was not reset after being faded out once.
* Small documentation typo.
=> Fix handling of pending nodes and placeholder layer

AsyncDisplayKit/ASTextNode.h, AsyncDisplayKit/ASTextNode.mm
Adds a new property, `passthroughNonlinkTouches` that will allow touches in non-link areas to pass through to other event handlers event with `userInateractionEnabled` for an `ASTextNode`.
=> Add option to pass through touches to non-link text in ASTextNode

AsyncDisplayKit/Private/ASDisplayNode+AsyncDisplay.mm
This fixes an issue that causes rasterized nodes that have a non-zero origin to draw incorrectly, as seen in #471 and #318.
This is a screenshot of the issue. The second box has an offset of about 150 points, which causes the rasterization to inset the subnodes with 150 points.
I've fixed it by using a frame with a zero origin when the node that's being rasterized is the container node.
=> Fix offset issue for rasterized nodes 

AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.mm
It's currently unreliable for some use cases that issue editing calls while
content is displayed or being interacted with.  The performance gain is not
sufficient to sacrifice correctness for the clients that hit this issue,
so it will remain off until fully resolved.
=> Disable asyncDataFetching in ASTableView and ASCollectionView init

AsyncDisplayKit/Private/ASDisplayNode+UIViewBridge.mm, AsyncDisplayKitTests/ASDisplayNodeTests.m
Bounds.origin shouldn't be affected by -[ASDisplayNode setFrame:] method. This affects many nodes, for example ASScrollNode scrolls to top after frame changing.
=> Fixed bounds in ASDisplayNode

AsyncDisplayKit/ASScrollNode.m, AsyncDisplayKit/Details/_ASDisplayLayer.mm, AsyncDisplayKit/Details/_ASDisplayView.mm
Remove -[_ASDisplayView layoutSubviews] and use only -[_ASDisplayLayer layoutSublayers]
This helps us support special cases such as ASScrollNode correctly driving the -layout
method for subclasses even though it is based on UIScrollView & can't use _ASDisplayView.
I suspect this will be useful for ASCollectionNode and ASTableNode as well, which would
allow nesting those classes inside of other collections / tables (e.g. horizontal
unit within a vertical unit).
=> Remove -[_ASDisplayView layoutSubviews] and use only -[_ASDisplayLayer layoutSublayers]

examples/Kittens/Sample/BlurbNode.m, examples/Kittens/Sample/ViewController.m
In particular, the NSValue-boxed CGSize array used as a data model for the kittens
is generated with random sizes, for unclear reasons.  It turns out this is a workaround
to convince PlaceKitten to send us unique images.
=> Cleaned up Kittens sample app and added comments for clarity.

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/Details/ASAbstractLayoutController.mm, AsyncDisplayKit/Details/ASCollectionViewLayoutController.h, AsyncDisplayKit/Details/ASCollectionViewLayoutController.mm, AsyncDisplayKit/Details/ASScrollDirection.h, AsyncDisplayKit/Details/ASScrollDirection.m, AsyncDisplayKit/Details/CGRect+ASConvenience.h, AsyncDisplayKit/Details/CGRect+ASConvenience.m
Replaces FlowLayoutController with CollectionViewLayoutController in ASCollectionView. The new layout controller leverages UICollectionViewLayout's layoutAttributesForElementsInRect in order to calculate index paths for items in AsyncDisplayKit ranges. UICollectionViewFlowLayout is still a requirement in order to test the waters. If this works well with existing clients, we can simply remove the UICollectionViewFlowLayout class assertion.
=> ASCollectionViewLayoutController

AsyncDisplayKit/ASCollectionView.mm
I think we might want to hold off on merging this until we verify that the new layout controller works well with flow layout as a first step.
=> Custom layout enabled. Removes UICollectionViewFlowLayout requirement.

AsyncDisplayKit.xcodeproj/project.pbxproj
The newly added iOS framework (added for Carthage support) was missing a few files, so it failed to build. This PR modifies the target membership for those files to make the target build. Fix verified to work with Carthage 0.7.4.
=> Include missing files in iOS Framework target

AsyncDisplayKit.podspec
Currently when using Cocoapods to install the latest version of AsyncDisplayKit using the `use_frameworks!` option, `ASDealloc2MainObject.h` is added to the headers build phase twice due to its inclusion in both the main podspec as well as the `ASDealloc2MainObject` subspec. This leads to a "Multiple build commands for output file" warning in Xcode.
In this case the fix is pretty simple - just exclude that header from the main spec (you're already doing this for `ASDealloc2MainObject.m`).
=> Exclude ASDealloc2MainObject.h from main spec

AsyncDisplayKit/ASTableView.mm
This is a candidate fix for the race condition @appleguy tracked down in #458. This version uses the single pending `NSIndexPath` approach but adds code to validate that the pending index path is always contiguous with respect to `UITableView`'s `indexPathsForVisibleNodes`. (I had previously discovered that the approach of tracking all visible nodes using willDisplay/didEndDisplaying is flawed because `UITableView` doesn't always call didEndDisplaying. Boo. See #427)
In order to do this we may make up to two calls to `-[ASDataController  numberOfRowsInSection:]` but this *only* happens when we have a pending index that is not part of the existing visible range (a rare but important edge case.) From what I've seen this happens pretty rarely and should not impact overall system performance. …
=> ASTableView programmatic scrolling fix w/contiguous guarantee

AsyncDisplayKit/ASCellNode.m, AsyncDisplayKit/ASTableView.mm
This helps work around a bug we are seeing in some rare cases (selected background view overlaps other cells if size of ASCellNode has changed.)
There is an edge case I ignored for this PR - if you set ASCellNode clipsToBounds while the cell is currently visible it will not propagate to the Cell until it is next displayed. (Just because it doesn't seem worth the added complexity.)
@appleguy I've tested this with my ADKFlicker test and my internal project and it masks the issue in both cases.
=> Propagate ASCellNode's clipsToBounds value to the __ASTableViewCell

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/Details/ASCollectionViewLayoutController.h, AsyncDisplayKit/Details/ASCollectionViewLayoutController.mm, AsyncDisplayKit/Details/ASDataController.h, AsyncDisplayKit/Details/ASDataController.mm, AsyncDisplayKit/Details/ASFlowLayoutController.h, AsyncDisplayKit/Details/ASFlowLayoutController.mm, AsyncDisplayKit/Details/ASIndexPath.h, AsyncDisplayKit/Details/ASMultidimensionalArrayUtils.h, AsyncDisplayKit/Details/ASRangeController.h, AsyncDisplayKit/Details/ASRangeController.mm, AsyncDisplayKitTests/ASTableViewTests.m, examples/ASTableViewStressTest/Sample.xcodeproj/xcshareddata/xcschemes/Sample.xcscheme, examples/ASTableViewStressTest/Sample/ViewController.m
This diff resolves all known consistency issues with ASTableView and ASCollectionView.
It includes significantly more aggressive thrash-testing in ASTableViewStressTest,
which now passes on a variety of device and simulator configurations.  It also updates
the unit tests run on every commit to ensure any regression is caught quickly.
A few of the salient changes in this diff:
- ASTableView now uses Rene's ASCollectionViewLayoutController, and actually uses a
UICollectionViewFlowLayout without any UICollectionView.  This resolves an issue where
ASFlowLayoutController was generating slightly out-of-bounds indicies when programmatically
scrolling past the end of the table content.  Because the custom implementation is likely
faster, I will revisit this later with profiling and possibly …
=> Overhaul ASDataController and extensively test ASTableView.

AsyncDisplayKit/ASDisplayNode.h, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/ASEditableTextNode.h, AsyncDisplayKit/ASEditableTextNode.mm, AsyncDisplayKit/Details/_ASDisplayView.mm, AsyncDisplayKitTests/ASDisplayNodeTests.m
(Note: this is the same PR as #513, which I've closed - I wanted to issue this PR from a different fork, and don't know of a more elegant way to do it).
@appleguy: thanks for the review. I'm not 100% sure of things here, since I'm not insanely experienced working with the responder chain, but here are my thoughts so far regarding your questions:
- layer-backed/rasterized nodes shouldn't ever care about becoming first responder, as this only really pertains to `UIView` hierarchies. To be more explicit about this, I now check if a node is `layerBacked` when calling `becomeFirstResponder`/`resignFirstResponder` and immediately return `NO` if so.
- I'm not really sure how to measure the performance degradation you're worried about. I don't know how UIKit keeps track of what views can become …
=> Add UIResponder methods to ASDisplayNode

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKitTests/ASCollectionViewTests.m
Test to show how ASCollectionViewController may crash. Looks like Apple bug. Simplest possible fix in ASDK is to modify ASCollectionView.mm:
```
- (void)reloadDataWithCompletion:(void (^)())completion
{
ASDisplayNodeAssert(self.asyncDelegate, @"ASCollectionView's asyncDelegate property must be set.");
ASDisplayNodePerformBlockOnMainThread(^{
[super reloadData];
[self layoutIfNeeded]; // Here is the FIX
});
[_dataController reloadDataWithAnimationOptions:kASCollectionViewAnimationNone completion:completion];
}
```
=> Implemented test for crash in ASCollectionView on reloadData

AsyncDisplayKit/ASMultiplexImageNode.mm
This update improves the memory consumption of `ASMultiplexImageNode` which are no longer on screen, but remain in memory. The downside to this change is that when the node gets re-rendered it will fetch images off the network, hopefully most users are using an image cache so this will not too negatively impact them.
This keeps things a bit more inline with how `ASNetworkImageNode` works, however, I noticed `ASNetworkImageNode` clears itself out in `clearFetchedData`. However, `ASMultiplexImageNode` is currently using `clearContents` for clearing itself out. I kept this logic inside `clearContents` because of that, but let me know if this is more appropriate in  `clearFetchedData`.
=> releasing downloaded image when multiplex image node exits render range

AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.mm
Short-circuit calls that make async updates to UITableView or UIViewController after the asyncDataSource has been set to nil. This can happen when an update is being processed asynchronously and the client begins tearing down an ASTableView or ASCollectionView instance.
This is a proposed fix for #572.
=> Prevent making async updates to UITable|CollectionView when asycDataSource is cleared

AsyncDisplayKit/ASCollectionView.h, AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.h, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/Details/ASDataController.h, AsyncDisplayKit/Details/ASDataController.mm, AsyncDisplayKit/Details/ASFlowLayoutController.mm, AsyncDisplayKit/Details/ASRangeController.h, AsyncDisplayKit/Details/ASRangeController.mm
This is a merged and cleaned-up version of PR #548.
This PR adds a new property for ASTableView (automaticallyAdjustsContentOffset) that, when enabled, will adjust the contentOffset for inserts and deletes before the visible viewport so the users view is maintained. In order to use this effectively, animations must be disabled while performing updates. To facilitate this an option has been added to endUpdates (and also a completion handler that has many uses.) Because this only works well with animations are disabled and it may require some thought to use effectively, it defaults to off.
There is a performance trade-off for this feature that I'd like anyone to weigh in on. In order to make this work, we need to know the heights of the nodes being inserted or deleted. (well we actually …
=> Take 2: Automatically adjust content offset for insertion/deletion

AsyncDisplayKit/ASCollectionView.mm, examples/ASTableViewStressTest/Sample/ViewController.m
Implement warning assertion for supplementary views in ASCollectionView.
Make sure ASTableViewStressTest passes.  It was sometimes testing a scenario UITableView itself doesn't support.
=> Implement warning assertion for supplementary views in ASCollectionView.

AsyncDisplayKit/ASEditableTextNode.h, AsyncDisplayKit/ASEditableTextNode.mm, examples/EditableText/Sample/ViewController.m
I needed this for a feature we're building at @pinterest.
Currently, when using an `ASEditableTextNode`, there's no way to set the `returnKeyType` of the node. This adds support for that functionality.
I updated the `EditableText` demo to use this feature.
=> Add support for configuring `returnKeyType` on ASEditableTextNode.

AsyncDisplayKit/ASEditableTextNode.h, AsyncDisplayKit/ASEditableTextNode.mm
This allows much more control over the display of ASEditableTextNodes and closes #549
=> Access to underlying UITextView for more configuration options.

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/Details/ASIndexPath.h, AsyncDisplayKit/Private/ASInternalHelpers.h
I looked into and fixed the recent build issues with AsyncDisplayKit's dynamic framework target (Issue #591).
There were a variety of reasons for this but it turned out to be mostly a matter of the framework missing some recently merged changes (that were only added to the library target).
=> Fixing build issues for framework target - Issue #591

AsyncDisplayKit/ASCollectionView.h, AsyncDisplayKit/ASCollectionView.mm, examples/ASCollectionView/Sample/ViewController.m
This is something we added internally that I want to bring back upstream. I saw that there was a similar implementation at #352, so I followed the feedback given to that patch and brought it up to speed.
Added a small inset to the example project so people could see it in a action.
=> Add support for sectionInset in ASCollectionView in property and delegate form

AsyncDisplayKit/ASDisplayNode.h, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Private/ASDisplayNode+UIViewBridge.mm, AsyncDisplayKit/Private/ASDisplayNodeInternal.h, examples/Kittens/Sample/KittenNode.h, examples/Kittens/Sample/KittenNode.mm, examples/Kittens/Sample/ViewController.m
This PR is the first in a series of PRs that aim to support relayout. Relayouts can be categorized into 2 types: external and internal.
- External relayouts are caused by a new constrained size applied to the root node (like orientation change). This can be easily supported by calling -measure on every nodes.
- Internal relayouts are not caused by a different constrained size used on the root node. Instead, they are caused by internal layout changes, like subnodes re-arrangement and/or subnodes' size change.
Internal relayouts are triggers by calling -setNeedsLayout. The method does following things:
- Invalidates calculated layout of the display node.
- If the node is not a root node, -setNeedsLayout will be recursively called on higher-level nodes, until the root node gets the message. …
=> Support internal relayout

AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/Details/ASDataController.h, AsyncDisplayKit/Details/ASDataController.mm, AsyncDisplayKit/Private/ASInternalHelpers.h, AsyncDisplayKit/Private/ASInternalHelpers.mm, examples/Kittens/Sample/AppDelegate.m, examples/Kittens/Sample/ViewController.m
External relayout (as defined in #594) can be handled by re-measure all relevant nodes with the new constrained size. This PR is about adding correct hooks that trigger re-measurements in response to some events, such as:
=> Support external relayout

AsyncDisplayKit/ASDisplayNode.mm
We must hold the lock for the duration of the block.
Failure to do this can result in the node loading while the block is inflight.
=> Fix race in ASDisplayNodeRespectThreadAffinityOfNode

AsyncDisplayKit/ASCollectionView.mm
My understanding is there's now support for non-flow layouts. So we shouldn't be assuming one here.
=> Don't assume flow layout

AsyncDisplayKit/ASDisplayNode.h, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/ASImageNode.mm, examples/Kittens/Sample/KittenNode.mm
ASNetworkImageNode defers to ASImageNode to return its calculatedSize. ASImageNode returns the size of its image. There is a good chance that ASNetworkImageNode hasn't downloaded its image yet when calculatedSize is called, so it returns a size of CGSizeZero.
On top of that, it is possible that the size of the image is not actually the size that we wish to display in our node.
I've added an "expectedImageSize" property that can be used to determine the calculatedSize of an ASNetworkImageNode.
=> Add expectedSize to ASNetworkImageNode

AsyncDisplayKit/ASCollectionView.h, AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.h, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/Details/ASDataController.h, AsyncDisplayKit/Details/ASDataController.mm
Since the return type is ASSizeRange, the min size, ASStackLayoutAlignItems and ASStackLayoutAlignSelf can now be fully utilized. 
One particular use case of min size can be found [here](https://github.com/nguyenhuy/AsyncMessagesViewController/commit/1d409ca8395054caa2cf03acf383ebc6d81a5ac1). In short, I need each cell node to have a positive min width. The min width acts as the min cross size of a vertical stack layout spec. Without a big enough min cross, I won't be able to do right alignment (via ASStackLayoutAlignItemsEnd), because the stack will [hug its content](https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/Private/ASStackPositionedLayout.mm#L46). (And yes, I've completely replaced manual layout with box-model layout in my AsyncMessagesViewController lib).
=> Support different constrained size range per node

AsyncDisplayKit/Details/ASRangeHandlerRender.mm
ASDK layout and display calls don't depend on UIView in any way, so this will reduce UIView-specific overhead from heirarchy manipulation.
I have a separate project to completely eliminate the working range window, but was impressed to see that this solution reduces the add / remove call by well over an order of magnitude — about 25x.  It is now so small, about 50ms -> 2ms on an iPhone 4 in my test case, that the main reason to remove the working window is no longer performance.  Rather, it is to support more advanced display features such as blocking on any unfinished display work if an app wants to ensure placeholders can never appear onscreen.
=> Optimization: use only layers for offscreen working range window.

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Private/ASDisplayNodeInternal.h
- Fix bug that causes preferred size to not be used if it is set after a layout pass.
- Fix bug that causes preferred size to not be used if -calculateSizeThatFits is not overridden.
=> Fix small bugs related to preferredFrameSize

AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/Details/ASDataController.h, AsyncDisplayKit/Details/ASDataController.mm, AsyncDisplayKit/Private/ASInternalHelpers.h, AsyncDisplayKit/Private/ASInternalHelpers.mm, examples/Kittens/Sample.xcodeproj/project.pbxproj, examples/Kittens/Sample/ViewController.m
- In -layoutSubviews of table and collection views, detect changes that cause a different constrained size for nodes, and trigger relayout immediately.
- Orientation change can be handled by this solution. So, no need to observe to its events.
- Clean up #595.
- Update Kittens example to support iPad (easier to catch bugs on these devices) and add a title to navigation bar (looks a bit nicer).
There is 1 bug left that hopefully I will be able to fix in the next few days:
- Invisible nodes are not re-measured after entering editing mode.
=> Improve relayout when constrained size of all nodes is changed

AsyncDisplayKit/ASDisplayNodeExtras.h, AsyncDisplayKit/ASDisplayNodeExtras.mm, AsyncDisplayKit/ASTextNode.mm
Re-use global instances of UIColor and NSAttributedString (since they are immutable) for a couple key init methods.
=> Node init performance: Use shares UIColor/NSAttributedString instances

AsyncDisplayKit/Details/ASTextNodeRenderer.mm, AsyncDisplayKitTests/ASTextNodeRendererTests.m
@appleguy In reference to issue #606 
This modifies the ASTextNodeRenderer to set `_calculatedSize` to `CGSizeZero` when the attributedString is either nil or an empty string
I've also added test coverage for these expectations :sunglasses: 
I thought this was the most logical place, but if you think it belongs else where please let me know!
=> 606 sizezero nil text

AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/Layout/ASStaticLayoutSpec.mm
because their size.width / size.height isn't nan, but FLT_MAX.
=> Static layout doesn't properly set a height for collection view cells

AsyncDisplayKit/Details/ASDataController.mm, AsyncDisplayKitTests/ASTableViewTests.m
Reported in #617.
The old version of relayoutAllRows triggers re-measurement on already loaded nodes, but doesn't consider the ones that were measured using the old constrained size and still waiting to be added to _completedNodes (on main thread).
This PR fixes the problem by adding a relayout block to the end of the editing queue. The block will then be executed on main thread, thus making sure all loaded nodes are there to be handled. A new test case is also included.
@wpK: Please help me to test this PR. Thanks!
=> Fix new constrained size is not applied to loading nodes

AsyncDisplayKit/ASTableView.mm, examples/Kittens/Sample/KittenNode.mm
Cell nodes in table view should almost always fill its width. To enforce this behaviour, this PR updates the default min constrained width. This new behaviour requires each cell node to have at least 1 flexible object that can fill available space (for example, a flexible shrink and grow text node, or a center layout spec). Users can always op-out of this behaviour by overriding data source's -tableView:constrainedSizeForNodeAtIndexPath:.
Here are screenshots of Kittens sample before and after this diff.
=> New min constrained width for cell nodes in table view

AsyncDisplayKit/Details/ASRangeHandlerRender.mm
Accomodate and document unusual cases in which it is necessary to remove views when clearing backing stores.
ASDK layout and display calls don't depend on UIView in any way, so this
will achieve the necessary behavior of the render range while eliminating significant
UIView-specific overhead from heirarchy manipulation.
=> Switch to use only layers in the offscreen window used for the render range.

AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKitTests/ASTableViewTests.m
First size change occurs during initial configuration. An expensive relayout pass is unnecessary at that time and should be avoided.
This PR proposes a simple fix for this problem, that is adding a new boolean flag. With the fix in place, my ~~manual~~ tests showed that main thread was not blocked at startup by an expensive relayout call. I also tested the use case in which a rotation occurred after initial configuration. The new size was picked up correctly via a relayout.
Another alternative fix would be to completely ignore size changes to *and* from a zero size. With this solution, we will also gain some optimizations in case the scroll view size is changed from a non-zero size (A) to zero, then back to A or another non-zero size (B), for example as the result of hide and unhide …
=> Avoid doing relayout during initial configuration

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Layout/ASLayoutSpec.mm, AsyncDisplayKit/Layout/ASLayoutablePrivate.h
A final layoutable method would look like:
```
- (id<ASLayoutable>)finalLayoutable
{
ASInsetLayoutSpec *insetSpec = [[ASInsetLayoutSpec alloc] init];
insetSpec.isFinalLayoutable = YES;
insetSpec.insets = UIEdgeInsetsMake(4, 4, 4, 4);
[insetSpec setChild:self];
return insetSpec;
}
```
While I'm not wild about this for a couple of reasons (1: we require the user to set a flag instead of doing something more seamless; 2: it makes it impossible to use the convenience methods on the layoutSpecs in finalLayoutable), I think it is better than before. We can probably do better though, so let's use this as a starting point to discuss.
=> First thoughts on fixing the finalLayoutable method.

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Layout/ASBackgroundLayoutSpec.mm, AsyncDisplayKit/Layout/ASCenterLayoutSpec.mm, AsyncDisplayKit/Layout/ASInsetLayoutSpec.mm, AsyncDisplayKit/Layout/ASLayoutOptions.h, AsyncDisplayKit/Layout/ASLayoutOptions.mm, AsyncDisplayKit/Layout/ASLayoutOptionsPrivate.h, AsyncDisplayKit/Layout/ASLayoutOptionsPrivate.mm, AsyncDisplayKit/Layout/ASLayoutSpec.h, AsyncDisplayKit/Layout/ASLayoutSpec.mm, AsyncDisplayKit/Layout/ASLayoutable.h, AsyncDisplayKit/Layout/ASOverlayLayoutSpec.mm, AsyncDisplayKit/Layout/ASRatioLayoutSpec.mm, AsyncDisplayKit/Layout/ASStackLayoutSpec.mm, AsyncDisplayKit/Layout/ASStaticLayoutSpec.mm, AsyncDisplayKit/Private/ASStackBaselinePositionedLayout.mm, AsyncDisplayKit/Private/ASStackPositionedLayout.mm, AsyncDisplayKit/Private/ASStackUnpositionedLayout.mm, AsyncDisplayKitTests/ASCenterLayoutSpecSnapshotTests.mm, AsyncDisplayKitTests/ASStackLayoutSpecSnapshotTests.mm
Addressed comments from the PR: https://github.com/facebook/AsyncDisplayKit/pull/644
Note: I did not change how the ASLayoutOptions are propagated. I did change the "copyInto" method to `propagateOptionsFromLayoutOptions:` (I even spelled it right on my second try). The reasoning behind this is I worry that traversing children to get a valid value for an option may be error prone. 
For example, imagine a stack of 3 text nodes wrapped in inset specs. You want the first 2 to align on the baseline but not the third. You set the 3rd nodes inset spec to have ascender/descender to 0.
While laying out the textNodes the stack spec starts traversing the 3rd node. It sees an inset spec with an ascender/descender of 0. This is the default value. What does it do? Does it assume that since this is a …
=> Addressed comments to LayoutOptions PR

AsyncDisplayKit/ASCollectionNode.h, AsyncDisplayKit/ASTableView.h, AsyncDisplayKit/Details/ASRangeController.h, AsyncDisplayKit/Layout/ASLayoutOptions.h
There are still some warnings left (see below). @rcancro will look at them later on.
```
WARN | ASLayoutOptions is not documented!
WARN | ASLayoutSpec.h@25: Description for parameter 'child' missing for -[ASLayoutSpec setChild:]!
WARN | ASLayoutablePrivate is not documented!
WARN | ASStackLayoutable is not documented!
WARN | ASStaticLayoutable is not documented!
```
=> Fix appledoc warnings

AsyncDisplayKit/Layout/ASLayoutSpec.h
No more warnings after this diff :) The main problem is that each method must have its own comment.
=> Fix appledoc warnings in ASLayoutSpec.h

AsyncDisplayKit/ASTableView.h, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKitTests/ASTableViewTests.m
- Above is the generic case. Correctly handling it means relayout when the table view enters or leaves editing mode is taken care of as well.
- Async data source API removal: In a table view, cell nodes should always fill its content view and table view widths. Thus async data source can no longer provide custom constrained size for cell nodes. This removal allows table view to better handle relayout.
- Some more tests are added to ASTableViewTests to check against use cases handled in this diff.
=> Relayout table view cell nodes if there is a mismatch between content view size and the node's constrained size

AsyncDisplayKit/Layout/ASLayout.mm
It is strictly enforcing this unused variable (when asserts are compiled out).
=> Fix building test / profile under Xcode 7

AsyncDisplayKit/ASImageNode.mm
This way you can get a performance boost by marking your image nodes as opaque. Before this PR, no matter what the background color, opaque image nodes with partially-transparent images always show a black background.
=> Fill image context with background color if image node is opaque

AsyncDisplayKit/ASCollectionView.mm
This resolves #654
We could remove the flag and just call `[self layoutIfNeeded]` immediately after `[super reloadData]`
- + Reduces complexity of ASCollectionView
- - Relies on implementation details of `UICollectionView`
- - Performance cost
=> Fix collection view data inconsistency

.travis.yml
This reverts commit a9539fea1aac22f0c4922b34cbdf752f2a2061af.
We can't get stuff done at Pinterest with the new version - need a day or two to get other stuff compliant.
=> Revert "Update Travis' Cocoapods version to 0.38.2"

AsyncDisplayKit/ASEditableTextNode.mm
When setting a default placeholder and an attributedString before `_textKitComponents.textView` was created, the placeholder and the string were both appearing in the text node.
`_updateDisplayingPlaceholder` is called in `setAttributedString`, but since  `_textKitComponents.textView` is nil the placeholder was not hidden. Calling `_updateDisplayingPlaceholder` after `_textKitComponents.textView` loads fixes this.
=> Placeholder bug in ASEditableTextNode

AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.mm, examples/ASTableViewStressTest/Sample/ViewController.m
This should address #612.  The stress test completes successfully; this issue prevented it from starting.
=> Fix simple issue with ASTableViewStressTest, make Table / Collection handle changes to dataSource / delegate.

AsyncDisplayKit/Details/ASDataController.mm
My attempt to fix #619. The idea is to capture ASDataController's _completedNodes and use that cache for any external queries until a current update transaction finishes.
Let me know what you think on this diff. If we don't want to cater ASDataController to work with UITableView and UICollectionView specific behaviours, I can simply make a wrapper/subclass that sits between UITableView/UICollectionView and ASDataController. It can intercept transaction calls as well as external data queries, and ensures data consistency using the same technique here.
I tested this diff by abusing Kitten sample with a bunch of insertions, deletions and device rotations. Really appreciate if @eanagel, @ryanfitz, @Adlai-Holler and @smyrgl can help me to test as well.
I have another diff that tries to fix the …
=> Ensure data consistency between ASDataController and its delegate while executing update transactions

AsyncDisplayKit/Layout/ASStaticLayoutSpec.mm
I noticed when creating a static layout that the sizeRange of the children was being ignored. The case was:
I had an image as a child of a static layout
The image was set to have an exact range of 90x90
When the static layout was measured, the constrained size came in as 375xInf (the width of the containing node and unbounded)
The static layout computed its final size as 375x90
According to the comments in component kit's header file the static layout  "[c]omputes a size that is the union of all childrens' frames." It appeared that we are only doing that in the unbounded direction. My fix is to do it in both directions.
@nguyenhuy Please take a look and let me know what you think.
=> Static layout bug?

AsyncDisplayKit/Details/ASDataController.mm
@appleguy @nguyenhuy Been majorly frustrated at work lately so it feels super good to have a nice, clean improvement to offer.
=> Faster Layout Nodes

AsyncDisplayKit/ASMultiplexImageNode.mm
Doesn't do much, but I reckon every little bit helps!
=> Use deep compare when setting image identifiers in ASMultiplexImageNode

AsyncDisplayKit/ASScrollNode.m
Because of Swift's initializer inheritance behavior, calling the `initWithViewBlock:` convenience initializer causes a runtime error. This is easily remedied by using the long-form designated initializer but `ASScrollNode` uses the convenience initializer within the framework. This change allows `master` to work better with Swift.
=> Use long-form view block initializer for better Swift support

AsyncDisplayKit/ASTextNode.mm, AsyncDisplayKit/Layout/ASStackLayoutDefines.h, AsyncDisplayKit/Layout/ASStackLayoutSpec.mm, AsyncDisplayKit/Private/ASStackBaselinePositionedLayout.mm, AsyncDisplayKit/Private/ASStackLayoutSpecUtilities.h
1) Set the ascender/descender of an ASTextNode when the attributeString is set. Previously ascender/descender were only being computed in `setValuesFromLayoutable` and only when the attribute string was not nil. May make sense to remove the computation from `setValuesFromLayoutable` entirely.
2) Remove ability to allow different children of a stack spec to aling to different baselines. This wasn't working before and I'm not convinced it is possible to do properly/useful enough to invest the time.
3) Have all stack spec run `ASStackBaselinePositionedLayout::compute` to compute the stack's ascender and descender. Even if the stack isn't aligning its children to a baseline, the stack itself may be a child of another stack that IS aligning to a baseline.
=> Fixes to baseline stack alignment

AsyncDisplayKit/ASMultiplexImageNode.h, AsyncDisplayKit/ASMultiplexImageNode.mm
Ugh, it kills me to have to do this but the framework will deadlock pretty quick otherwise once you start hammering it.
=> Workaround Photos.framework deadlock by locking

AsyncDisplayKit/Details/ASDataController.mm
Pursuant to #735, here's some more documentation! I added some questions in `FIXME` comments. 
I also replaced two needless calls to `enumerateObjects:` with NSFastEnumeration instead. I reckon every bit of performance counts!
=> Document Cell Layout Passes

AsyncDisplayKit/ASMultiplexImageNode.mm
I found that sometimes iOS was inferring `UserInteractive` for these, which would degrade UIKit performance.
=> Demote Photos.framework image request QoS

AsyncDisplayKit/ASCellNode.h, AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.mm
Selected/highlighted properties on ASCellNode can be useful for doing some work when table view cell is selected or highlighted (e.g. change node's background color).
=> ASCellNode selected/highlighted properties

AsyncDisplayKit/ASViewController.m
ASViewController currently cannot be subclassed in Swift, as the original call to `[super init]` directs to calling the designated initializer of UIViewController `[self initWithNibName:bundle:]`. Because of Swift's initializer inheritance behavior, this designated initializer will not implicitly be available on the subclassed ASViewController without some extra boilerplate. Adding an explicit call to the designated initializer fixes this issue.
=> Call UIViewController's designated initializer in ASViewController

AsyncDisplayKit/ASTableView.mm, AsyncDisplayKitTests/ASTableViewTests.m
There is a bug in ASTableView that causes unnecessary relayout when the table view width is zero initially. This PR includes the fix for this bug and some minor refactorings.
#758, #753
=> Fix table view tests

AsyncDisplayKit/ASCollectionView.h, AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/Details/ASCollectionDataController.mm, AsyncDisplayKit/Details/ASCollectionViewFlowLayoutInspector.h, AsyncDisplayKit/Details/ASCollectionViewFlowLayoutInspector.m, AsyncDisplayKit/Details/ASDataController+Subclasses.h, AsyncDisplayKit/Details/ASDataController.mm, AsyncDisplayKitTests/ASCollectionViewTests.m
Went through @appleguy's post-merge review on #694 and cleaned up various aspects of the supplementary node implementation.
=> Respond to supplementary node feedback

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/ASDisplayNode.h, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Layout/ASAsciiArtBoxCreator.h, AsyncDisplayKit/Layout/ASAsciiArtBoxCreator.m, AsyncDisplayKit/Layout/ASLayoutSpec.h, AsyncDisplayKit/Layout/ASLayoutSpec.mm, AsyncDisplayKit/Layout/ASOverlayLayoutSpec.mm, AsyncDisplayKit/Layout/ASRatioLayoutSpec.mm, AsyncDisplayKit/Layout/ASStackLayoutSpec.mm, AsyncDisplayKit/Layout/ASStaticLayoutSpec.mm
Created a class called `ASAsciiArtBoxCreator` that, given a parent name and an array of string representations of the children, will create an ascii representation of the parent. 
Objects that want to be rendered in ascii art should implement the `ASLayoutableAsciiArtProtocol` protocol. The two methods are:
```
- (NSString *)asciiArtString;
- (NSString *)asciiArtName;
```
I have updated `ASDisplayNode` and `ASLayoutSpec` so that they conform to this new protocol. If you are working on a layout, you can put a breakpoint at the end of `- (ASLayoutSpec *)layoutSpecThatFits:(ASSizeRange)constrainedSize` and type `po [layoutSpec asciiArtString]` to see a visual representation of your layout.
For example, this is what the layout for `KittenNode` looks like:
```
(lldb) po [insetSpec …
```
=> Ascii art visual debugging for ASLayoutSpecs

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/ASTableViewInternal.h, AsyncDisplayKit/Details/ASChangeSetDataController.h, AsyncDisplayKit/Details/ASChangeSetDataController.m, AsyncDisplayKit/Details/ASCollectionDataController.h, AsyncDisplayKit/Details/ASDataController.h, AsyncDisplayKit/Private/ASInternalHelpers.h, AsyncDisplayKit/Private/ASInternalHelpers.mm, AsyncDisplayKit/Private/_ASHierarchyChangeSet.h, AsyncDisplayKit/Private/_ASHierarchyChangeSet.m, AsyncDisplayKitTests/ASTableViewTests.m
#684, #693.
@levi, @Adlai-Holler: Please also let me know your thoughts on this PR. Thanks.
=> Sort edit commands during batch updating of table and collection views

AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/Private/ASInternalHelpers.h
We already had this `ASPerformBlockWithoutAnimation` convenience function, so I elevated it from `ASTableView.mm -> ASInternalHelpers.h` and reimplemented it using `performWithoutAnimation`. Now we never call `setAnimationsEnabled:` which should resolve #788
=> Avoid overwriting areAnimationsEnabled if app changes it again during animation

AsyncDisplayKit/ASNetworkImageNode.h, AsyncDisplayKit/ASNetworkImageNode.mm, AsyncDisplayKit/ASTextNode.h, AsyncDisplayKit/ASTextNode.mm, AsyncDisplayKit/Details/ASBasicImageDownloader.h, AsyncDisplayKit/Details/ASBasicImageDownloader.mm, examples/Kittens/Sample/ViewController.m
This should not directly affect more complex apps that don't use the ASBasicImageDownloader.  Straight alloc/init of ASNetworkImageNode without the cache or downloader options could cause this problem, as well as manually allocating an ASBasicImageDownloader.
Both the downloader and cache are now weak references from the image node, and ASBasicImageDownloader is now a singleton.
This patch also disables the default-on text placeholders, as they churn memory during the measurement pass.  They were intended to be written with pure layers (without using backing stores), so I don't
think it is a reasonable default-on behavior until that is fixed.
=> Fix retain cycle for basic ASNetworkImageNodes (allocated without a cache)

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit.xcodeproj/xcshareddata/xcschemes/AsyncDisplayKit-iOS.xcscheme, AsyncDisplayKit.xcodeproj/xcshareddata/xcschemes/AsyncDisplayKit.xcscheme, AsyncDisplayKit/ASButtonNode.h, AsyncDisplayKit/ASButtonNode.mm, AsyncDisplayKit/ASTextNode.mm, AsyncDisplayKit/AsyncDisplayKit.h, examples/Multiplex/Sample.xcodeproj/project.pbxproj, examples/Multiplex/Sample/ScreenNode.h, examples/Multiplex/Sample/ScreenNode.m, examples/Multiplex/Sample/ViewController.m
Thanks to @garrettmoon at Pinterest for writing this.  It's been a long time coming — originally planned for development in the 1.1 era, we finally have a simple default button built on top of the widely used ASControlNode.  The main reason we've made it so far without it is that both ASImageNode and ASTextNode can addTarget/action pairs and respond to control events, but it has remained inconvenient to pair a simple image / icon with text in a button.
=> Adding ASButtonNode.  Simple but flexible, add features as desired!

AsyncDisplayKit/Layout/ASStackLayoutSpec.h, AsyncDisplayKit/Layout/ASStackLayoutSpec.mm
It felt cumbersome to repeatedly specify the direction of an ASStackLayoutSpec so I thought it'd be nice to provide these convenience classes. I also ran into cases where I named an ASStackLayoutSpec as a verticalStack or horizontalStack but forgot to set it's direction causing me to waste time debugging.
=> adds convenience methods to return a vertical and horizontal stack spec

AsyncDisplayKit/ASEditableTextNode.h, AsyncDisplayKit/ASEditableTextNode.mm
Previously, it was only possible to configure the textContainerInset of the typed textView by accessing the textView property on didLoad. This would cause the placeholder and typed textViews to become desynced however, so in this commit we add the ability to configure both.
=> Make textContainerInset configurable for ASEditableTextNode

AsyncDisplayKit/ASCellNode.h, AsyncDisplayKit/ASCellNode.m, AsyncDisplayKit/ASCollectionView.h, AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASDisplayNode.h, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/ASImageNode.mm, AsyncDisplayKit/ASTableView.h, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/Details/ASDataController.mm, AsyncDisplayKit/Details/ASRangeController.mm, AsyncDisplayKit/Private/ASDisplayNode+UIViewBridge.mm, AsyncDisplayKit/Private/ASDisplayNodeInternal.h, AsyncDisplayKit/Private/ASInternalHelpers.h, AsyncDisplayKit/Private/ASInternalHelpers.mm, examples/Kittens/Sample/KittenNode.mm, examples/Kittens/Sample/ViewController.m
As discussed in #792:
- Introduce ASCellNodeDelegate. Cell node automatically notifies the delegate after a relayout (caused by -setNeedsLayout). Confirming to ASCellNodeDelegate; ASTableView and ASCollectionView reload the calling cell upon notifications. These views automatically set themselves as delegate of every node.
- The result is that ASCellNode subclasses don't need to manually notify the containing view. Thus, `-relayoutItemAtIndexPath` and `-relayoutRowAtIndexPath` are removed (#722, #718).
- Kittens example is updated to reflect the change.
=> Improve cell node relayout

examples/ASCollectionView/Sample.xcodeproj/project.pbxproj, examples/ASCollectionView/Sample/AppDelegate.m, examples/ASCollectionView/Sample/ViewController.m, examples/ASTableViewStressTest/Sample.xcodeproj/project.pbxproj, examples/ASTableViewStressTest/Sample/AppDelegate.m, examples/ASTableViewStressTest/Sample/ViewController.m
So far unable to reproduce the reports of rows or items not being released.
@eanagel, @levi, @nguyenhuy, @ERussel — anyone plz help!  I'm more than happy to finish testing & refining the fix that @eanagel has put up, but multiple attempts have never reproduced the issue.  I've tried more with ASTableView than ASCollectionView, but in this example with ASCollectionView I still haven't seen the behavior.  Here's a memory trace showing about 5 copies of the controller being pushed, scrolled, and popped with no leaks or obvious latent memory shown.
=> Add "Push Another Copy" to ASViewController demo for memory testing.

AsyncDisplayKit/ASDisplayNode.h, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Details/ASRangeHandlerRender.mm, AsyncDisplayKit/Private/ASDisplayNode+UIViewBridge.mm, AsyncDisplayKit/Private/_ASHierarchyChangeSet.m
This resolves #815.  It also removes the -name property from CALayer and UIView categories, which is at far too high risk of a namespace collision and provides very little value (sorry, yes, totally unrelated change).
=> Fix unusual cell content blanking issue when making existing cells much taller.

AsyncDisplayKit/ASCellNode.h, AsyncDisplayKit/ASCellNode.m, AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASDisplayNode.h, AsyncDisplayKit/ASTableView.mm, examples/Kittens/Sample/KittenNode.mm
- Instead of reloading, layout delegates (i.e ASTableView and ASCollectionView) trigger an empty update transaction after a cell relayout (fix #808).
- Since delegates don't animate layout changes anymore, revert the animation example in KittenNode.
- Only set a default layout delegate to ASCellNode if it is not provided by the async data source. This allow developers to set their own delegate.
- Address comments in #793.
=> Improve cell node layout delegate

AsyncDisplayKit/Details/ASRangeHandlerRender.mm
This is a temporary fix until #828 is ready to land and release.  It eliminates the overwhelming majority of lost memory (still only a couple KB) in the case of inserts and deletions that orphan nodes in the workingWindow.
=> Patch for properly tearing down Working Window

AsyncDisplayKit/Layout/ASLayoutSpec.mm
The API lets people create things with the children array even if they only have one child.
=> Fix crash in ASCII art creator for one-element children arrays.

AsyncDisplayKit/Details/ASRangeHandlerRender.mm
This was a bug I introduced when porting @eanagel's diff from being view-based to layer-based.
-subviews returns a copy of the array and is actually safe to mutate directly, so I removed the -copy that Ethan had added.  However once I made it -sublayers instead, this was no longer safe.
=> Fix for behavior difference between CA and UIKit that causes mutation crash.

AsyncDisplayKit/ASMultiplexImageNode.mm
Before this PR, if the node leaves the render range, but stays in the preload range, its image download will be canceled and another won't be enqueued so the user may see a lower-quality image or no image.
=> [Critical] Don't Cancel Image Downloads in ASMultiplexImageNode.clearContents

AsyncDisplayKit/ASCollectionView.h, AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.h, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/Details/ASAbstractLayoutController.h, AsyncDisplayKit/Details/ASAbstractLayoutController.mm, AsyncDisplayKit/Details/ASLayoutController.h, AsyncDisplayKit/Details/ASRangeController.h, AsyncDisplayKit/Details/ASRangeController.mm
I'm currently reading through range controller and saw a few things that needed some syntax and organization clean up:
- Removed deprecated layout controller methods that were long longer needed.
- Now that we're closer to a 2.0, we should start the discussion of removing the remaining deprecated methods that live in ASDisplayNode—there are only three.
- Cleaned up syntax usage in ASRangeController
- Separated data and callback methods into data source and delegate protocols, respectively. It's now a little clearer what data is required for the range controller to work. In the process, I reordered some of the naming of the methods to make them a bit more readable.
=> Clean up syntax and organization of ASRangeController

AsyncDisplayKit/Private/_ASHierarchyChangeSet.h, AsyncDisplayKit/Private/_ASHierarchyChangeSet.m
This resolves #869. @appleguy
See below. ~~The diff is hard-to-read since I reordered lines, but all that is different is when we enumerate changes in reverse (for deletes) our "end index" is actually the _first_ index in the set, not the last index.~~
=> [critical] Fix Table View Updating Errors

examples/SocialAppLayout/Sample/PostNode.m
I was looking for a sample code to answer [@bimawa's question in #855](https://github.com/facebook/AsyncDisplayKit/issues/855#issuecomment-157397779) when I found out that, although a reserve-image-ratio logic is available in PostNode of SocialAppLayout example, it isn't used. No use no more :)
=> Trigger a relayout once the media image of PostNode in SocialAppLayout is loaded

AsyncDisplayKit/ASMultiplexImageNode.mm, AsyncDisplayKit/ASNetworkImageNode.mm
The first commit is the actual relevant change. The second commit is for consistency with the rest of the framework plus mutexes are more flexible than spin locks. The third commit fixes two issues 1) we shouldn't copy the array in the getter and 2) we should deep copy the array in the setter.
This is pursuant to the mention in #850 @appleguy
=> Use ASInterfaceState to Fetch Image Node Data when Image Source Changes

AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.mm
UITableView claims that `this method uses the index path to perform additional configuration based on the cell’s position in the table view.` I reckon it can't hurt to pass that information along. It may save us some view hierarchy swapping if it makes it more likely UITableView will give us the cell previously assigned to that index path. Plus it's less code and more consistent. So fresh and so clean, clean.
=> ASTableView: Use Fancy dequeueReusableCellWithIdentifier:forIndexPath: Method

AsyncDisplayKit/ASTextNode.mm
Before we were canceling the highlight as soon as we got `touchesMoved:` but some of our users are sloppy organic humanoids, and they couldn't figure out why taps weren't working. :smiley:
=> Allow User to Move While Touching Link As Long As They Stay In Range

AsyncDisplayKit/ASCellNode.h, AsyncDisplayKit/ASCellNode.m, AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.mm
@nguyenhuy @appleguy Experimenting with Kittens shows that when you enlarge the image this still correctly updates the table view, but when you swap the image and text it correctly does not bother the table view.
- Change delegate method `nodeDidRelayout:` to `nodeDidRelayoutWithSizeChange:` to filter layouts that don't affect height.
- In `ASTableView`, `ASCollectionView`, enqueue `beginUpdates()/endUpdates()` in the run loop. These calls can be expensive – querying 100 nodes for their heights and enqueuing an animation – so this should be worth the effort.
=> Reduce Frequency of beginUpdates/endUpdates Due to Node Relayout

AsyncDisplayKit/ASTextNode.h, AsyncDisplayKit/ASTextNode.mm
This changes the default value to `YES`, which falls in line with many other `thing:shouldActWithThing:` patterns. Also, the text node no longer consults the delegate when handling external calls to `linkAttributeValueAtPoint:`.
I reckon this could be released immediately. Users who don't implement the method obviously aren't using highlighting.
=> Reduce Reliance on -textNode:shouldHighlightLinkAttribute:value:atPoint:

AsyncDisplayKit/ASDisplayNode+Subclasses.h, AsyncDisplayKit/ASDisplayNode.h, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKitTests/ASDisplayNodeTests.m
This resolves #897. I added two test cases, and also posted a toy project https://github.com/Adlai-Holler/ASDKPlainNodeTest.
- Add new interface state `ASInterfaceStateInHierarchy` that unites all others. This is the interface state for non cell-hosted nodes that are in the window hierarchy. I don't like the name – I considered `Unknown` but that seems like none more than all, and I considered `All` but that's not very informative.
- What's the safest way to push the `inCellNode`ness down the hierarchy? It's sort of unsafe to walk up the node hierarchy to check during `willEnterHierarchy` and `didExitHierarchy`
- I added `checkViewHierarchy:` param to `_supernodeWithClass` but honestly I wish I had just removed that behavior altogether. We don't call `_supernodeWithClass` anywhere in our …
=> Provide Basic Interface State Support for Nodes Outside of Cells

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/ASCellNode.m, AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASDisplayNode+Subclasses.h, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/ASDisplayNodeExtras.h, AsyncDisplayKit/ASDisplayNodeExtras.mm, AsyncDisplayKit/ASMultiplexImageNode.mm, AsyncDisplayKit/ASNetworkImageNode.mm, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/ASViewController.m, AsyncDisplayKit/Details/ASRangeHandlerPreload.mm, AsyncDisplayKit/Details/ASRangeHandlerRender.mm, AsyncDisplayKit/Details/ASRangeHandlerVisible.mm, AsyncDisplayKit/Details/_ASDisplayLayer.mm, AsyncDisplayKit/Details/_ASDisplayView.mm, AsyncDisplayKit/Private/ASDisplayNode+AsyncDisplay.mm, AsyncDisplayKit/Private/ASDisplayNode+FrameworkPrivate.h, AsyncDisplayKit/Private/ASDisplayNode+UIViewBridge.mm, AsyncDisplayKit/Private/ASDisplayNodeInternal.h, AsyncDisplayKit/TextKit/ASTextNodeWordKerner.m, AsyncDisplayKitTests/ASDisplayNodeTests.m, AsyncDisplayKitTests/ASSnapshotTestCase.mm
This fixes the recently-reported deadlock, at least to the extent of my testing so far (100% repro with @Adlai-Holler 's test app before, 0% after).
It also adds a new header, ASDisplayNode+FrameworkPrivate.h, to avoid over-usage of *Internal and *+Subclasses.  I cleaned up several such usages.  Having wanted to do this for quite some time, I'm pretty happy to have the file established and know there is more cathartic refactoring to come!
ASHierarchyState itself is obviously similar to ASInterfaceState, but currently has only two state types and does /not/ currently perform operations when the state changes.  Instead, the state is checked by several key codepaths.  I would like to consider expanding this in the future to integrate things like isInHierarchy, and possibly finer-grained …
=> [ASDisplayNode] Introduced ASHierarchyState, eliminating upward traversal and locking.

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/Details/ASCollectionDataController.mm
=> Ensure that newly inserted section supplementary nodes are added to backing store

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/Details/ASDataController.mm, AsyncDisplayKit/Details/ASMainSerialQueue.h, AsyncDisplayKit/Details/ASMainSerialQueue.mm
ASDataController’s completedNodes is accessed by treating the main thread as a serial queue. The ​*problem*​ is, operations can cut in line by being added while on the main thread. I.e. it just calls the block instead of dispatch_async’ing to the main thread. This results in data inconsistency.
To address this, I've added a queue of operations which get run serially (not to be confused with a serial dispatch queue). Instead of running blocks directly on the main thread, if it’s called while not on the main thread, it dispatch_asyncs to the main thread and runs any blocks in the queue. If it ​*is*​ on the main thread, it runs any blocks already in the queue and then runs the block.
=> Fixes out of order blocks running on main queue in ASDataController

AsyncDisplayKit/ASEditableTextNode.mm
Setting clipBounds = NO causes UITextView to overflow in iOS9 (works fine however in iOS8), so we fix by removing this config.
Addressing the deleted comment:
1. From my tests, selection handle doesn't clip anymore in iOS9+ and iOS8.4 simulator
2. If there is clipping of the handle in any case, we recently made the textView inset configurable which should address the problem by providing a way to give the handle room to breathe.
before:
after: (more than three lines, the extra lines are clipped)
This should also fix the placeholder text overflowing which has been reported by @steveram
=> fix overflow issues with ASEditableTextNode's textView

AsyncDisplayKit/Layout/ASDimension.mm
When laying out a node I got to a state where the constrained width was min 132.22222pts and max width was 100%. When resolving the relative size to pts it rounded to 132pt. This caused an assert in ASSizeRangeMake because the min width (132.222pt) was bigger than the max width (132pt)
=> Do not round when resolving relative dimensions

AsyncDisplayKit/TextKit/ASTextKitCoreTextAdditions.m, AsyncDisplayKitTests/ASTextKitCoreTextAdditionsTests.m
Fixed ASTextKit CoreText attributes bug which was incorrectly reading an NSParagraphStyle as CTParagraphStyleRef
=> ASTextKit CoreText attributes cleanse bug

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/ASMapNode.h, AsyncDisplayKit/ASMapNode.mm
Hey @appleguy, here are changes based on your latest feedback
Notable changes:
- Changed init method to `-initWithRegion:` instead of `initWithCoordinate:`
- You can now call setLiveMap before ASMapNode has been loaded to start off with a live map view.
- Smaller syntax changes and clean up.
Just had a thought though, would it be useful for people to be able to change the region after the initialisation of ASMapNode, should we provide a method for this?
=> Improve ASMapNode to get ready for 2.0

AsyncDisplayKit/ASDisplayNode.h, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKitTests/ASDisplayNodeTests.m
This avoids CoreAnimation from capturing the name from a background thread deep within the internals
of AVPlayerLayer, which commits transactions off the main thread.  If the main thread is also accessing
properties that require the lock, in very specific app architectures relying on AVPlayerLayer, this
can cause a deadlock.
The "name" property is primarily used by ASDK's unit test infrastructure, so I'm leaving it in place for
that purpose - and it may still be used for debugging, if someone wants to set it.  It will remain
possible to get the node from a layer or view with asyncdisplaykit_node, and access name from there.
=> Remove CALayer and UIView implementations of "name" property.

AsyncDisplayKit/ASTableView.mm
Ensure they behave as managed nodes - which prevents them from clearContents-ing
their subnodes when the table reloads, as they will be onscreen as long as the table is.
=> Enable node detection for tableHeaderView and tableFooterView on ASTableView.

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Details/_ASDisplayView.mm, AsyncDisplayKitTests/ASDisplayNodeTests.m
Improve UIView & CALayer handling of -addSubnode:, and ensure node hierarchies are hooked up even when addSubview: is used directly.
@1nput0utput, could you please test this?  I have already done so with your app and am pretty sure it is the complete fix.  This one was a hell of a hard time to develop.  I tried all combinations of addSubview / addSubnode for both the ingoing and outgoing of the animation (including mismatched ones - going wild over here!)
I did quite a bit of debugging for the flash, but sadly and strangely have not been able to locate it yet.  The contents of the image node is NOT being cleared and the image is NOT re-decoding.  So I think the actual cause is likely that the view controllers are not swapped out in the same runloop or something like that.
Just so you …
=> [ASDisplayNode] Automatically find and hook up node hierarchies, even when -addSubview: is used directly.

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Details/ASBasicImageDownloader.h, AsyncDisplayKit/Details/ASBasicImageDownloader.mm, AsyncDisplayKit/Private/ASDisplayNode+DebugTiming.mm, AsyncDisplayKit/Private/ASDisplayNode+FrameworkPrivate.h, AsyncDisplayKit/Private/ASDisplayNodeInternal.h, AsyncDisplayKitTests/ASBasicImageDownloaderTests.m, AsyncDisplayKitTests/ASDisplayNodeAppearanceTests.m
Before, it was expensive to check this value, even though it was rarely set.
Now the cost is moved to setting the value, and is made very cheap to check with _hierarchyState.
=> [ASDisplayNode] Order-of-magnitude speedup in handling of "disable visibility" notifications.

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/ASButtonNode.h, AsyncDisplayKit/ASButtonNode.mm
@appleguy This small change allows content alignment like in the UIButton. The reason I had initially implemented this was to align 4 ASButtonNodes with flexBasis set with ASRelativeDimension(type: .Percent, value: 0.25). I simply wanted the ability to align ASButtonNode's content to make my whole view look good. I will create another PR for other behaviours I have in my app.
=> ASButtonNode content alignement properties

AsyncDisplayKit/ASMapNode.h, AsyncDisplayKit/ASMapNode.mm
This fixes #971 as raised by @tomizimobile. It also greatly improves the internal logic of ASMapNode. Most notably:
- You can now set _liveMap = YES on a background thread, and it will only be actioned when that node comes on screen.
- Added asserts to handle layer backing scenarios.
- Added a few additional comments to improve documentation.
Will add an example app and tests in a future diff (soon :D )
@appleguy
=> [ASMapNode] Greatly improve the internal logic of ASMapNode. Also fixes bug #971

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit.xcworkspace/contents.xcworkspacedata, AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/Details/ASDelegateProxy.h, AsyncDisplayKit/Details/ASDelegateProxy.m, AsyncDisplayKitTests/ASBasicImageDownloaderTests.m, examples/ASCollectionView/Sample.xcodeproj/project.pbxproj, examples/ASCollectionView/Sample.xcworkspace/contents.xcworkspacedata, examples/ASCollectionView/Sample/AppDelegate.h, examples/ASCollectionView/Sample/AppDelegate.m, examples/ASCollectionView/Sample/PresentingViewController.h, examples/ASCollectionView/Sample/PresentingViewController.m, examples/ASCollectionView/Sample/ViewController.m
In addition to being a nice cleanly refactoring, this should resolve the task from @tomizimobile - https://github.com/facebook/AsyncDisplayKit/issues/982
It also supersedes / integrates the work from @RuiAAPeres to ensure that both ASTableView and ASCollectionView can run without any delegate set on them, since those protocols are technically optional (though very commonly used).  That is to say, this diff replaces https://github.com/facebook/AsyncDisplayKit/pull/960
=> New ASDelegateProxy class to unify logic for Table & Collection forwarding.  Fix dealloc-during-animation crash.

.travis.yml, build.sh, examples/Swift/Sample.xcodeproj/project.pbxproj, examples/Swift/Sample/ViewController.swift
@appleguy Pursuant to https://github.com/facebook/AsyncDisplayKit/pull/664#issuecomment-141697512 , here's a branch that just has the Travis updates. On my local machine using Xcode 7A220 I still get the same unrecognized selector errors for category properties like `CALayer.asyncdisplaykit_node`
=> Travis use Xcode 7

AsyncDisplayKit/Details/ASCollectionDataController.mm, examples/CustomCollectionView/Sample/ViewController.m
This only occurs after reloading individual sections (not inserting them, or reloading everything).
Thank you @wieseljonas for reporting this in https://github.com/facebook/AsyncDisplayKit/issues/986 - and providing a test case modification to CustomCollectionView.  It is the only way I was able to fix this for 1.9.4, and I think this just about wraps up the release.
=> Supplementary nodes must be added to the completed nodes after their measurement completes.

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKitTests/ASDisplayNodeTests.m
This behavior changed in 1.9.3 and introduced flickering in some cases.  Preserving the contents is closer to UIKit behavior.
Thank you @tuyuan2012 for reporting this in https://github.com/facebook/AsyncDisplayKit/issues/991, and providing a test project that made it easier to fix in the most correct way!  @Adlai-Holler, heads up regarding this behavior - I think you may have been expecting it to clear the contents here, so make sure your app calls -clearFetchedData and/or -clearContents manually if so.  I am thinking of other ways to refine this behavior in the future, such as suspending updates to interfaceState in certain situations and then un-suspending them to apply a pending state.
=> [ASDisplayNode] Preserve contents after non-range-managed nodes are removed from superviews or windows.

AsyncDisplayKit/ASPagerNode.h, AsyncDisplayKit/ASPagerNode.m, examples/VerticalWithinHorizontalScrolling/Sample/ViewController.m
It was being overwritten to be "self", but the final implementation of ASPagerNode turned out to not need any delegate methods.
=> [ASPagerNode] Ensure delegate property can be set before the view is loaded.

AsyncDisplayKit/ASTableView.mm
Allow ASNodeCell to specify pointInside of UITableViewCell.
This is very usefull, if ASNodeCell is presented as bubble aligned to
left or right (like Messages.app) and we need to be able to select row
only if user taps on bubble.
=> Bridge UITableViewCell pointInside to ASNodeCell

AsyncDisplayKit/ASTableView.mm
Reverts facebook/AsyncDisplayKit#1008 -- cc @yury 
I want to make sure this is supported for all ASCellNodes before it is delivered in a production release.  I investigated supporting it in ASCollectionView and ran into some concerns with how the frames are set on the node (they are not necessarily equal to the size of the item cell, yet are at a 0, 0 position that can't be controlled by the engineer).  This could cause regressions for some apps where the touch target becomes smaller than they desire / currently experience.
I think the right fix for this could be to use ASControlNode or similar inside the ASCellNode, rather than relying on the UITableView or UICollectionView tap delegate methods responding only to an area that is smaller than the UIKit component actually is.  That said, …
=> Revert "[ASCellNode] Forward pointInside to node implementation from UITableViewCell."

AsyncDisplayKit/ASCellNode.m, AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/Details/ASDelegateProxy.m, examples/CustomCollectionView/Sample/ViewController.m
cc @levi, @stowy maybe we can fix this at some point soon, but for now, away they go - they're not safe to use unless reconciled with the async layout delay.
=> Prevent calling unsupported UICollectionViewDelegate methods (supplementary view appearance)

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/ASPagerNode.m, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/Details/ASAbstractLayoutController.h, AsyncDisplayKit/Details/ASAbstractLayoutController.mm, AsyncDisplayKit/Details/ASCollectionViewLayoutController.h, AsyncDisplayKit/Details/ASCollectionViewLayoutController.mm, AsyncDisplayKit/Details/ASFlowLayoutController.mm, AsyncDisplayKit/Details/ASLayoutController.h, AsyncDisplayKit/Details/ASLayoutRangeType.h, AsyncDisplayKit/Details/ASRangeController.h, AsyncDisplayKit/Details/ASRangeController.mm, AsyncDisplayKit/Details/ASRangeControllerBeta.h, AsyncDisplayKit/Details/ASRangeControllerBeta.mm, AsyncDisplayKit/Details/ASRangeHandlerPreload.mm, AsyncDisplayKit/Details/ASRangeHandlerRender.mm, AsyncDisplayKit/Details/CGRect+ASConvenience.h, AsyncDisplayKit/Details/CGRect+ASConvenience.m, AsyncDisplayKit/Details/UICollectionViewLayout+ASConvenience.m, AsyncDisplayKit/Private/ASDisplayNode+FrameworkPrivate.h, AsyncDisplayKit/Private/ASDisplayNode+UIViewBridge.mm, examples/VerticalWithinHorizontalScrolling/Sample/AppDelegate.m, examples/VerticalWithinHorizontalScrolling/Sample/GradientTableNode.mm, examples/VerticalWithinHorizontalScrolling/Sample/RandomCoreGraphicsNode.h, examples/VerticalWithinHorizontalScrolling/Sample/RandomCoreGraphicsNode.m
Lots more to come here.
- The display queue system needs to be significantly upgraded.  It has to be able to check for parent-child relationships in its queue, minimize lock contention, and support neverShowPlaceholders.
- ASLayoutController will be revised, particularly the removal of updateBounds and changing how range "validity" is used so that updates are more frequent, allowing the code to be more functional.
- Nested ASRangeControllers will be supported, with a notion of collaborating orthogonal elements.
- Visibility will be inherited from above, such that a currently-offscreen view being preloaded will not tell its about-to-be visible cells that they are visible until they truly are.
=> [ASRangeController] Newly rewritten, functional-style range controller based on ASInterfaceState.

AsyncDisplayKit/ASViewController.h
This pull request allows subclasses of `ASViewController` to specify the type of `ASDisplayNode` it
contains which allows for stronger type-checking and auto-completion against
the specified display node type.
Example Subclass Declaration:
```
@interface MyASViewController : ASViewController<MyASDisplayNodeSubclass *>
@end
```
=> Update interface of ASViewController to use lightweight generics. 

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/ASControlNode.m
Mutation crash in ```- (void)sendActionsForControlEvents:(ASControlNodeEvent)controlEvents withEvent:(UIEvent *)event```
The crashed is due to removing a target within the selector body.
```
func addTarget() {
self.addTarget(self, action: "tapMe", forControlEvents:  .TouchUpInside)
}
func tapMe() {
self.removeTarget(self, action: "tapMe", forControlEvents:  .TouchUpInside)
}
```
=> Fix ASControlNode mutation crash

AsyncDisplayKit/ASButtonNode.mm, AsyncDisplayKit/ASControlNode.h, AsyncDisplayKit/ASControlNode.m
- selected state isn't implicitly controlled by ASControlNode anymore
- highlighted state can be overriden by users
- Decouple ASButtonNode's state from control events
@appleguy @connor
=> Make ASControlState imitate UIControlState

AsyncDisplayKit/Details/ASRangeController.mm
This addresses #1028 #1055 #1047 .
The issue seems to be caused by one of the changes in ffcddf3 where we stopped checking if the range was valid before removing nodes from the working range. I just reverted that change exactly as-was and the issue is gone for me.
@appleguy I'm not sure the implications of this change. I suspect it means that under certain conditions, nodes won't be removed from the working range. We may now be throwing the baby out with the bathwater.
=> Resolve Internal Inconsistency During Updates When Using Stable Range Controller

AsyncDisplayKit/ASControlNode.m
On iPhone 6s, iOS 9.2 (and maybe other versions) sometimes calls -touchesEnded:withEvent: on the view for one call to -touchesBegan:withEvent:. On ASControlNode, it used to trigger twice an action unintentionally. Now, we ignore that even if we're not in a tracking state in order to have a correct behavior.
It might be related to that issue: http://www.openradar.me/22910171
=> Fixed behavior of ASControlNode when -touchesEnded:withEvent: sometimes firing twice.

AsyncDisplayKit/ASCollectionView.h, AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.h, AsyncDisplayKit/ASTableView.mm
If I delete a node from the data source while it's on-screen, I'd like the table view delegate to know which node will end displaying. Using `nodeForRowAtIndexPath:` is incorrect because the node will already have been removed from the table view at this point, and I'll get some other node instead.
I've tested this in my project and it's working well, both for scrolling nodes offscreen and deleting/replacing nodes.
=> Add New didEndDisplayingNode:forItemAtIndexPath: delegate methods to provide removed node

AsyncDisplayKit/Details/ASThread.h
Looks like not only are spin locks dumb, they're also dangerous!
Recently big time Apple engineers have said spin locks are illegal on iOS. So for the sake of cleanliness, I think we should remove the corresponding class.
Source: http://mjtsai.com/blog/2015/12/16/osspinlock-is-unsafe/
=> Remove SpinLock to ensure it doesn't get used in new code.

AsyncDisplayKit/TextKit/ASTextKitRenderer.mm
Hey @appleguy This is to fix the bug specified in #1076. I'm not entirely sure this is the correct place in the stack to fix this issue. The issue stems from the fact that the `headIndent` property of NSAttributedString actually alters the origin of the boundRect rather than just increase it's size. This bug fix address this by incorporating the origin offset into the final size calculation.
The `tailIndent` property seems to break things even more, that can be fix in a future diff (haven't got to the bottom of that)
=> [ASTextKitRenderer] Potential fix headIndent attribute not being accounted for by the shadower.

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/ASCollectionNode+Beta.h, AsyncDisplayKit/ASCollectionNode.h, AsyncDisplayKit/ASCollectionView.h, AsyncDisplayKit/ASCollectionView.mm
@appleguy 
There's only one public interface that allows users to create a collectionNode/View with the new layoutFacilitator, and the interface is hidden in the +beta header.
=> Remove public interface for ASCV with facilitator

README.md
As specified in #1086. Hey @appleguy Turns out these links have been there all along but were just hidden since they were using http (I think). The img.shields.io is a bit unstable at times but seems to be the best solution so far. Will update in future if better solutions come up!
=> Update ReadMe to include Cocoapods downloads badge

AsyncDisplayKit/ASTextNode.mm
This is a small fix where we coalesce the nil before checking equality so that the text node will correctly ignore setting the text to nil when it is already at "". 
A bigger change would be to make ASTextNode's nullability consistent. Currently it defaults to nil at initialization, and then if you set it to nil any time after that it gets set to "". I don't know much about the our TextKit setup so I didn't want to pull that thread in this PR.
=> Make ASTextNode Ignore Setting Text to Nil When Text Is Already Empty

AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/Details/ASCollectionDataController.mm, AsyncDisplayKit/Details/ASDataController.h, AsyncDisplayKit/Details/ASDataController.mm, AsyncDisplayKit/Details/ASRangeController.h, AsyncDisplayKit/Details/ASRangeController.mm, AsyncDisplayKit/Details/ASRangeControllerBeta.mm
and notify its delegate once instead of a series of deletes and inserts. UITableView and UICollectionView are notified via `reloadData` and so flashes are minimized (if not eliminated).
I'm not sure if I also need to change anything in ASCollectionDataController, especially `prepareForReloadData` and `willReloadData`? Tests are passing though (excepts snapshot tests, which is a different story I guess).
Will consider applying the same fix to `reloadRows` and `reloadSections` if this diff gets through.
=> [ASDataController] Optimize reloadData to avoid performing deletions or insertions.

AsyncDisplayKit.podspec, AsyncDisplayKit/ASDisplayNode.h, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/ASEditableTextNode.mm, AsyncDisplayKit/ASMapNode.h, AsyncDisplayKit/ASMapNode.mm, AsyncDisplayKit/ASMultiplexImageNode.h, AsyncDisplayKit/ASMultiplexImageNode.mm, AsyncDisplayKit/ASPagerNode.m, AsyncDisplayKit/ASTableViewProtocols.h, AsyncDisplayKit/Details/ASPhotosFrameworkImageRequest.h, AsyncDisplayKit/Details/ASPhotosFrameworkImageRequest.m, AsyncDisplayKit/Details/_ASDisplayView.mm, AsyncDisplayKit/Private/ASDisplayNode+UIViewBridge.mm, AsyncDisplayKit/Private/_ASPendingState.m
This is currently WIP but I wanted to issue a PR to start a discussion about how to best support tvOS. My initial findings are that it is relatively easy to make ASDK build on tvOS and further more expose the relevant methods (`UIFocusEnvironment` Protocol) that are needed to lay the foundation of tvOS support, as witnessed by this PR.
The **main** work is making all the nodes in ASDK respond to the UIFocus Engine. I am in favour of having a default behaviour implementation on ASDisplayNode that is then inherited by all other nodes. This will ensure that all nodes have a basic behaviour, which can then be overridden to provide a better experience.
Once the default behaviour approach is decided, the second decision to be made is who's responsibility it is to provide great UIFocus …
=> [WIP][tvOS] ASDK tvOS support

AsyncDisplayKit/ASMapNode.h, AsyncDisplayKit/ASMapNode.mm
@appleguy this will resolve #988 
Breaking Change:
`region` property has been superseded by `options` which is a MKMapSnapshotOptions object. This allows for more flexibility and customisation. All snapshot options will be applied to the MKMapView when it is activated.
Currently working on an example app and tests to better showcase ASMapNode!
=> [ASMapNode] now supports MKMapSnapshotOptions 

AsyncDisplayKit/ASButtonNode.h, AsyncDisplayKit/ASButtonNode.mm
Align the ASButtonNode API with that of UIButton. These new methods will ease the pain of creating NSAttributedString when you only really want is set a title or a colour on ASButtonNode.
=> [ASButtonNode] Add support for backgroundImage.  Extend & simplify API with separate title and color.

AsyncDisplayKit/ASCollectionNode+Beta.h, AsyncDisplayKit/ASTextNode.mm, AsyncDisplayKit/TextKit/ASTextKitContext.h, AsyncDisplayKit/TextKit/ASTextKitContext.mm, AsyncDisplayKit/TextKit/ASTextKitRenderer.h, AsyncDisplayKit/TextKit/ASTextKitRenderer.mm, AsyncDisplayKit/TextKit/ASTextKitTailTruncater.mm, AsyncDisplayKit/TextKit/ASTextKitTruncating.h, AsyncDisplayKitTests/ASTextKitTruncationTests.mm
This also fixes three fairly subtle but serious bugs: #1076, #1046 and #1031.
cc @aaronschubert0 - note I ended up tracing a logic flaw to the most recent patch in this area (#1079), which altered the inset handling with the shadower.  I'm still glad you put up this change because it did very clearly appear to improve the behavior, but worsened other situations, like the centering case.  
@nvh - you'd be the most valuable tester, although I confirmed both types of clipping miscalculations very strategically recreated in your awesome sample app appear fully corrected.
@yxztj - I actually was using your sample app for the majority of the time it took me to carefully understand and adjust this code.
@bsmith11, @timominous, @AttilaTheFun, @nguyenhuy, @1nput0utput, @stowy, @lappp9, @RCacheaux, …
=> [ASTextNode] Optimize handling of constrained size to almost never recreate NSLayoutManager

AsyncDisplayKit/ASDisplayNode+Subclasses.h, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/ASTextNode.mm
This allows the change in size for the NSTextContainer to occur off the main thread, whenever that size change is necessary.  Then the text relayout can occur earlier, during the process of computing ASLayoutSpecs.
=> [ASLayout, ASTextNode] Create -calculatedLayoutDidChange and use it in text node.

AsyncDisplayKit/Details/ASRangeControllerBeta.mm
@knopp, please do take a look!  Is there any more efficient way you can think to do this?  I'm particularly bummed about creating all the index paths - I think we could make an alternate codepath that iterates over the nodes themselves, keeping a local integer of section and item number, doing something like the multidimensional helper function does internally by building up the index path by index - but not having to create a full array of them.  This might not help efficiency much, though it would also eliminate accessing the nodes out of the 2D array.
=> [ASRangeControllerBeta] Scan all nodes after edit operations.

AsyncDisplayKit/ASTextNode.mm
Actually it is possible that truncated string is longer then original
string.
For example, original string:
```
hello
this is
very long
message here
and there
```
with maximumNumberOfLines=4, truncationAttributedString = ' ...' and
additionalTruncationMessage = 'read more'
will give
```
hello
this is
very long
message here ... read more
```
So `[attributedString attribute:attributeName atIndex:characterIndex
longestEffectiveRange:&range inRange:visibleRange]` will crash.
=> [ASTextNode] Fix out-of-bounds error when truncation string is longer than the original string.

AsyncDisplayKit/TextKit/ASTextKitRenderer.mm
See [comment](https://github.com/facebook/AsyncDisplayKit/commit/99fbc97bdaecd2f99009b9734ba0f8f2b665632b#commitcomment-15649130)
Fixes #865.
attributedString on ASTextNode should be set after all truncationStrings...
=> [ASTextNode] Prompt creation of truncater object when the context object is accessed.

AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/Details/ASDataController.h, AsyncDisplayKit/Details/ASDataController.mm, AsyncDisplayKit/Details/ASRangeController.h, AsyncDisplayKit/Details/ASRangeController.mm, AsyncDisplayKit/Details/ASRangeControllerBeta.mm
The ASCollectionView data inconsistency crash introduced by #1093 occurs because I didn't apply the same workaround added in #672. With the root cause discovered, I'd like to bring that PR back. When time permits, I will write a unit test to make sure this kind of crash won't happen again.
=> Bring reloadData optimizations back

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/Details/Transactions/_ASAsyncTransaction.mm
Relevant for #1080 
GCD can get *very* impatient. I've seen dozens of spawned threads during scrolling on iPad 3 when the rendering doesn't keep up. The semaphore in `ASDisplayNode+AsyncDisplay` doesn't help much when this happens and the main thread gets crushed.
The patch introduces a very lightweight queue/group that reliably limits number of drawing threads and reduces GCD calls (which can get expensive when there's lot queued). In future the queue could also be used for rendering prioritization if desired (i.e. prioritize rendering labels to images, etc).
=> [_ASAsyncTransaction] limit number of spawned threads

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/ASTextNode+Beta.h, AsyncDisplayKit/ASTextNode.h, AsyncDisplayKit/ASTextNode.mm, AsyncDisplayKit/TextKit/ASTextKitAttributes.h, AsyncDisplayKit/TextKit/ASTextKitFontSizeAdjuster.h, AsyncDisplayKit/TextKit/ASTextKitFontSizeAdjuster.m, AsyncDisplayKit/TextKit/ASTextKitRenderer.h, AsyncDisplayKit/TextKit/ASTextKitRenderer.mm
User can specify a minimumScaleFactor on ASTextNode. 
Then the ASTextRenderer will shrink the font size if there are words that doesn't fit in the container.
If the word is too long, i.e. even with the minimumScaleFactor applied, it sill doesn't fit in the container. Then it will fall back to the default font size.
=> [ASTextNode] Support iteratively shrinking font size in order to ensure no single words are wrapped.

AsyncDisplayKit/ASDisplayNode.h, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Details/Transactions/_ASAsyncTransaction.h, AsyncDisplayKit/Details/Transactions/_ASAsyncTransaction.mm, AsyncDisplayKit/Private/ASDisplayNode+AsyncDisplay.mm, AsyncDisplayKit/Private/ASDisplayNodeInternal.h
Something to consider.
Two commits here. One somewhat unrelated tweaks number of threads. Just `activeProcessorCount` does indeed seem to be a bit conservative. New code does `activeProcessorCount * 2` and decreases the result by 1 when tracking.
Second implements prioritization of transaction operations. Priority is a number, operations with higher priority are more likely to get executed sooner. Some details:
* one (first) processing threads executes all operation in queue order; This is to ensure that even lower priority operations will not be completely ignored; Subsequent threads execute higher priority operations first
* scheduling and retrieving scheduled operations is done in constant time (in practice; corner cases where no two operations have same priority, would be log(n), but …
=> [_ASAsyncTransaction] implement operation priority

AsyncDisplayKit/ASCollectionNode+Beta.h, AsyncDisplayKit/ASCollectionNode.mm, AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASCollectionViewLayoutFacilitatorProtocol.h, AsyncDisplayKit/Details/ASCollectionInternal.h
so when someone is trying to insert/delete/update cells/sections at the same time can batch them in an easy fashion:
```
[self.collectionNode beginUpdates]
updates()
[self.collectionNode endUpdatesAnimated:NO];
```
@appleguy @levi
=> expose beginUpdates and endUpdates

AsyncDisplayKit.xcodeproj/project.pbxproj
This fixes the problems described in #1116 
I guess because the prefix headers weren't used when compiling the framework target, the preprocessor macro's weren't available and the code in the `ASMultiPlexImageNode` implementation was removed by the preprocessor.
=> Added Prefix Headers to framework target

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/TextKit/ASLayoutManager.h, AsyncDisplayKit/TextKit/ASLayoutManager.m, AsyncDisplayKit/TextKit/ASTextKitContext.mm, AsyncDisplayKitTests/ASTextKitTests.mm
Addresses issue #967 by subclassing `NSLayoutManager` to force TextKit to use `NSForegroundColorAttributeName` in all cases including when rendering text with link attributes. Also adds tests for this by comparing against a `UITextView` with `linkTextAttributes` set to the same color.
=> [ASTextKit] Use NSForegroundColorAttributeName for links in ASTextKitRenderer

AsyncDisplayKitTests/ASTextKitTests.mm
Fixes a typo when copying the attribute value in testLinkInTextUsesForegroundColor snapshot test and varies underline color to improve the test case. Also verified tests were working by comparing images generated by snapshot.
=> Fix attribute value setting in testLinkInTextUsesForegroundColor 

AsyncDisplayKit.podspec, AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/ASTextNode.mm, AsyncDisplayKit/TextKit/ASTextKitAttributes.h, AsyncDisplayKit/TextKit/ASTextKitContext.h, AsyncDisplayKit/TextKit/ASTextKitContext.mm, AsyncDisplayKit/TextKit/ASTextKitRenderer.mm, AsyncDisplayKit/TextKit/ASTextKitTailTruncater.mm, AsyncDisplayKitTests/ASTextKitTruncationTests.mm, examples/Kittens/Sample/KittenNode.mm
* Added a member to `ASTextKitAttributes` that is an optional delegate to the struct's NSLayoutManager.
* Changed ASTextNode to set this delegate to an instance of ASTextNodeWordKerner.
* Updated init method of `ASTextKitContext` to take an optional NSLayoutManager delegate
* Added the files in TextKit folder to the public headers (so we can include ASTextNodeTypes.h)
=> Added ASTextNodeWordKerner support to ASTextNode

AsyncDisplayKit/ASDisplayNode+Beta.h, AsyncDisplayKit/ASDisplayNode.h, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/ASImageNode.mm, AsyncDisplayKit/ASTextNode.mm, AsyncDisplayKit/Details/_ASDisplayLayer.h, AsyncDisplayKit/Private/ASDisplayNode+AsyncDisplay.mm, AsyncDisplayKit/Private/ASDisplayNode+FrameworkPrivate.h, AsyncDisplayKit/Private/ASDisplayNodeInternal.h
This patch switches to instance methods of draw and display for
ASTextNode and ASImageNode to attempt to increase their performance.
It also fixes some thread safety issues in ASImageNode which appear
to have been regressions (though probably not hit very often).
And it sets up work for allowing modification of CGContexts before
and after a node's contents are drawn.
=> Switch to instance methods of draw and display

AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/Details/ASScrollDirection.h, AsyncDisplayKit/Details/ASScrollDirection.m
Addresses Issue #1126 by adding support for batch fetching for ASTableView and ASCollectionViews with inverted transforms by having the scrollDirection take the current transform into account.
=> [ASTableView] make scrollDirection transform aware in ASCollectionView and ASTableView

AsyncDisplayKit/TextKit/ASTextKitRenderer.mm
It seems that text truncation doesn't work if the truncater is initialized after the context is. I previously mentioned a fix in https://github.com/facebook/AsyncDisplayKit/issues/1033 which initialized the truncater in -init, but I think it can be deferred to -_calculateSize.
More background: https://github.com/facebook/AsyncDisplayKit/pull/1110
=> Fix text truncation

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/ASDisplayNode+Beta.h, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Layout/ASLayout.mm, AsyncDisplayKit/Private/ASDisplayNodeInternal.h, AsyncDisplayKit/Private/NSArray+Diffing.h, AsyncDisplayKit/Private/NSArray+Diffing.m, AsyncDisplayKitTests/ASDisplayNodeImplicitHierarchyTests.m, AsyncDisplayKitTests/ArrayDiffingTests.m
=> Implicit node hierarchy handling with ASLayouts

AsyncDisplayKit/ASCollectionView.h, AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/Details/ASAbstractLayoutController.mm, AsyncDisplayKit/Details/ASCollectionViewLayoutController.mm, AsyncDisplayKit/Details/ASFlowLayoutController.mm, AsyncDisplayKit/Details/ASLayoutController.h, AsyncDisplayKit/Details/ASRangeController.mm, AsyncDisplayKit/Details/ASRangeControllerBeta.mm, AsyncDisplayKit/Private/ASInternalHelpers.mm
by avoiding pre-rendering when it is not visible or not scrolling.
Two things to consider:
=> Reduce early creation of views and layers in collection view

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/ASCollectionView.h, AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASPagerNode.h, AsyncDisplayKit/ASPagerNode.m, AsyncDisplayKit/ASTableView.h, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/Details/ASCollectionDataController.h, AsyncDisplayKit/Details/ASCollectionDataController.mm, AsyncDisplayKit/Details/ASDataController.h, AsyncDisplayKit/Details/ASDataController.mm, AsyncDisplayKit/Details/ASDelegateProxy.m, AsyncDisplayKitTests/ASCollectionViewFlowLayoutInspectorTests.m, AsyncDisplayKitTests/ASCollectionViewTests.m, AsyncDisplayKitTests/ASTableViewTests.m
Introducing a block-based API for ASCellNode creation in ASDataController. Move allocations and loaded node layouts to occur during batch layout phase. Existing nodeForItemAtIndex path methods will now have their value's wrapped in a block that will be resolved later in ASDataController during layout.
=> Move ASCellNode allocation off the main thread

AsyncDisplayKit/ASControlNode.m, AsyncDisplayKit/ASTextNode.mm
This reverts commit 35a4b268d64e922b3928f247614b664a9413ad3b, reversing
changes made to 4201df5f31077ea31bf014fc01828c065bd31c1c.
After #1162 was landed, setting `userInteractionEnabled = YES` on a node before adding it as a subnode and then attaching gesture recognizers directly to the node's view no longer worked because the `addTarget:action:forControlEvents` never got fired.
One workaround is to set `userInteractionEnabled = YES` _after_ adding the node as a subnode. However, that seems buggy to me so I think we should revert the original diff.
=> Revert "Merge pull request #1162 from maicki/controlnode-init-optimization"

AsyncDisplayKit/ASPagerNode.m, AsyncDisplayKitTests/ASCollectionViewFlowLayoutInspectorTests.m, AsyncDisplayKitTests/ASCollectionViewTests.m
ASPagerNode's api was not updated while addressing comments in the initial ASCellNode background allocation PR. This change fixes that issue.
=> ASPagerNode's api was not updated while addressing comments

AsyncDisplayKitTestHost/Info.plist
To be able to make http requests in tests we should disable the NSAppTransportSecurity of the AsyncDisplayKitTestsHost target. Otherwise tests like -[ASBasicImageDownloaderTests testAsynchronouslyDownloadTheSameURLTwice] will show an error.
=> Disable App Transport Security in AsyncDisplayKitTestsHost target

AsyncDisplayKit/ASVideoNode.mm
To be consistent with ASControlNode and ASImageNode lock variable naming, maybe it would make sense to rename the lock variable name within ASVideoNodeLock from a generic to a more specific one.
=> [ASVideoNode] Rename lock instance variable

AsyncDisplayKit/ASCollectionView.h, AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASPagerNode.h, AsyncDisplayKit/ASPagerNode.m, AsyncDisplayKit/ASTableView.h, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/Details/ASCollectionDataController.h, AsyncDisplayKit/Details/ASCollectionDataController.mm, AsyncDisplayKit/Details/ASDataController.h
This is mostly a follow-up to the original addition of the block-based asynchronous node creation api that was introduced recently. This change makes synchronous node creation api methods optional but enforces that one of the two approaches is implemented when the dataSource property is set.
=> [Table, Collection, Pager] Update data source protocols to not @require non-block node method.

AsyncDisplayKit/Private/_ASHierarchyChangeSet.h, AsyncDisplayKit/Private/_ASHierarchyChangeSet.m
I'm basically updating the indexPaths of all the reloads based on any deletion/insertions before it.
Here's the verified UIKit behavior, for reference:
**delete/reload** indexPaths that you pass in should all be their** current** indexPaths
**insert** indexPaths that you pass in should all be their **future** indexPaths after deletions
@appleguy @rahul-malik @Adlai-Holler
=> [ASDataController] Adjust index paths for reloads contained in the same changeset as deletes / inserts.

AsyncDisplayKit/Details/ASChangeSetDataController.m, AsyncDisplayKit/Details/ASDataController+Subclasses.h, AsyncDisplayKit/Details/ASDataController.mm, AsyncDisplayKit/Private/_ASHierarchyChangeSet.h, AsyncDisplayKit/Private/_ASHierarchyChangeSet.m
Addressed issues @Adlai-Holler mentioned in the [previous PR](https://github.com/facebook/AsyncDisplayKit/pull/1219)
Added an internal API:
`- (void)reloadRowsAtIndexPaths:(NSArray *)indexPaths withIndexPathsAfterUpdates:(NSArray *)indexPathAfterUpdates withAnimationOptions:(ASDataControllerAnimationOptions)animationOptions`
because with reloads as we just delete+insert them, and after the inserted nodes are completed, we call the super methods on the UICollectionView. This means that the delete indexPaths should be current and insert indexPaths should be future, which will be different in many cases, but we are passing through the same set.
@appleguy @rahul-malik
We need a lot of testing on this, I'll try to write a testing app soon, but I'm really out of cycles at the moment.
=> [ASDataController] Improvements to index paths shifting reloads in changesets.

AsyncDisplayKit/ASTextNode.mm
Before:
After:
Here is a simple app to recreate the bug:
[JumbledText.zip](https://github.com/facebook/AsyncDisplayKit/files/132985/JumbledText.zip)
Eventually I want to look into the issue, but until then this will stop the text error.
Word Kerner is also used in ASEditableTextNode. Should we take it out there as well?
=> Remove wordkerner in ASTextNode to fix jumbled text bug

AsyncDisplayKit/Details/ASChangeSetDataController.m, AsyncDisplayKit/Details/ASDataController+Subclasses.h, AsyncDisplayKit/Details/ASDataController.mm, AsyncDisplayKit/Private/_ASHierarchyChangeSet.h, AsyncDisplayKit/Private/_ASHierarchyChangeSet.m
@adlai-holler @appleguy @rahul-malik
What we are currently doing when batchUpdating:
1. remove the delete items/sections from internal datasource
2. remove the reloading items/section from internal datasource
3. insert reloading items/section from internal datasource
4. insert the insertion items/sections
5. call [super performBatchUpdate] when all nodes are completed.
However, even with index shifting, we run into crashes at step 2 because after we delete items from internal data array in step 1, the indexes of reloads are no longer valid. e.g. original array (item0, item1), we delete item at 0, and reload item at 1. after removing item 0 from internal data array, we try to remove item at index 1, and it crashes.
I think the most straight forward way for us to handle reloads is to just …
=> [_ASHierarchyChangeSet] Improve reload handling in BatchUpdates

AsyncDisplayKit/ASMultiplexImageNode.mm, AsyncDisplayKit/Details/ASImageProtocols.h, AsyncDisplayKit/Details/ASPINRemoteImageDownloader.m
A good old fashioned main-thread short-circuit for our image loading. @appleguy
=> [ASNetworkImageNode] Provide Synchronous Loading Path on Cache Hits

AsyncDisplayKit/ASMultiplexImageNode.mm
As the delegate `- (nullable NSURL *)multiplexImageNode:(ASMultiplexImageNode *)imageNode URLForImageIdentifier:(ASImageIdentifier)imageIdentifier;` does not require `imageIdentifier` to be nullable, we need to check `loadedImageIdentifier` before sending it to the delegate.
I'm not pretty sure why this variable is null, but when using this class on Swift, it causes crashing from my end.
=> [ASMultiplexImageNode] Check loadedImageIdentifer before sending it to delegate

AsyncDisplayKit/ASCellNode.h, AsyncDisplayKit/ASCellNode.m, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Private/ASInternalHelpers.mm
I also snuck in a couple minor tweaks to ASInternalHelpers, replacing [NSThread isMainThread] with ASDisplayNodeThreadIsMain() and using block objects directly rather than wrapping them in more blocks.
=> [ASCellNode] Use ASViewController.node Directly Instead of Wrapping

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/AsyncDisplayKit.h
Adds four missing public headers to the umbrella header in order to prevent warnings when the framework built with the framework target is linked with another project.
Also removes a private header from the umbrella header and from the public headers group.
https://github.com/ekurutepe/ASDKTest is a simple test project which should compile without warnings.
=> Fix Umbrella Header

AsyncDisplayKit/ASCollectionView.mm
Talked to @nguyenhuy and it sounds like there wasn't any need for disabling animations during this resize operation. Enabling this fixes a few animation issues we've been seeing in m3 as of late.
=> Enable animated bounds changes in ASCollectionView

AsyncDisplayKit/ASTableView.mm
Initialize `_asyncDelegateImplementsScrollviewDidScroll` so we forward `scrollViewDidScroll:` calls correctly.
@Xinchi
=> [ASTableView] Fix recent regression to ensure scrollViewDidScroll: is forwarded correctly

AsyncDisplayKit/ASDisplayNode+Subclasses.h, AsyncDisplayKit/ASEditableTextNode.mm
Leaving `[super layout]` out is pretty easy to do (it wasn't required pre-ASLayout) and breaks ASLayout. It's also a big time killer to debug - I can tell you that from experience ;) If you are not using layout this isn't technically required but calling it should be safe. I've also added `[super layout]` to `ASEditableTextNode` to quiet the warning.
=> [ASDisplayNode] Add NS_REQUIRES_SUPER for -layout.

AsyncDisplayKit/ASMapNode.mm
@appleguy This is pretty critical, since if you have a live map and it leaves the display range but stays in the fetch data range, and you scroll back to it, your map will be gone!
I used ASPerformBlockOnMainThread because I believe `fetchData` and `clearFetchedData` may be called off the main thread. If that's not correct, or some other approach is needed, let me know.
=> [ASMapNode] Remove Live Map in clearFetchedData, Not clearContents

AsyncDisplayKit/ASDisplayNode.mm
In `ASDisplayNode+Beta.h`, the method signature is `didCompleteLayoutTransition`, but in `ASDisplayNode.mm`, the actual implementation uses `didCompleteTransitionLayout`. This causes overriding implementation in my node subclass not being called.
=> Fix didCompleteLayoutTransition

AsyncDisplayKit/ASMapNode.h, AsyncDisplayKit/ASMapNode.mm
I decided to make it `nonnull` which incurs a slight performance penalty but it makes for safer code, and it mirrors MKMapView's `annotations` property.
=> [ASMapNode] Promote annotations to a Formal Property

AsyncDisplayKit/ASTextNode+Beta.h, AsyncDisplayKit/ASTextNode.h, AsyncDisplayKit/ASTextNode.mm, AsyncDisplayKit/TextKit/ASTextKitAttributes.h, AsyncDisplayKit/TextKit/ASTextKitRenderer.mm
Was running into issues where the scale factor would get cleared when setting a new `atributedString` on `ASTextNode`.
I was clearing out `currentScaleFactor` when setting an attributedString into `ASTextNode`. It appears that `_calculateSize` isn't always called when setting a new string into a `ASTextNode`. It can be the case that only `drawInContext:bounds:` is called. With `_currentScaleFactor` cleared out the newly created renderer that calls`drawInContext...` was being created with a scaleFactor of 0.
It could be that the fix could simply be to remove the clearing of `currentScaleFactor` from `setAttributedString`, but clearing the scale factor there seems like the right thing to do. Regardless, leaving scaling all in the renderer (what this PR does) seems like the safer fix to me. …
=> [ASTextNode] Stopped trying to cache the currentScaleFactor

examples/ASCollectionView/Sample/PresentingViewController.m, examples/ASCollectionView/Sample/SupplementaryNode.m, examples/ASCollectionView/Sample/ViewController.m, examples/CatDealsCollectionView/Sample/ViewController.m, examples/CollectionViewWithViewControllerCells/Sample/ViewController.m, examples/CustomCollectionView/Sample/ImageCellNode.m, examples/CustomCollectionView/Sample/ViewController.m, examples/HorizontalWithinVerticalScrolling/Sample/HorizontalScrollCellNode.mm, examples/SocialAppLayout/Sample/CommentsNode.h, examples/SocialAppLayout/Sample/CommentsNode.m, examples/SocialAppLayout/Sample/LikesNode.h, examples/SocialAppLayout/Sample/LikesNode.m, examples/SocialAppLayout/Sample/Post.h, examples/SocialAppLayout/Sample/PostNode.h, examples/SocialAppLayout/Sample/PostNode.m, examples/SocialAppLayout/Sample/TextStyles.m, examples/SocialAppLayout/Sample/ViewController.m
Update examples to use collectionView:nodeBlockForItemAtIndexPath: or tableView:nodeBlockForItemAtIndexPath: to return node blocks in ASCollectionDataSource / ASTableDataSource objects as well as overall code improvements.
=> Example improvements

AsyncDisplayKit.xcodeproj/project.pbxproj
I was getting the following error when including AsyncDisplayKit using Carthage:
```-[__NSArrayM asdk_diffWithArray:insertions:deletions:compareBlock:]: unrecognized selector sent to instance 0x7ff2885cd780```
This pull request adds two missing .m files to the iOS Framework target.
=> Added NSArray+Diffing.m and ASDefaultPlayButton.m to iOS Framework target

AsyncDisplayKit/ASVideoNode.mm, AsyncDisplayKitTests/ASVideoNodeTests.m
The current implementation of `setAsset:` does an unsafe cast to `AVURLAsset`. This causes a crash when a AVAsset subclass other than `AVURLAsset` (ex `AVComposition`) is used.
`testVideoNodeDoesNotReplaceAVPlayerItemWhenSameURLIsSet` has also been updated to check if setting different objects with the same URL does not replace the AVPlayerItem.
=> [ASVideoNode] AVAsset type cast safety

AsyncDisplayKit/Details/ASDataController.mm, AsyncDisplayKit/Details/_ASDisplayLayer.mm, AsyncDisplayKit/Private/ASDisplayNode+UIViewBridge.mm, AsyncDisplayKit/Private/ASMultidimensionalArrayUtils.h, AsyncDisplayKit/Private/ASMultidimensionalArrayUtils.mm
These optimizations are surprisingly impactful.  -setNeedsDisplay being called
for every node triggered cancelAsyncDisplay, locking, and memory management overhead
that is completely avoidable because Core Animation triggers first display automatically.
The mutable array copy optimizations reduced this key cost by over 10x, from 52ms to 5ms
on an iPad Air 2 / A8X with a real-world test case.
=> [ASDisplayNode] Optimize -setNeedsDisplay, deep mutable array copies.

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/Details/ASCollectionDataController.mm, AsyncDisplayKit/Details/ASDataController+Subclasses.h, AsyncDisplayKit/Details/ASDataController.mm, AsyncDisplayKit/Details/ASIndexedNodeContext.h, AsyncDisplayKit/Details/ASIndexedNodeContext.m
- It is a container object that holds enough information to construct and measure a cell node
- All information is gathered on main thread. This allows ASDataController to capture the correct state of its data source before going to background.
Next step is to use ASIndexPath as the primary index type of a context. There will be a lazily loaded NSIndexPath object that is created on demand.
=> Introduce ASIndexedNodeContext

AsyncDisplayKit/ASCollectionView.mm
In the Pinterest notifications You tab, the collectionView contentSize height for the first page is always smaller than the bounds height because we need to add a top contentInset so the collectionView doesn't underlap the segmented control node.
We need to include the contentInset in the scrollDirection calculation otherwise it returns ASScrollDirectionNone and the collectionView does not fetch any additional pages.
=> Account for contentInset when calculating ASScrollDirection

AsyncDisplayKit/ASTextNode.mm
A text node's renderer is often invalidated. Save the renderer's constrained size locally so we can use it when creating a new renderer after invalidation.
=> [ASTextNode] Fix bug with constrained size when rendering text the second time

AsyncDisplayKit/Details/ASCollectionDataController.mm
- These calls cause supplementary nodes to be allocated and laid out, but not inserted afterward. So the nodes are thrown away.
- Next time when it is the right time to allocate these nodes, it is the second allocation request and triggers assertion in ASIndexedNodeContext #1296.
@smyrgl Please help me to test this and make sure supplementary nodes are correctly handled.
=> Remove unncessary batch layout calls in ASCollectionDataController

AsyncDisplayKit/ASMultiplexImageNode.mm, AsyncDisplayKit/ASNetworkImageNode.mm
Add deallocation of image in ASMultiplexImageNode. It's mostly the same code as in ASNetworkImage for now. We need to revisit that as soon as we implement the other task and we can streamline that.
Furthermore removed the unecessary extra __block variable in ASNetworkImageNode and ASMultiplexImageNode
=> [ASMultiplexImageNode] Deallocate image on background thread

AsyncDisplayKit/Details/ASMainSerialQueue.mm, AsyncDisplayKit/Details/ASThread.h, AsyncDisplayKit/Details/Transactions/_ASAsyncTransaction.mm
Also, support assertion to log specific return value for pthread_mutex_destroy failures.
=> [_ASAsyncTransaction] Reduce locking overhead by removing C++ stack-allocated MutexLocker objects.

AsyncDisplayKit/ASCollectionView.h, AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.h, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/Details/ASChangeSetDataController.m, AsyncDisplayKit/Details/ASDataController.h, AsyncDisplayKit/Details/ASDataController.mm
The API allows consumer of ASTableView or ASCollectionCiew to block execution of the main thread until all section and row updates are committed.
=> [ASCollection/TableView] Add -waitUntilAllUpdatesAreCommitted to wait for concurrent measurement to finish

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/ASTextNode.mm, AsyncDisplayKit/Details/_ASDisplayView.mm, AsyncDisplayKit/Private/ASDisplayNode+UIViewBridge.mm, AsyncDisplayKit/Private/ASDisplayNodeInternal.h
- Measurement is performed on the calling thread, which can be a background one.
- Transition context is strictly handled on main.
- ASTextNode uses its bounds to initiate a renderer if needed. It can happen during layout measurement, so it uses a new thread safe bounds.
=> [ASDisplayNode] Support measureWithSizeRange: on background, and seamless layout spec animation after complete.

AsyncDisplayKit/ASDisplayNode.mm
Currently the flag was being reset to NO in all cases. It should ignore turning off the hierarchy management when the user has already enabled it.
=> Preserve usesImplicitHierarchyManagement when doing animations

AsyncDisplayKit/ASViewController.m
…licitHierarchyManagement set to YES
There are content inset problems if a ASViewController is initialized with a root node (e.g a ASCollectionNode subclass) that has usesImplicitHierarchyManagement set to YES. The reason for that is that the subviews (e.g. the UICollectionView) of the ASViewController root node get's added to the view hierarchy in measureWithSizeRange: in ASDisplayNode.  measureWithSizeRange: of the root node is called in -viewWillLayoutSubviews in ASViewController. That is too late, so UIKit does not apply the automatic content inset to the UICollectionView anymore.
=> [ASViewController] Trigger measurement pass at viewWillAppear: to ensure implicit hierarchy operations complete in time for UIKit inset configuration.

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/ASCollectionView.h, AsyncDisplayKit/ASCollectionView.mm
Remove section inset delegate for now as it is doing nothing. Or we can deprecate this. 
But it is good to have support for different section inset for different sections. I will explore on a correct version of the sectionInset implementation this weekend.
=> [ASCollectionView] Remove the dead code for section inset behavior & mark it as deprecated

AsyncDisplayKit/ASCollectionView.mm
If a UIScrollVIew has alwaysBounce(Vertical|Horizontal) = YES then it will always be scrollable in that direction.  Adding these additional checks will allow us to handle cases where an ASCV without a flow layout has a data source whose first page load doesn't expand contentSize beyond bounds in the desired scroll direction. When the user scrolls in the intended direction, batch fetching will be triggered if there is more content to load.
=> [ASCollectionView] scrollableDirections must account for alwaysBounce(Vertical | Horizontal)

AsyncDisplayKit/ASControlNode+Subclasses.h, AsyncDisplayKit/ASControlNode.h, AsyncDisplayKit/ASControlNode.mm
[ASControlNode] A debug feature on ASControlNode to visualize tap-able areas (by adding a highlight overlay ASDisplayNode as a subnode) when addTarget:action:ControlEvent: is called. Uses hitTestSlop to get ASControlNode's UIEdgeInset and set the highlight overlay's frame to be the ASControlNode frame + edge insets. Disables clip to bounds on ASControlNode. Enabled by calling +[ASControlNode setEnableHitTestDebug:YES];
=> [ASControlNode] A debug feature on ASControlNode to visualize tap-able areas

AsyncDisplayKit/Details/ASDataController.h, AsyncDisplayKit/Details/ASDataController.mm, AsyncDisplayKit/Details/ASMainSerialQueue.mm, AsyncDisplayKit/Private/ASMultidimensionalArrayUtils.h, AsyncDisplayKit/Private/ASMultidimensionalArrayUtils.mm
This is a substantial performance optimization in cases where apps unnecessarily call insertSections: or similar before the table / collection has initial layout.
=> [ASDataController] If app code issues edit commands before first reload, ignore them, as UIKit will call -reloadData.

AsyncDisplayKit/ASCollectionView.mm
This is important when the ASCollectionNode is itself in a node (like a ASTableView of Collections) where the ASCollectionNode is constructed with a zero size and then later resized to the correct size by the layout system.
=> Ensure that we use the correct default size for collection nodes even if layoutSubviews has not been called yet

AsyncDisplayKit/ASTextNode.mm
In ASTextNode, bail from touchesMoved:withEvent: if the previousLocationInView is the same as the locationInView. On 3D Touch enabled phones, this gets fired with chages in force, and will usually get fired immediately after touchedBegan:withEvent, causing touches to usually be cancelled
=> [ASTextNode] Fix tapping on truncation token for 3D Touch phones

AsyncDisplayKit/ASTextNode.mm, AsyncDisplayKit/Private/ASStackBaselinePositionedLayout.mm, AsyncDisplayKit/TextKit/ASTextKitFontSizeAdjuster.mm
1) cache the scale in the font adjuster. The adjuster will be dealloc'ed when the renderer that owns it is dealloc'ed (or invalidated). Until that time we can trust the scale that the adjuster has computed.
2) When measuring line count, make sure that we are not bounding the height of the container's size. This will cause the wrong number of lines to be returned.
3) Instead of setting the ascender/descender on an ASTextNode when an attributed string is added, wait until after the renderer calculates size. This way, if there is any need to scale the font to fit we can apply that scale to the ascender/descender.
=> [ASTextNode] Improvements to the implementation of the font scale adjuster.

AsyncDisplayKit/ASCollectionView.mm
..if layoutSubviews has not been called yet. This is a more conservative approach than the previous PR #1344 which caused issues for @tomizimobile. This fixes the issues I was seeing and shouldn't break anything else ;) (Previous version could keep the initial relayoutAllNodes from being called in layoutSubviews in some situations.)
=> Ensure that we use the correct default size for collection nodes even

AsyncDisplayKit/TextKit/ASTextKitFontSizeAdjuster.mm, AsyncDisplayKit/TextKit/ASTextKitRenderer.mm
Previously I was multiplying the calculated height of the text by the scale factor. This fails in the case where we have a long string that doesn't fit, but it is shrunk so much that it now has more than enough room in the renderer's constrained size. In this case we fail to update the calculated size's width.
Also updated `lineCountForString` in `ASTextKitFontSizeAdjuster` to reuse a sizer layout manager and text container.
=> [ASTextNode] More refinements to the new font size adjuster behavior.

AsyncDisplayKit/ASTextNode.mm
@appleguy Appreciate your super busy at the moment.
Little fix to address #1295. There is an easy workaround for this but turned out to be a simple fix to correct it to the expected behaviour.
=> [ASTextNode] Fix default ellipsis not showing for line breaks

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASImageNode.mm, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/Details/ASAbstractLayoutController.mm, AsyncDisplayKit/Details/ASLayoutRangeType.h, AsyncDisplayKit/Details/ASRangeController.h, AsyncDisplayKit/Details/ASRangeController.mm, AsyncDisplayKit/Details/ASRangeControllerUpdateRangeProtocol+Beta.h, AsyncDisplayKit/Private/ASWeakSet.m, AsyncDisplayKit/Private/_ASPendingState.mm
Introduces ASLayoutRangeModeVisibleOnly, allowing the preservation of decoded backing stores without any extra padding to
strictly minimize memory usage while supporting immediate re-display of content.  Set visible range controllers to this mode
upon app suspend / memory warning, while more aggressively clearing others to the ASLayoutRangeModeLowMemory mode.
By default, when the app is running and recieves a memory warning, we set the range mode for non-visible controllers to
ASLayoutRangeModeVisibleOnly.  This is because, unlike in the app suspend case where on app resume we can restore controllers
from LowMemory to VisibleOnly, the memory warning doesn't provide a good opportunity to do this.
A new +Beta API to control this behavior is called +setRangeModeForMemoryWarnings:, as some …
=> [ASRangeController] Improvements to application state change and memory warning handling

AsyncDisplayKit/TextKit/ASTextNodeWordKerner.m
`NSControlCharacterWhitespaceAction` has been deprecated since iOS 9. `NSControlCharacterActionWhitespace` is its replacement, which has been available since iOS 7.
=> [TextKit] Replace usage of deprecated NSControlCharacterAction value

AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/Details/ASRangeController.mm, AsyncDisplayKit/Private/ASWeakSet.h, AsyncDisplayKit/Private/ASWeakSet.m
Use this array while enumerating ASRangeController instances in response to UIApplication notifications,
as it is possible for these events to trigger the mutation of the ASWeakSet and cause an enumeration error.
=> [ASWeakSet] Support -allObjects to return a retained array of contents.

AsyncDisplayKit/Layout/ASDimension.h, AsyncDisplayKit/Layout/ASDimension.mm
Often times I find myself doing `[node measureWithSizeRange:ASSizeRangeMake(size, size)]`. Adding this method to make this a little more straightforward to do.
=> [ASDimension / ASSizeRange] Add ASSizeRangeMakeExactSize method

AsyncDisplayKit/ASDisplayNode.mm
Now that I understand the notation, finding that we're not using it correctly.
=> Use property underscore notation for recursivelyTriggerDisplayAndBlock

AsyncDisplayKitTests/ASBasicImageDownloaderTests.m
This test fails occasionally in Travis CI. I've had better luck with asynchronous test consistency when XCTest expectations are used.
=> [Tests] Replace sleep() with XCTest asynchronous expectations

AsyncDisplayKit/ASDisplayNode+Subclasses.h, AsyncDisplayKit/ASDisplayNode.mm
This should fix a deadlock in ASDisplayNode and it's caused by displayWillStart: and where one thread is recursing down the tree and another thread is recursing up the tree. We remove the lock in _pendingDisplayNodes for the property, but need to guarantee that we only modify the _pendingDisplayNodes state on the main thread.
Furthermore add documentation on what thread displayWillStart and displayDidFinish will be called
=> [ASDisplayNode] Fix display node pending node property deadlock

AsyncDisplayKit/ASImageNode.h
`imageModificationBlock` defaults to nil, and can be set to nil.
=> [ASImageNode] Annotate imageModificationBlock as nullable

AsyncDisplayKit/Details/ASRangeController.mm, AsyncDisplayKit/Private/ASMultidimensionalArrayUtils.mm
- optimized ASRecursivelyFindIndexPathsForMultidimensionalArray() to remove enumerateUsingBlock:
- replaced single project call to ASIndexPathsForMultidimensionalArray() in ASRangeController with ASIndexPathsForTwoDimensionalArray()
=> [ASMultidimensionalArrayUtils] Optimization for recursive version, expanded use case of more efficient 2D version

AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/ASDisplayNodeExtras.h, AsyncDisplayKit/ASDisplayNodeExtras.mm, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/Details/ASRangeController.mm, AsyncDisplayKit/Details/ASRangeControllerUpdateRangeProtocol+Beta.h, AsyncDisplayKit/Private/ASDisplayNode+FrameworkPrivate.h
- Only update range mode if visibility changes if the node is not range controlled
- Only change explicitly set range mode if ASRangeController becomes visible
- Return interface state for range controller in ASCollectionView and ASTableView based on if the containing node is range managed
=> [ASRangeController] Improvements for automatic range mode

AsyncDisplayKit/ASNetworkImageNode.mm
This allows -setImage: to fully unlock before it calls -invalidateCalculatedSize.
=> [ASImageNode] -setDefaultImage: should release lock before calling -setImage:

AsyncDisplayKit/ASRunLoopQueue.mm
It is not guaranteed that the runloop will turn if it has no scheduled work, and this causes processing of the queue to stop. Attaching a custom loop source to the run loop and signal it if new work needs to be done
=> [ASRunLoopQueue] Add custom run loop source to signal if jobs are still enqueued, to guarantee another runloop turn.

examples/CustomCollectionView/Sample/MosaicCollectionViewLayout.m
Issue (#1366):
CustomColelctionView example app always returns YES from shouldInvalidateLayoutForBoundsChange: which triggers a re-layout.
Fix:
Comparing CGSize rather than CGRect is enough to  handle rotation support without always triggering a re-layout.
=> [CustomCollectionView Example] Fix shouldInvalidateLayoutForBoundsChange: method

AsyncDisplayKit/ASDisplayNode+Beta.h, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/ASImageNode.mm, AsyncDisplayKit/ASMultiplexImageNode.mm, AsyncDisplayKit/ASNetworkImageNode.mm
If previously-displayed contents is gone (e.g. clearContents), and is not finished displaying
by the time the node is onscreen, recreate the placeholder immediately.
=> [ASDisplayNode] Placeholders should always be recreated if returning to cleared nodes.

AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/Details/ASRangeController.mm, AsyncDisplayKit/Details/ASRangeControllerUpdateRangeProtocol+Beta.h
Grab a strong reference for asyncDataSource and asyncDelegate in ASCollectionView and ASTableView before executing the range update to be sure they are not going away while executing the range update. This can happen in range updates while going back in the view controller hierarchy
=> [ASRangeController] Prevent deallocation of dataSource & delegate in Collection & Table when navigating back, during final range update.

AsyncDisplayKit/ASCellNode.h
Using NS_ENUM macro on ASCellNodeVisibilityEvent improves its Swift interface. This change should cause no side effects in the Objective-C interface.
Interface before:
``` swift
public struct ASCellNodeVisibilityEvent : RawRepresentable, Equatable {
public init(_ rawValue: UInt)
public init(rawValue: UInt)
public var rawValue: UInt
}
/** 
* Indicates a cell has just became visible 
*/
public var ASCellNodeVisibilityEventVisible: ASCellNodeVisibilityEvent { get }
/**
* Its position (determined by scrollView.contentOffset) has changed while at least 1px remains visible.
* It is possible that 100% of the cell is visible both before and after and only its position has changed,
* or that the position change has resulted in more or less of the cell being visible.
* Use CGRectIntersect between …
```
=> [Refactoring] ASCellNodeVisibilityEvent Swift interface

AsyncDisplayKit/ASButtonNode.h, AsyncDisplayKit/ASButtonNode.mm, AsyncDisplayKit/Layout/ASStackLayoutDefines.h, AsyncDisplayKit/Private/ASStackLayoutSpecUtilities.h, AsyncDisplayKitTests/ASStackLayoutSpecSnapshotTests.mm
The Swift interface of these enums are improved when given a consistent prefix. The old names are marked deprecated, and internal uses have been updated.
ex.
``` swift
contentHorizontalAlignment = foo ? .AlignmentLeft : .HorizontalAlignmentNone
```
is now
``` swift
contentHorizontalAlignment = foo ? .Left : .None
```
Interface before:
``` swift
/** Orientation of children along horizontal axis */
public enum ASHorizontalAlignment : UInt {
/** No alignment specified. Default value */
case HorizontalAlignmentNone
/** Left aligned */
case AlignmentLeft
/** Center aligned */
case AlignmentMiddle
/** Right aligned */
case AlignmentRight
}
/** Orientation of children along vertical axis */
public enum ASVerticalAlignment : UInt {
/** No alignment specified. Default value */
case …
```
=> [Refactoring] ASHorizontalAlignment & ASVerticalAlignment Swift interface

AsyncDisplayKit/ASDisplayNode.h, AsyncDisplayKit/ASDisplayNodeExtras.mm
I have some insanely complex table view cells, and as I scroll through them, I eventually get an `NSFastEnumerationMutation` exception when a node leaves the display range. It's crunch time and I'm exhausted, so I don't know what code on my end is modifying the layer tree due to leaving the display range, but I'll attach some snapshots. It's easy to reproduce so if you want to investigate @appleguy let me know. Nothing interesting or consistent going on on other threads.
This also corrects the property declaration for `ASDisplayNode.subnodes`.
=> [ASDisplayNode] When Enumerating Subtree, Copy sublayers to Avoid NSFastEnumerationMutation Exception

AsyncDisplayKit/ASCellNode.h, AsyncDisplayKit/ASEditableTextNode.h, AsyncDisplayKit/ASEditableTextNode.mm, AsyncDisplayKit/Details/ASDataController+Subclasses.h, AsyncDisplayKit/TextKit/ASTextKitRenderer.h
Prior to this change: `ASPanningOverriddenUITextView`'s `_shouldBlockPanGesture` would not reflect `scrollEnabled`'s value unless you assigned it after `didLoad` was invoked.
=> [ASEditableTextNode] Assign textView's scrollEnabled on creation

AsyncDisplayKit/ASDisplayNode.mm
This resolves https://github.com/facebook/AsyncDisplayKit/issues/1436
cc @Adlai-Holler, @maicki, @nguyenhuy, @garrettmoon, @rahul-malik
=> [ASDisplayNode] Alternative implementation of interfaceState -> invisible that avoids a subclass call from -dealloc.

AsyncDisplayKit/ASEditableTextNode.mm
A normal `UITextView` with `scrollEnabled == false` does not capture the scroll-to-top gesture. Which makes sense. If there's nothing to scroll, a command to scrolling to the top would do nothing. This behavior  allows other scroll views a chance to capture the gesture. 
`ASEditableTextNode` does not follow this behavior. This is due to `ASPanningOverriddenUITextView`'s `scrollEnabled` setter preventing changes to the base value.
This change synchronizes `ASPanningOverriddenUITextView`'s `scrollsToTop` value with `scrollEnabled` in its overridden setter. Restoring the base `UITextView` behavior.
Code like this:
```obj-c
editableTextNode.scrollEnabled = NO
editableTextNode.textView.scrollsToTop = NO
```
Is now simply:
```obj-c
editableTextNode.scrollEnabled = NO
```
=> [ASEditableTextNode] Synchronize scrollsToTop with scrollEnabled

AsyncDisplayKit/ASControlNode.mm, AsyncDisplayKitTests/ASControlNodeTests.m
This matches the UIControl behavior based on: [DuplicateActionsTest.playground.zip]( https://github.com/facebook/AsyncDisplayKit/files/205466/DuplicateActionsTest.playground.zip)
=> [ASControlNode] Deduplicate Target-Action-Events Entries, Fix Exception When Removing Nil Target

AsyncDisplayKit/ASMapNode.mm
Sometimes during the first layout passes for complex hierarchies, my map node will get measured with 0-height or 0-width, and MapKit will throw an exception if you set MKMapSnapshotOptions.size with 0 area. This avoids that exception.
=> [ASMapNode] Never Provide Invalid Snapshot Dimensions to MapKit

AsyncDisplayKit/ASVideoNode.mm, AsyncDisplayKitTests/ASVideoNodeTests.m
Addresses #1468 and mutes the player when the node is muted.
=> [ASVideoNode] Ensure mute property is passed onto the internal player

AsyncDisplayKit/ASTableView.mm
A crash currently occurs if called updateCurrentRangeWithMode: on an ASTableNode. The problem is that the ASTableView within the ASTableNode does not expose the rangeController, but the ASTableNode demands it within updateCurrentRangeWithMode:.
=> [ASTableView] Fix crash if called updateCurrentRangeWithMode: on an ASTableNode

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/ASDisplayNode.h, AsyncDisplayKit/ASDisplayNodeExtras.h, AsyncDisplayKit/ASDisplayNodeExtras.mm, AsyncDisplayKit/Details/_ASDisplayView.mm, AsyncDisplayKit/Details/_ASDisplayViewAccessiblity.h, AsyncDisplayKit/Details/_ASDisplayViewAccessiblity.mm, AsyncDisplayKit/Private/ASDisplayNode+UIViewBridge.mm, AsyncDisplayKit/Private/ASDisplayNodeInternal.h, AsyncDisplayKit/Private/_ASPendingState.mm, AsyncDisplayKitTests/ASDisplayNodeTests.m
Improves Accessibility support especially for ASDisplayNodes with that has layerBacked or shouldRasterizeDescendants enabled should still supported by the accessibility mechanism. To enable this the _ASDisplayView implements the UIAccessibilityContainer methods now and is responsible for creating UIAccessibilityElement for subnodes.
Open Questions:
=> [ASDisplayNode] Automatically integrate with Accessibility even for layer-backed or rasterized subtrees.

AsyncDisplayKit/ASControlNode.mm, AsyncDisplayKit/AsyncDisplayKit+Debug.h
- added orange overlay edge highlighting if tapable area clipped by .clipsToBounds of any parent in the hierarchy
- fixed bug in comparison of child / parent rect edges
- updated +Debug.h header to explain colors
=> [ASControlNode] Improved hitTestDebug to account for limiting display area by parent .clipsToBounds

README.md
The "getting started" and "appledoc" links were out of date.
=> [AsyncDisplayKit.org] Updated links in readme

AsyncDisplayKit/ASMapNode.mm, AsyncDisplayKit/Layout/ASDimension.h, AsyncDisplayKit/Layout/ASLayout.h, AsyncDisplayKit/Layout/ASLayout.mm
These conditions already had assertions, but at runtime, an insufficiently tested and incorrect ASLayoutSpec could generate values that cause UIKit to enter an infinite loop (e.g. inside of UICollectionView layout validation).
=> [ASLayout] Add additional validation step to intercept incorrect values in production and safely zero them out.

AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.mm
Don't schedule a new check for a batch fetch if no data changed previous batch fetch.
This addresses #1515
=> [ASBatchContext] If API adoption is incomplete, protect against repeat fetching at end of content.

AsyncDisplayKit.podspec
This pull request moves all mandatory files into its own `Core` subspec.
Cocoapods that have AsyncDisplayKit as a dependency can not exclude `PINRemoteImage`.
Cocoapods are able to specify the `Core` subspec as a dependency:
```
spec.dependency 'AsyncDisplayKit/Core', '~> 1.9.7'
```
```
$ pod spec lint AsyncDisplayKit.podspec
-> AsyncDisplayKit (1.9.7.2)
Analyzed 1 podspec.
AsyncDisplayKit.podspec passed validation.
```
=> Add Core subspec

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKitTests/ASDisplayNodeTests.m
- Also add a small improvement to async transition: Bail early if a scheduled transition was invalidated before its block executes, thus save some CPU cycles that would otherwise be spent on an unnecessary measurement. Idea borrowed from `_enqueueAsyncSizingWithSentinel`.
=> [ASDisplayNode][Refactoring] Remove internal and unused async sizing methods

AsyncDisplayKit.xcodeproj/project.pbxproj
Addresses issue: #875 
As we don't use any C++ features that need the GNU compatibility mode I changed the xcodeproj to use the c++11 flag instead of using the gnu++0x flag which had the GNU compatibility mode features enabled.
=> Fix podspec vs xcodeproj inconsistency with c++ build flag

examples/ASDKgram/Sample/AppDelegate.m, examples/ASDKgram/Sample/CommentView.m, examples/ASDKgram/Sample/CommentsNode.m, examples/ASDKgram/Sample/Info.plist, examples/ASDKgram/Sample/PhotoCellNode.h, examples/ASDKgram/Sample/PhotoCellNode.m, examples/ASDKgram/Sample/PhotoFeedNodeController.m, examples/ASDKgram/Sample/UserModel.h, examples/ASDKgram/Sample/Utilities.m, examples/ASDKgram/Sample/WindowWithStatusBarUnderlay.h, examples/ASDKgram/Sample/WindowWithStatusBarUnderlay.m, examples/ASDKgram/Sample/main.m
- overrode the -(void)fetchData method in PhotoCellNode.m to download the photo’s comments. This method gets called with the PhotoCellNode enters ASInterfaceStateFetchData, which is set by the rangeController.
- UIKIT COMPARISON: I left the comment bulk download (for all photos in a page load) in the PhotoFeedViewController side for UIKit because when implemented in the PhotoTableViewCell, each cell jumped around as it changed size when it came on screen.
- minor appearance updates
- updated color scheme
- fixed status bar style to darkBackgroundColor
- cleaned up layoutSpecThatFits: in PhotoCellNode
=> [ASDKgram example update] overrode -fetchData in PhotoCellNode & addressed PR comments

AsyncDisplayKit/ASVideoNode.h, AsyncDisplayKit/ASVideoNode.mm, AsyncDisplayKitTests/ASVideoNodeTests.m
Isolated fixes extracted from https://github.com/facebook/AsyncDisplayKit/pull/1496 These changes do not touch the player construction / fetchData cleanup from the original PR. I will rebase those changes in a separate PR.
1. Corrects map between `AVLayerVideoGravityResize` and its corresponding `UIViewContentMode` (`ScaleToFill` instead of `Redraw`).
2. Changing gravity now updates the placeholder node's `contentMode`.
3. Replacing the `playButton` now cleans-up the previous button's state.
4. Fix video stalling caused by backgrounding & foregrounding the app.
=> [ASVideoNode] Several small bug fixes, improved code quality, added more tests.

AsyncDisplayKit/Private/NSArray+Diffing.m, AsyncDisplayKitTests/ArrayDiffingTests.m
The issue was: The left operand of '>=' is a garbage value in else if check for lengths[i+1][j] ... I had to rewrite the algorithm to quiet the static analyzer.
I also added a couple of tests for _asdk_commonIndexesWithArray:
@levi @appleguy Could you guys take a look over it please.
=> [NSArray+Diffing] Static analyzer issue with common indexes algorithm in _asdk_commonIndexesWithArray:

AsyncDisplayKit/ASVideoNode.mm
According to AVFoundation [guide](https://developer.apple.com/library/ios/documentation/AudioVideo/Conceptual/AVFoundationPG/Articles/02_Playback.html) on playback, we can't use an AVAsset directly for HTTP live stream media. The latest changes unifying the API under `AVAsset` broke HLS for me.
This change: 
1. first checks if there are tracks loaded on the `AVAsset`
2. if not, creates an `AVPlayerItem` directly from URL
Let me know your thoughts on this change. Thanks!
=> [ASVideoNode] Re-enables HLS support

AsyncDisplayKit/Private/ASSentinel.m
OSAtomicIncrement32 does not work on OS < 7.1
=> Update ASSentinel to use OSAtomicAdd32 to support iOS7.0

AsyncDisplayKit/ASVideoNode.mm, AsyncDisplayKitTests/ASVideoNodeTests.m
Extracted state observing cleanup from #1496. 
These changes include:
1. Simplified visibility state change handling.
2. Switching assets now updates the placeholder image.
3. Placeholder image is now cleared in `clearFetchedData` ([prevents runaway memory usage](https://s3.amazonaws.com/f.cl.ly/items/3i1b3o2G3o1D1u2Y091c/before_after.png)).
4. Review feedback from https://github.com/facebook/AsyncDisplayKit/pull/1549
In hopes to minimize conflicts with other open PRs in this file, I've incorporates changes from https://github.com/facebook/AsyncDisplayKit/pull/1535 & https://github.com/facebook/AsyncDisplayKit/pull/1546
=> [ASVideoNode] State observing cleanup

AsyncDisplayKit/ASCollectionNode.mm, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/ASTableNode.m, AsyncDisplayKit/Private/ASDisplayNode+UIViewBridge.mm, AsyncDisplayKit/Private/ASDisplayNodeInternal.h, AsyncDisplayKit/Private/_ASPendingState.h, AsyncDisplayKit/Private/_ASPendingState.mm
If the background color is applied via the pending state it's applied to the layer of the UICollectionView / UITableview. Unfortunately UITableView / UICollectionView does not consider using the layer backgroundColor property as it's background color, so it needs to be applied to the view after the ASCollectionNode / ASTableNode did load and the view is available
=> Fix ASTableNode / ASCollectionNode backgroundColor does not apply correctly.

AsyncDisplayKit/Details/ASDelegateProxy.m
Currently if the _interceptor and the _target object in ASDelegateProxy are nil and an object calls a method on the ASDelegateProxy it will raise a [NSProxy methodSignatureForSelector:] exception.
The reason for that is that we are not implementing -methodSignatureForSelector that will be called in case -respondsToSelector: will return NO and -forwardingTargetForSelector: will return nil.
Unfortunately just returning nil from -methodSignatureForSelector will not help in this case we have to return some kind of NSMethodSignature. If we would return nil in -methodSignatureForSelector it would raise an selector not found exception. In order to get this object to work properly, the use of a method which creates an NSMethodSignature from a C string and just returns that if no method signature …
=> [ASDelegateProxy] Fix "[NSProxy methodSignatureForSelector:] called!" crash

AsyncDisplayKit/ASVideoNode.mm
Limits the [resuming of buffered videos](https://github.com/facebook/AsyncDisplayKit/pull/1535) to nodes that are visible.
=> [ASVideoNode] Limit resuming of buffered videos to those that are visible

AsyncDisplayKit/ASMapNode.mm
@hannahmbanana @appleguy @garrettmoon 
Thanks for waiting a bit longer while I spent a deeper time looking at this issue. Apologies @hannahmbanana after re-reading your implementation another time it's clear that the issue would be fixed your way also.
However upon reproducing your initial crash (I created a sample project with your example code) and walking through the code, I realised that this assert is no longer needed and is actually a misguiding assert, YES - `self.calculatedSize` may be zero *but* this is actually ok. This is because previously we used to set `self.options.size` to `self.calculatedSize` without any check but this is now in place L:127 & L:281 so this assert is no longer needed. I'm confident that this will solve your issue but please put it to test fully and let me …
=> [ASMapNode] Remove assertion that checks calculatedSize rather than options.size.

AsyncDisplayKit/ASCellNode.m
As discussed in Slack (starting here: https://asyncdisplaykit.slack.com/archives/general/p1461252947000266) there can be layout issues with ASCellNodes in an ASCollectionView. The scenario uses a cell that loads an image from the network, and the size of the image is unknown, so a default aspect ratio is used for layout purposes. When the image loads, the cell is resized using `setNeedsLayout()`. This can occasionally cause cells to overlap, or for there to be large gaps between cells. Removing the check for `self.isNodeLoaded` resolves the issue.
=> [ASCellNode] Remove check to fix layout issues

AsyncDisplayKit/ASDisplayNode+Subclasses.h, AsyncDisplayKit/ASDisplayNode.h, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKitTests/ASDisplayNodeImplicitHierarchyTests.m
- Add layoutSpecBlock to ASDisplayNode
- Add assert so subclasses do not implement layoutSpecThatFits: and provide a layoutSpecBlock
- Move assert for checking if a layoutSpecBlock or one of the three layout methods are overridden. This needs to happen on runtime now as we cannot figure out if a layoutSpecBlock was provided in the class +initialize method
- Fix ASDisplayNodeImplicitHierarchyTests that already had a class with a layout spec block
=> [ASDisplayNode] Add a block API to provide an ASLayoutSpec without having to subclass ASDisplayNode

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/ASCellNode.h, AsyncDisplayKit/ASCellNode.mm
Resolves #1574. `setNeedsLayout` is just a figurehead – the real magic happens in `__setNeedsLayout` so that's where the cell needs to involve itself.
=> [ASCellNode] Repair Layout Delegate Behavior When Triggered Off-Main

AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/Details/ASDataController.mm
Should fix: #1512 and #1569
Further information:
- We mark every node as visible in the ASRangeController which NSIndexPath is returned from visibleNodeIndexPathsForRangeController:
- In visibleNodeIndexPathsForRangeController: we get the visible index path's via a call to UITableView's "indexPathsForVisibleRows" method.
- Unfortunately in this case we cannot use indexPathsForVisibleRows to get all the visible index paths as apparently in a grouped UITableView it would return index paths for cells that are just a bit over the edge of the visible area.
- But this edge cells will never get a call for -tableView:cellForRowAtIndexPath:, but we will mark them as visible in the range controller
- In tableView:cellForRowAtIndexPath: we call -configureContentView:forCellNode
- Because we never …
=> [ASDisplayNode] Fix assertion on cell deallocation due visibility not being cleared

AsyncDisplayKit/ASVideoNode.mm
Originally [reported in Slack](https://asyncdisplaykit.slack.com/archives/general/p1461569479000382). `ASVideoNode` is blocking the UI thread while it loads metadata. It's hard to notice when using a local file, but it's obvious with a remote file on a poor network. @yichungwang created a [simple project to demonstrate the issue](https://asyncdisplaykit.slack.com/files/daydreamer/F1429JP26/videonodesample.zip) 👏 
`AVAsset`'s tracks metadata properties block the calling thread until it the track metadata is known. If the asset is remote, this blocks the thread while waiting on the network.
1.  PR https://github.com/facebook/AsyncDisplayKit/pull/1552 added a call to the `tracks` property on the main thread. 
2.  The changed pulled in from …
=> [ASVideoNode] Fix UI thread blocking with remote assets

_docs/cell-node.md, _docs/containers-ascollectionnode.md, _docs/containers-aspagernode.md, _docs/containers-astablenode.md, _docs/containers-asviewcontroller.md, _docs/containers-overview.md, _docs/layout-engine.md, static/main.css
I changed the style of our \<code\> blocks so they were less aggressive/jarring.  Now they're similar to the code blocks on raywenderlich.com, which means that all big code blocks that aren't inline should use the toggle based divs.
That doesn't mean you have to add the swift version if you don't want to, just copy the html from the "Installation" page if you only want to show one language.
There are also a few wording updates just to make some stuff a little more clear/concise as well as a few cleaned up errors in code blocks.
=> [AsyncDisplayKit.org] General cleanup, styling and rewording

AsyncDisplayKit/ASVideoNode.mm, AsyncDisplayKitTests/ASVideoNodeTests.m
Following up with issue #1600, the following PR modifies `-fetchData` so that we can prepare an asset (HLS and non-HLS) for playback in a uniform way.
Namely:
1. Calls [`-loadValuesAsynchronouslyForKeys:completionHandler:`](https://developer.apple.com/library/ios/documentation/AVFoundation/Reference/AVAsynchronousKeyValueLoading_Protocol/index.html#//apple_ref/occ/intfm/AVAsynchronousKeyValueLoading/loadValuesAsynchronouslyForKeys:completionHandler:) in `-fetchData`.
2. Creates the `AVPlayerItem` and `AVPlayer` in `-prepareToPlayAsset:withKeys:`.
3. No longer extracts the URL from an AVAsset.
In doing so, the AVPlayer is not immediately available when `-fetchData` is called. Thanks and let me know your thoughts :)
@gazreese @ejensen
=> [ASVideoNode] Prepare asset for playback in a uniform way

AsyncDisplayKit/ASNetworkImageNode.mm
Summary:
Because we trampoline to main when setting _currentImageQuality, there would be situations where displayWillStart was called, we get a cached image and set currentImageQuality to 1.0, and then a background thread calling setDefaultImage would enqueue an operation that sets currentImageQuality to 0 and overwrites the correct value.
=> [ASNetworkImageNode] Fix threading issue in current image quality

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/ASVideoNode.h, AsyncDisplayKit/ASVideoNode.mm, examples/Videos/Sample.xcodeproj/project.pbxproj, examples/Videos/Sample.xcworkspace/contents.xcworkspacedata, examples/Videos/Sample/ViewController.m
Added new delegate methods : 
This method is called after each state change. at this moment this states are supported: 
````
typedef enum {
ASVideoNodePlayerStateUnknown,
ASVideoNodePlayerStatePlaying,
ASVideoNodePlayerStateLoading,
ASVideoNodePlayerStatePaused,
ASVideoNodePlayerStateFinished
} ASVideoNodePlayerState
````
This method is called before play and pause actions. asks delegate if play and pause are allowed states for ASVideoNode. For example you can disable pause method for some videos.
This method i called from `periodicTimeObserver` and informs delegate about ASVideoNode playback current time. Can be used for scrubber UI or ads in video. For example you can pause video on 10 second and show some ads. you can control `periodicTimeObserver` timescale by setting …
=> [ASVideoNode] Several new delegate methods and ASVideoNodePlayerState to monitor and control playback

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Private/ASDisplayNodeInternal.h
Currently in a race condition situation it can happen that subnodes get transition ids from supernodes where the supernodes transition id was reset but the subnode still has the old transition id value. This will trigger an exception although the assignment of the transition id is totally valid. This PR should address this by not reseting the transition id at all for a node and increase the transition id for new transitions.
cc @nguyenhuy @appleguy @levi
=> [ASDisplayNode] Improve Transition ID handling

README.md
- update cocoapods numbers
- add slack badge - clicking it should take you to a slack invite landing page using a slack invite bot hosted on Heroku (Slackin)
=> [Update README.md with Slack badge + invite bot]

README.md
Will re-add once we have we have unlimited server time (paid Heroku account or deployed on our own server).
=> [README.md] Removing Slack badge to save server time

AsyncDisplayKit/ASMultiplexImageNode.mm
In a recent update to PINRemoteImage, its memory cache went from storing UIImage instances to containers of NSData which are used to generate a UIImage instance on demand. Unfortunately, these UIImage instances show `isEqual: NO` compared to one another.
Since the images appear to be different, if you wire `ASMultiplexImageNodeDataSource.imageForImageIdentifier` up to synchronously retrieve an image from the PINRemoteImageManager instance, the image will change every time, which will call setNeedsDisplay, which will call displayWillStart, which will call fetchData, which will generate a new UIImage instance.
To break this cycle, this patch avoids requesting the image for an already-loaded image identifier from the multiplex node's data source. The only issue I can see with this is, if you …
=> [ASMultiplexImageNode] Do Not Request Already-Loaded Images From Data Source

AsyncDisplayKit/ASVideoNode.mm, examples/Videos/Sample/ViewController.m
This PR will move ASVideoNode to use layout spec to layout all of it's subnodes.
- This should fix assignment and position adjustments of a custom play button
- We can now use it properly within other nodes as subnodes and it throws an assertion if used the wrong way
- Fix sample project use of ASVideoNode
=> [ASVideoNode] Move layout of ASVideoNode to layout specs

AsyncDisplayKit/TextKit/ASTextKitRenderer.mm, AsyncDisplayKit/TextKit/ASTextKitTailTruncater.mm, AsyncDisplayKit/TextKit/ASTextKitTruncating.h, AsyncDisplayKitTests/ASTextKitTruncationTests.mm
Summary: Previously the first thing we did when calculating the size of text was to truncate it. This could lead to ASFontSizeAdjuster being sent a truncated string which, obviously, never needed to shrink. If we change the order then we first shrink, then truncate if still necessary.
=> Fix to text shrinking

AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/Details/ASDelegateProxy.m
If a delegate / dataSource get's set to nil in ASTableView or ASCollectionView on iOS 8.0 / 8.1 it triggers an accessibility call that the delegate / dataSource proxy is catching. The problem with that is that it goes into a loop as it tries to call `proxyTargetHasDeallocated` what could again trigger to set the delegate / dataSource to nil and the accessibility call is triggered again.
=> [Accessibility / iOS 8] Fix 8.0 and 8.1-only, VoiceOver crash when clearing delegate / dataSource for Table or Collection

AsyncDisplayKit/ASTextNode.h, AsyncDisplayKit/ASTextNode.mm, AsyncDisplayKitTests/ASTextNodeTests.m
- Deprecate attributedString in ASTextNode in favor of attributedText to be aligned with UILabel
- Deprecate truncationAttributedString in ASTextNode in favor of truncationAttributedText to be aligned with attributedText
=> [ASTextNode] Fix API ASTextNode API inconsistencies

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/ASNavigationController.h, AsyncDisplayKit/ASNavigationController.m, AsyncDisplayKit/ASTabBarController.h, AsyncDisplayKit/ASTabBarController.m, AsyncDisplayKit/ASViewController.h, AsyncDisplayKit/ASViewController.mm, AsyncDisplayKit/ASVisibilityProtocols.h, AsyncDisplayKit/ASVisibilityProtocols.m, AsyncDisplayKit/AsyncDisplayKit.h
This adds support for the concept of visibility depth.
Visibility essentially defines the number of user actions it would
take a user to have a view controller visible. Knowing a view controllers
visibility depth allows view controllers to take action such as clearing
out memory that can be restored at a later date.
This patch also add two new view controller subclasses which adopt
the ASManagesChildVisibilityDepth protocol. Any view controller
that has child view controllers can adopt this protocol to indicate
to the child what they're visibility is. For example, ASNavigationController
will return a visibility depth of it's own visibilityDepth + 1 for
a view controller that would be revealed by tapping the back button.
=> [ASViewController] Add visibility depth management

AsyncDisplayKit/Details/ASDataController.mm
In _layoutNodesFromContexts:ofKind:completion: we pass the full array of contexts to _layoutNodes:fromContexts:atIndexesOfRange:ofKind: but for nodes we pass a subarray of nodes instead based on the batchCount. As batchRange we always start from 0 to batchCount. We now use the same indexes that we use to create the subarray of nodes to get a subarray of contexts that we pass to _layoutNodes:fromContexts:atIndexesOfRange:ofKind:.
=> Fix passing wrong constrained size to nodes

AsyncDisplayKit/Details/ASCollectionDataController.mm
- Mutating a dictionary using -enumerateKeysAndObjectsUsingBlock:
can have unintended consequences.
- Using a copy of the keys to iterate over the values inside the
dictionary instead.
=> [Sample] Resolve mutation during enumeration issue

Base/ASAvailability.h
My implementation of AS_AT_LEAST_IOS9 broke when 8.4.1 was released.
I ran the iOS 9.0 simulator to find the proper `kCFCoreFoundationVersionNumber` value for iOS9, added this as `kCFCoreFoundationVersionNumber_iOS_9_0` and updated the `AS_AT_LEAST_IOS9` macro
=> [ASAvailability.h] Add kCFCoreFoundationVersionNumber_iOS_9_0 define

AsyncDisplayKit/ASContextTransitioning.h, AsyncDisplayKit/ASDisplayNode+Beta.h
There may be more public headers missing nullability annotations, but these are the ones I noticed while using them.
=> [Swift] Add missing nullability annotations to transition methods

AsyncDisplayKit/ASImageNode.h
When using this block the border is optional. However, currently it is necessary to pass a non-nil value for `borderColor` even if `borderWidth` is 0.
=> Allow nil borderColor when using ASImageNodeRoundBorderModificationBlock

AsyncDisplayKit/ASTableView.h, AsyncDisplayKit/ASTableView.mm
It is known that the visible nodes of an `ASTableView` are `ASCellNode`s. This diff specialize the `visibleNodes` method in `ASTableView` to return an array of `ASCellNode`s instead of an array of `ASDisplayNode`s. This way, it is both clearer of what the objects of that array truly are and also avoids unnecessary casts when using this method.
=> Change ASTableView's visibleNodes interface to return array of ASCellNodes

AsyncDisplayKit/ASCollectionView.h, AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.h, AsyncDisplayKit/ASTableView.mm
The purpose of this PR is to expose `relayoutAllNodes` from `ASCollectionDataController` to `ASCollectionView` to allow us to manually trigger size changes. Particularly useful during an interactive transition where cells are resized by some try of gesture.
=> expose relayoutAllNodes at ASCollectionView level

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Private/ASDisplayNodeInternal.h, AsyncDisplayKit/Private/ASLayoutTransition.h, AsyncDisplayKit/Private/ASLayoutTransition.mm
Giving the public context object a little more...context. As we complete the layout transition API, this object will be a key facilitator in not just state, but also behavior during the transition duration.
=> [ASDisplayNode] Rename ASDisplayNodeTransitionContext to ASLayoutTransition

Podfile
Resolves the following error with `pod install`
Will resolve https://github.com/facebook/AsyncDisplayKit/issues/1690
```
[!] Invalid `Podfile` file: [!] Unsupported options `{:exclusive=>true}` for target `AsyncDisplayKitTests`..
>  target :'AsyncDisplayKitTests', :exclusive => true do
```
=> remove exclusive => true due to CocoaPods 1.0.0 changes

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/ASEditableTextNode.mm, AsyncDisplayKitTests/ASEditableTextNodeTests.m
- Add ability to measure the ASEditableTextNode based on the content now by calling `measure:`
- ASEditableTextNode considers `preferredFrameSize` now
- Fix crash if ASEditableTextNode is included in a horizontal stack
- Add tests for ASEditableTextNode
Addresses: #1701
=> [ASEditableTextNode] Fix measurement of ASEditableTextNode

examples/SocialAppLayout/Sample/PostNode.m
UITableViewCell traverses through all its descendant views and adjusts their background color accordingly either to [UIColor clearColor], although potentially it could use the same color as the selection highlight itself. After selection, the same trick is performed again in reverse, putting all the backgrounds back as they used to be. But in our case, we don't want to have the background color disappearing so we reset it after highlighting or selection is done.
=> [Example] Fix disappearing of social app example divider

AsyncDisplayKit/ASDisplayNode.h, AsyncDisplayKit/ASDisplayNode.mm, examples/Videos/Sample/ViewController.h, examples/Videos/Sample/ViewController.m
Normally `measure:` will be called on a `ASDisplayNode` before layout occurs. If this doesn't happen, nothing is going to call it at all.  An experimenting developer probably added a node to the hierarchy directly. We now simply call `measureWithSizeRange:` using a size range equal to whatever bounds were provided to that element. This will make initial experimentation using layoutSpecs much easier.
=> [ASDisplayNode] Add automatic measure before layout

AsyncDisplayKit/ASTextNode.mm, AsyncDisplayKit/TextKit/ASTextKitRenderer+TextChecking.mm, AsyncDisplayKit/TextKit/ASTextKitRenderer.h, AsyncDisplayKit/TextKit/ASTextKitRenderer.mm, AsyncDisplayKit/TextKit/ASTextKitTailTruncater.mm, AsyncDisplayKit/TextKit/ASTextKitTruncating.h, AsyncDisplayKitTests/ASTextKitTruncationTests.mm, AsyncDisplayKitTests/ASTextNodeTests.m
The crash happens in the placeholderImage of ASTextNode. The node is not visible in the time it try to get the `placeholderImage` and so the `visibleRange` has count 0 and a crash happens while accessing the first object of an empty array.
I improved tests around that area too so look into the `testHandleZeroHeightConstrainedSize` in `ASTextKitTruncationTests` for an example how the crash can be reproduced
=> [ASTextKitRenderer] Fix crash truncating a string of an ASTextNode with a zero size

AsyncDisplayKit/Details/ASDataController.mm
1. Use NSFastEnumeration directly instead of getting a NSEnumerator for iterating through completedNodes which should improve performance
2. Use the sorted array in `reloadRowsAtIndexPaths:withAnimationOptions:`. Before we just sorted it, but didn't use it :/
3. Remove FIXME about sorting index paths for deleting rows. @Adlai-Holler I saw you added the FIXME, why do you think we should order in descending order before deleting?
cc @appleguy
=> [ASDataController] Small improvements

AsyncDisplayKit/ASDisplayNode.mm, examples_extra/Placeholders/Sample/PostNode.m, examples_extra/Placeholders/Sample/SlowpokeImageNode.m, examples_extra/Placeholders/Sample/SlowpokeTextNode.m
Placeholder are not appearing if a node is measured after the initial placeholder was set. This should fix this behavior by creating the placeholder layer and the placeholder image in the right size while layout happens. 
Furthermore put in a workaround for the Placeholder example that was broken. But would be reproducible by running the Placeholder example and comment out the fix in `ASDisplayNode`.
=> [ASDisplayNode] Fix placeholder image is not appearing if size of node changed after initial placement

AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/Details/ASCollectionViewFlowLayoutInspector.h, AsyncDisplayKit/Details/ASCollectionViewFlowLayoutInspector.m, AsyncDisplayKitTests/ASCollectionViewTests.m
The purpose of the ASCollectionViewCustomLayoutInspector is to provide a default implementation if a custom layout is given, but no layout inspector. We remove the necessary `if` handling if no layout inspector is given and replace it with a "Null Object".
=> [ASCollectionView] Add a "Null Object" for a layout inspector if custom layout is given but no layout inspector

AsyncDisplayKit/ASDisplayNode.mm
=> [ASDisplayNode] Copy Sublayers in recursivelyTriggerDisplayForLayer to Avoid NSFastEnumerationMutation Exception

AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/Details/ASDelegateProxy.m
This supercedes https://github.com/facebook/AsyncDisplayKit/pull/1656, in order to fix a merge conflict.
=> [ASCellNode] Adding support for scroll view begin / end drag to VisibilityEvent changes.

AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/Details/ASCollectionViewFlowLayoutInspector.h, AsyncDisplayKit/Details/ASCollectionViewFlowLayoutInspector.m, AsyncDisplayKitTests/ASCollectionViewTests.m
Reverts facebook/AsyncDisplayKit#1674
@maicki some careful bisecting discovered that this caused a layout regression in the Pinterest feed, so I need to revert it for now.  Looking forward to re-landing once fixed.  Fortunately the issue reproduces every time.
=> Revert "[ASCollectionView] Add a "Null Object" for a layout inspector if custom layout is given but no layout inspector"

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/ASNetworkImageNode.h, AsyncDisplayKit/ASVideoNode.h, AsyncDisplayKit/ASVideoNode.mm, AsyncDisplayKitTests/ASVideoNodeTests.m
Changes:
- remove _placeholderImageNode property of ASVideoNode (uses self.image now instead)
- move layoutSpecThatFits: code to calculateSizeThatFits: & layout: methods as ASImageNode uses calculateSizeThatFits:
As mentioned in #1677.
=> [ASVideoNode] Change superclass to ASNetworkImageNode so that it can be its own placeholder

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Layout/ASBackgroundLayoutSpec.mm, AsyncDisplayKit/Layout/ASInsetLayoutSpec.mm, AsyncDisplayKit/Layout/ASLayout.h, AsyncDisplayKit/Layout/ASLayout.mm, AsyncDisplayKit/Layout/ASLayoutSpec.mm, AsyncDisplayKit/Layout/ASOverlayLayoutSpec.mm, AsyncDisplayKit/Layout/ASRatioLayoutSpec.mm, AsyncDisplayKit/Layout/ASRelativeLayoutSpec.mm, AsyncDisplayKit/Layout/ASStackLayoutSpec.mm, AsyncDisplayKit/Layout/ASStaticLayoutSpec.mm, AsyncDisplayKit/Private/ASDisplayNodeInternal.h, AsyncDisplayKit/Private/ASLayoutTransition.h, AsyncDisplayKit/Private/ASLayoutTransition.mm, AsyncDisplayKit/Private/ASStackUnpositionedLayout.mm, AsyncDisplayKitTests/ASLayoutSpecSnapshotTestsHelper.m, examples/AsyncDisplayKitOverview/Sample/Node Containers/OverviewASPagerNode.m, examples/PagerNode/Sample/PageNode.m
I have this grand master plan of turning our use of ASLayouts into something like a browser render tree, a tree that every node queries when it wants to know its own size and position on screen. This is a change to move into that direction, as constrainedSize ultimately belongs in ASLayout because ASLayoutables (objects that create ASLayouts) all pass a constrainedSize when they generate a layout.
Moreover, I've removed the legacy concept of a node being "measured". Instead, ASLayouts can now be marked as dirty, which then is used to replace the `isMeasured` bit flag. As we mature the underlying ASLayout tree structure, we should move away from "measurement" and begin to use nomenclature that describes generating layouts and rendering nodes.
=> [ASDisplayNode] Move constrained size to ASLayout

AsyncDisplayKit/Details/ASCollectionDataController.mm, AsyncDisplayKit/Details/ASDataController+Subclasses.h, AsyncDisplayKit/Details/ASDataController.mm, AsyncDisplayKit/Private/ASMultidimensionalArrayUtils.h, AsyncDisplayKit/Private/ASMultidimensionalArrayUtils.mm
Currently within `ASCollectionView`, there is an assumption that there will always be a static number of supplementary views per section—even when additional items are added or removed from that section. This is evidenced by the fact that when you invoke -[ASCollectionView insertItemsAtIndexPaths:], the data source method -[ASCollectionDataSource collectionView:nodeForSupplementaryElementOfKind:atIndexPath:] is not invoked, preventing consumers from specifying a new number of supplementary nodes for the new set of items.
With this change, the set of supplementary nodes for a section is now recalculated not only on section-level mutations, but also on item-level mutations as well. This adds item-level counterparts to the section-level `-prepareFor...` subclassing hooks in …
=> [ASCollectionView] Repopulate supplementary views on item-level changes

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Layout/ASLayoutSpec.h, AsyncDisplayKit/Layout/ASLayoutSpec.mm
If a layoutSpec is asked for its `asyncTraitCollection`, it creates it on demand.
=> [ASLayoutSpec] Remove cached ASTraitCollection

AsyncDisplayKit/ASVideoNode.h, AsyncDisplayKit/ASVideoNode.mm
Use a strong reference to the current asset in order to prevent setting a placeholder image if the asset is set to nil while the placeholder image is generating.
Also corrects the documentation of the `periodicTimeObserverTimescale` default.
=> [ASVideoNode] Prevent setting old poster image if the asset was set to nil

AsyncDisplayKit/ASImageNode+AnimatedImage.mm, AsyncDisplayKit/ASImageNode.h, AsyncDisplayKit/ASImageNode.mm, AsyncDisplayKit/Private/ASImageNode+AnimatedImagePrivate.h
`NSDefaultRunLoopMode` suspends while a scrollview is tracking. This causes animated images in the scrollview to pause while scrolling. This behavior is not always desired. So this change enables the configuration of the animation runloop mode.
=> [ASImageNode] Allow configuration of animation runloop

AsyncDisplayKit/ASNetworkImageNode.mm, AsyncDisplayKit/Details/ASImageProtocols.h, AsyncDisplayKit/Details/ASPINRemoteImageDownloader.m
Previously, animated images would only work if the URL is to a remote location. This change adds support to file system URLs. 
I'm not keen on the path extension check. Please let me know if there's a better way to ensure URLs to non-animated images aren't treated as if they are animated.
=> [ASNetworkImageNode] Support loading local animated images

AsyncDisplayKit/ASCellNode.mm, AsyncDisplayKit/ASCollectionNode.mm, AsyncDisplayKit/ASDisplayNode+Subclasses.h, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/ASImageNode+AnimatedImage.mm, AsyncDisplayKit/ASMultiplexImageNode.mm, AsyncDisplayKit/ASNetworkImageNode.mm, AsyncDisplayKit/ASTableNode.mm, AsyncDisplayKit/ASVideoNode.mm, AsyncDisplayKit/ASVideoPlayerNode.mm, AsyncDisplayKit/Details/ASRangeController.mm, AsyncDisplayKitTests/ASDisplayNodeTests.m, AsyncDisplayKitTests/ASVideoNodeTests.m
So at the moment, the naming that seemed to make the most sense was something similar to the view controller lifecycle callback naming conventions.
- (void)didEnterDisplayRange;
- (void)didExitDisplayRange;
- (void)didEnterFetchDataRange;
- (void)didExitFetchDataRange;
I like that -visibilityDidChange: returns a boolean representing whether it is entering or exiting the visible range, but getting the other ones to work that way seems like it would be tough to do without having some sort of difficult to understand naming going on.
Also, I know there is already -fetchData and -clearFetchedData as well as -clearContents, but having these specifically as override methods that don't necessarily imply that you have to do anything specific could be nice?
=> [ASDisplayNode] Added callbacks for entering and exiting fetch data and display ranges

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Layout/ASLayout.h, AsyncDisplayKit/Layout/ASLayout.mm, AsyncDisplayKit/Layout/ASLayoutSpec.mm, AsyncDisplayKit/Layout/ASLayoutable.h, AsyncDisplayKit/Private/ASLayoutTransition.mm, AsyncDisplayKit/_ASTransitionContext.m, AsyncDisplayKitTests/ASLayoutSpecSnapshotTestsHelper.m
My aim here is to simplify the flattening process such that it is an accessible piece of code that new readers can understand. Here's an itemized overview of my process:
1. I cleaned up the flatten BFS — this was original in #1730, but I got carried away cleaning up the entire class. There are now less iterations and it now uses the `flattened` ivar as a visitation marker so that a layout doesn't contain sublayouts that aren't direct subnodes defined in the node's layout spec.
2. Removed the predicate block. It's very flexible having a block-based API, but we currently don't use it effectively to warrant the design. The API has been renamed to `filteredNodeLayoutTree`, to simplify the API footprint and better communicate the resulting structure.
3. `immediateSublayouts` is gone. This was …
=> [ASLayout] Clean up flattening process of ASLayout

AsyncDisplayKit/ASMultiplexImageNode.mm, AsyncDisplayKit/ASNetworkImageNode.mm, AsyncDisplayKit/ASTextNode.mm, AsyncDisplayKit/Private/ASInternalHelpers.h, AsyncDisplayKit/Private/ASInternalHelpers.mm
Currently it’s very suboptimal how many threads ASDK is spawning at some point. You can see that especially by running the ASCollectionView and reload the collection view a couple of times or ASTableViewStressTest example by just running it and push a couple of view controller. It spawns over 100 threads pretty fast.
I looked into that a bit into this and it seems like the main drivers are the dispatches to the background queue in ASTextNode, ASNetworkImageNode, ASMultiplexImageNode where we destroy the text renderer, images etc. 
Instead of using a global background queue this PR is adding a dedicated serial queue that we use to destroy the objects mentioned above. This reduces the threads we spawn tremendously.
=> [Performance] Prevent GCD thread explosion due to object deallocation workloads (serial deallocation queue).

AsyncDisplayKit/ASEditableTextNode.mm
Rounding up to the next device pixel was calculating a height smaller
than UITextView's contentSize. This was causing the baseline to move as
the user was typing.
=> [ASEditableTextNode] Round up editable text node to the next point

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Private/ASLayoutTransition.mm, AsyncDisplayKitTests/ASDisplayNodeTests.m
The prior implementation of removeFromSupernode would acquire _propertyLock and then attempt to lock the supernode (e.g. by calling `layerBacked` on it). If another thread is traversing down the node hierarchy at the same time, and holding a supernode's lock while trying to acquire the subnode's lock, we get a deadlock.
This patch never acquires supernode's lock while holding self's lock.
- Remove lock overlapping in `removeFromSupernode`
- Optimize `applySubnodeInsertions/Removals` for good measure
- Add some removeFromSupernode tests
=> [ASDisplayNode] Resolve Deadlock Caused By removeFromSupernode

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Private/ASDisplayNodeInternal.h
Should fix: #853
I looked into the internals of `UIImageView` a bit. I would recommend to not fixing this in a universal way. `UIImageView` is specifically optimized for performance and does not use the usual way to provide the contents of the `CALayer` that backs the `UIImageView`.
Furthermore we cannot trigger a recreation of the contents of the `UIImageView` layer as if it get’s cleared and we call `setNeedsDisplay` on it it goes trough the normal flow to assign the contents to a layer via the `CALayerDelegate` methods. Unfortunately `UIImageView` does not do it, it actually does not implement some of the methods at all, so nothing will show up. It’s getting better, by calling `setNeedsDisplay` on an `UIImageView` layer it actually clears the contents and nothing is visible anymore. So …
=> [Wrapping Views] Fix wrapped UIKit components are disappearing

AsyncDisplayKit/ASTextNode.mm, AsyncDisplayKit/TextKit/ASTextKitContext.mm
- Move lock from ASDN::Mutex to std::mutex in ASTextKitContext
- Small cleanup in ASTextNode
- For now we use a big recursive lock. This needs to be revisited as we revisit the whole ASDK locking strategy.
Related: #1739, #1703
=> [ASTextNode] Refactor locking to account for recent feature additions and on-demand initialization.

AsyncDisplayKit/ASImageNode+AnimatedImage.mm
ASImageNode only starts animating when the animated image's `playbackReadyCallback` is called. If the animate image was ready for playback before it was assigned as ASImageNode's animated image, then `playbackReadyCallback` is never called in the context of ASImageNode. This change checks the playbackReady property, and if it's true, starts playback immediately.
=> [ASImageNode] Fix animated image playback if file is ready

AsyncDisplayKit/AsyncDisplayKit-Prefix.pch, AsyncDisplayKit/Details/ASPINRemoteImageDownloader.m
Resolves Issue 1 of #1780. 
Users who don't use CocoaPods will have PIN_REMOTE_IMAGE defined in .pch file.
=> [Carthage] define PIN_REMOTE_IMAGE in .pch for non-CocoaPod users

Cartfile, examples/CarthageBuildTest/Sample.xcodeproj/project.pbxproj
Resolve Issue 2 of #1780 with ASDK Cartfile addition.
Installation Notes (WIP)
Create project with a cartfile that just lists ASDK, as seen in the following. NOTE: this will only work with master until we have a release with a cartfile.
git "file:///Users/htroisi/Code/AsyncDisplayKit" "master" (testing on my machine)
github "facebook/AsyncDisplayKit" "master" (haven't tested this yet, will test this once cartfile is merged)
Run carthage update. This will fetch dependencies into a Carthage/Checkouts folder, then build each one.
> carthage update --platform iOS (don't need iOS, but I only tested with that so far)
Look for terminal output confirming AsyncDisplayKit, PINRemoteImage (3.0.0-beta.2) and PINCache are ALL installed (despite only ASDK being listed in your project's Cartfile).
The …
=> [Carthage] Add cartfile, update example

AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/Details/ASRangeController.h, AsyncDisplayKit/Details/ASRangeController.mm
During various layout changes that trigger content size changes, batch fetching needs to recalulate it's number of screens left to scroll before the delegate -collectionView:beginBatchFetchingWithContext: is called. 
Just exposes `[self _checkForBatchFetching];`
**UPDATE:**
Due to conversations with @appleguy the approach has changed to triggering `[self _checkForBatchFetching];`internally, at the appropriate times.
After some digging, it appears triggering this on `- (NSArray *)visibleNodeIndexPathsForRangeController:(ASRangeController *)rangeController` exhibits the least amount of additional calculations, but covers a range of use cases that require a batch fetch re-measurement.
From the code comments:
> // We must re-check the batch measurement range when additional cells enter the …
=> [Table / Collection] Trigger new batch fetch after programmatic scrolls, or layout transitions.

AsyncDisplayKit/ASVideoNode.mm, AsyncDisplayKitTests/ASVideoNodeTests.m
Before this change the user of ASVideoNode could set the .delegate property but the ASNetworkImageNode delegate methods were not called. This meant that the client of ASVideoNode was not able to observe image progress or errors.
I've tested this both with the test harness and in my own project.
=> [ASVideoNode] Ensure that both ASVideoNode and ASNetworkImageNode delegate methods are called

AsyncDisplayKit/ASImageNode.mm, AsyncDisplayKit/ASTextNode.mm
The purpose of this PR is to move from an ObjC object to a struct for drawing parameters in ASTextNode and ASImageNode.
Furthermore as we improved the performance by going from the class drawing method to an instance drawing method we prevent custom drawing in ASTextNode or ASImageNode subclasses now.
If we decide to merge that PR we should close: #1728 as this is not necessary anymore.
cc @appleguy @ocrickard @garrettmoon: Curious about your thoughts about this PR.
=> [ASTextNode / ASImageNode] Use structs for drawing parameter

AsyncDisplayKit/Layout/ASBackgroundLayoutSpec.mm, AsyncDisplayKit/Layout/ASLayoutSpec.h, AsyncDisplayKit/Layout/ASLayoutSpec.mm, AsyncDisplayKit/Layout/ASOverlayLayoutSpec.mm
Converted the backing store of children to a std::vector. Subclass now have defined indexes instead of string keys to add children.
=> [ASLayoutSpec] Remove use of dictionary to hold children

AsyncDisplayKit/ASCellNode.h, AsyncDisplayKit/ASCellNode.mm, AsyncDisplayKit/ASCollectionView.mm
@Eke discovered that we don't support applyLayoutAttributes: on ASCellNode. 
He has already tested this patch on one collection and it worked. He has 4 other collection views that need custom animations, etc and so he'll update us as he tests it on each of those collections.
=> [ASCollectionView, ASCellNode] Add support applyLayoutAttributes: on ASCellNode

AsyncDisplayKit/Details/ASEnvironment.h
I'm not completely sure this change is the best solution. Here is context:
An ASEnvironmentTraitCollection has a pointer to an optional context that an ASVC is the owner of. When the ASVC is dealloc'ed, we go through all subnodes of the VC and clear out the context so that the struct isn't holding on to a garbage pointer.
Setting the traitCollection on ASCollectionNode/ASTableNode causes the cells to relayout if the trait collection changed (this is  a special case for these two nodes since their cells are not actually subnodes). Setting the context to nil registered as a trait collection change and was causing a layout even as we were dealloc'ing the VC.
The logic I'm implementing here is:
If the trait collection changed AND the displayContext did not, then we should relayout.
If the …
=> [ASEnvironment] Don't relayout as a result of clearing a traitCollection's context

AsyncDisplayKit/ASCollectionView.h, AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.h, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/Details/ASChangeSetDataController.m, AsyncDisplayKit/Details/ASCollectionDataController.mm, AsyncDisplayKit/Details/ASDataController.h, AsyncDisplayKit/Details/ASDataController.mm, AsyncDisplayKit/Private/ASMultidimensionalArrayUtils.mm, AsyncDisplayKitTests/ASTableViewTests.m
I was doing a deep-dive into this code in preparation for some work, and I saw a bunch of possible improvements. So here they are.
- Remove asyncDataFetching logic, deprecating the associated methods. We no longer call the locking methods because we now follow the UIKit synchronization paradigm – submit your edits on the main queue, and we'll query you back immediately on the main queue.
- Add assertions to data controller about which queue we're on
- Make data controller use _editingTransactionQueue even when doing synchronous reload (so that those assertions pass).
- Other small tweaks/optimizations (avoiding needless allocations/method calls)
I've tested this thoroughly by hand.
=> [ASDataController] Remove asyncDataFetching Option, Cleanup

AsyncDisplayKit/ASTextNode.mm
This reduces the number of calls to -length, and also releases the lock as soon as possible.  
Because we use the local variable, there is a chance that another thread will set _attributedString before me, but self.accessibilityLabel after me, and they'd fall out of sync. Since mitigation would be so ugly, this is considered an acceptable risk. Review? @maicki @appleguy
=> [ASTextNode] Release Lock Sooner in -setAttributedText:

AsyncDisplayKit/Details/ASDelegateProxy.m
Currently we don't forward `conformsToProtocol:` to the `target` in `ASDelegateProxy`. Unfortunately there can be some problems with that. I ran into this as I tried to implement a custom UICollectionViewLayout that checks if it's delegate conforms to a protocol. Currently this will will crash so we should forward that `conformsToProtocol:` call to the target.
=> [ASDelegateProxy] Add `conformsToProtocol:`

AsyncDisplayKit/Details/ASEnvironment.h
This fixes an issue where the propagation of trait collections trigger are creation of the node if the node view was not loaded yet.
cc @rcancro Does this make sense or am I overlooking something?
=> Don't propagate trait collections to cells if the node is not loaded yet

AsyncDisplayKit/ASDisplayNode.mm
Should fix our placeholder example as well as #563
This fixes the placeholder issue again that was already fixed via #1707, but it was reverted with this PR: #1717 that actually didn't have to do something with this fix.
=> [ASDisplayNode] Handle placeholder layer creation in case the size of the node changes after the initial placeholder layer was created

AsyncDisplayKit.xcodeproj/project.pbxproj
The header contents are wrapped in `#if PIN_REMOTE_IMAGE` so we won't compile anything for users that are on our "Core" spec. I've tested this and it resolves #1815 and behaves well for Core & default subspecs. @appleguy @maicki
=> [Project] Publicize ASPINRemoteImageDownloader.h

AsyncDisplayKit/ASVideoNode.mm, AsyncDisplayKit/ASVideoPlayerNode.h, AsyncDisplayKit/ASVideoPlayerNode.mm
At the moment there's no way to access the underlying ASVideoNode and make use of the recent functionality for placeholder images. I've added a property to expose this.
=> [ASVideoPlayerNode] Expose placeholder image for the underlying ASVideoNode

AsyncDisplayKit/ASVideoNode.mm
During testing with my own app I noticed that my observer was getting called far too often for the methods in ASVideoNodeDelegate such as `videoDidPlayToEnd:`. Some investigation identified that this was due to the object being set to observe all other ASVideoNode objects when the internal `setCurrentItem:` method was called.
This was quite simple to avoid by guarding the addPlayerItemObservers: when the player item is nil.
I tried to add a unit tests but it's difficult to mock NSNotificationCenter without injecting one into the class at construction. This would change too much of the internals, so decided against it.
I've verified the operation of this with my own app (containing multiple ASVideoNode objects) and it appears to work fine. You can probably check the behaviour with he …
=> [ASVideoNode] Ensure that observer methods don't observe all other ASVideoNode objects

AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKitTests/ASCollectionViewTests.m
I've been trying to use the tuning parameters in a project and I noticed that they were having no effect. This appears to be due to the tuning parameter methods on ASCollectionView being passed straight through to the _collectionNode member.
The _collectionNode member doesn't appear to actually get set anywhere, and it would only pass these through to the range controller anyway. Passing these directly through seems to fix the problem, and I can see on my own project that the changes are having the desired affect.
The use of _collectionNode throughout this class does seem to be in need of a review, but I'm not that well up on the code to dive in myself unfortunately.
The get/set of the tuning parameters is quite easy to unit test, so I've covered this already. There might be more in-depth …
=> [ASCollectionView] Tuning parameters not set

AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/Private/ASInternalHelpers.h, AsyncDisplayKit/Private/ASInternalHelpers.mm
We should not check if we are running under a specific iOS version via [UIDevice systemVersion]. This PR switches to check the foundation version.
=> Remove check of [UIDevice systemVersion] if running on iOS 7

AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/Details/ASDataController.mm
This is a modification of #1827 that achieves the same effect in a different way. Let's call 1827 option A and this option B. In this option, to achieve the animated relayout, we submit an empty update just before [super layoutSubviews] rather than wrapping the layout in an animation block.
Reasons to go with option B:
- Doesn't cause the collection view to take any snapshots.
- Update animations follow the layout's normal update style (e.g. moved items slide rather than crossfade). Option A causes all items to crossfade.
Reasons to go with A:
- Option A is completely API-safe. This is Apple's "golden path."
- The resized cell node gets a fancy double-sided crossfade animation as it moves to its new size, rather than simply "jumping" to its new size.
- Option B's submitting an empty …
=> [ASCollectionView] Greatly Improve Cell Node Resizing

AsyncDisplayKit/ASCollectionView.mm
Under iOS < 9, when a collection view is removed from the hierarchy and being prepared for deallocation, its layer may become a dangling pointer and put the collection view into a dangerous state where pretty much any call will crash.
This shouldn't be possible, since views are supposed to retain their layers, but it happens all the same. This adds a separate strong pointer to ASCollectionView to workaround the issue.
This issue is not technically ASDK-specific, but under ASDK it is _far_ more likely to manifest because of the fact that ASDisplayNode intentionally keeps self alive for the next run loop turn in -didExitHierarchy
=> [ASCollectionView] Add strong Layer Pointer Under iOS < 9 to Workaround Crashes

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Details/ASRangeController.mm, AsyncDisplayKit/Private/ASDisplayNode+FrameworkPrivate.h
Previously, `ASRangeController` registers to notification center every time a range update is performed, regardless of the number of nodes that need to schedule for a recursive display in response to the update. 
Instead, if this number is taken into account and range controller doesn't observe further notifications if it is zero, we can minimize the number of range updates executed and may fix #1460 (verification needed though).
=> [ASRangeController] Minimize number of registrations to node display notifications

AsyncDisplayKit/ASCollectionNode.h, AsyncDisplayKit/ASCollectionNode.mm, AsyncDisplayKit/ASTableNode.h, AsyncDisplayKit/ASTableNode.mm, AsyncDisplayKit/Details/ASAbstractLayoutController.mm
Changing the range mode needs to access the view within the node. If the view was not loaded at this point it will trigger a view load, but that's not necessarily wanted so prevent changing it if the node is not loaded yet.
cc @garrettmoon Garrett does this change makes sense or do you have other ideas around it?
=> [ASVisibility] Don't change the range mode if the node was not loaded yet

AsyncDisplayKit/ASViewController.h, AsyncDisplayKit/ASViewController.mm, AsyncDisplayKit/Details/ASEnvironment.h, AsyncDisplayKit/Details/ASEnvironment.mm, AsyncDisplayKit/Details/ASTraitCollection.h, AsyncDisplayKit/Details/ASTraitCollection.m, AsyncDisplayKit/Private/ASEnvironmentInternal.mm
Passing around a pointer was leading to crashes as the ASVC was the sole owner of the context. There are cases where the VC would dealloc while its subnodes were laying out. This could lead to the subnodes accessing a garbage pointer.
=> 	[ASTraitCollection] Remove traitCollectionContext from ASTraitCollection; add containerWindowSize

AsyncDisplayKit/Details/ASChangeSetDataController.m
If enabled, these might interfere with some app-level developers so per @appleguy we're giving them a grace period.
Landing this once the build passes.
=> [ASDataController] Temporarily Disable Some Troublesome Assertions

AsyncDisplayKit/ASCollectionView.h, AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/Details/ASCollectionDataController.mm
- Exposing `-supplementaryNodeOfKind:atIndexPath:` on `ASCollectionView`
- Modifies `ASCollectionDataController` to return `nil` if a supplementary node doesn't exist (as opposed to asserting / returning an empty `ASCellNode`) much like a standard node.
- Adds proper nullability on `ASCollectionView` `-nodeForItemAtIndexPath`
=> [ASCollectionDataController] Exposing -supplementaryNodeOfKind

AsyncDisplayKit/ASTableView.mm
Follow up PR for #1820.
To align ASTableView with ASCollectionView we set the tuning parameters on the range controller instead of the layout controller. The range controller basically just call's through to the layout controller though.
=> [ASTableView] Move setting of tuning parameters to the range controller

AsyncDisplayKit/ASViewController.mm
Summary:
The old assignment of `self.node.environmentTraitCollection.containerSize = windowSize;` doesn't because the struct creates a copy and then assigns `windowSize` to that copy.
Also realized that we need to create a new `ASEnvironmentTraitCollection` in `willTransitionToTraitCollection:withTransitionCoordinator`:. If we only update in `viewWillTransitionToSize:` we will only update the `containerSize` value in `self.environmentTraitCollection` as we don't have the new trait collection yet.
Differential Revision: https://phabricator.pinadmin.com/D101807
=> [ASEnvironmentTraitCollection] Fixed bug where containerSize wasn't being saved

AsyncDisplayKit/ASImageNode+AnimatedImage.mm, AsyncDisplayKit/ASImageNode.mm, AsyncDisplayKit/Private/ASImageNode+AnimatedImagePrivate.h
Having a dealloc method in a category can be very problematic as the superclass dealloc method will not be called in case it exists.
=> [ASImageNode] Move dealloc method from ASImageNode+AnimatedImage category to ASImageNode

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Layout/ASLayoutSpec.mm, AsyncDisplayKit/Layout/ASLayoutable.h, AsyncDisplayKit/Private/ASDisplayNodeInternal.h, AsyncDisplayKit/Private/ASLayoutTransition.h, AsyncDisplayKit/Private/ASLayoutTransition.mm, AsyncDisplayKitTests/ASDisplayNodeImplicitHierarchyTests.m
Currently measurement always needs to happen on the main thread if implicit hierarchy management is enabled as adding and removing from nodes needs to happen on the main thread. We now will trampoline to the main thread to do the insertion and deletion of nodes.
This also resolves the issue that can occur if a node is already loaded deep in the layout hierarchy in the layout that the node is transforming to. Before insertion or deletion is happening we need to crawl the layout hierarchy to check that though.
*Open things:*
* This theoretically that would enable us always measure nodes in the data controller asynchronous
* Furthermore this also would us allow to get rid of the `shouldMeasureAsync` parameter in `transitionLayoutWithAnimation:shouldMeasureAsync:measurementCompletion:` that I …
=> [ASDisplayNode] Allow measure always be off the main thread

AsyncDisplayKit/ASVideoNode.mm
At the moment ASVideoNode automatically resets the playback of the video to the beginning when the end is reached. This, as far as I can tell, is not done by the standard AVVideoPlayer. 
If the user wanted to do this there is no reason why they couldn't by implementing `videoDidPlayToEnd:` and doing the seek themselves there. The seek is obviously required if the video is set to auto-repeat, so I've left the code in there, but inside the `if`.
For my own project I was trying to get the video to pause at the end of the playback and stick on the last frame. The previous code made this impossible because the `videoDidPlayToEnd:` is invoked before the seek. Any modifications I did to the seek time were overwritten.
=> [ASVideoNode] Only seek to beginning when auto repeating

AsyncDisplayKit/TextKit/ASTextKitContext.h, AsyncDisplayKit/TextKit/ASTextKitContext.mm, AsyncDisplayKit/TextKit/ASTextKitRenderer.mm, AsyncDisplayKit/TextKit/ASTextKitTailTruncater.mm, AsyncDisplayKitTests/ASTextNodeTests.m
Before truncation happens no invalidation of the text storage happened. That had the effect, if the constrained size of a text node increases a new size for the text node will be calculated. While this calculation is happening a truncation on the text will happen. Unfortunately the truncation will happen on the already truncated string.
This PR resets the text storage to the original value before the truncation is happening so it always will truncate on the same string no matter what constrained size is given.
Should fix #1841
=> [ASTextNode] Fix text node truncation

AsyncDisplayKit/ASVideoPlayerNode.mm
At the moment the activity indicator for ASVideoPlayerNode, shown when the video is loading, is displayed inside a black box. This seems to be due to the background of the containing node not being transparent.
This simple change makes the node transparent, leaving the activity indicator shown in white just like the other playback controls.
=> [ASVideoPlayerNode] Ensure activity indicator view is transparent

AsyncDisplayKit/TextKit/ASTextKitContext.mm
We need to consider the `textStorageCrationBlock` while resetting the text storage if one is given in the initializer.
=> [ASTextNode] Use textStorageCreationBlock for resetting the text storage

AsyncDisplayKit/ASNetworkImageNode.mm
Hi guys,
This is a very simple PR concerning the issue I just opened #1848. A test project can be found here: https://github.com/flovouin/ASDK-NetworkImageCrash
Basically what happens is that when `shouldCacheImage = NO` and the `URL` fed to an `ASNetworkImageNode` points to a file that doesn't exist, `nil` data is passed to the `_downloader`, which causes a crash.
My fix is simply to check that the data is indeed not `nil` before trying to load an animated image. However I get the feeling that something more could be done here. If the image exists but is not animated, it gets loaded two times: once as the `nonAnimatedImage`, and once as the `animatedImage`. Isn't there a way to load the image only once and check whether it's animated?
Tell me what you think :-)
Cheers,
=> [ASNetworkImageNode] Fix crash when local file URL doesn't exist

AsyncDisplayKit/ASCellNode.mm
This should resolve https://github.com/facebook/AsyncDisplayKit/issues/1659, which corresponds to this
Fabric log for Pinterest: https://fabric.io/pinterest6/ios/apps/com.pinterest.enterprise/issues/5776fbfeffcdc042501a5f20/sessions/c178e977614b4ebab853084847fb241
8
=> [ASCellNode] Add gating for -convertRect: call upon invisibility notification for iOS 7 & 8 edge case.

AsyncDisplayKit/ASDisplayNode.mm
For performance reasons change to directly lock and unlock calls on the property lock instance
=> [ASDisplayNode] Change from MutexLocker / MutexUnlocker to lock() and unlock() directly on property lock

AsyncDisplayKit/ASTableView.mm
We have reason to believe #1861 affects table view as well. This adds a retained layer pointer for the same reason.
=> [ASTableView] Add retainedLayer a la Collection View

AsyncDisplayKit/ASDisplayNode.mm
Current if `[ASDisplayNode invalidateCalculatedLayout]` and `[ASDisplayNode setNeedsLayout]` called in a subclass (see` [ASButtonNode setTitle:]`) the call actually does not trigger any relayout. It does not even bubble up the tree as it returns early in `[ASDisplayNode __setNeedsDisplay]`
After talking with @nguyenhuy about the initial intention why we are returning early there we found a better way for it.
This should resolve: #1865
@nguyenhuy @levi @appleguy Can I get a look over please
=> [ASDisplayNode] Fix setNeedsLayout triggered from subnode will not trigger relayout

AsyncDisplayKit/ASButtonNode.mm
I found this interesting line while debugging #1865. We're basically trying to avoid unnecessary updates by comparing the old and existing titles. However, we should be comparing the contents of these strings instead of their memory addresses, no?
=> [ASButtonNode] Correctly compare and update its title

AsyncDisplayKit/ASCellNode.mm, AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/Details/ASRangeController.h, AsyncDisplayKit/Details/ASRangeController.mm, AsyncDisplayKit/Details/ASRangeControllerUpdateRangeProtocol+Beta.h
First off, I know how critical this code is, so I've tried to minimize changes and especially additions.
- Perform update immediately in `visibleNodeIndexPathsDidChangeWithScrollDirection` and `updateRangeWithMode`. This is the meat of the PR. 
- The comment at ASRangeController.mm:98 claimed this was already executed immediately, but it wasn't.
- Unfortunately this means that we will perform a range update for each call to `willDisplayCell:` rather than max once per run loop. Is this an acceptable cost for the guarantee that a cell will not be visible before the ranges are updated? I believe so.
- Replace `scheduleRangeUpdate` and `performRangeUpdate` with `performRangeUpdateSynchronously:`.
- In ASTableView, change how we compute the visible index paths. Once I started updating …
=> [ASRangeController] Update Synchronously More Often

examples/AsyncDisplayKitOverview/Sample/Node Containers/OverviewASCollectionNode.m
With "sizeForItemAtIndexPath" it shows empty screen instead of collection items.
=> [Examples] AsyncDisplayKitOverview collection nodes size fix

AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/Details/ASCollectionViewFlowLayoutInspector.h, AsyncDisplayKit/Details/ASCollectionViewFlowLayoutInspector.m, AsyncDisplayKitTests/ASCollectionViewTests.m
- Fix not using itemSize of UICollectionViewFlowLayout
- Move automatic constrained size calculation to the ASCollectionViewFlowLayoutInspector
- Provide a null layout inspector for throwing exceptions if a custom
UICollectionView is given but no ASCollectionViewLayoutInspecting
- Fix not checking for optional layout inspecting data source methods
are implemented or not
- Improving tests around ASCollectionViewLayoutInspecting
cc @levi that's the pull request we talked the other day about. Let me know what you think
=> [ASCollectionViewLayoutInspecting] Refactor usage of ASCollectionViewLayoutInspecting

AsyncDisplayKit/ASViewController.mm
Adresses: #1905 and more robust check if ASViewController is modal presented that was fixed previously in regard to: #1810
=> [ASViewController] Fix sizing of root node in ASViewController for modal presentation and root view controller

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Details/ASDataController.mm
Some crazy idea and follow up to #1839. We will push the layout of nodes to always be on a background thread as based on the work in #1839 we will trampoline the layout automatically to the main thread if at least one node is loaded.
Furthermore there needs to be some more improvements to it:
- Moving away from dispatching to global dispatch queues in layout transition and ASDataController
- Remove the semaphore in ASDataController
- Adding tests
@Adlai-Holler @nguyenhuy @appleguy @levi What do you guys think about that? We have to carefully think about that and check for any gotchas that could happen, if we really want to go forward with that.
=> [ASDisplayNode] Always layout nodes on a background thread

AsyncDisplayKit/ASTextNode.mm, AsyncDisplayKit/TextKit/ASTextKitRenderer.mm, AsyncDisplayKitTests/ASTextNodeTests.m
Throw away the all subcomponents to create them with the new constrained size new as well as let the truncater do it's job again for the new constrained size. This is necessary as after a truncation did happen the context would use the truncated string and not the original string to truncate based on the new constrained size
This should fix #1841 and finally #1865
=> [ASTextNode] Fix wrong truncation after constrained size changes

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/ASControlNode.mm, AsyncDisplayKit/ASDisplayNodeExtras.mm, AsyncDisplayKit/ASVideoPlayerNode.mm, AsyncDisplayKit/Details/ASCollectionDataController.mm, AsyncDisplayKit/Details/ASDataController.mm, AsyncDisplayKit/Details/ASFlowLayoutController.mm, AsyncDisplayKit/Details/NSIndexSet+ASHelpers.m, AsyncDisplayKit/Layout/ASLayoutSpec.mm, AsyncDisplayKit/Private/ASLayoutTransition.mm, AsyncDisplayKit/Private/ASMultidimensionalArrayUtils.mm, AsyncDisplayKit/Private/_ASHierarchyChangeSet.m, AsyncDisplayKit/Private/_ASHierarchyChangeSet.mm
I got on a bit of a rabbit trail here. A couple common tactics:
- Replace `enumerateIndexes` with `enumerateRanges`, using a for-loop to go through the indexes in each range. This reduces block invocations.
- Replace `.allKeys/.allValues` with plain dictionary enumeration and `objectEnumerator` when possible to avoid making copies. 
- Replace `enumerateObjectsUsingBlock` with fast enumeration when possible.
- Prefer `-[NSIndexPath indexPathForItem:inSection:]` because in 64-bit architectures there's some special mechanism to use singletons for these.
- Don't call the same thing 3 times in a row. Especially if that thing allocates memory!
=> [Performance] Various Easy Performance Wins

AsyncDisplayKit/ASCollectionNode.h, AsyncDisplayKit/ASDisplayNode+Beta.h, AsyncDisplayKit/ASTableNode.h, AsyncDisplayKit/ASViewController.h, AsyncDisplayKit/ASViewController.mm, AsyncDisplayKit/Details/ASRangeController.mm, AsyncDisplayKit/Details/ASRangeControllerUpdateRangeProtocol+Beta.h, AsyncDisplayKitTests/ASCollectionViewTests.m, AsyncDisplayKitTests/ASTableViewTests.m
This morning Michael and I found that our range mode updating is basically not working at all for a couple reasons.
- ASCollectionNode and ASTableNode declare their conformance in a category, which apparently doesn't work and causes the runtime to return NO for conformsToProtocol:
- Pinterest (and I'm sure other apps) have ASViewControllers with non-table, non-collection nodes. Sometimes these are plain old ASDisplayNodes. None of them conform to the update protocol.
- ASTableNode and ASCollectionNode did not implement +setRangeModeForMemoryWarnings: so they actually didn't conform to the updating protocol. This also means none of our users is calling that method or it would have crashed.
- Worst of all, we had no idea that none of this was working.
So
- Move the conformances in …
=> [ASRangeController] Fix Major Range Mode Updating Issues

AsyncDisplayKit/ASTextNode.mm
I have a subclass of `ASTextNode` that uses `pointSizeScaleFactors`. Currently I have to recompute the scale factors any time the font size changes. If `_rendererAttributes` used the property accesor for the scale factors I would only have to create them when asked. I hope this little change can make it in :)
=> [ASTextNode] use accessor for `pointSizeScaleFactors`

AsyncDisplayKit/ASDisplayNode.mm
// If the constrainedSize is completely zero-area, then there is no possibility for layout calculations to be successful.
// This also avoids the issue of an inset being applied to 0, creating negative frame values.
=> [ASDisplayNode] Short circuit measure calls that have a zero-area constrainedSize.

AsyncDisplayKit/Private/ASDisplayNode+AsyncDisplay.mm
@johnepinterest @maicki @Adlai-Holler @chrisdanford @hannahmbanana 
Hey all - this method had grown a bit over time, as features like instance method display were added, and it was time for cleanup.
I took time to do this carefully enough that I feel regressions are unlikely once it has been fully tested with the app, which I'll do over the weekend.  I am very familiar with the original state of the code.
I'd like to switch the order of the if / else so that rasterization comes second, but didn't want to move it for now so the diff has a slight element of readability lol.
This should improve efficiency by eliminating several lock acquisitions, and also adding a few strategically relevant isCancelled checks.  Particularly on the slowest devices with fast user input / large amounts of …
=> [ASDisplayNode+AsyncDisplay.mm] Refactor display block creation method for conciseness and readability.

AsyncDisplayKit/Details/ASDataController.mm
NSOperationQueue doesn't support backtrace recording, so it is impossible to tell where operations got enqueued from. 
This patch makes debugging data controller trouble a lot easier by migrating to GCD. I've tested this thoroughly. The only thing that we lose with this, is we lose a somewhat valuable assertion. @maicki @appleguy @levi Needs review
=> [ASDataController] Migrate Editing Queue to GCD for Performance/Debuggability

AsyncDisplayKit/ASCollectionView.mm
This was a bit of premature optimization that I introduced in c62a4d3. Even if the user didn't tell us about any updates, a batch update can be useful for triggering an animated relayout of the collection view. 
This resolves #1945
=> [ASCollectionView] Do Not Suppress Empty Updates

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/ASDisplayNode+Beta.h, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Details/ASChangeSetDataController.mm, AsyncDisplayKit/Details/ASDataController+Subclasses.h, AsyncDisplayKit/Details/ASDataController.h, AsyncDisplayKit/Details/ASDataController.mm, AsyncDisplayKit/Private/_ASHierarchyChangeSet.h, AsyncDisplayKit/Private/_ASHierarchyChangeSet.mm, AsyncDisplayKitTests/ASCollectionViewTests.mm, Base/ASAssert.h
This adds assertions like "attempt to delete item 10 in section 0 which only contained 5 items before the update" and "Invalid number of sections: count after the update (5) must equal the count before the update (2) plus or minus the number of sections inserted or deleted (4 inserted, 0 deleted)."
This also adds the identity of the data controller into the name of its editing queue, to help debugging.
This is ready for review! @appleguy @nguyenhuy @maicki @levi
=> [ASDataController] Validate Client-Submitted Update Operations

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKitTests/ASDisplayNodeTests.m
If trying to insert a nil node via `insertSubnode:atIndex:` likely a crash will happen. Add assert in case passing in a nil node or return in production.
=> [ASDisplayNode] Don't crash if inserting a nil node

AsyncDisplayKit/ASCollectionNode.h, AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/Details/ASDataController.h, AsyncDisplayKit/Details/ASDataController.mm, AsyncDisplayKit/Details/ASLayoutController.h, AsyncDisplayKit/Details/ASRangeController.h, AsyncDisplayKit/Details/ASRangeController.mm
I am working on the data controller teardown/cancellation and I found some dead code. I wanted to break it out into a separate PR. I also found that range controller is calling an optional protocol selector without checking if it responds.
I removed some optional editing methods from the ASLayoutController protocol. They aren't called anywhere, and not implemented by FlowLayoutController.
@maicki @levi @appleguy Quick review?
=> [General] Remove Dead Code, Check Optional Protocol Selector

AsyncDisplayKit/Details/ASPINRemoteImageDownloader.m
These values appear to be inverted, which was causing progress greater than 1.0 to be returned in the progress block.
=> [ASPINRemoteImageDownloader ] Fix inverted ASPINRemoteImageDownloader progress

AsyncDisplayKit/Details/ASPINRemoteImageDownloader.m
The ASImageDownloaderProtocol specifies that cancelImageDownloadForIdentifier: has no effect if `downloadIdentifier` is nil.
While ASBasicImageDownloader checks for nil, ASPINRemoteImageDownloader does not.
I tested this and passing in nil does indeed result in a crash.
=> Fixed ASPINRemoteImageDownloader cancelImageDownloadForIdentifier: crash

AsyncDisplayKit/TextKit/ASTextKitComponents.h
I don't know why these were here but they're not currently used.
Technically, since this header file is public, this is an API change. But it's incredibly minor and any user that's upset can easily implement their own.
`[UIScreen mainScreen]` should only be called on main. Plus it's expensive! I advocate for landing this immediately despite the teensy API change. @maicki @appleguy @levi @Yue-Wang-Google
=> [ASTextKitComponents] Remove Unused Scale Conversion Functions

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/Private/ASInternalHelpers.m
This should retain full precision on both 32-bit and 64-bit. 
I dropped the file down to Objective-C from Objective-C++ because tgmath (and ctgmath) seem not really to work under Objective-C++. The internet says that C++ has a separate overloading mechanism but when I Cmd+click on the function names under C++ I always get pointed to just the `double` version. Huh.
Ready for review @maicki @appleguy @levi
=> [ASInternalHelpers] Use Type-Generic Maths

AsyncDisplayKit/Layout/ASDimension.mm
Until we merge #1767 (Adlai's percent -> fraction naming fix) it is a bit confusing whether the provided value should be 0-100 or 0-1.
=> [ASDimension] add assertion for percent values outside 0-1

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Private/ASDisplayNodeInternal.h, AsyncDisplayKit/Private/ASLayoutTransition.h, AsyncDisplayKit/Private/ASLayoutTransition.mm
Simplify applying layout transition in preparation for bigger Layout Transition API work. Changes are:
- Always go through `_pendingLayoutTransition`
- Move from `[ASDisplayNode _applyLayout:layoutTransition:]` to `[ASDisplayNode _applyLayout:]` and `[ASDisplayNode _applyLayoutTransition:]`
- Change from `[ASLayoutTransition startTransition]` to `[ASLayoutTransition applyTransition]`
@levi @appleguy Can you review. This is the first small change in preparation for the bigger change that will come for the Layout Transition API
=> [Layout Transition API] Simplify applying layout transition

AsyncDisplayKit/ASVideoPlayerNode.h, AsyncDisplayKit/ASVideoPlayerNode.mm
The default spinner size looked a bit lost in my project, especially on iPad. The default is quite small and the 'large' version isn't exactly big either.
We're already exposing the tint colour, so it seemed only right to allow the user to set the spinner style also.
I've tested this on my own project and it appears to work fine.
=> [ASVideoPlayerNode] Expose the UIActivityIndicatorViewStyle to clients

AsyncDisplayKit/Details/ASChangeSetDataController.m
This is a reduced version of #1894 . This resolves an issue where non-batched reloads, when decomposed into delete/inserts, would be executed separately one-after-another. This causes crashes in Pinterest 6.7.
=> [ASDataController] Always Process In Batches

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Private/ASStackUnpositionedLayout.mm
This can happen in rare cases when multiple relayouts occur while a transition is being measured.
=> [ASDisplayNode] Ensure that nil can never be returned from -measureWithSizeRange:

AsyncDisplayKit/Private/ASEnvironmentInternal.mm
Using fast enumeration on an ASEnvironment child can crash. This should be a temporary fix until we have time to dive deeper into that.
=> Use children directly instead of fast enumeration of ASEnvironment object

AsyncDisplayKit/ASDisplayNode.mm
If a node was added to a supernode, the supernode could be in a layout pending state. All of the hierarchy state properties related to the transition need to be copied over as well as propagated down the subtree. This is especially important as with Implicit Hierarchy Management adding subnodes can happen while a transition is in fly
=> [Layout Transition] Fix not propagating updating and propagating down the layout transition id if a subnode is added

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/ASViewController.mm, AsyncDisplayKit/Details/ASEnvironment.h, AsyncDisplayKit/Layout/ASLayoutSpec.mm, AsyncDisplayKit/Layout/ASStackLayoutSpec.mm, AsyncDisplayKit/Layout/ASStaticLayoutSpec.mm, AsyncDisplayKit/Private/ASEnvironmentInternal.mm, AsyncDisplayKit/Private/ASLayoutSpec+Private.h, AsyncDisplayKitTests/ASDisplayNodeTests.m, AsyncDisplayKitTests/ASLayoutSpecSnapshotTestsHelper.m
I reverted the revert of the previous PR and added one important fix for fast enumeration in ASLayoutSpec:
NSFastEnumeration is potentially quite dangerous in the wrong hands. In particular, it does not provide a safe mechanism for you to return temporary objects directly, and it does not provide any guarantee that you will be called when the enumeration has completed; therefore if we generate temporaries and store them in an instance variable, we will not necessarily be able to clean them up! This means fast enumeration methods should never be called within an autorelease pool or the autorelease pool be drained within the fast enumeration loop.
The reason is we store references to objects in the stackBuf struct by casting the child pointer to __autoreleasing id. If we pop the autorelease …
=> [ASLayoutSpec] Use childrenMap directly to prevent creating an NSArray within ASDK Part 2

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/ASImageNode.mm, AsyncDisplayKit/Private/ASWeakMap.h, AsyncDisplayKit/Private/ASWeakMap.m, AsyncDisplayKitTests/ASWeakMapTests.m
This change shares computed layer contents between instances of ASImageNodes that are visually identical.
- Reduce total memory usage by not computing and retaining multiple, identical content images.
- The caching mechanism should not retain any UIImage (neither the source image nor the computed contents image) for longer than it had previously.  Therefore, in the worst case of a 0% cache hit rate, peak memory usage will be no worse than before (minus the size of the `ASWeakMap` itself, which is not substantial).
- ASImageNode's layer contents are cached, and the cache key is an`ASImageNodeContentsKey` which contains all data that is passed to draw calls that generate the contents bitmap.
- Contents are stored in `ASWeakMap`.  The `ASImageNode` must retain the `Entry` object returned by …
=> ASImageNode backing store sharing for memory and CPU reduction

AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.mm
This feature has been requested by Google and others. We could in the future make an asynchronous option that would enqueue this with other edit operations, but that would get messy quickly.
NOTE: It is a known issue that `-waitUntilAllUpdatesAreCommitted` has no effect if the initial reload hasn't been enqueued. Simply adding that line causes other issues that I don't have bandwidth to investigate right now, so this change will only work if the initial reload has already been started. Ship task 156 covers this.
Ready for review @maicki @levi @appleguy
=> [ASTableView/ASCollectionView] Enable Scrolling/Selecting Pending Items

AsyncDisplayKit/ASCellNode.h, AsyncDisplayKit/ASCellNode.mm, AsyncDisplayKit/ASEditableTextNode.h, AsyncDisplayKit/ASEditableTextNode.mm, AsyncDisplayKit/ASImageNode.h, AsyncDisplayKit/ASImageNode.mm, AsyncDisplayKit/ASTextNode.h, AsyncDisplayKit/ASTextNode.mm, AsyncDisplayKit/ASVideoNode.h, AsyncDisplayKit/ASVideoNode.mm, AsyncDisplayKit/ASViewController.h, AsyncDisplayKit/Details/ASAbstractLayoutController.h, AsyncDisplayKit/Layout/ASLayout.h, Base/ASBaseDefines.h
Using Objective-C attributes, in this case `unavailable`, we can hide unsupported APIs at compile time instead of detecting and warn about it at runtime with a set of asserts.
I think this is not only more safe but also more friendly to newcomers which are able to correctly identify the API that they should be using with each node.
=> Prevent API misuse at compile time

AsyncDisplayKit/ASDisplayNode.mm
The pending layout transition needs to stay alive at least until applySubnodeInsertions did finish execute as it can happen that with Implicit Hierarchy Management new nodes gonna be added that internally call setNeedsLayout what will invalidate and deallocate the transition in the middle of inserting nodes
Stack Trace:
[__pendingLayoutTransition__recursively_being_set_while_still_in_use_.m.zip](https://github.com/facebook/AsyncDisplayKit/files/404188/__pendingLayoutTransition__recursively_being_set_while_still_in_use_.m.zip)
=> [ASDisplayNode] Fix if pending layout will be deallocated

AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/Details/ASCollectionDataController.h, AsyncDisplayKit/Details/ASCollectionDataController.mm, AsyncDisplayKit/Details/ASDataController.h, AsyncDisplayKit/Details/ASDataController.mm, AsyncDisplayKit/Details/ASIndexedNodeContext.h, AsyncDisplayKit/Details/ASIndexedNodeContext.mm, AsyncDisplayKit/Details/ASRangeController.mm, AsyncDisplayKit/Private/ASDataController+Subclasses.h
- Set it up to cancel work if the data source goes away.
- Rename and clean up some methods
- Make `dataSource` readonly, so that once it's gone we can be sure it's time to stop doing anything
- Add a mechanism to see how much work we avoided with this change. I don't have a device handy right now but the results on the simulator aren't great. I'll test it with a device and report back. 
@appleguy I'd like to cancel laying out nodes on reload data, but I'm hesitating because I want your opinion about the risk involved with completion handlers. So if I call insertRowsAtIndexPaths: with 20 items, and in the completion handler I assume those 20 items are there, but I pre-empted it with reloadData, we should probably still call the completion handler but those items may not have been …
=> [ASDataController] Cancel Work if We Lose Data Source, Cleanup

AsyncDisplayKit/Private/ASImageNode+CGExtras.m
Quick fix pointed out by @GitGadd in issue #2040.
This code is original (circa 2014) and appears to be a mistake?
=> [ASImageNode] fix scaling math

AsyncDisplayKit/ASTextNode.mm
We didn't pass through shadow properties via the renderer attributes. That meant that the renderer shadower didn't get those and so setting a shadow on the text node did not have any effect.
=> [ASTextNode] Fix ASTextNode shadow is not rendering 

AsyncDisplayKit/Details/ASChangeSetDataController.mm
We should have already been doing this but ASDataController thought it knew what it was doing.
=> [ASDataController] Bail on waitUntilUpdatesAreCommitted if batch updating

AsyncDisplayKit/Layout/ASLayoutSpec.h
Move to property for `child` and `children` in `ASLayoutSpec` for nice dot syntax
=> [ASLayoutSpec] Make child and children a property

AsyncDisplayKit/Details/ASDataController.mm
ASChangeSetDataController is responsible for interpreting batch updates now. Having this dead code here hid a pretty major issue from us earlier today, so it's time to go. It also makes the data controller seem way more complex than it is.
I know the diff is hard to read because the indentation level so here's the changes:
- Remove `editCommandWithBlock` – all edit commands should be processed immediately
- Remove _pendingEditCommandBlocks and _batchUpdateCounter – same reason
- Move our beginUpdates logic into the actual beginUpdates, instead of the beginning of endUpdates
I've tested this for a while against current Pinterest master.
=> [ASDataController] Remove Unused Batch Update Processing Code

AsyncDisplayKit/ASContextTransitioning.h, AsyncDisplayKit/ASDisplayNode+Beta.h, AsyncDisplayKit/ASDisplayNode.h, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/_ASTransitionContext.m, AsyncDisplayKitTests/ASDisplayNodeImplicitHierarchyTests.m
Work so far:
- Move out Transition Layout API of beta header
- Remove `shouldMeasureAsync` parameter and deprecate old Layout Transition API methods
- Rename `cancelLayoutTransitionsInProgress` to `cancelLayoutTransition`
=> [Layout Transition API] Move Transition Layout API out of beta header and remove shouldMeasureAsync from API

AsyncDisplayKit/ASVideoNode.mm
Hi guys,
I looked into how the `playerStatus` is handled in the `ASVideoNode`, and how the `asset` / `playerItem` are loaded. It seems that some unnecessary reloading is happening. For example, `fetchData` loads the `playerItem` if the state is not `ASVideoNodePlayerStateInitialLoading`, but what about if the `playerItem` is already loaded (paused for example)?
This brought me to make the following changes:
- `fetchData` only triggers loading when the state is `ASVideoNodePlayerStateUnknown`. If you think about it, all other states actually indicate that the item is currently loading or has been loaded, so no need to do that again.
- `ASVideoNodePlayerStateInitialLoading` is no longer used. I think it is a bit ambiguous. For example, if someone calls `pause` during the initial loading, …
=> [ASVideoNode] Improve playerStatus behaviour and image generation

AsyncDisplayKit/ASCollectionView.h, AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASPagerNode.h, AsyncDisplayKit/ASPagerNode.m, AsyncDisplayKit/Details/ASCollectionViewFlowLayoutInspector.h, AsyncDisplayKit/Details/ASCollectionViewFlowLayoutInspector.m, examples/AsyncDisplayKitOverview/Sample/Node Containers/OverviewASPagerNode.m, examples/VerticalWithinHorizontalScrolling/Sample/ViewController.m
Moving `constrainedSizeForNodeAtIndexPath:` to delegate in `ASCollectionView` as well as `ASPagerNode` to be aligned with similar Apple API's in `UICollectionView`
Will replace #1740
=> [ASCollectionView / ASPagerNode] Move constrainedSizeForNodeAtIndexPath from the DataSource to the Delegate

AsyncDisplayKit/ASVideoNode.h, AsyncDisplayKit/ASVideoNode.mm
The `playerLayer` is needed for picture in picture support on the iPad (`AVPictureInPictureController`).
Example:
```swift
guard AVPictureInPictureController.isPictureInPictureSupported() else { return }
guard let playerLayer = videoNode.playerLayer else { return }
pipController = AVPictureInPictureController(playerLayer: playerLayer)
```
=> [ASVideoNode] Expose AVPlayerLayer on ASVideoNode

AsyncDisplayKit/ASViewController.h
This wrong annotation was introduced by me in #2035, `- initWithCoder:` which is a failable initialiser needs a return type marked as `nullable`.
=> Fix wrong annotation which is causing a warning at compile time

AsyncDisplayKit/ASDisplayNode.mm
This fixes a regression (found in Pinterest) with #2052.
=> [ASDisplayNode] Don't use the default layout transition animation of no animation is wanted

AsyncDisplayKit/ASPagerNode.m, AsyncDisplayKit/Details/ASDelegateProxy.m
This is a fix for a regression caused by #2065.
=> [ASPagerNode] Fix methods from ASCollectionDelegate are not passed through to pager delegate

AsyncDisplayKit/ASTextNode.mm, AsyncDisplayKit/Details/CGRect+ASConvenience.h
=> [ASTextNode] placeholder image shouldn't draw for zero area strings

AsyncDisplayKit/Details/_ASDisplayViewAccessiblity.mm
There are two changes here:
1. Because we can't reliably update the screen positions of accessibility elements
contained within a scroll view, we need to calculate them on demand, so we override
the accessibilityFrame method to do that.
2. Throwing away our calculated accessibility elements on frame change seemed to
cause the accessibility system to be confused.
Combining these two fixes together results in success, yay!
=> [_ASDisplayViewAccessiblity] Fix accessibility in scroll views

AsyncDisplayKit/Details/ASWeakProxy.h, AsyncDisplayKit/Details/ASWeakProxy.m
But I think I do now :)
Previously I inherited from NSObject because I didn't think I needed
anything fancy, but it turns out NSProxy is *less* fancy than NSObject
and allows for overriding more methods. This change is probably purely
academic in that we don't use this class to forward NSObject specific
messages, but I believe this is the 'right thing'.
=> I didn't really understand NSProxy

AsyncDisplayKit/ASTableView.mm
This can cause pointless beginUpdates/endUpdates pairs that interfere with scrolling animations.
=> [ASTableView] Ignore Table Cell Layouts When There's No Node Assigned

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Private/ASDisplayNodeInternal.h
This clarifies some behavior that I found confusing when debugging. This does not change any behavior. Worked with @maicki to:
- Rename `canCallNeedsDisplayOfLayer` to `canCallSetNeedsDisplayOfLayer` to be clearer.
- Make the rationale around that flag clearer. The actual behavior of the code is the same.
- We cannot clear the contents or setNeedsDisplay of UIImageView-wrapping nodes.
- We can do both of the above on any other kind of node.
- We must call `setNeedsDisplay` on all non-UIImageView wrapper nodes in `recursivelyTriggerDisplayForLayer`, but there's no need to call it on normal nodes
=> [ASDisplayNode] Clarify Some Special Logic Around Wrapper Nodes

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/Details/ASCollectionDataController.h, AsyncDisplayKit/Details/ASCollectionDataController.mm, AsyncDisplayKit/Details/ASCollectionViewFlowLayoutInspector.h, AsyncDisplayKit/Details/ASCollectionViewFlowLayoutInspector.m, AsyncDisplayKitTests/ASCollectionViewFlowLayoutInspectorTests.m, AsyncDisplayKitTests/ASUICollectionViewTests.m
This adds a test that confirms UICollectionView will throw an exception for supplementary nodes that are outside of the normal `-numberOfSections` range.
This means that there is only one set of sections, so this method is a misconception. Deprecated as a reminder to remove, and we'll never call it.
This is probably the first of many changes to our collection view stuff
=> Remove numberOfSectionsForSupplementaryNodeOfKind: Method

AsyncDisplayKit/ASViewController.mm, AsyncDisplayKit/Details/ASEnvironment.mm
Previously we were only propagating the trait collection on `viewWillTransitionToSize` since it is called shortly after `willTransitionToTraitCollection`. However, some important things can happen in that time “shortly after” (like collection view layout). As long as nothing changes from `willTransitionToTraitCollection` to `viewWillTransitionToSize` (which it shouldn’t) the traits will not be re-propagated anyhow.
Also make sure to use the `ASEnvironmentTraitCollectionMakeDefault` method when creating new envTraitCollection so the struct isn’t filled with junk.
=> [ASViewController] Propagate the traits on willTransitionToTraitCollection

AsyncDisplayKit/Details/ASCollectionDataController.mm, AsyncDisplayKit/Details/ASDataController.mm, AsyncDisplayKit/Private/ASDataController+Subclasses.h
This resolves an issue where, say you have 3 sections, but only 2 of them have headers. Before, we would only store 2 sections' worth of headers, but if you then delete section #2, we are out of bounds when we try to retrieve that section of headers.
This diff makes sure that even if only 2 sections have headers, we always have 3 arrays, so that items & supplementaries stay completely in sync.
This issue recently became more apparent because we removed the sectionsForSupplementaryNodeOfKind: method which, ironically, if implemented correctly would have caused the problem but was virtually always implemented just to return `numberOfSections`, masking it. In the future (ship task 193) we will continue to make changes to our storage of supplementary nodes, to support section-level …
=> [ASDataController] Ensure Supplementary Section Count Always Tracks Item Section Count

AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/Details/_ASDisplayLayer.h, AsyncDisplayKit/Details/_ASDisplayLayer.mm, AsyncDisplayKitTests/ASCollectionViewTests.mm
We previously waited until `layoutSubviews` but that's too late as @rcancro discovered.
I added a failing test case that ensures everything is up-to-date before the first relayout after a rotation.
I expect this to be somewhat controversial because I did something unusual. In order for ASCollectionView to find out about the bounds change before UICollectionView requeries the layout object, I added an optional `ASCALayerExtendedDelegate` protocol. Basically if your view responds to these methods, ASDisplayLayer will call them. I can't use our _ASDisplayLayerDelegate because collection views may not have nodes.
I considered adding an _ASCollectionLayer class with special functionality but decided this more general solution was better.
I also renamed some ivars in ASCollectionView for …
=> [ASCollectionView] Relayout Nodes as Soon as Bounds Changes

AsyncDisplayKitTests/ASImageNodeSnapshotTests.m
The test was throwing an exception because the image node had not been formally measured. This fixes it.
=> [ASImageNodeSnapshotTests] Fix Issue with forcedSize Test

AsyncDisplayKit/ASViewController.mm
Wait until all subnodes have the new trait collection before laying out the root node. The way I’m using `asyncTraitCollectionDidChange`, I sometimes call methods that call `setNeedsLayout` which causes a new layout pass to begin before the new trait collection has been propagated to all nodes. This leads to weird behavoir, like nodes being laid out twice in the same call stack or being laid out with the node's previous constrainedSize (instead of the new size from the bounds). 
This change won’t stop possibly unnecessary layout passes because of `asyncTraitCollectionDidChange`, but it will at least do a complete layout pass once we have propagated all traits.
Ultimately the solution to this problem (as Adlai pointed out) is to wait until the CA transaction commit to perform the actual …
=> [ASViewController] Layout root node AFTER propagating all the traits

AsyncDisplayKit/TextKit/ASTextKitRenderer.mm
In the future we should try and reuse these, as setting them up is super expensive, but this brings a pretty serious benefit by letting layout continue in parallel with the teardown:
[BeforeAndAfterTextKitDeallocationQueue.trace.zip](https://github.com/facebook/AsyncDisplayKit/files/436083/BeforeAndAfterTextKitDeallocationQueue.trace.zip)
@appleguy @maicki
=> [ASTextKitRenderer] Shift TextKit Teardown onto the Deallocation Queue

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/ASViewController.mm, AsyncDisplayKitTests/ASViewControllerTests.m
This fixes an issue where view controllers that participate in custom transitions may be the wrong size at the end. It comes with a unit test!
The issue was, view controllers in custom transitions are fullscreen in viewWillAppear: and when they get their correct size, we then overwrite it by calling -setNeedsLayout in -propagateNewEnvironmentTraitCollection, which remeasures us against the old bad size.
The solution is to measure the VC against the new constrained size when the new environment trait collection goes down.
This fixes Martin's issue, and it should go into 6.10. @garrettmoon @maicki @rcancro
=> [ASViewController] Remeasure Node With New Constrained Size When Propagating Traits

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/Details/ASDataController.mm, AsyncDisplayKit/Private/ASDispatch.h, AsyncDisplayKitTests/ASDispatchTests.m
`dispatch_apply` always spawns only one thread per core. That's not enough for us!! So I made a variant that allows you to specify how many threads you want.
@appleguy @maicki @levi
=> [ASDataController] Use 2 Threads Per CPU When Measuring Nodes

AsyncDisplayKit/ASTextNode+Beta.h, AsyncDisplayKit/ASTextNode.mm, AsyncDisplayKit/TextKit/ASTextKitAttributes.h, AsyncDisplayKit/TextKit/ASTextKitAttributes.mm, AsyncDisplayKit/TextKit/ASTextKitContext.h, AsyncDisplayKit/TextKit/ASTextKitContext.mm, AsyncDisplayKit/TextKit/ASTextKitFontSizeAdjuster.mm, AsyncDisplayKit/TextKit/ASTextKitRenderer.mm, AsyncDisplayKit/TextKit/ASTextKitTailTruncater.mm, AsyncDisplayKitTests/ASTextKitTruncationTests.mm
This API was a hack. In the future we will be reusing NSTextStorage objects and we need to have control over how they are created. 
Pinterest is no longer using this API.
Ready for review @maicki @appleguy
=> Remove textStorageCreationBlock API

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/ASCellNode.mm, AsyncDisplayKit/ASCollectionNode.mm, AsyncDisplayKit/ASDisplayNode+Deprecated.h, AsyncDisplayKit/ASDisplayNode+Subclasses.h, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/ASImageNode+AnimatedImage.mm, AsyncDisplayKit/ASMultiplexImageNode.mm, AsyncDisplayKit/ASNetworkImageNode.mm, AsyncDisplayKit/ASTableNode.mm, AsyncDisplayKit/ASVideoNode.mm, AsyncDisplayKit/ASVideoPlayerNode.mm, AsyncDisplayKitTests/ASDisplayNodeTests.m, AsyncDisplayKitTests/ASVideoNodeTests.m
We finally settled on
didEnter/ExitDisplayState
didEnter/ExitPreloadState
didEnter/ExitVisibleState
This change is meant to unify the range update methods to relate to each
other and hopefully be a bit more self explanatory.
=> [ASDisplayNode] Renamed range update callbacks

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/Details/CGRect+ASConvenience.h, AsyncDisplayKitTests/ASPerformanceTestContext.h, AsyncDisplayKitTests/ASPerformanceTestContext.m, AsyncDisplayKitTests/ASTextNodePerformanceTests.m, AsyncDisplayKitTests/ASTextNodeTests.m
This will hopefully help us monitor and improve our text layout performance. There is certainly a ton of room for improvement. 
The tests are currently single-threaded. In the future we could beef em up to be multithreaded. 
Ready for review @maicki @appleguy @garrettmoon @levi 
Here are the current results on my machine:
```
Test Suite 'Selected tests' started at 2016-08-28 15:26:24.649
Test Suite 'ASTextNodePerformanceTests' started at 2016-08-28 15:26:24.650
Test Case '-[ASTextNodePerformanceTests testPerformance_OneParagraphLatinWithTruncation]' started.
Results:
<UIKit               : time-per-1000=0.06 rel-perf=1.00 user-info={     size = "{348, 134}"; }>
<ASDK                : time-per-1000=0.47 rel-perf=0.13 user-info={     size = "{344, 134}"; }>
Test Case …
```
=> [Unit Tests] Add Text Layout Performance Tests

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Private/ASInternalHelpers.h, AsyncDisplayKit/Private/ASInternalHelpers.m, AsyncDisplayKitTests/ASDisplayNodeLayoutTests.mm
It's not allowed to modify submodes in `layoutSpecThatFits:` or in the `layoutSpecBlock` block. This PR adds an assertion if DEBUG enabled to assert if this is happening.
=> [Layout] Assert if subnodes where modified during layoutSpecThatFits:

AsyncDisplayKit/Details/ASCollectionViewFlowLayoutInspector.m, AsyncDisplayKitTests/ASCollectionViewFlowLayoutInspectorTests.m
With 2.0 `collectionView:constrainedSizeForNodeAtIndexPath:` was moved to the delegate. Assert if not implemented on the delegate but on the data source.
=> [ASCollectionView] Add assert for data source implementing collectionView:constrainedSizeForNodeAtIndexPath: instead of delegate

AsyncDisplayKit/Details/Transactions/_ASAsyncTransaction.h, AsyncDisplayKit/Details/Transactions/_ASAsyncTransaction.mm, AsyncDisplayKit/Private/ASDisplayNode+AsyncDisplay.mm
Now that ASAsyncTransaction manages a thread pool, we don't need to use a semaphore to limit concurrent displays.
@appleguy should probably review this since he's the only one with super deep knowledge about this code. Obviously this isn't urgent, it'll be here whenever you have time.
=> [ASDisplayNode] Remove Display Semaphore

AsyncDisplayKit/ASDisplayNodeExtras.h
Resolves linker errors and allows inline functions such as `ASInterfaceStateIncludesVisible` to be used outside of ASDK framework files.
Also according to this:
http://stackoverflow.com/questions/18623392/how-to-write-global-inline-functions-in-objective-c-using-c-syntax
Global inline functions should be static
=> make inline functions in ASDisplayNodeExtras.h static 

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Details/_ASDisplayView.mm, AsyncDisplayKitTests/ASCollectionViewTests.mm, AsyncDisplayKitTests/ASDisplayNodeTests.m
See #2011 .
The issue is, if the view outlives the node and its subnodes, then its sublayers will not get the order-out action until after willMoveToSuperview.
So I moved the `__exitHierarchy` call from `willMoveToSuperview` to `didMoveToSuperview` which fixes the issue!
=> Fix Case Where Node Is Deallocated While Visible

AsyncDisplayKit.xcodeproj/xcshareddata/xcschemes/AsyncDisplayKit.xcscheme, AsyncDisplayKitTests/ASTextNodePerformanceTests.m
This will skip the performance tests when you ⌘U or when the CI runs "xcodebuild test".
You can still run/profile them whenever you want by clicking the little diamond. In the future we may remove the expected performance ranges, but for now I'm leaving them.
=> Skip Performance Tests By Default

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKitTests/ASDisplayNodeLayoutTests.mm
If no measure pass happened or the bounds changed between layout passes we manually trigger a measurement pass for the node using a size range equal to whatever bounds were provided to the node
=> [Layout] Automatic measure pass in layout pass if not happened before

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Private/ASDisplayNode+UIViewBridge.mm
_ASPendingState objects can add up very quickly when adding
many nodes. This is especially an issue in large collection views
and table views. This needs to be weighed against the cost of
reallocing a _ASPendingState. So in range managed nodes we
delete the pending state, otherwise we just clear it.
@Adlai-Holler @appleguy Does this patch make sense? Is it safe?
Profiling Pinterest and just scrolling down these start to add up.
With ~500 pin nodes and a total of 115MiB, pending state made
up 3.52MiB. With this patch, no matter how far you scroll, pending
state stays at about 500KiB.
Separately, I looked at allocation of nodes vs pending states
created when scrolling and they approximately matched when
scrolling the homefeed suggesting there's no cost to recreating them?
=> [ASDisplayNode] Dealloc _pendingViewState if range managed

AsyncDisplayKit/ASDisplayNodeExtras.mm, AsyncDisplayKitTests/ASDisplayNodeTests.m
We don't call the block on every subnode if the node that is passed in ASDisplayNodePerformBlockOnEveryNode has shouldRasterizeDescendants enabled as it tries to iterate through the sublayer hierarchy, but there are no sublayers
=> [ASDisplayNode] Fix using ASDisplayNodePerformBlockOnEveryNode if node is loaded and has shouldRasterizeDescendants enabled

AsyncDisplayKit/ASCellNode.mm, AsyncDisplayKit/ASDisplayNode+Deprecated.h, AsyncDisplayKit/ASDisplayNode.h, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKitTests/ASDisplayNodeImplicitHierarchyTests.m, examples/ASDKLayoutTransition/Sample/ViewController.m
We need a way to force a synchronous measurement in a layout transition. As the API we wanted to introduce in 2.0 does not didn't took that in consideration I think it makes the most sense to go back to the old API but not to force calling the layout transition API from the main thread.
@appleguy @levi @Adlai-Holler Would be great if you could take a look
=> [Transition API] Add old transition API back but allow call from background thread

AsyncDisplayKit/Private/_ASHierarchyChangeSet.mm
So they can read the message before the exception bubbles up.
=> [ASDataController] Log Update Validation Message Before Throwing

AsyncDisplayKit/Layout/ASStackLayoutSpec.mm
To align with the CSS `align-items` property we should set alignItems to `ASStackLayoutAlignItemsStretch` instead of `ASStackLayoutAlignItemsStart`: https://drafts.csswg.org/css-flexbox-1/#propdef-align-items
=> [ASStackLayoutSpec] Set alignItems to ASStackLayoutAlignItemsStretch

AsyncDisplayKit/ASImageNode.mm
By default, images are drawn with the normal blending mode. kCGBlendModeCopy is a lot faster when you can use it.
~~Compare the following results from 30 seconds of Pinterest, the first using normal and the second using copy. Currently PINRemoteImage returns images that falsely have alpha components so for this test, I ALWAYS used copy. So this is basically a theoretical maximum. But most of our large images are JPEGs so we should be able to get close.~~
|                              | Normal | Copy   |
|------------------------------|--------|--------|
| ImageNode Drawing            | 3361ms | 1813ms |
| TextNode Drawing (reference) | 353ms  | 405ms  |
| Ratio                        | 9.5x   | 4.48x  |
~~So image drawing, which is the most expensive operation we do, is twice as fast …
=> [ASImageNode] Use kCGBlendModeCopy when Possible

AsyncDisplayKit/ASImageNode.mm, AsyncDisplayKit/Private/ASInternalHelpers.h
This is a follow-up to #2197 that considers other CGImageAlphaInfo values that also indicate opaque.
=> [ASImageNode] Use kCGBlendModeCopy More Often

AsyncDisplayKit/ASViewController.mm
We don't need to do anything with our traits at this point. Propagating just leads to confusion as the view bounds don't always match up with the new traits.
=> [ASViewController] stop propagating traits in the `viewWill...` methods

AsyncDisplayKit/ASCellNode.mm, examples/ASDKgram/Sample/CommentsNode.m, examples/ASDKgram/Sample/PhotoCellNode.m
Don't use `automaticallyManageSubnodes` in `ASTextCellNode` as all subclasses will inherit this behavior. In ASDKGram the `CommentsNode` is a subclass of `ASTextCellNode` and in there we didn't expect ASM of the superclass so subnodes where added and removed explicitly. Currently asm does not support automatic and manual adding and removing of subnodes yet. This caused crashes in ASDKGram.
A PR will follow that will add error handling (throw exception to the user with information) for this case.
=> [Layout] Don't use `automaticallyManageSubnodes` in ASTextCellNode

AsyncDisplayKit/ASTextNode.mm
A hash collision was causing some false positive cache hits.
=> Fix Equality in ASTextKitRendererKey

AsyncDisplayKit/ASDisplayNode.h, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Private/ASDisplayNodeInternal.h, AsyncDisplayKitTests/ASDisplayNodeTests.m
Obviously we already have `didLoad`, but engineers still do view-related stuff in `init`.
This provides engineers with an easy way to capture arguments or state from `-init` and run it safely after the view is loaded. 
What do you guys think? Worthwhile?
P.S. I also realized that if you make a wrapper node with `initWithViewBlock:` and then we unload it because it becomes rasterized, we actually can't get it back because we dispose of the view block. I added assertions against rasterizing wrapper nodes for this reason and since it's a very bad idea.
=> [ASDisplayNode] Add `onDidLoad` Method to Perform Work When Loaded

AsyncDisplayKitTests/ASDisplayNodeTests.m
We were (correctly) getting a crash when the block_invoke tried to retain self.
=> Fix the Dealloc Test

AsyncDisplayKitTests/ASDisplayNodeTests.m
In the time between #2128 passed its tests, and when it landed, `ASDisplayNodeTests.m` was migrated to ARC so the code became incompatible. This fixes that.
=> Fix the DisplayNode Test Merge Fail

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Details/_ASDisplayView.mm, AsyncDisplayKit/Private/ASDisplayNode+FrameworkPrivate.h
The previous code used either a `@property` with `assign, nonatomic` semantics, or a `__unsafe_unretained` (non-atomic) ivar pointer to an instance for `asyncdisplaykit_node`.
This commit changes those access so that they have the equivalent of `weak, atomic` semantics.
- `_ASDisplayView.mm`
- Removes the `_node` ivar that was qualified with `__unsafe_unretained`.
- Removes `@synthesize asyncdisplaykit_node = _node;`.
- All direct uses of `_node` were replaced with:
- Creates a strong reference via `ASDisplayNode *node = _asyncdisplaykit_node;`.
- `s/_node/node/`.
- These changes were made even if there's a single use of `_asyncdisplaykit_node` as a consistency / defensive measure so that anyone editing this code in the future does not accidentally use a `weak` reference twice.
- …
=> Fixes unsafe use of `asyncdisplaykit_node`.

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Private/ASObjectDescriptionHelpers.h, AsyncDisplayKit/Private/ASObjectDescriptionHelpers.m
I believe that #2229 is caused by #2011 failing the assertion, and attempting to describe the node during dealloc.
The description method has not been dealloc-safe since #2208. This patch makes the description functions dealloc-safe.
=> Make Description Functions Dealloc-Safe

AsyncDisplayKit/Details/ASEnvironment.h, AsyncDisplayKit/Details/ASEnvironment.mm, AsyncDisplayKit/Private/ASEnvironmentInternal.mm, AsyncDisplayKitTests/ASStackLayoutSpecSnapshotTests.mm
This is a freshly-rebased variant of #2071 for merging.
To align with the CSS flex-shrink spec, set the default value of flexShrink to YES: http://www.w3.org/TR/css-flexbox-1/#propdef-flex-shrink
=> Set .flexShrink to YES by default

AsyncDisplayKit/ASTableView.mm
If this happens, it can cause invalid update exceptions because the data source count unexpectedly dropped from e.g. 32 to 0. A more correct fix for this is #2182 but it's causing other problems, and this is sufficient.
=> [ASTableView] Don't beginUpdates/endUpdates on Cell Relayout If No Data Source

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Details/ASWeakProxy.m, AsyncDisplayKit/Details/Transactions/_ASAsyncTransactionContainer.h, AsyncDisplayKit/Details/Transactions/_ASAsyncTransactionContainer.m, AsyncDisplayKit/Details/_ASDisplayView.mm, AsyncDisplayKit/Private/ASDisplayNode+UIViewBridge.mm, AsyncDisplayKitTests/ASDisplayNodeTests.m
CALayer's delegate property is declared `weak` but implemented `assign`.
If the node is marked for deallocation on a background thread, and the layer tries to access its delegate before the node runs `dealloc` (deferred by ASDealloc2MainObject) then you get a crash for trying to retain an object after it's marked for deallocation.
This diff uses a proxy object between the layer and the node. The layer retains the proxy.
=> [ASDisplayNode] Use Weak Proxy to Avoid Dangling CALayer.delegate

AsyncDisplayKit/ASDisplayNode.mm
While debugging today, I was trying to `po someLoadedNode` (calls -debugDescription) from a background thread and ran into the `inHierarchy` thread affinity assertion. We don't need it, so let's get rid of it.
=> Remove Unneeded Thread Affinity Assertions

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/ASDisplayNode+Beta.h, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/ASDisplayNodeExtras.h, AsyncDisplayKit/Details/ASEnvironment.h, AsyncDisplayKit/Details/ASEnvironment.mm, AsyncDisplayKit/Details/ASTraceEvent.h, AsyncDisplayKit/Details/ASTraceEvent.m, AsyncDisplayKit/Private/ASDisplayNode+FrameworkPrivate.h, AsyncDisplayKit/Private/ASDisplayNodeInternal.h, AsyncDisplayKit/Private/ASObjectDescriptionHelpers.h, AsyncDisplayKit/Private/ASObjectDescriptionHelpers.m
When trying to debug issues like #2242 or the recent retain crashes, it can be extremely valuable to know the history of a node. So now you can define `ASDISPLAYNODE_EVENTLOG_ENABLE` (on in debug by default), and we will save the last `ASDISPLAYNODE_EVENTLOG_CAPACITY` (default 20) events for each node in a ring buffer. 
Subclasses can log custom events with `ASDisplayNodeLogEvent(self, @"myEvent: %@", myArg);`
Obviously this shouldn't be used in production. It's designed to be pretty efficient and so will probably not affect debugging.
This was tremendously helpful in isolating #2242 and I think it will serve us very well in future development.
Events:
- init
- didLoad
- supernodeDidChange
- add/removeSubnode
- interfaceState changes
- hierarchyState changes
- size/layout calculations
- …
=> [ASDisplayNode] Add Event Tracing to Help Debugging

AsyncDisplayKit/ASViewController.mm
Fixes an iOS 7 regression that would reliably cause crashes, from #2202.
=> [ASViewController] Fix Accessing traitCollection on iOS 7

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/ASDisplayNodeExtras.h, AsyncDisplayKit/ASDisplayNodeExtras.mm, AsyncDisplayKitTests/ASSnapshotTestCase.m
Scenario: An ASCollectionNode is a subnode of an ASCellNode.  A layout transition is started, resulting in the removal of the ASCollectionNode as a subnode.  As it is removed, the hierarchy state is cleared - including the "range managed" bit - on the ASCollectionNode.  However, the deep recursion traverses the layer hierarchy too, and clears this bit on the ASCellNodes inside the ASCollectionNode.  A moment later, the collection performs its final ASRangeController update to mark its cells as invisible and free memory.  Then an assertion is triggered in ASRangeController, because it is operating on nodes that do not have the "range managed" bit set.
It turns out that ASInterfaceState also propogates in this way, but that behavior is efficient and beneficial in its current configuration …
=> [ASDisplayNode] Ensure ASHierarchyState propagation does not jump discontinuities in the node hierarchy.

AsyncDisplayKit/ASButtonNode.h, AsyncDisplayKit/ASButtonNode.mm
Currently `ASButtonNode`, when both image and text co-exist, the only possible placement combination is image at the left and text at the right. This is because in the `layoutSpecThatFits:` implementation in `ASButtonNode`, an horizontal `ASStackLayoutSpec` is used and no customization is possible.
Subclassing `ASButtonNode` to solve this is not trivial as well given the fact that the stack spec might be a child of another spec.
=> Add support to image alignment in ASButtonNode

AsyncDisplayKit/ASDisplayNode+Beta.h, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Private/ASDisplayNodeInternal.h, AsyncDisplayKit/Private/_ASScopeTimer.h
Revises performance measurement naming and structure based on Scott's feedback.
- Revises naming from LayoutSpecGeneration to LayoutSpecComputation
- Adds a struct instead of an NSDictionary to retrieve performance metrics
- Includes ASEnvironmentStatePropagateDown in LayoutSpecComputation measurements
=> Revise performance measurement naming and structure

AsyncDisplayKit/Details/ASEnvironment.mm, AsyncDisplayKitTests/ASStackLayoutSpecSnapshotTests.mm
After learning about the number and art of changes we had to do for bringing the recent change for `flexShrink = YES` to Pinterest,  I did further research on the default for `flexShrink = YES` and found other libraries default it to `NO` — even though CSS on the web is `YES`. We've made a final decision that `flexShrink` should remain its current default of `NO`
=> [Layout] Set default value of `flexShrink` to `NO`

AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKitTests/ASCollectionViewTests.mm, AsyncDisplayKitTests/ASTableViewTests.m
Improves assertion message if `tableView:nodeBlockForRowAtIndexPath:` / `tableView:nodeForRowAtIndexPath:` or `collectionView:nodeForItemAtIndexPath:` / `collectionView:nodeBlockForItemAtIndexPath:` is not implemented
=> [ASTableView / ASCollectionView] Improve assertion messages if necessary data source methods are not implemented

AsyncDisplayKit/Layout/ASDimension.h, AsyncDisplayKitTests/ASDimensionTests.mm
- Enabling assertions for creating auto dimensions via `ASDimensionMake` and providing a value != 0. There is also a constant that actually makes creating auto dimensions called: `ASDimensionAuto`
- Enabling assertions for creating fraction dimensions within the range of 0.0 and 1.0
=> [Layout] Add assertions for creating an invalid ASDimension from type ASDimensionUnitAuto and ASDimensionUnitFraction

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Layout/ASLayoutSpec.mm, AsyncDisplayKit/Layout/ASLayoutable.h
Currently the styleClass property does not give us any benefits. Let's remove it for now until we found a more though trough way to add extensibility for styles.
=> [Layout] Remove styleClass property from ASLayoutable for now

AsyncDisplayKit/ASCollectionView.h, AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.h, AsyncDisplayKit/ASTableView.mm
This addresses cases where users are calling `waitUntilAllUpdatesAreCommitted` during this callback in order to get the cell node. This practice is unsafe, because you may be editing a collection view while the collection view is calling back to you.
Ready for review @maicki @appleguy @hannahmbanana!
=> [ASCollectionView] Pass the Cell Node Through in willDisplayNode: Delegate Method

.travis.yml, build.sh
Now that our Jenkins builds run on Xcode 8, we need to use the iOS 10 SDK. This should fix Jenkins builds where [examples fail](http://jenkinsmaster-vpc-007.ec2.pin220.com/job/AsyncDisplayKit-PRs/384/console) due to missing 9.3 SDK.
=> [build.sh] Update Build Scripts to Get CI Working

AsyncDisplayKit/ASButtonNode.mm, AsyncDisplayKit/ASDisplayNode.h, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/ASImageNode.mm, AsyncDisplayKit/ASVideoNode.mm, AsyncDisplayKit/Private/ASDisplayNodeInternal.h, AsyncDisplayKitTests/ASDisplayNodeTests.m
- Remove all support for preferredFrameSize in ASDK
- preferredFrameSize setter calls through and sets the width and height of the node
- preferredFrameSize getter tries to return a CGSize based on the width and height properties otherwise if this is not possible it throws
=> [Layout] Further deprecation steps for `preferredFrameSize`

AsyncDisplayKit/ASCollectionNode.h, AsyncDisplayKit/ASCollectionView.h, AsyncDisplayKit/Details/ASChangeSetDataController.mm, AsyncDisplayKit/Private/_ASHierarchyChangeSet.h, AsyncDisplayKit/Private/_ASHierarchyChangeSet.mm, AsyncDisplayKitTests/ASCollectionViewTests.mm, AsyncDisplayKitTests/ASUICollectionViewTests.m
Prior to this diff, we would only call the outermost completion handler.
Ready for review! @appleguy @maicki @levi
=> [ASDataController] Call All Completion Handlers after Nested Batch Updates

AsyncDisplayKit/ASButtonNode.h, AsyncDisplayKit/ASDisplayNode.h, AsyncDisplayKit/ASImageNode.h, AsyncDisplayKit/ASNavigationController.h, AsyncDisplayKit/ASPagerFlowLayout.h, AsyncDisplayKit/ASTabBarController.h, AsyncDisplayKit/ASTableNode.h, AsyncDisplayKit/ASTextNode+Beta.h, AsyncDisplayKit/ASVisibilityProtocols.h, AsyncDisplayKit/AsyncDisplayKit+Debug.h, AsyncDisplayKit/Details/ASCollectionInternal.h, AsyncDisplayKit/UIImage+ASConvenience.h
I was poking around in the Swift example this morning and I found some missing nullability specifiers. These make for an extremely unpleasant Swift experience.
After this diff, all of our public headers (the ones in the root folder anyway) have full nullability specifications.
=> Add More Nullability Annotations to Public Headers

AsyncDisplayKitTests/ASDisplayNodeTests.m
=> [ASDisplayNode] Failing Test Case: Rasterized Nodes Should Get Interface State Updates

AsyncDisplayKit/ASTextNode.mm
Due to recent changes in the text system the `ASTextKitRenderer` is not build in a thread safe way anymore and if the same renderer is used in multiple text nodes can cause crashes.
Disable the renderer cache for the time being.
=> [ASTextNode] Disable ASTextKitRenderer cache

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/Layout/ASAbsoluteLayoutElement.h, AsyncDisplayKit/Layout/ASAbsoluteLayoutSpec.h, AsyncDisplayKit/Layout/ASBackgroundLayoutSpec.h, AsyncDisplayKit/Layout/ASLayoutElement.h, AsyncDisplayKit/Layout/ASLayoutElement.mm, AsyncDisplayKit/Layout/ASLayoutSpec+Subclasses.h, AsyncDisplayKit/Layout/ASLayoutSpec+Subclasses.mm, AsyncDisplayKit/Layout/ASLayoutSpec.mm, AsyncDisplayKit/Layout/ASOverlayLayoutSpec.h, AsyncDisplayKit/Layout/ASStackLayoutElement.h, AsyncDisplayKitTests/ASDisplayNodeImplicitHierarchyTests.m
This replaces #2289 (really messy rebase).  
Renaming for clarity:
- `ASStackLayoutable` —> `ASStackLayoutElement`
=> [Layout] Rename ASStackLayoutable to ASStackLayoutElement

AsyncDisplayKit/ASCellNode+Internal.h, AsyncDisplayKit/ASCellNode.h, AsyncDisplayKit/ASCellNode.mm, AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKitTests/ASCollectionViewTests.mm
I came across these issues while working with some excellent engineers from Pinterest yesterday.
- `applyLayoutAttributes` was never being called on `ASCellNode`. See the documentation in the diff for why.
- It is useful to be able to safely get the layout attributes for a node in `willDisplayNode:forItemAtIndexPath:`. At this point you can't convert the frame because the node's not in the hierarchy yet. See the documentation in the diff for why.
The product engineers _do_ have a workaround in place for this, but we should merge this as soon as possible. Ready for review @maicki @appleguy @levi @garrettmoon @rcancro
=> [ASCellNode] Fix applyLayoutAttributes Not Called, Add Readonly Property

AsyncDisplayKit/ASButtonNode.mm
To avoid unnecessary layout pass in Pin Closeup. 
While testing the sync candidate branch for Pinterest, I noticed that the pin-to-pin closeup swipe seemed slower than normal. Unnecessary layout passes are being called every time the action bar buttons are updated for a new pin. 
Before
After
@appleguy: could you review & merge so I can get this into `6.12` and `6.13` tonight?
=> [ASButtonNode] Only change state if it's different

AsyncDisplayKit/Details/ASChangeSetDataController.mm, AsyncDisplayKit/Private/_ASHierarchyChangeSet.h, AsyncDisplayKit/Private/_ASHierarchyChangeSet.mm, AsyncDisplayKitTests/ASCollectionViewTests.mm, AsyncDisplayKitTests/ASUICollectionViewTests.m
There is an issue with UICollectionView (tested and documented in this diff) where issuing an update before the initial data load will cause an exception to be thrown.
Since #2274 , ASCollectionView has had the same issue. Since it's so infuriating, and since it's relatively easy for us to workaround on the user's behalf, this diff restores the old behavior of ignoring updates before initial data load.
=> [ASCollectionView] Allow User to Submit Updates Before Initial Data Load

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Private/ASDisplayNodeInternal.h
In at least some cases, _pendingDisplayNodes referencing self can cause the
object to live longer than the application needs, e.g. while tearing down views.
It also appears there may be a cancellation condition where this state is
not balanced properly, which can cause a reference-cycle leak.  This change
safely fixes this problem when tested against a repro case for it.
I'm filing a followup task to make sure all cancellation edge cases have
proper accounting for this codepath, even though the leak is fixed.
=> [ASDisplayNode] Change _pendingDisplayNodes from NSMutableSet to ASWeakSet

AsyncDisplayKit/ASTextNode+Beta.h, AsyncDisplayKit/TextKit/ASTextKitFontSizeAdjuster.mm, examples_extra/ASTraitCollection/Sample/KittenNode.m, examples_extra/ASTraitCollection/Sample/OverrideViewController.m
Previously we used maximumNumberOfLines and the longest word in a string to scale font size. This adds taking the constrainedSize’s height into consideration. If, without scaling, a string’s height is larger than the constrainedSize height, apply scaling.
Also fixed up the ASTraitCollection sample to work with the new layout API.
=> [ASTextKitFontSizeAdjuster] Use the constrainedSize’s height to adjust font scaling

AsyncDisplayKit/ASCollectionView.mm
See comments for details – doing this empty-update-remeasure-all-nodes is both extremely expensive and also somewhat unsafe if the data source has unreported changes. This drastically reduces the instances of it, since many collection views flow vertically and change bounds height due to status bar/nav bar/tab bar changes.
Fixes an issue in Pinterest with low risk. A permanent fix for the data unsafety issue is in #2182 but it caused other issues and I haven't had time to circle back on it yet.
Ready for review with an aim to land into our p6.12 branch.
=> [ASCollectionView] Only Remeasure All Nodes if Bounds Changed in Fixed Direction

AsyncDisplayKit/ASDisplayNode.h, AsyncDisplayKit/Details/Transactions/_ASAsyncTransaction.h, AsyncDisplayKit/Details/Transactions/_ASAsyncTransaction.mm, AsyncDisplayKit/Details/Transactions/_ASAsyncTransactionContainer+Private.h, AsyncDisplayKit/Details/Transactions/_ASAsyncTransactionContainer.h, AsyncDisplayKit/Details/Transactions/_ASAsyncTransactionContainer.m, AsyncDisplayKit/Details/Transactions/_ASAsyncTransactionGroup.h, AsyncDisplayKit/Details/Transactions/_ASAsyncTransactionGroup.m, AsyncDisplayKit/Private/ASDisplayNode+UIViewBridge.mm
The `ASAsyncTransaction` system is one of the most fundamental components of AsyncDisplayKit. It powers the asynchronous layer display process which is possibly the most reliable & performance-tuned component of the framework.
It provides lightweight, cancellable, waitable, transactionable operation semantics. It seems like it could be useful in other contexts than drawing, such as layout, or updating UIKit/CALayer properties from background threads. There's a ton of promise here.
The only problem with it, is that it works so reliably that @appleguy is the only maintainer who understands how it works and how it could be applied in other contexts.
This diff contains no functional changes. Its only purpose is to help make the system easier to understand and open the door for more general …
=> [ASAsyncTransaction] Make System Less Specific to Layer Display, More Readable

AsyncDisplayKit/ASDisplayNode+Subclasses.h, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/ASNetworkImageNode.mm, AsyncDisplayKit/Details/_ASDisplayLayer.h, AsyncDisplayKit/Private/ASDisplayNode+AsyncDisplay.mm
This is an optimization for displays where synchronous image caching is not needed, e.g. standard display-ahead in a range controller.
The first highlighted line here is the relevant one:
=> [ASDisplayNode] Add -displayWillStartAsynchronously: method to allow skipping synchronous image cache check.

AsyncDisplayKit/ASCellNode+Internal.h, AsyncDisplayKit/ASCellNode.h, AsyncDisplayKit/ASCellNode.mm, AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKitTests/ASCollectionViewTests.mm
#2321 was reverted because its test was failing under iOS 10. iOS 10 seems to use a much larger reuse queue for collection cells, which revealed an issue with the previous implementation of this feature.
This restores #2321, plus:
- We used to clear the layout attributes only in `prepareForReuse` but now we clear it in `didEndDisplayingCell:`. 
Ready for review @maicki @appleguy
=> [ASCellNode] Restore Layout Attributes Fix + iOS 10 Modification

AsyncDisplayKit/ASButtonNode.h, AsyncDisplayKit/ASCollectionNode.h, AsyncDisplayKit/ASCollectionView.h, AsyncDisplayKit/ASControlNode.h, AsyncDisplayKit/ASDisplayNode+Beta.h, AsyncDisplayKit/ASDisplayNode.h, AsyncDisplayKit/ASDisplayNodeExtras.h, AsyncDisplayKit/ASEditableTextNode.h, AsyncDisplayKit/ASMultiplexImageNode.h, AsyncDisplayKit/ASPagerNode.h, AsyncDisplayKit/ASTableView.h, AsyncDisplayKit/ASTextNode.h, AsyncDisplayKit/ASViewController.h, AsyncDisplayKit/Details/ASWeakSet.h, AsyncDisplayKit/Layout/ASAbsoluteLayoutSpec.h, AsyncDisplayKit/Layout/ASBackgroundLayoutSpec.h, AsyncDisplayKit/Layout/ASCenterLayoutSpec.h, AsyncDisplayKit/Layout/ASDimension.h, AsyncDisplayKit/Layout/ASInsetLayoutSpec.h, AsyncDisplayKit/Layout/ASLayout.h, AsyncDisplayKit/Layout/ASLayoutSpec.h, AsyncDisplayKit/Layout/ASOverlayLayoutSpec.h, AsyncDisplayKit/Layout/ASRatioLayoutSpec.h, AsyncDisplayKit/Layout/ASRelativeLayoutSpec.h, AsyncDisplayKit/Layout/ASStackLayoutSpec.h, AsyncDisplayKit/Private/ASMultidimensionalArrayUtils.h, AsyncDisplayKit/Private/ASMultidimensionalArrayUtils.mm, AsyncDisplayKit/Private/ASWeakMap.h, AsyncDisplayKit/UIImage+ASConvenience.h, Base/ASBaseDefines.h
This attribute triggers compiler warnings/errors (in ASDK it's errors) when calling a function or method and not using its result.
This diff also makes `scrollableDirections` and `scrollDirection` properties for a slightly cleaner Swift import. I'm willing to revert this if someone thinks it's bad.
=> [Umbrella] Add warn_unused_result Attribute to Public Headers

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Layout/ASLayoutSpec.mm
To not necessary allocate `ASLayoutElementStyle` objects let's initialize them lazily.
=> [Layout] Lazy initialize ASLayoutElementStyle in ASDisplayNode and ASLayoutSpec

AsyncDisplayKit/ASCollectionView.mm
Tragically, this is failing some of our rotation unit tests so we need to revert it until we adjust the tests or adjust the implementation. #2375
=> Revert "Scrollable direction is invalid until a relayout. (#2375)"

AsyncDisplayKit/ASTextNode.mm, AsyncDisplayKit/TextKit/ASTextKitAttributes.h, AsyncDisplayKit/TextKit/ASTextKitContext.h, AsyncDisplayKit/TextKit/ASTextKitContext.mm, AsyncDisplayKit/TextKit/ASTextKitRenderer.h, AsyncDisplayKit/TextKit/ASTextKitRenderer.mm
In 6.11 we introduced a text node renderer cache, and removed the `renderer` ivar from text node. Pinterest started getting a lot of text node related crashes.
In 6.12 we disabled the cache – not a revert, just removed the cache itself – and we still get the same crashes, maybe even with higher frequency. In addition, this means creating a lot more renderers.
This diff is a clean revert back to the original renderer-ivar-invalidation behavior. We can fix forward from here.
=> [ASTextNode] Go Back to Having Renderer as Ivar

AsyncDisplayKit/ASNetworkImageNode.mm, AsyncDisplayKit/Layout/ASAbsoluteLayoutSpec.mm, AsyncDisplayKit/Layout/ASDimension.h, AsyncDisplayKit/Layout/ASRatioLayoutSpec.mm, AsyncDisplayKit/Layout/ASRelativeLayoutSpec.mm
We are catching the behavior if a developer set an URL and asks for the size of the node but the image was not loaded yet.
This is not the right behavior in my opinion, but we should add it for the transition time. That's also the reason we only added it to `ASNetworkImageNode` as it's the most common case.
We also will flag that and in the future we should think about removing that check.
=> [Layout] Return CGSizeZero in case a ASNetworkImageNode is asked for the size and the image did not load yet

AsyncDisplayKit/ASCellNode.mm, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Private/ASInternalHelpers.m
Profiling showed this area as the most expensive part of ASRangeController propogation of .interfaceState, when scrolling an ASTableView.
This is very much on the critical path for sustained 60FPS in these views.
Before **This is filtered to only the method in question**, meaning a total of 1.4% impact on main with a single moderate-speed swipe.  It is also triggered in a different runloop stage offscreen:
After *not directly comparable* but shows the absence of the method:
=> [ASCellNode] Add subclass method cache; skip visibility rect calculations in the common case.

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/ASNetworkImageNode.mm, AsyncDisplayKitTests/ASNetworkImageNodeTests.m
I found the old logic hard to reason about, and I had no confidence that it behaved ideally. In fact, specifically when the download identifier changed the old download's progress block was not unbound which could have led to drawing the wrong image.
In practice that rarely matters, but this adds our first `ASNetworkImageNode` tests which we desperately need, fixes that issue, and makes the progress image binding logic much much more reliable.
Ready for review @maicki @appleguy
=> [ASNetworkImageNode] Test and Improve the Progress Block Handling

AsyncDisplayKit/ASCollectionView.mm
Current layout inspector property is declared weak in the public header but the ivar is not weak in ASCollectionView. This can cause retain cycles.
Adresses: #2400
=> [ASCollectionView] Layout inspector instance variable should be weak

AsyncDisplayKitTests/ASNetworkImageNodeTests.m
This test is designed to ensure that network image nodes set and clear their progress blocks when the node becomes visible/invisible. This avoids extra progressive image renders.
Previously, the test had a race condition where the download might not have started (it starts asynchronously) before the node becomes visible and we verify that the progress image block is set.
Now the test waits for the download to start before making the node visible/invisible.
=> [ASNetworkImageNode] Make Test More Stable

AsyncDisplayKit/Layout/ASLayout.mm
This shows up in benchmarking profiles for layout-bound workloads.
@maicki @Adlai-Holler @garrettmoon
=> [ASLayout - Performance] Avoid weak ivar access & method call to check layoutElementType.

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Layout/ASAbsoluteLayoutSpec.mm, AsyncDisplayKit/Layout/ASBackgroundLayoutSpec.mm, AsyncDisplayKit/Layout/ASInsetLayoutSpec.mm, AsyncDisplayKit/Layout/ASLayout.h, AsyncDisplayKit/Layout/ASLayout.mm, AsyncDisplayKit/Layout/ASLayoutPrivate.h, AsyncDisplayKit/Layout/ASLayoutSpec.mm, AsyncDisplayKit/Layout/ASOverlayLayoutSpec.mm, AsyncDisplayKit/Layout/ASRatioLayoutSpec.mm, AsyncDisplayKit/Layout/ASRelativeLayoutSpec.mm, AsyncDisplayKit/Private/ASStackBaselinePositionedLayout.mm, AsyncDisplayKit/Private/ASStackPositionedLayout.mm
Add a private `ASLayout` header to let us move the `position` to readonly in the public API. `ASLayout` should be an immutable object and exposing properties as readwrite defeats this.
Also integrates: #2398
=> [ASLayout] Improve ASLayout

AsyncDisplayKit/ASRunLoopQueue.mm
Although this didn't occur _currently_, the code was incorrect and needs to be fixed.
=> [ASDeallocQueue] Fix teardown of dealloc thread.

AsyncDisplayKit/Layout/ASRatioLayoutSpec.mm
The child constrained size should be in the constrained size given the ratio spec.
=> [ASRatioLayoutSpec] Final size should always be in constrainedSize in ratio spec

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Layout/ASLayoutSpec.mm, AsyncDisplayKit/Private/ASLayoutSpecPrivate.h, AsyncDisplayKitTests/ASDisplayNodeTests.m
Currently we have a major issue where, if the user returns a layout spec tree that contains duplicated elements (nodes or specs) there will be a hard crash when the layout gets applied.
This diff adds an assertion that the tree contains no duplicated elements. In production, we will use an empty `ASLayoutSpec` in this case.
This is an extremely performance-sensitive method. It avoids allocating a result set unless needed, and it avoids membership checking in favor of checking `count`.
I considered using `NSHashTable` with `NSHashTableObjectPointerPersonality` to avoid the retains and hashing etc but avoided it because of [this table](https://www.objc.io/issues/7-foundation/collections/#performance-characteristics-of-nshashtable). It's possible that the table they used was configured …
=> [Layout] Check Layout Spec Tree for Duplicated Elements

AsyncDisplayKit/ASTableView.mm
Fixes ASDK v2.0 ASTableNode async delegate methods `tableNode:willDisplayRowWithNode:` and `tableNode:willDisplayRowWithNode:` not triggering due to their asyncDelegateFlags not being set.
=> [ASTableNode] Add missing ASTableNode delegate flag setup

AsyncDisplayKit/ASCollectionNode.h, AsyncDisplayKit/ASCollectionNode.mm
Can't believe I forgot this.
We had previously planned to update the name of this method, but since this particular change is urgent for Pinterest, and since the ideal name might change in light of the recent behavior change of `nodeForRowAtIndexPath:`, this diff does not do that.
=> [ASCollectionNode] Add waitUntilAllUpdatesAreCommitted Method

AsyncDisplayKit/Layout/ASLayoutElement.mm
- Move `ASLayoutElement` properties to use std::atomic
- Remove some `objc_msgSend` and locking overhead for sizing properties
@appleguy Let's give it a try and let me know
=> [ASLayoutElementStyle] ASLayoutElementStyle improvements

AsyncDisplayKit/Details/ASDataController.mm, AsyncDisplayKit/Details/ASRangeController.mm, Base/ASLog.h
=> [Operations] Fix Xcode 7 Build Failing Due to Missing Signposts Header

AsyncDisplayKit/Layout/ASAbsoluteLayoutSpec.h, AsyncDisplayKit/Layout/ASAbsoluteLayoutSpec.mm
For the transition phase let's add `ASStaticLayoutSpec` back without deprecation warnings.
=> [ASLayoutSpec] Add ASStaticLayoutSpec back without deprecation warning

AsyncDisplayKit/Layout/ASLayoutElement.h, AsyncDisplayKit/Layout/ASLayoutElement.mm, AsyncDisplayKitTests/ASLayoutElementStyleTests.m
After getting some feedback it seems like the `preferredSize` is read more often than expected. The goal of not adding it as a getter in the first place was to prevent an unexpected behavior if the `width` and `height` of the style is not of dimension points and to give the responsibility to the developer to be sure that the right dimensions are set to the `width` and `height`. Furthermore it should give the developers the opportunity to think what the `width` and `height` `ASDimension` actually means ...
... however this PR add's a getter for `preferredSize` to `ASLayoutElementStyle` and throws an assertion, if `width` or `height` of the `ASLayoutElementStyle` are not of unit points.
=> [ASLayoutElementStyle] Add preferredSize as getter to ASLayoutElementStyle

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/ASImageNode.mm, AsyncDisplayKit/ASRunLoopQueue.mm, AsyncDisplayKit/Details/Transactions/_ASAsyncTransaction.mm, AsyncDisplayKit/Private/ASDisplayNode+AsyncDisplay.mm
I've confirmed that the optimizer does not remove these calls automatically, even though they're unnecessary.
Under ARC, block copying is done automatically when required. So calling `-copy` is purely wasted resources.
http://clang.llvm.org/docs/AutomaticReferenceCounting.html#id50
> With the exception of retains done as part of initializing a `__strong` parameter variable or reading a `__weak` variable, whenever these semantics call for retaining a value of block-pointer type, it has the effect of a `Block_copy`. The optimizer may remove such copies when it sees that the result is used only as an argument to a call.
Details at http://stackoverflow.com/a/23352604
I was also able to make the display completion block static, since it's pure. Not huge, but hey it's a freebie!
=> Remove Explicit Calls to -copy on Blocks

AsyncDisplayKit/Details/ASCollectionViewFlowLayoutInspector.m
The layout inspector system is an eyesore, but it is what it is. The base layout inspector class already called this, but flow layout inspector overrides the method and was not updated. Resolves #2443 .
=> Make Flow Layout Inspector Call the New Constrained Size Method

AsyncDisplayKit.podspec
Beta 4 added a PINCache subspec which was required for ASDK. However,
Beta 5 reverted this in an attempt to fix automatically updated versions
of ASDK. So this patch sets the specific version to beta 5 until we're
ready to launch.
=> Fix to beta 5 of PINRemoteImage

Podfile
The latest version of ios-snapshot-test-case (v2.1.4) brought back the "old" deployment target
`s.ios.deployment_target  = '7.0'`.
=> [Project Config] switch ios-snapshot-test-case back to main repo

AsyncDisplayKit/ASCollectionNode.h, AsyncDisplayKit/ASCollectionNode.mm, AsyncDisplayKit/ASTableNode.h, AsyncDisplayKit/ASTableNode.mm, AsyncDisplayKitTests/ASCollectionViewTests.mm
refs #2450
**ASCollectionNode:**
- [ASCollectionNode selectItemAtIndexPath:animated:scrollPosition:]
- [ASCollectionNode deselectItemAtIndexPath:animated:]
Unsure if you think the following are needed, but I added them just in case.
- BOOL allowsSelection -> collectionView.allowsSelection
- BOOL allowsMultipleSelection -> collectionView.allowsMultipleSelection
**ASTableNode:**
- [ASTableNode selectRowAtIndexPath:animated:scrollPosition:]
- -[ASTableNode deselectRowAtIndexPath:animated:]
Unsure if you think the following are needed, but I added them just in case.
- BOOL allowsSelection -> collectionView.allowsSelection
- BOOL allowsSelectionDuringEditing -> collectionView.allowsSelectionDuringEditing
- BOOL allowsMultipleSelection -> collectionView.allowsMultipleSelection
- BOOL …
=> Added selection API to ASTableNode and ASCollectionNode

AsyncDisplayKit/Layout/ASLayoutSpec.h, AsyncDisplayKit/Layout/ASLayoutSpec.mm
Currently there is no good way to return multiple children from `layoutSpecThatFits:`. The workaround is to use an `ASAbsoluteLayoutSpec` and set the sizing option to `ASAbsoluteLayoutSpecSizingSizeToFit`.
Let's add the capability to the wrapper layout spec to have multiple children so multiple children can be returned in `layoutSpecThatFits:` without using `ASAbsoluteLayoutSpec` as hack around it.
This almost completely removes the case for using an `ASAbsoluteLayoutSpec ` with `ASAbsoluteLayoutSpecSizingSizeToFit` and we have a default way to use or return multiple children within a layout spec.
=> [ASWrapperLayoutSpec] Add support  for multiple children

AsyncDisplayKit/Details/ASCollectionViewLayoutController.mm
I'm not sure if there's a different way to optimize this instead.
=> [ASCollectionView] Caching scrollable directions is not safe

AsyncDisplayKit/ASCollectionNode.mm, AsyncDisplayKit/ASTableNode.mm, AsyncDisplayKitTests/ASCollectionViewTests.mm
refs #2457
- Call reloadData if necessary when accessing specific methods.
- Added test case.
NB: Since the nodes aren't visible at this time, you won't be able to get all the correct information from the node, for instance:
```
NSIndexPath *indexPath = [NSIndexPath indexPathForItem:0 inSection:0];
ASCellNode *node = [cn nodeForItemAtIndexPath:indexPath];
```
In this case `node.indexPath`will actually be `nil` even if the node itself is correct. Take a look at #2468.
=> Table & Collection Node Should Enqueue Initial Reload If Needed

AsyncDisplayKit/ASCollectionNode.h, AsyncDisplayKit/ASCollectionNode.mm, AsyncDisplayKit/ASCollectionView.h, AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASPagerNode.m, AsyncDisplayKit/ASTableNode.h, AsyncDisplayKit/ASTableNode.mm, AsyncDisplayKit/ASTableView.h, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/ASTableViewInternal.h, AsyncDisplayKit/Details/ASCollectionInternal.h
Resolves #2461 
- Deprecates `ASTableView` and `ASCollectionView` scrollToItem methods. Removes override.
- ⚠️ This changes the methods to take view index paths instead of node index paths. This is unlikely to affect current usage but we should do an audit.
- Modifies conversion methods to handle section index paths.
=> Add scrollToItem: Method to Node, Handle Section Index Paths

AsyncDisplayKit/Layout/ASLayoutElement.mm, AsyncDisplayKitTests/ASLayoutElementStyleTests.m
If width and height of an `ASLayoutElement` is not of unit type `ASDimensionUnitPoints` we throw an assertion for accessing the `style.preferredSize`.
Instead of throwing an assertion if the unit type is not `ASDimensionUnitPoints` we will throw an assertion if the unit type is `ASDimensionUnitFraction`. If the unit type is `ASDimensionUnitPoints` or `ASDimensionUnitAuto` we will use the value of the `width` and `height` dimension to create the size to return.
Addresses: #2483
=> [Layout] Only throw if width or height are fractions in preferredSize getter

AsyncDisplayKit/TextKit/ASTextKitRenderer.mm
When using the new fast path in text node under iOS 7, the text may be truncated on the second-to-last line in some cases.
Adding a small fudge factor to the drawing height (in iOS 7) works around the issue.
=> Workaround iOS 7 Early-Truncation Bug

AsyncDisplayKit/Private/ASEnvironmentInternal.mm
I ran across this while debugging. I don't think this is used currently, but it may be in the future.
=> [ASEnvironment] add descender to ASEnvironmentMergeObjectAndState()

examples/ASDKgram/Sample/CommentsNode.m, examples/ASDKgram/Sample/PhotoCellNode.m
The goal of this change is to have an extended example that show's what the Layout API is able to. 
The style of composing layout elements in `layoutSpecThatFits:` is most of the time matter of taste so this change can be controversial, but as said it's more for demonstrating what's possible now.
=> [Example] Rewrite `layoutSpecThatFits:` in ASDKgram

AsyncDisplayKit/Details/ASDataController.mm, AsyncDisplayKitTests/ASTableViewTests.m, Podfile
Resolves #2487.
- In `reloadData`, skip deleting the rows. Deleting the sections is plenty.
- In `reloadData`, batch the deleteSections and insertSections calls together for efficiency.
- When deleting/reloading sections, skip deleting the rows. We know the rows are gone.
I've tested this with Pinterest and it's working very well!
=> Reduce Traffic to Table/Collection View When Updating

AsyncDisplayKit/Layout/ASDimension.h
It's a programming error to set an infinite height or width with a point value. If we assert here the programmer is more likely to be able to easily address the issue.
=> [ASDimension] We need to ensure point dimensions are valid for sizing.

.gitignore, examples/ASLayoutSpecPlayground-Swift/Podfile, examples/ASLayoutSpecPlayground-Swift/Sample.xcodeproj/project.pbxproj, examples/ASLayoutSpecPlayground-Swift/Sample.xcodeproj/xcshareddata/xcschemes/Sample.xcscheme, examples/ASLayoutSpecPlayground-Swift/Sample/Info.plist, examples/ASLayoutSpecPlayground-Swift/Sample/Sample.h, examples/ASLayoutSpecPlayground-Swift/Sample/Sample.playground/Pages/HorizontalStackWithSpacer.xcplaygroundpage/Contents.swift, examples/ASLayoutSpecPlayground-Swift/Sample/Sample.playground/Pages/Index.xcplaygroundpage/Contents.swift, examples/ASLayoutSpecPlayground-Swift/Sample/Sample.playground/Pages/PhotoWithInsetTextOverlay.xcplaygroundpage/Contents.swift, examples/ASLayoutSpecPlayground-Swift/Sample/Sample.playground/Pages/PhotoWithOutsetIconOverlay.xcplaygroundpage/Contents.swift, examples/ASLayoutSpecPlayground-Swift/Sample/Sample.playground/Pages/StackLayout.xcplaygroundpage/Contents.swift, examples/ASLayoutSpecPlayground-Swift/Sample/Sample.playground/Sources/ASPlayground.swift, examples/ASLayoutSpecPlayground-Swift/Sample/Sample.playground/Sources/HorizontalStackWithSpacer.swift, examples/ASLayoutSpecPlayground-Swift/Sample/Sample.playground/Sources/PhotoWithInsetTextOverlay.swift, examples/ASLayoutSpecPlayground-Swift/Sample/Sample.playground/Sources/PhotoWithOutsetIconOverlay.swift, examples/ASLayoutSpecPlayground-Swift/Sample/Sample.playground/Sources/StackLayout.swift, examples/ASLayoutSpecPlayground-Swift/Sample/Sample.playground/Sources/Utilities.swift, examples/ASLayoutSpecPlayground-Swift/Sample/Sample.playground/contents.xcplayground
Added Swift playground with the following example layouts:
- StackLayout (Simplified stack layout example with an easy way to demonstrate the effects of flexShrink)
- PhotoWithInsetTextOverlay (Same as the online docs + ObjectiveC playground)
- PhotoWithOutsetIconOverlay (Same as the online docs + ObjectiveC playground)
- HorizontalStackWithSpacer (Same as the online docs + ObjectiveC playground)
=> [Examples] Playground swift

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/ASImageNode.mm, AsyncDisplayKit/ASNetworkImageNode.mm, AsyncDisplayKit/Layout/ASLayout.mm, AsyncDisplayKitTests/ASDisplayNodeImplicitHierarchyTests.m, AsyncDisplayKitTests/ASDisplayNodeTests.m
This change will return constrainedSize from ASDisplayNode in calculateSizeThatFits: instead of CGSizeZero. The reason for that is that the constrainedSize usually is within the range of the style.preferredSize. The old behavior did not consider that.
* Change check for valid size in `ASLayout` to check for sizing instead of for layout
* Removes the invalid constrainedSize check within ASNetworkImageNode.
* Fix tests: As ASDisplayNode does not return CGSizeZero anymore we have to give the display nodes we use in tests and are involving a stack spec an intrinsic content size.
Replaces: #2503 and #2389
=> [ASDisplayNode] Proper handling of `constrainedSize`

AsyncDisplayKit/ASDisplayNode+Deprecated.h, AsyncDisplayKit/ASDisplayNode.h
Solves the following warnings (posted on Slack by emeskhi):
```
ASDisplayNode+Deprecated.h:15:27: Duplicate definition of category 'Deprecated' on interface 'ASDisplayNode'
```
```
ASDisplayNode+Deprecated.h:55:13: Pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)
```
=> [Swift] Addressed two warnings when building for swift.

AsyncDisplayKit/ASCollectionNode.h, AsyncDisplayKit/ASCollectionNode.mm, AsyncDisplayKit/ASCollectionView.h, AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableNode.h, AsyncDisplayKit/ASTableNode.mm, AsyncDisplayKit/ASTableView.h, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/ASTableViewInternal.h, AsyncDisplayKit/Details/ASCollectionInternal.h
refs #2485 
**[ASCollectionNode]** added:
- `-[ASCollectionNode indexPathForItemAtPoint:]`
- `-[ASCollectionNode cellForItemAtIndexPath:]`
**[ASCollectionView]** deprecated:
- `-[ASCollectionView(Deprecated) selectItemAtIndexPath:animated:scrollPosition:]`
**[ASTableNode]** added:
- `-[ASTableNode rectForRowAtIndexPath:]`
- `-[ASTableNode cellForRowAtIndexPath:]`
- `-[ASTableNode indexPathForSelectedRow]`
- `-[ASTableNode indexPathForRowAtPoint:]`
- `-[ASTableNode indexPathsForRowsInRect:]`
- `-[ASTableNode indexPathsForVisibleRows]`
**[ASTableView]** deprecated:
- `-[ASTableView(Deprecated) selectRowAtIndexPath:animated:scrollPosition:]`
=> Deprecate indexPath-based Methods on ASTableView/ASCollectionView

AsyncDisplayKit/ASTableNode.mm, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/ASTableViewInternal.h, AsyncDisplayKitTests/ASTableViewTests.m, AsyncDisplayKitTests/ASXCTExtensions.h
This is a diff that I developed with @chrisdanford – it resolves #2501.
- Only call `beginUpdates/endUpdates` if the node's height changed as a result of remeasuring against content view.
- Subtract section index frame from bounds-width when determining the row width. Otherwise, when the cell comes on screen, it's going to have to synchronously remeasure.
- Fix an unrelated issue where if you call `ASTableNode.numberOfSections` before the first layout, it'll reload data with `_nodesConstrainedWidth = 0` and all the rows will get measured against 0 which is less than ideal.
@chrisdanford Would you be willing to download this as a patch and try it against Pinterest to make sure that I haven't regressed anything since the last profiling?
=> Improve Table Performance, Especially When Using Section Index Bar

AsyncDisplayKit/Layout/ASStackLayoutSpec.h, AsyncDisplayKit/Layout/ASStackLayoutSpec.mm, AsyncDisplayKit/Private/ASStackBaselinePositionedLayout.h, AsyncDisplayKit/Private/ASStackBaselinePositionedLayout.mm, AsyncDisplayKit/Private/ASStackPositionedLayout.h, AsyncDisplayKit/Private/ASStackPositionedLayout.mm, AsyncDisplayKit/Private/ASStackUnpositionedLayout.h, AsyncDisplayKit/Private/ASStackUnpositionedLayout.mm
Moves layout calculations of the stack layout spec in the C++ layer of the layout spec implementation. Previously we used references of `ASLayout` to as for specific properties like `layoutElement` and `style` or `size` on the `ASLlayoutElement`.
Now we create a C++ wrapper around the `ASLayout` before the actual layout calculations happening and use this to access the common components to reduce the overhead of Objc message calling.
- Add `ASStackLayoutSpecItem ` and don't separate between unpositioned and positioned items anymore. This didn't work properly previously in the first place as the `ASLayout` that was included was basically shared, so on ASDK side having them was basically nonsense. It would have make sense if we would have create specific `ASLayout` objects for unpositioned …
=> [ASStackLayoutSpec] Performance improvements

AsyncDisplayKit/ASTextNode.mm, AsyncDisplayKit/TextKit/ASTextKitRenderer.h, AsyncDisplayKit/TextKit/ASTextKitRenderer.mm
Resolves #2515 
Instead of fixing the immediate issue, I decided to make a more substantial change and remove `setConstrainedSize:` from the renderer.
The renderer is meant to be one-shot, and this bug would never have cropped up if we had stuck to that. Changing the constrained size basically gutted the entire renderer anyway, so this change hardly matters.
I've tested this with Pinterest and it resolves the issue nicely.
=> Invalidate TextNode Renderer Instead of Changing constrainedSize

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/ASDisplayNode+Deprecated.h, AsyncDisplayKit/ASDisplayNode.h, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/AsyncDisplayKit.h, AsyncDisplayKit/Layout/ASLayoutElement.h, AsyncDisplayKit/Layout/ASLayoutElementPrivate.h, AsyncDisplayKit/Layout/ASLayoutSpec.h, AsyncDisplayKit/Layout/ASLayoutSpec.mm, AsyncDisplayKitTests/ASDisplayNodeTests.m
- Add deprecations for node / layoutSpec style properties
- Implement missing methods on ASDisplay from deprecation header
- Cleanup all of the deprecation categories
=> Improve deprecation situation for 2.0

AsyncDisplayKit/ASDisplayNode.mm, examples/Swift/Sample/TailLoadingCellNode.swift, examples/Swift/Sample/ViewController.swift
While going through our Swift example I discovered some strange behavior if a UIActivityIndicatorView is wrapped in a node via a view block. If the node is get a specific size via `style.preferredSize` it will just show up as a black box.
After looking into it a bit more it seems it has the same problems as an `UIImageView` and it’s not safe to clear the contents of the layer of the view and recreate it by calling `setNeedsDisplay`.
@appleguy @garrettmoon  @Adlai-Holler  Ready for review
=> [ASDisplayNode Fix using UIActivityIndicatorView provided via view block

AsyncDisplayKit/ASDisplayNode.mm
Subnode hierarchy management within `ASDisplayNode` uses different paths for adding, modifying the subnode hierarchy. While looking into that it was harder to understand what is actually going on in  each phase.
Let's consolidate and cleanup the situation and have one central place to add and modify the subnode hierarchy.
As it's also a hot path let's remove the overhead of creating a block while dispatching adding / removing views / layers as they should run on the main thread anyway and we have them so there are not problems in production.
@Adlai-Holler @appleguy @nguyenhuy Ready for review
=> [ASDisplayNode] Consolidate and cleanup subnode hierarchy management

AsyncDisplayKit/Private/ASControlTargetAction.m
This could have been… bad. It's amazing that Xcode doesn't get angry about this :(
=> [ASControlNode] Implementation needs to match decleration.

AsyncDisplayKit/ASTextNode.mm, AsyncDisplayKit/TextKit/ASTextKitRenderer.h, AsyncDisplayKit/TextKit/ASTextKitRenderer.mm
This is an attempt to fix #2504.
@Adlai-Holler what do you think?
@garrettmoon I tried setting the context to be `self.stringDrawingContext` but that didn't work – it only worked as expected when the context is `nil`.
=> [ASTextNode] Ensure that isTruncated computes the correct value when sizing fast-path is used.

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/ASCollectionNode.mm, AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASDisplayNode+Beta.h, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/ASTableNode.mm, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/ASTableViewInternal.h, AsyncDisplayKit/Details/ASChangeSetDataController.mm, AsyncDisplayKit/Details/ASCollectionDataController.h, AsyncDisplayKit/Details/ASCollectionDataController.mm, AsyncDisplayKit/Details/ASCollectionInternal.h, AsyncDisplayKit/Details/ASDataController.h, AsyncDisplayKit/Details/ASDataController.mm, AsyncDisplayKit/Details/ASObjectDescriptionHelpers.h, AsyncDisplayKit/Details/ASObjectDescriptionHelpers.m, AsyncDisplayKit/Private/ASDisplayNodeInternal.h, AsyncDisplayKit/Private/ASEventLog.h, AsyncDisplayKit/Private/ASEventLog.mm, AsyncDisplayKit/Private/_ASHierarchyChangeSet.h, AsyncDisplayKit/Private/_ASHierarchyChangeSet.mm, AsyncDisplayKitTests/ASTableViewTests.m
#2486 
- Introduce thread-safe ASEventLog
- ASCollectionNode and ASTableNode share their event log with their ASDataController. The controller uses it to log change set submitting and finishing events.
- ASCollectionNode and ASTableNode print their data source and delegate in their debug description.
*Sample output:*
```
submitting: <_ASHierarchyChangeSet: 0x60800015c040; reloadItemChanges = { @0 : { 3 7 9-10 13 16-17 } }; insertedItemChanges = { @0 : { 3 7 9-10 13 16-17 } }; deletedItemChanges = { @0 : { 3 7 9-10 13 16-17 } }>
finished: <_ASHierarchyChangeSet: 0x60800015c040>
submitting: <_ASHierarchyChangeSet: 0x600000340fd0; reloadSectionChanges = { 3-7 }; insertedSections = { 3-7 }; deletedSections = { 3-7 }>
finished: <_ASHierarchyChangeSet: 0x600000340fd0>
```
(These change sets …
=> Beter table/collection update history

AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/Details/ASCollectionViewFlowLayoutInspector.h, AsyncDisplayKit/Details/ASCollectionViewFlowLayoutInspector.m, examples/CustomCollectionView/Sample/MosaicCollectionViewLayout.m
Thanks to @Baevra for catching this (#2540) and @Adlai-Holler for debugging this with me!
**Issue:**
Rotation from Portrait to Landscape in CustomCollectionView example does not trigger the layout inspector's `-constrainedSizeForNodeAtIndexPath` method. 
**Explanation:**
The collectionView's `scrollableDirections` was getting set to all directions because the bounds size changed before the content size changed. Going from portrait to landscape, the bounds size changed from a smaller width to a larger width, triggering a relayout of all nodes. Going from landscape to portrait, the bounds size changed from a larger width to a smaller width, causing the data controller to think that it was scrollable in the horizontal direction as well. 
Since laying out all nodes is expensive, we only do …
=> [ASCollectionViewLayoutInspecting] make -scrollableDirections  required

AsyncDisplayKit/ASPagerNode.m, AsyncDisplayKitTests/ASViewControllerTests.m
We disabled an ASViewController test because it was failing after #2561 landed.
It turns out the cause of the failure is that the pager node tests set the application's key window and when the ASViewController test updated the key window, the previous one would be released and torn down. The pager node would have its data source set to `nil`, and would throw an exception because `nil` doesn't implement either `nodeBlockAtIndex:` or `nodeAtIndex:`.
This diff updates the flags handling for `ASPagerNode` pretty holistically, handling the `nil` case, and restores the affected view controller test.
=> Fix Issue in ASPagerNode Flags Handling, Restore Disabled Test

AsyncDisplayKit/Private/_ASHierarchyChangeSet.mm
This fixes an issue where the compiler will error due to unused variable when assertions are disabled. Will merge when CI passes.
=> Only Create Assert-Only Variable if Assertions Enabled

AsyncDisplayKit/ASDisplayNode+Beta.h, AsyncDisplayKit/Details/ASDataController.h, AsyncDisplayKit/Details/ASEventLog.h, AsyncDisplayKit/Details/ASTraceEvent.h, AsyncDisplayKit/Details/ASTraceEvent.m, Base/ASBaseDefines.h
While #2570 fixed the memory consumption caused by backtrace recording, it added significant CPU cost for debug builds.
This diff adds a new macro `AS_SAVE_EVENT_BACKTRACES`, which defaults to `0`. If the user defines it otherwise, then we use the pre-2570 behavior.
=> Disable ASTraceEvent Backtraces by Default

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Layout/ASLayout.mm, AsyncDisplayKitTests/ASDisplayNodeImplicitHierarchyTests.m, AsyncDisplayKitTests/ASDisplayNodeTests.m
Resolves #2549 
This diff changes the flattening traversal from breadth-first to depth-first, so that the resulting node array will have an ordering that matches the user's expectations, and adds some unit tests which failed before the change.
=> Improve Automatic Subnode Management Node Ordering

AsyncDisplayKit/Details/ASDataController.mm, AsyncDisplayKitTests/ASTableViewTests.m
Issuing updates to `UICollectionView` is one of the most expensive operations we perform.
This diff combines the section-delete, section-insert, and first-batch-of-rows-insert operations during initial data load & reload data. This will fix flashing in cases where the first batch of items covers the visible area, and it will reduce the total number of UIKit update operations we perform.
=> Reduce Flashing & Optimize ASTableNode/ASCollectionNode Data Loading

AsyncDisplayKit/Details/ASPINRemoteImageDownloader.h, AsyncDisplayKit/Details/ASPINRemoteImageDownloader.m
This will be the configuration used by the PINRemoteImageManager instance contained by ASPINRemoteImageDownloader. This will allow callers to supply their own custom
logic whether that is background downloads, custom http headers, cookie
storage, etc.
=> Add method to specify the default NSURLSessionConfiguration

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/AsyncDisplayKit.h
Carthage on master is complaining that three files are missing from the umbrella header.
I marked ASTraceEvent and ASLayoutElementInspectorNode as Project since they shouldn't be public, and added ASObjectDescriptionHelpers to the umbrella header because although it's undocumented, it sure is handy so we'll share the love.
Going to merge when CI passes.
=> Fix the Carthage Build

AsyncDisplayKit/Details/ASCollectionViewLayoutController.mm
Removed assert which prevents decoration views from being displayed in `ASCollectionView` as discussed in issue https://github.com/facebook/AsyncDisplayKit/issues/1829. I confirmed that decoration views are displayed properly in our project using ASDK when this assert is disabled.
=> [ASCollectionView] Allow Decoration Views

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Details/ASEventLog.h, AsyncDisplayKit/Details/ASEventLog.mm, AsyncDisplayKit/Details/ASTraceEvent.h, AsyncDisplayKit/Details/ASTraceEvent.m, AsyncDisplayKitTests/ASTableViewTests.m
This addresses some issues with our event logging.
Performance improvements:
- Go back to event logging only in debug (!!!)
- Store event log contents in a shared NSCache so that the memory consumption is limited.
- Store the strings for unnamed threads in the thread dictionary to save resources.
- Only form the object description 1 time for the whole event log, rather than for each event.
```
po node.eventLog
<ASEventLog: 0x7fdae0d10b10>
po [node.eventLog eventLog]
<__NSArrayM 0x7fdae0c17690>(
<<ASEventLog: 0x7fdae0d10b10> (Main) t=  9.441: calculatedSize: {50, 50}>,
<<ASEventLog: 0x7fdae0d10b10> (Main) t=  9.442: didLoad>,
<<ASEventLog: 0x7fdae0d10b10> (Main) t=  9.445: setHierarchyState: oldState = { Normal }, newState = { Rasterized }>,
<<ASEventLog: 0x7fdae0d10b10> (Main) t=  9.448: …
```
=> [ASTraceEvent, Debugging] Greatly Improve Event Logging.

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKitTests/ASDisplayNodeLayoutTests.mm
In this case, the user hasn't specified enough about the layout of a node.  We default to
0, 0 - but ideally the case should not occur at all.  So it's important to help developers
detect these cases and fix them quickly.
An assertion causes developers several problems:
- They can't see important information unless an exception breakpoint is manually added.
- They can't see their layout onscreen and so visually understanding the problem is impossible.
- They can't proceed with testing to trigger other faults in the layout and are blocked fixing one at a time.
A log fixes every one of those problems:
- They can set a breakpoint on the log line very easily if desired.
- They can see their layout display and recognize the 0,0 node even more quickly than the log text information.
- They can …
=> [ASDisplayNode] Convert assertion to log so developer can see layout issues onscreen.

AsyncDisplayKit/ASVideoNode.mm, examples/Videos/Sample/ViewController.m
Prevents flashing the background color in between the placeholder and the first frame of the video.
For more info refer to issue: https://github.com/facebook/AsyncDisplayKit/issues/2329
=> [ASVideoNode] Prevent premature placeholder image clear when setting the video asset

AsyncDisplayKit/ASDisplayNode.mm
Using CGSizeZero for the sizeRange can cause negative values in client layout code. Most likely called transitionLayout: without providing a size, before first layout pass.
=> [ASDisplayNode] Re-add layout transition check for invalid constrained size

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Details/ASRangeController.mm
`CFAbsoluteTime` is the time as displayed to the user, which can be changed e.g. as the device syncs with the server. `CACurrentMediaTime` is the time since machine booted, which is what we should use for these kinds of internal purposes. See http://nshipster.com/benchmarking/ for info. It might also be faster but I'm not sure.
=> Use CACurrentMediaTime Instead of CFAbsoluteTime

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/ASDisplayNodeExtras.h, AsyncDisplayKit/ASDisplayNodeExtras.mm
If you want to manually deallocate something on the main thread, you can now call `ASPerformMainThreadDeallocation`. It might be worth publicizing `ASPerfomBackgroundDeallocation` but this is very urgent so I'm going to minimize the change and land after CI passes.
=> Make a Public Function for Main Thread Deallocation

AsyncDisplayKit/Details/ASPINRemoteImageDownloader.m
Currently setting an NSURLSessionConfiguration through ASPINRemoteImageManager
will crash. 
- PINRemoteImage is not linked with ASDK so it makes it difficult to make changes in this file without adding it manually into the Podfile.  
- Also I noticed the compiler will yell at you for `unrecognized selector` calls if you use the actual class name (`ASPINRemoteImageDownloader`) vs `[self class]`. I expected the build should fail since we should create the build in configurations where PINRemoteImage is available or unavailable.
=> Expose internal singleton method as a class method vs instance method in ASPINRemoteImageDownloader

AsyncDisplayKit/ASCollectionNode.h, AsyncDisplayKit/ASCollectionNode.mm, AsyncDisplayKitTests/ASCollectionViewTests.mm
- Remove `initWithFrame:collectionViewLayout:` and replace with `initWithCollectionViewLayout:`. This is more inline with `ASTableNode` and `ASDisplayNode`, rather than `UIView`.
- Add `initWithCollectionViewLayout:layoutInspector:` for when they have a layout inspector to provide. It is still acceptable to set the layout inspector later.
Note that the layout inspector API is likely to be replaced by a single asynchronous layout object, that serves as both our equivalent to `UICollectionViewLayout` and the layout inspector.
=> [ASCollectionNode] Modify Initialization API

AsyncDisplayKit/Details/ASPINRemoteImageDownloader.m
Tested locally with the Pinterest app. 
The issue that caused this to be revered in the first place was the value for `alternativeRepresentationProvider` was set to the `ASPINRemoteImageDownloader` class instead of an instance. This slipped when converting the singleton method to a class method.
Included in this PR:
- Revert "Revert "Expose internal singleton method as a class method vs instance method.""
- Fix assignment of alternativeRepresentationProvider to be the singleton
instance of ASPINRemoteImageDownloader.
=> Re-add NSURLSessionConfiguration support and fix crashes

AsyncDisplayKit.podspec
Just updating ASDK within Buffer, noticed the podspec wasn't including beta 2 yet.
=> Update AsyncDisplayKit.podspec for 2.0-beta.2

AsyncDisplayKit/ASViewController.mm
Calling `viewController.node.view` or passing in a already loaded view will not automatically trigger a `loadView` on the view controller. This PR should address this issue by either triggering a `loadView` if the node is already loaded or observing the node loaded state and trigger a `loadView` in case the view controller's view is not already loaded
Addresses: #2350
=> [ASViewController] Trigger load view in ASViewController if node did load but not the view of the view controller

AsyncDisplayKit/ASDisplayNode+Subclasses.h, AsyncDisplayKit/Details/_ASDisplayLayer.h
This resolves #2299 and improves the Swift import in general.
=> Add noescape Attribute to isCancelledBlock Parameters

AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/Private/_ASCoreAnimationExtras.h, AsyncDisplayKit/Private/_ASCoreAnimationExtras.mm
Fix strange artifacts in ASTableView are visible when changing the device orientation or other animations are going on while calling endUpdates
Resolves #1361
=> [ASTableView] Not animated for end updates if animation is already going on within ASTableView

AsyncDisplayKit/ASViewController.mm
Syntax highlighting is still broken in Xcode 8 so I sometimes prefer using Xcode 7.3.1. Previously `isViewLoaded` was a method, not a property, and this uses that method explicitly.
=> Use the Method Form for UIViewController.viewLoaded – Maintains Xcode Backwards Compatibility

AsyncDisplayKit/ASDisplayNode.mm
Calling `layoutIfNeeded` before actually starting the layout transition pcoess can cause a measurement pass with the already new layout description to happen. This means instead of animating the nodes in and out as well as the position of nodes, it will just apply the new layout immediately without any animation.
=> [Layout Transition] Layout Transition Fixes

AsyncDisplayKit/ASViewController.mm
This call has been there since the initial implementation of ASViewController, but it's not needed.
=> [ASViewController] Remove Extra recursivelyFetchData Call 

AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/Details/ASRangeController.h, AsyncDisplayKit/Details/ASRangeController.mm, AsyncDisplayKit/Private/ASBatchFetching.h, AsyncDisplayKit/Private/ASBatchFetching.m, AsyncDisplayKitTests/ASBatchFetchingTests.m, AsyncDisplayKitTests/ASCollectionViewTests.mm
- Add a (previously-failing) unit test that when the content starts off not filling the screen, and then a batch fetch is issued that results in the new content filling the screen, we do not start another batch fetch.
- Remove `didCompleteUpdatesInRangeController:`
- This required callback is to inform ASCollectionView/ASTableView that the range controller has updated the ranges of visible nodes.
- Its name is easily confused with `rangeController:didEndUpdatesAnimated:completion:`
- It was previously used to schedule a batch fetch check when the ranges were updated.
- Batch fetching here has two issues:
- It doesn't really make sense. The range controller updating the interface state of nodes has no impact on whether it is appropriate to batch fetch or not.
- It may cause batch fetches …
=> Improve Batch Fetching Call Pattern to Reduce Fetch Calls

AsyncDisplayKit/ASTableView.mm, AsyncDisplayKitTests/ASTableViewTests.m
Resolves #2252 
This is one _very strange_ edge case and huge props to @tomizimobile for providing a reliable repro. I distilled the repro down into a unit test and found the problem.
In `grouped` style with section headers and footers, table views will sometimes return more index paths than necessary from `indexPathsForVisibleRows`. We knew this, but considered the risk acceptable. The risk isn't really acceptable – if we mark a node as `visible` we are relying on the fact that it is hosted in an actual cell, so that if the range controller doesn't mark the node invisible before it is removed (say, the item is deleted from the collection or the collection is deallocated) the code in `ASDisplayNode.didExitHierarchy` will retain the node and clear the visible bit before deallocating.
Added …
=> Fix Edge Cases of Table Cell Nodes Deallocated While Visible

AsyncDisplayKit/ASViewController.h, AsyncDisplayKit/ASViewController.mm
Replaces: #2636
- Remove `layoutThatFit:` call in `viewWillAppear:` and only force a layout pass to execute automatic subnode management
- Deprecate `-[ASViewController nodeConstrainedSize]`
- Use the view’s bounds to layout the node
- ASViewController/ASPagerNode layout bug since version 1.9.81 https://github.com/facebook/AsyncDisplayKit/issues/1949 (fixed)
- ASViewController does not resize when contained in a Container View https://github.com/facebook/AsyncDisplayKit/issues/2085 (fixed)
- Accepts edgesForExtendedLayout without any hacks (fixed without special code) https://github.com/facebook/AsyncDisplayKit/pull/2123
- [ASViewController] Regression causing layout issues when presenting a portrait-only view controller while in landscape (fixed without special code) …
=> [ASViewController] Improve ASViewController view behavior

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASDisplayNode+Beta.h, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/Details/ASChangeSetDataController.mm, AsyncDisplayKit/Details/ASDataController.h, AsyncDisplayKit/Details/ASDataController.mm, AsyncDisplayKit/Private/_ASHierarchyChangeSet.mm, AsyncDisplayKitTests/ASCollectionViewTests.mm, AsyncDisplayKitTests/ASTableViewTests.mm
Resolves #2529 to the best of our ability.
The original hope was to get the data source class into the exception backtrace, but since the symbols are set at compile-time and loaded from the _actual_ implementation, we have no way to do that without adding an optional `collectionNode:handleInvalidUpdateWithError:` data source method that users would have to implement.
Instead this diff injects the data source's class name into the exception reason, which is still extremely helpful.
This diff also deprecates the `suppressesInvalidCollectionUpdateExceptions` now that the exceptions have matured and this flag has defaulted to `NO` for a couple months. We will remove it soon.
=> Inject Data Source Class Name into Validation Exceptions

AsyncDisplayKit/Details/ASCollectionViewLayoutController.mm, AsyncDisplayKitTests/ASCollectionViewTests.mm
UICollectionViewFlowLayout returns items that are adjacent to the requested rectangle, which can be a pretty significant problem! See the comment I added to the code.
Also I updated a test.
=> Filter Out Extra Items Returned from Collection View Layout

AsyncDisplayKit/ASDisplayNode.mm
Our calculated layout is suitable for this constrainedSize, so keep sing it and invalidate any pending layout that has been generated in the past.
=> [Layout] Remove pending layout if calculated layout is valid and we call layoutThatFits:

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKitTests/ASDisplayNodeTests.m
This bug was initially introduced in #2130 as moved the check for `supportsRangeManagedInterfaceState` for `clearFetchedData` from `setInterfaceState` to `didExitPreloadState` within #2130
Let's get the old behavior back and move the `supportsRangeManagedInterfaceState` check back to `setInterfaceStateState` as it was before all of this renaming PRs. This also does allows us to not have to introduce some internal `_didExitPreloadState` method.
Resolves: #2709
=> [ASDisplayNode] Fix flickering for nodes that support range managed interface state

Base/ASAssert.h
I was debugging earlier today and I saw that the message is sometimes not provided, which is irritating. This is because `nil` is passed into `ASDisplayNodeAssertWithSignal`.
I decided to do a quick pass simplifying and standardizing our assertions, and fixing this bug.
=> Improve Assertion Macros

AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/Private/ASBatchFetching.h, AsyncDisplayKit/Private/ASBatchFetching.m, AsyncDisplayKitTests/ASBatchFetchingTests.m, AsyncDisplayKitTests/ASCollectionViewTests.mm
Resolves #2714.
- If they are visible, batch fetch until we have the leading screens, unless they're scrolling toward the head.
- If they are not visible, batch fetch until we have the visible area.
=> Ensure Batch Fetching Includes Leading Screens, Even if Not Scrolling

AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.mm
UIKit is very harsh about invalid index paths, and will crash you in production if you attempt e.g. to scroll to an invalid item.
This adds assertion & production workarounds to reduce the incidence of this.
=> Add View Index Path Validation

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Layout/ASLayout.mm, AsyncDisplayKitTests/ASDisplayNodeLayoutTests.mm
Referencing `ASLayoutElement`'s in `layoutSpecThatFits:` without holding a strong reference can to lead crashes if the measurement pass happens in a background thread and applied later in a layout pass. 
To assure that layout elements that are referenced in sublayouts life while the root layout is alive we should hold a strong reference to the sub layout layout elements while the root layout is alive.
Resolves: #2673
=> [Layout] Don't crash if layout elements are created in `layoutSpecThatFits:`

AsyncDisplayKit.xcodeproj/xcshareddata/xcschemes/AsyncDisplayKit.xcscheme, AsyncDisplayKit/ASDisplayNode+Beta.h, AsyncDisplayKit/ASDisplayNode.h, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/ASDisplayNodeExtras.h, AsyncDisplayKit/ASDisplayNodeExtras.mm, AsyncDisplayKit/Details/_ASDisplayViewAccessiblity.mm, AsyncDisplayKit/Private/ASDisplayNode+FrameworkPrivate.h, AsyncDisplayKitTests/ASDisplayNodeTests.m, AsyncDisplayKitTests/ASLayoutSpecSnapshotTestsHelper.m, examples/ASDKgram/Sample/PhotoCellNode.m
This resolves #2205 and restores the rasterization used in ASDKgram.
All of the test cases added in this diff were failing before the diff.
`shouldRasterizeDescendants` has been moved to a Beta header while we continue to develop it. If in the future we decide that its performance benefits don't justify its maintenance cost, we may deprecate it and later remove it.
In addition to fixing those behaviors, this diff
- Removes `-deallocSafeSupernode` since it's literally the exact same code as `-supernode` and updates the documentation for the latter to specify that it needs to be dealloc-safe.
- Removes cases where we were calling `ASPerformBlockOnMainThread` in cases where, in the same method, we had already asserted that we were on the main thread.
- Adds a handy little macro …
=> Improve Handling of Rasterized Node Interface & Hierarchy States

AsyncDisplayKit/ASControlNode.h, AsyncDisplayKit/ASControlNode.mm
There is a use for this in Pinterest -- however, I've also seen external requests for it, and it's quite generally useful.
This does increase the number of iterations we check for the mask, but this should be instantaneous at runtime.  It scans across some currently unused values, but this could also allow third parties to add their own if they want to be especially crafty and life on the edge :).
=> [ASControlNode] Add ASControlNodeEventValueChanged to support creating switches, sliders, etc.

AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKitTests/ASPagerNodeTests.m, AsyncDisplayKitTests/ASViewControllerTests.m
This PR will fix the problem that if pushed back to a full screen pager node the UICollectionViewCell that contains the ASCellNode will have an y value of -64.
It does not fix the ASPagerFlowLayout message that comes up. To fix that we will add some more documentation that view controller should use `self.automaticallyAdjustScrollViewInsets = NO` if the pager node is used full screen.
Addresses: #1949
=> [ASPagerNode] Fix content insets are wrong in pager node if root node of ASViewController and transition back

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/_ASTransitionContext.h, AsyncDisplayKit/_ASTransitionContext.m
After removing a subnode via the animated layout transition we should set the alpha value back to the old value.
The reasoning behind is that if the subnode would be added back via a next non animated layout transition (e.g. instead of calling `transitionLayout...`, call `setNeedsLayout` it would still have an alpha value of 0 and although measured the right size it not show up. Furthermore we should also do the same for inserted nodes.
=> [Layout Transition] Reset the alpha value for inserted and removed subnode to initial value

AsyncDisplayKit/ASDisplayNode.mm
If a node is being added as a subview to a UIVIew, we must make sure to remove it as a subnode of its supernode.
=> [ASDisplayNode] Remove node from supernode before adding it as a subview

AsyncDisplayKit/ASTextNode.mm, AsyncDisplayKit/TextKit/ASTextKitRenderer.h, AsyncDisplayKit/TextKit/ASTextKitRenderer.mm
#2550 was merged directly into p6.15 and never made it to master. The fast-path is currently disabled so this will have no immediate effect, but we should bring it over for the future's sake.
Will merge when CI passes.
=> Cherry-Pick Truncation PR to Master

AsyncDisplayKit/ASMultiplexImageNode.mm, AsyncDisplayKit/ASNetworkImageNode.mm, AsyncDisplayKit/Details/ASImageProtocols.h
When we removed some long-deprecated image downloader & cache methods, we didn't do a very thorough job of cleaning up. For example, now that there is only one primary image downloader method, we can mark it required and remove the silly assertion message `"You must implement either downloadImageWithURL:callbackQueue:downloadProgress:completion:."`
This ungunkifies our code, and lets the compiler enforce protocol requirements for us.
=> Remove Vestigial Code Supporting Removed Methods

AsyncDisplayKit/ASNetworkImageNode.h, AsyncDisplayKit/ASNetworkImageNode.mm
After much discussion I think this is the correct behavior. It seems
like it's much more likely to be the expected behavior but still enables
you to use the network image node like an regular image node.
Resolves https://github.com/facebook/AsyncDisplayKit/issues/2756
=> [ASNetworkImageNode] Don't behave like an image node if URL is set.

AsyncDisplayKit/Layout/ASBackgroundLayoutSpec.h, AsyncDisplayKit/Layout/ASOverlayLayoutSpec.h
Resolves #2747.
Michael and I couldn't think of a use case for allowing an `ASBackgroundLayoutSpec` with a nil background layout element. cc @nguyenhuy
=> [AS{Overlay,Background}LayoutSpec] Don't allow nil layout elements

AsyncDisplayKit/ASDisplayNode+Subclasses.h, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/ASNetworkImageNode.mm, AsyncDisplayKit/ASVideoNode.mm, AsyncDisplayKit/Details/ASThread.h
This PR adds a mechanism that detects if a thread tries to access supernode of a node while holding its recursive lock (e.g early sign of upward lock gathering). To detect that, I eventually had to record mutex's owner and level of the ownership. The new code is turned off by default to avoid rather significant overheads.
This PR also changes the locking strategy in ASDisplayNode to avoid situations in which we hold a node's instance lock and call methods outside the scope of `self` (for example, [subnode __setSuperNode:self]`) or didEnter/Exit state. These methods can trigger methods that are meant to be overridden by developers in which they walk up the node tree and grab other locks and potentially cause deadlocks (like #2605). Moreover, they perform expensive tasks that cause the lock …
=> [ASThread][ASDisplayNode] Detect and avoid deadlocks caused by upward lock gathering in didEnter/Exit states

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/Private/ASInternalHelpers.m
Fix [this](https://github.com/facebook/AsyncDisplayKit/issues/2802) issue
=> [ASDisplayNode Deallocation] Fix for crash when certain types are used as instance variables.

AsyncDisplayKit/Details/ASRangeController.mm, AsyncDisplayKit/Details/ASWeakSet.h, AsyncDisplayKit/Details/ASWeakSet.m, AsyncDisplayKitTests/ASCollectionViewTests.mm, AsyncDisplayKitTests/ASTableViewThrashTests.m
This should resolve a huge swath of our cell node visibility issues, such as #2436 #2203 #2658.
=> Range Controller Explicitly Marks Disappeared Nodes as Invisible

AsyncDisplayKit/Layout/ASBackgroundLayoutSpec.mm, AsyncDisplayKit/Layout/ASOverlayLayoutSpec.mm
Addresses https://github.com/facebook/AsyncDisplayKit/pull/2795#issuecomment-267878024
Add assertions here to reenforce the non-nullability of the background and overlay layout elements.
cc  @maicki
=> [AS{Overlay,Background}LayoutSpec] Assert when attempting to set a nil background / overlay layout element.

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKitTests/ASTableViewThrashTests.m
CC #2436 #2203 #2658 
This diff ensures that all cell nodes are deallocated before the thrash test method returns. 
We now have another good test case for cell node visibility issues linked above. Unfortunately, that test case is currently failing, so the test has to remain disabled.
=> Fix Issue Where Thrash Tester Would Throw Exceptions During Other Tests

AsyncDisplayKit/Details/ASDataController.h, AsyncDisplayKit/Details/ASDataController.mm, AsyncDisplayKit/Details/ASRangeController.mm
This change is specific to the reloadData path, which had the last-known occurrence of "deallocated while marked visible".
https://github.com/facebook/AsyncDisplayKit/issues/2711
=> [ASDataController] Ensure ASRangeController has an opportunity to update visible nodes before they're deleted by -reloadData path.

AsyncDisplayKit/Private/ASStackPositionedLayout.mm
- Remove `lastChildOffset`. It's unncessary after #2627.
- Remove the version of `stackedLayout()` that takes 1 less param. Isn't worth the complexity.
=> [ASStackLayoutSpec] Clean up ASStackPositionedLayout

AsyncDisplayKitTests/ASCollectionViewTests.mm
When these fire on the CI, nothing is shown in the log message and it just silently fails. That's super annoying. Obviously I feel bad just removing them but the call patterns around these methods vary so much from iOS version to iOS version – as Apple continuously retools UICollectionView – so chasing a guarantee this strict right now isn't worth our time.
=> Remove Irritating Layout Attributes Assertions

AsyncDisplayKit/ASCellNode.h, AsyncDisplayKit/ASCellNode.mm, AsyncDisplayKitTests/ASCollectionViewTests.mm
Adds a (disabled) unit test for #2825.
This has the side effect of making ASTextCellNode use automatic subnode management. @garrettmoon @appleguy
=> Add a Unit Test For Automatic Subnode Management Interface State Issue

AsyncDisplayKit/ASVideoNode.mm, AsyncDisplayKitTests/ASVideoNodeTests.m
It's confusing to have 2 `_delegate` ivars at the same time: one `ASVideoNode` and another in its super class (e.g `ASNetworkImageNode`), and both of them are accessed/set by the same pair of getter/setter. It also introduces a bit of boilerplate code in `ASVideoNodeTests`.
=> [ASVideoNode] Remove duplicated _delegate ivar

AsyncDisplayKit/UIImage+ASConvenience.h, AsyncDisplayKit/UIImage+ASConvenience.m
Originates from `pi_imageNamed`. Credit goes to @garrettmoon and @rcancro. 
cc @appleguy and @rewandy.
=> [UIImage+ASDKAdditions] Add convenient as_imageNamed methods

AsyncDisplayKit/ASCollectionView.mm
According to Instagram, having this option set to `YES` when unused degrades scroll performance ~5% https://github.com/Instagram/IGListKit/issues/318
=> Disable UICollectionView Prefetching to Improve Scroll Performance

AsyncDisplayKit/Details/ASDataController.mm
Since moves are composite operations (like `reloadItems` and `reloadSections`), they must be handled by `ASChangeSetDataController` and they _are_. The `ASDataController`-level implementations are completely unused and don't fit into the current architectural model for the two classes. In preparation for #698, which we'll hopefully implement soon, we should remove this code to reduce confusion and complexity.
=> Remove Unused Implementations of moveItem: and moveSection:

AsyncDisplayKit/ASImageNode.mm, examples/Kittens/Sample/KittenNode.mm
Implementation copied from ASTextNode: https://github.com/facebook/AsyncDisplayKit/blob/f637392a770ae193c41b7aadd9a01b49b335d9d3/AsyncDisplayKit/ASTextNode.mm#L849
Addresses: https://github.com/facebook/AsyncDisplayKit/issues/2865
Also updates the `Kitten` sample project to demonstrate the `placeholderColor`/`placeholderFadeDuration` APIs.
=> [ASImageNode] Copy ASTextNode’s implementation of placeholderImage into ASImageNode in order to fix usage of ASImageNode.placeholderColor (#2865)

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/ASNetworkImageNode.mm
Addresses #2785
To avoid performance issues, we should avoid locking the downloader.
To achieve this we need to do some kinda gross things. Essentially
the cost is the code is more complex and potentially far less performant
in edge cases. In testing, edge cases are nearly never hit, but I'm not
sure how good I feel about the cost in code complexity. This exacerbates
the locking issues in ASNetworkImageNode:
1. There is no convention for which methods lock.
2. There's no indication which vars are only set on init and therefore
safe to access except in the class extension definition.
=> [ASNetworkImageNode] Don't lock while calling downloader

AsyncDisplayKit/ASVideoNode.mm
- When a video node is first visible, it's player is called to play if `_shouldAutoplay` flag is on. However, the player might not be ready by that time, especially when the video is loaded on a slow network. The player just continues loading its asset.
- When the player is ready, we should check if it is expected to be playing and if true, try to play again.
Tested on sample project provided in #2835, under DSL network (Network Link Conditioner).
=> [ASVideoNode] Should play when its player is ready and if it is expected to play

Podfile
I've just realized that the new Buck abstract target can mess up with tests target. Since the post_install hook is the only necessary thing, let's remove buck target.
=> Remove Buck abstract target in Podfile

AsyncDisplayKit/ASCollectionView.mm
Resolves #2659 
Doing the same thing for `_ASTableViewCell` is actually pretty complex because we have a separate architecture for handling content view size changes. This is at least a step forward.
=> Pin Collection cellNode.frame = contentView.bounds

AsyncDisplayKit/ASTableView.mm, AsyncDisplayKitTests/ASTableViewTests.mm
UITableView actually wants you to include the separator height in `heightForRowAtIndexPath:`. Which is terrible! But if you want a content view of height `44` you need to return `44.5` on a 2x screen if you have separators turned on.
=> Account for Cell Separators when Reporting Table View Row Height

README.md
This updates the values automatically, which is perfect to reflect the growth of ASDK. I've wanted to do this for ages but the shield.io API didn't have the support up till now. We lose some granularity but I think this is worth it.
Maybe @hannahmbanana or @nguyenhuy could take a quick look. Sorry it's been a while since I've kept up to date with the project, not sure if @appleguy is still directly involved.
=> [Nitpick] Update CocoaPod badges to be dynamic.

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/ASDisplayNodeExtras.h, AsyncDisplayKit/ASDisplayNodeExtras.mm, AsyncDisplayKitTests/ASDisplayNodeTests.m, Base/ASBaseDefines.h
Resolves #2888 @hannahmbanana 
I didn't know this, but `convertPoint:toLayer:nil` behaves a lot differently from `convertPoint:toView:nil` and so it's important that we call the appropriate method for the appropriate case.
=> Use Native convertRect:, convertPoint: Methods to Handle Nil Cases

AsyncDisplayKit/ASControlNode.mm
Proposed fix for #2877. It takes the hitTestSlop into account when ASControlNode considers if a tracked touch is 'inside'.
This is my first PR here; Let me know if anything is off!
=> [ASControlNode] Respect hitTestSlop when determining if a tracked touch is inside

AsyncDisplayKit/UIImage+ASConvenience.m, README.md
Resolves #2903.
#Incorrect:
Corrected:
=> [UIImage+ASConvenience] as_resizableRoundedImage border doesn't respect roundedCorner argument

AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/Details/ASCollectionViewFlowLayoutInspector.h, AsyncDisplayKit/Details/ASCollectionViewFlowLayoutInspector.m, Base/ASBaseDefines.h
I found these while working on IGListKit support, and wanted to break them out into their own PR:
- Always use the same reuse identifier. As documented, UICV separates supplementaries by kind so we don't have to.
- Remove unused code from `ASCollectionViewFlowLayoutInspector`
=> Minor Collection Simplifications

AsyncDisplayKit/ASDisplayNode.mm
We are currently check for duplicate layout elements in a subtree although the compiler flag to check it is not defined / enabled. We should consider the compiler flag so in production no extra work is done.
=> [ASLayout] Consider the dedupe compiler flag to check for duplicate elements in a subtree

AsyncDisplayKitTests/ASCollectionViewTests.mm
Our collection view is not exception-safe, and this was increased by #2923 . In our collection view tests, windows pile up because the system retains them (animation delegates etc.), and when the device is rotated during some tests, the collection views that were killed by intentional exceptions in prior tests crash.
I tried waiting for the windows to die on their own – by a couple different methods – but no dice. This suffices to fix it.
=> Fix Test Failures Caused by Pollution Between Test Cases

AsyncDisplayKit/ASRunLoopQueue.mm
- The crash mainly occurs on these old iOS versions (~93%) and p6.16.1. There might be a client code issue that causes this crash, but it's hard to tell if it also crashes on newer iOS versions AND p6.17.
- Let's disable this feature for now and re-investigate if it resurfaces on p6.19 and iOS 9/10.
Closes #2767.
=> Disable background deallocation on iOS 8 and below

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/Details/ASCollectionDataController.mm, AsyncDisplayKit/Details/ASDataController.mm, AsyncDisplayKit/Private/ASDataController+Subclasses.h
Resolves #2961 
This is designed to be a minimal change so that we can hotfix it in. The method names in data controller are currently kind of confusing – a situation that @nguyenhuy 's refactoring work will help greatly with.
The idea here is, when we delete sections, we delete sections of all element kinds simultaneously. That way the caller doesn't need to bother knowing which kinds of supplementaries existed before the update, and that way all section indexes stay aligned.
cc @ay8s Could you give this a try and see if it resolves the issue you're seeing?
=> Fix Deleting Sections Issue

AsyncDisplayKit/Details/ASIndexedNodeContext.h, AsyncDisplayKit/Details/ASIndexedNodeContext.mm
Caching the `ASEnvironmentTraitCollection` upon creation of `ASIndexedNodeContext` can lead to it becoming out of date. Ask the `id<ASEnvironment>` object for the trait collection when we need it.
=> [ASIndexedNodeContext] Do not cache the envTraitCollection, use the delegate to request it when needed

AsyncDisplayKit/ASPagerNode.h, AsyncDisplayKit/ASPagerNode.m
- Instead of using `[CGSizeZero, pagerNode.bounds.size]` as the size range for pages, use exactly `pagerNode.bounds.size`. Much of the logic in `ASPagerNode` depends on the pages filling the bounds, and we've had issues in Pinterest where pages did not fill the bounds and that was very unexpected and annoying.
- Deprecate `pagerNode:constrainedSizeForNodeAtIndex:` with no replacement. As said above, the only appropriate size range for a page in a pager node is exactly `pagerNode.bounds.size` which is now the default behavior.
=> Force ASPagerNode Pages to Fill Pager Bounds

AsyncDisplayKit/Private/ASIGListAdapterBasedDataSource.h
This doesn't restore IGListKit functionality like #2988 but it gets the CI building again.
Will merge after CI passes.
=> Fix the CI

AsyncDisplayKit/ASCollectionNode.h, AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/Private/ASIGListAdapterBasedDataSource.h, AsyncDisplayKit/Private/ASIGListAdapterBasedDataSource.m
We recently accidentally broke IGListKit support when we added support for full nodeless interop.
This diff ensures that both modes (IGListKit and full passthrough) work correctly.
=> Restore IGListKit Support

AsyncDisplayKit/ASDisplayNode.h, AsyncDisplayKit/Details/ASObjectDescriptionHelpers.h, AsyncDisplayKit/Layout/ASLayoutElement.h, AsyncDisplayKit/Layout/ASLayoutSpec.h
We currently have the `debugName` property in `ASLayoutElement` although it can live in the debug layer and does not need to be in the layout layer.
Let's move this into a separate protocol in the debug layer.
=> [Debug] Move debugName into it’s own protocol out of the ASLayoutElement protocol

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/Layout/ASLayoutElementExtensibility.h, AsyncDisplayKitTests/ASLayoutSpecTests.m
With the introduction of ASLayoutElementStyle that combines all style related properties for a ASLayoutElement we need to provide some kind of extensibility support. This is important as it should be possible to add custom layout specs and extend the ASLayoutElementStyle for usage within the custom layout specs.
The general idea is outline in this gist via examples: https://gist.github.com/maicki/2630b51f62cbedc0cb34e0bcac96d6c9
Original diff #2294 and replaces #2943
=> [Layout] Add extensibility support to ASLayoutElementStyle

AsyncDisplayKit/ASDisplayNode.h, AsyncDisplayKit/ASDisplayNode.mm, Base/ASAssert.h
Currently Async Display Kit doesn't provide a mechanism for "asserting" in production. In many the framework can recover from failures, but that would happen silently when in production.
This code changes gives the ability to set a "non-fatal error block" on `ASDisplayNode` class, so it can be plugged in many areas where we have asserts, for example, so developers have the change to capture and report such failures in production.
This addresses #2807 .
=> [ASDisplayNode] Add support for setting non-fatal error block

AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/Details/ASCollectionViewLayoutInspector.h, AsyncDisplayKit/Details/ASCollectionViewLayoutInspector.m, AsyncDisplayKit/Details/UICollectionViewLayout+ASConvenience.h, AsyncDisplayKit/Details/UICollectionViewLayout+ASConvenience.m, AsyncDisplayKit/Private/ASCollectionViewFlowLayoutInspector.h, AsyncDisplayKit/Private/ASCollectionViewFlowLayoutInspector.m, AsyncDisplayKitTests/ASCollectionViewFlowLayoutInspectorTests.m
Resolves #3002 and #2634 
Before you say it, I know we should protocolize this. We will. But at this stage I don't want to go halfway and do that. This change is intentionally very small so we can get it deployed immediately.
- Replace `asdk_isFlowLayout` with `asdk_layoutInspector`
- Call `didChangeCollectionViewDelegate/didChangeCollectionViewDataSource` when the layout inspector is bound, so they don't have to call it on themselves.
- Remove the `collectionView` argument from the layout inspector initializer because we don't need it anymore.
=> Allow UICollectionViewLayout to Provide Layout Inspector, Always Update Delegate

AsyncDisplayKit/ASNetworkImageNode.h, AsyncDisplayKit/ASNetworkImageNode.mm
Here's one other idea for addressing this problem. Essentially,
we assert if you've set both the URL and the image. I've played around
with Pinterest and there's only one case where we hit this (the transition).
So I've also added another method (which is a bummer, it's weird I know)
but there's one good reason to add this method, ephemeralImage, which is
the user doesn't have to manually clear it out like they would if they
used defaultImage to save memory.
Putting this up for discussion.
=> [ASNetworkImageNode] Assert if both URL and image are set

AsyncDisplayKit/UIImage+ASConvenience.h, AsyncDisplayKit/UIImage+ASConvenience.m
Order the methods so the most valuable one, as_imageNamed, is more immediately noticeable.
Also added a block comment describing its purpose and usage suggestions.
Separated @implementation for fairly unrelated methods by categories.
=> [UIImage+ASConvenience] Reorder header and add more documentation.

AsyncDisplayKit/ASVideoNode.mm
Resolves #2230 
It's scary that this wasn't triggering a warning, even when I explicitly added the warning flag.
=> Have ASVideoNode Override Superclass's Designated Initializer

AsyncDisplayKit/ASCollectionView.h, AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.h, AsyncDisplayKit/ASTableView.mm, examples/CustomCollectionView-Swift/Sample/MosaicCollectionViewLayout.swift
Resolves #2245 and improves interop with frameworks like TLYShyNavBar which set the delegate of the table/collection view.
We do not guarantee that we support these other frameworks, but in cases like this where the cost is low, we can help.
=> Route setDelegate: to setAsyncDelegate:

examples/CatDealsCollectionView/Sample/ViewController.m
I accidentally landed some unused method names into this example – `referenceConstrainedSizeForHeaderInSection:` which actually ended up being named `sizeRangeForHeaderInSection:`. This restores the supplementary views.
Will land after CI passes.
=> Fix CatDealsCollectionView Supplementary Node Handling

AsyncDisplayKit/ASCollectionView.h, AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.h, AsyncDisplayKit/ASTableView.mm, examples/CustomCollectionView-Swift/Sample/MosaicCollectionViewLayout.swift
This reverts commit 5c8818d107252da8eb6a91cf88237916ec26f5ed.
Resolves #3016 and unresolves #3007 . I'm marking that issue as `wontfix` since (1) the issue is very old and (2) it's not very high value.
=> Revert "Route setDelegate: to setAsyncDelegate: (#3007)"

examples_extra/ASDKgram-Swift/ASDKgram-Swift.xcodeproj/project.pbxproj, examples_extra/ASDKgram-Swift/ASDKgram-Swift.xcodeproj/project.xcworkspace/contents.xcworkspacedata, examples_extra/ASDKgram-Swift/ASDKgram-Swift/AppDelegate.swift, examples_extra/ASDKgram-Swift/ASDKgram-Swift/Assets.xcassets/AppIcon.appiconset/Contents.json, examples_extra/ASDKgram-Swift/ASDKgram-Swift/Base.lproj/LaunchScreen.storyboard, examples_extra/ASDKgram-Swift/ASDKgram-Swift/Base.lproj/Main.storyboard, examples_extra/ASDKgram-Swift/ASDKgram-Swift/Constants.swift, examples_extra/ASDKgram-Swift/ASDKgram-Swift/Date.swift, examples_extra/ASDKgram-Swift/ASDKgram-Swift/Info.plist, examples_extra/ASDKgram-Swift/ASDKgram-Swift/NetworkImageView.swift, examples_extra/ASDKgram-Swift/ASDKgram-Swift/PX500Convenience.swift, examples_extra/ASDKgram-Swift/ASDKgram-Swift/PhotoFeedModel.swift, examples_extra/ASDKgram-Swift/ASDKgram-Swift/PhotoFeedTableNodeController.swift, examples_extra/ASDKgram-Swift/ASDKgram-Swift/PhotoFeedTableViewController.swift, examples_extra/ASDKgram-Swift/ASDKgram-Swift/PhotoModel.swift, examples_extra/ASDKgram-Swift/ASDKgram-Swift/PhotoTableNodeCell.swift, examples_extra/ASDKgram-Swift/ASDKgram-Swift/PhotoTableViewCell.swift, examples_extra/ASDKgram-Swift/ASDKgram-Swift/PopularPageModel.swift, examples_extra/ASDKgram-Swift/ASDKgram-Swift/UIColor.swift, examples_extra/ASDKgram-Swift/ASDKgram-Swift/UIImage.swift, examples_extra/ASDKgram-Swift/ASDKgram-Swift/URL.swift, examples_extra/ASDKgram-Swift/ASDKgram-Swift/Webservice.swift, examples_extra/ASDKgram-Swift/Podfile
This is a swift example of the Objective-C ASDKgram in the examples folder.
It is not an exact replica although does attempt to replicate the comparison between UIKIt and ASDK performance. The main differences are: 
- For the UIKit TableViewCell, autolayout is used exclusively 
- It does not show a comment view
- It does not demonstrate the visual style of flexbox layout
- Minor visual differences
It could prove beneficial to Swift who are unfamiliar with Objective-C like myself.
=> [Examples] Add ASDKgram-swift to examples_extra

AsyncDisplayKit/Layout/ASDimension.h, AsyncDisplayKit/Private/ASDisplayNode+UIViewBridge.mm
Even with application checks (for Inf and NaN) before assigning a frame to a node, it is still possible to have the newPosition containing NaN values. Since there is still some logic being done in `setFrame:` where other values are considered to calculate the new position and new bounds, it is possible that the NaN is being generated here.
This PR is meant to prevent that from happening by checking the final values before assigning them.
=> Safer checks in ASDisplayNode’s setFrame before assigning bounds and position

AsyncDisplayKit/ASTextNode.mm
This was actually causing practical problems. Resolves #2976 .
=> Lock ASTextNode.attributedText

AsyncDisplayKit/ASViewController.h, AsyncDisplayKit/ASViewController.mm, examples/ASDKgram/Sample.xcodeproj/project.pbxproj, examples/ASDKgram/Sample/AppDelegate.h, examples/ASDKgram/Sample/PhotoFeedBaseController.h, examples/ASDKgram/Sample/PhotoFeedBaseController.m, examples/ASDKgram/Sample/PhotoFeedControllerProtocol.h, examples/ASDKgram/Sample/PhotoFeedListKitViewController.h, examples/ASDKgram/Sample/PhotoFeedNodeController.h, examples/ASDKgram/Sample/PhotoFeedNodeController.m, examples/ASDKgram/Sample/PhotoFeedViewController.m
Thanks to @nguyenhuy for the initial work! Unfortunately there were a couple of bigger changes since the last commit of the initial PR so I rebased and also cleaned it up a bit. Will replace #2810
This PR makes ASViewController's node optional. This allows developers to use ASViewController like a normal UIViewController. More importantly, it can be used as a base class for view controllers among which some use a node hierarchy and some don't.
Resolve #2760.
=> [ASViewController] Support optional node

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/ASCollectionView.h, AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/ASPagerFlowLayout.m, AsyncDisplayKit/ASPagerNode.h, AsyncDisplayKit/ASPagerNode.m, AsyncDisplayKit/AsyncDisplayKit.h, AsyncDisplayKit/Private/ASResponderChainEnumerator.h, AsyncDisplayKit/Private/ASResponderChainEnumerator.m, AsyncDisplayKit/UIResponder+AsyncDisplayKit.h, AsyncDisplayKit/UIResponder+AsyncDisplayKit.m, examples/PagerNode/Sample/PageNode.m, examples/PagerNode/Sample/ViewController.m
Resolves #2974 and other major pager node rotation/content inset issues.
- Deprecates `ASCollectionView.zeroContentInsets`.
- This flag was added as a hack during development of `ASPagerNode` to "undo" the effects of `UIViewController.automaticallyAdjustsScrollViewInsets`.
- The flag adds `contentInsets = .zero` into `layoutSubviews`, after `[super layoutSubviews]`
- This means our `contentInsets` is thrashing around constantly.
- The view controller _also_ sets `contentOffset` during its insets adjustment, which we didn't account for.
- Adds a flag `ASPagerNode.allowsAutomaticInsetsAdjustment`.
- Defaults to `NO` since you virtually NEVER want UIVC to adjust pager node insets.
- If `NO`, finds the owning view controller of the pager and sets `automaticallyAdjustsScrollViewInsets=NO`, and …
=> Fix Pager Node Issues

AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKitTests/ASTableViewTests.mm
Fixes the rest of #2955 
The logic behind this flag is pretty nonsensical. The only reason we would ever get `layoutSubviews` before our size is "final" is if someone calls `layoutIfNeeded` specifically on us, which they might do I guess.
But in the normal case, we get `layoutSubviews` after our superview gets `layoutSubviews` and sets our frame to e.g. `(375, 667)` or whatever our final frame is. Silly silly silly!
=> Don't Skip Remeasurement On First Layout Pass

AsyncDisplayKit/ASCollectionView.h
This method has some valid uses, for example if your `UICollectionViewLayout` wants to get the current view-space index path for a node (node-tracking is actually extremely valuable in some cases, and often a much better choice than index path tracking).
=> Undeprecate -[ASCollectionView indexPathForNode:]

AsyncDisplayKit/TextKit/ASTextKitContext.mm
A quick fix for CJK language layout issue, which is supposed to bring no side effect. Has been tested in our production for one month.
See https://github.com/facebook/AsyncDisplayKit/issues/2894
=> [TextKit] Fix text layout issue for CJK laungages

AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.h, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/Details/ASDataController.h, AsyncDisplayKit/Details/ASDataController.mm, AsyncDisplayKit/Details/ASRangeController.h, AsyncDisplayKit/Details/ASRangeController.mm, AsyncDisplayKitTests/ASTableViewTests.mm
- Only do it for non-animated updates. For animated updates, as I mention in the comments, we can't synchronize with table view's update animation and you see an ugly wave.
- This is **breaking API** but we need to do it. No user would ever prefer to see this effect.
- Switch our tracking system to be much simpler and to account for section headers/footers/etc.
- Add a unit test for content offset adjusting
Old system:
> Update about to start
> Save first visible index path
> Update inserted rows
> Sum up all the nodes' `calculatedSize.height`
> Update deleted rows
> Subtract all the nodes' `calculatedSize.height`
> Update about to end
> Find the row at the saved index path (!!! may not be correct)
> Add the summed-up value to contentOffset.y
New system:
> Update about to start
> Save the …
=> Majorly Improve automaticallyAdjustsContentOffset

AsyncDisplayKit/ASDisplayNode+Beta.h, AsyncDisplayKit/ASDisplayNode+Yoga.mm, AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKit/AsyncDisplayKit-Prefix.pch, AsyncDisplayKit/Layout/ASDimension.h, AsyncDisplayKit/Layout/ASDimension.mm, AsyncDisplayKit/Layout/ASLayoutElement.mm, AsyncDisplayKit/Layout/ASStackLayoutDefines.h, AsyncDisplayKit/Private/ASDisplayNodeInternal.h, AsyncDisplayKit/Private/Layout/ASStackPositionedLayout.mm, Base/ASAvailability.h
This patch also adds ASEdgeInsetsZero, and one fix to passthrough of UIKit Supplementary Views.
The core team shouldn't spend any time supporting this, though.  If there is an upcoming refactor in a file like ASDisplayNode or ASLayoutElement, please feel free to delete the integration points.
Because almost all of the implementation is contained within ASDisplayNode+Yoga.mm, I'm very comfortable with re-implementing the integration points if any refactoring effort removes them.
There is now pretty good testing of this feature. I believe there won't be any significant new integration points (like the #if gating), so this should be the level of impact on ASDisplayNode.mm's main file.
=> [Yoga] Fix ASLayout hierarchy to only include immediate subnodes.

AsyncDisplayKit/ASDisplayNode.mm, AsyncDisplayKitTests/ASDisplayNodeTests.mm, examples/ASDKgram/Sample/CommentsNode.m
Resolves #3038
Doing this will prevent required callbacks like `didMoveToWindow` from getting sent to our view.
=> Prevent Adding View-Backed Nodes to Layer-Backed Hierarchies

AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/Details/ASDataController.mm
After #3017, it's much easier to support native reloads now. Since updates are already broken down to inserts and deletes by `_ASHierarchyChangeSet`, `ASDataController` can consume these inserts and deletes as is, and then `ASCollectionView`/`ASTableView` forward the original changes to `UICollectionView`/`UITableView`. This resolves #469. 
Demo:
- [Reload item](https://cl.ly/jIkf)
- [Reload section](https://cl.ly/jIC7)
=> [ASCollectionView/ASTableView] Support native item and section reloads

AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/Details/ASDataController.h, AsyncDisplayKit/Details/ASDataController.mm
- Before data controller had one mutable & one immutable representation of the data.
- Now data controller has just two immutable data representations: `completedElements` and `pendingElements`
- Mutable representation is never saved – it's created in `updateWithChangeSet:` and provided to methods that are expected to modify it, and then immediately cloned.
This makes the data controller much easier to reason about, and sets the stage for building a custom immutable representation of the state-of-the-world for data controller.
=> ASDataController: Eliminate Mutable State

AsyncDisplayKit/ASDisplayNode.mm
Because doing so can cause deadlocks if the hooks cause main thread to wait for a background thread which in turn needs the instance lock. Example in screenshots below:
=> [ASDisplayNode] Avoid holding instance lock while calling layout subclass hooks

AsyncDisplayKit.xcodeproj/project.pbxproj, AsyncDisplayKit/ASCellNode+Internal.h, AsyncDisplayKit/ASCellNode.mm, AsyncDisplayKit/ASCollectionNode.mm, AsyncDisplayKit/ASCollectionView.mm, AsyncDisplayKit/ASTableNode.mm, AsyncDisplayKit/ASTableView.mm, AsyncDisplayKit/Details/ASCollectionElement.mm, AsyncDisplayKit/Details/ASDataController.h, AsyncDisplayKit/Details/ASDataController.mm, AsyncDisplayKit/Details/ASRangeController.h, AsyncDisplayKit/Details/ASRangeController.mm, AsyncDisplayKit/Details/ASTraitCollection.h, AsyncDisplayKit/Details/NSIndexSet+ASHelpers.h, AsyncDisplayKit/Details/NSIndexSet+ASHelpers.m, AsyncDisplayKit/Private/ASElementMap.h, AsyncDisplayKit/Private/ASElementMap.m, AsyncDisplayKit/Private/ASMutableElementMap.h, AsyncDisplayKit/Private/ASMutableElementMap.m
- Add a new immutable class `ASElementMap` that gives a state-of-the-world for a collection/table.
- Have `ASDataController` vend two maps: one visible and one pending.
- Have `ASTableView ASCollectionView ASRangeController` use the maps directly to answer questions like `numberOfSections` etc.
- Remove `cachedIndexPath` and `supplementaryElementKind` fields from `ASCellNode+Internal`. Add new `collectionElement` field to it.
- Index path can be efficiently looked up from a given element map.
- Supplementary element kind can be looked up from new `collectionElement` field.
- `collectionElement` field added on assumption that if you return an existing cell node in a node block, then it no longer participates in the old collection view.
Plenty more work to do from here! At least now we can …
=> ASDataController: Adopt ASElementMap

AsyncDisplayKit/ASCollectionView.mm
These changed recently with the addition of the ability to provide nodeBlocks.
It might be more strict to assert that nil can't be provided unless the datasource supports
inter-op, but I think it is also pretty reasonable to just use an empty ASCellNode in this case.
Either way, I'm really amazed / surprised to see all the improvements that appeared in ASDataController!
=> [ASCollectionView] Allow mixing supplementaryViews and Nodes by relaxing assertions.

Source/ASTableView.mm, Source/Private/ASElementMap.m, Source/Private/ASMultidimensionalArrayUtils.mm, Source/Private/ASMutableElementMap.m, Tests/ASCollectionViewTests.mm
- Fix the crash reported by @appleguy in #3074. It occurs because we never create a dictionary that holds supplementaries of a new kind ([here](https://github.com/facebook/AsyncDisplayKit/compare/master...nguyenhuy:HNASElementMapCras?expand=1#diff-1f7bf759dcd5f7e05395f0e53842b26eR93)).
- Fix the crash reported by @maicki on [Slack](https://asyncdisplaykit.slack.com/files/maicki/F4ALP7M2R/-.swift). We just need to gratefully handle `nil` index path internally.
=> Fix crashes in ASElementMap and ASMutableElementMap

Source/Layout/ASBackgroundLayoutSpec.mm, Source/Layout/ASLayoutSpec.h, Source/Layout/ASOverlayLayoutSpec.mm
Current calling `layoutSpec.child` on a background or overlay layout spec would cause assertion: 
```
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'This layout spec does not support more than one child. Use the setChildren: or the setChild:AtIndex: API'
```
This is inconvenient to users because it forbids them from doing something like below and instead have to rely on initializers of these specs:
```Objective-C
ASOverlayLayoutSpec *containerSpec = [[ASOverlayLayoutSpec alloc] init];
containerSpec.overlay = titleSpec;
containerSpec.child = self.imageNode;
```
[Reported within Pinterest](https://pinterest.slack.com/archives/ios-help/p1487814286000839). Inconvenient no more!
=> Allow users to set child directly on overlay and background specs

Source/ASCellNode.h, Source/ASTableView.mm, Source/Details/_ASCollectionViewCell.m
Resolves #3037
This is a do-over of c85aa11, with the following differences:
- Fixed `_ASTableViewCell` properties **always** being mutated to match corresponding `ASCellNode` passthrough properties, even when the hosted `ASCellNode` is currently `nil`. Now only inheriting passthrough properties when there’s an actual instance of `ASCellNode` to read them from.
- Corrected spelling of `ASCellNode`’s `separatorInset` property.
- Reverted `_ASCollectionViewCell` inheriting the hosted cell node’s `backgroundColor` & `clipsToBounds` properties. This seems to be surprising and unwanted behavior to some, as seen in #3053 and #3044.
- Moved passthrough of `UITableViewCell`’s `selectedBackgroundView` into `_ASTableViewCell`’s `-setNode:` method for consistency.
=> Fix cell selection state issues

Source/Details/ASPhotosFrameworkImageRequest.h
The nullability in this declaration is incorrect (throws warnings under some environments), and honestly it's not needed anyway. Goodbye!
=> Remove Declaration of ASPhotosFrameworkImageRequest.isEqual

Source/ASDisplayNode.mm
It has locking and is backed by an ivar, not UIKit.
=> [ASDisplayNode] Don't protect contentsScaleForDisplay with thread affinity

examples_extra/Multiplex/Sample/ScreenNode.m
Changed ASImageDownloaderProtocol method that changed a while back.
Resolves #3086
=> [Example] Fix Multiplex example due to ASImageDownloaderProtocol method mismatch

Source/ASCollectionView.mm
This is for UICollectionView interop.
=> [ASCollectionView] Always call sizeForItem: method for index paths that don't use ASCellNodes.

Source/ASDisplayNode.mm
Set the node to not opaque if it’s wrapping an UIActivityIndicatorView. It's reproducible in the Swift example.
=> [ASDisplayNode] Fix node is showing up as black box if wrapping an UIActivityIndicatorView

Source/Details/ASLayoutController.h, Source/Details/ASRangeController.mm, Source/Details/ASTableLayoutController.m
We previously:
- Waited for `setVisibleNodexIndexPaths:`.
- Found the min row and max row.
- Measured the range bounds distance from the min row and max row.
- Searched in rects at that distance away from the min row and max row, growing our search rect until we found one.
We now:
- Ask the table view for the index paths of the rows in the specified rect.
=> Majorly Simplify ASTableLayoutController

Source/Details/ASAbstractLayoutController.mm
> Method `allIndexPathsForScrolling:rangeMode:displaySet:preloadSet:` in protocol `ASLayoutController `not implemented.
=> Fix a Compiler Warning from ASAbstractLayoutController.mm

Source/ASCellNode.mm, Source/ASCollectionView.mm, Source/ASDisplayNode.mm, Source/ASTableView.mm, Source/Details/ASDataController.h, Source/Details/ASDataController.mm, Source/Private/ASDisplayNode+FrameworkPrivate.h
Another step to simplify our layout code within `ASDisplayNode`. After we landed the new handling of `ASCellNode` if a root node needs to do a layout pass now we try to remove the clutter around the layout transitions and how they are handling currently.
The big thing here is that instead of using the bounds of the node we will call `rectForRowAtIndexPath:` or grab the layout element in collection view to get the current height of the cell and determine based on that if we have to trigger a measure pass.
=> [Layout] Use rectForRowAtIndexPath: to check if a cell node size changed

Source/ASCellNode.h, Source/ASDisplayNode.h, Source/ASDisplayNode.mm, Source/ASEditableTextNode.h, Source/ASMultiplexImageNode.h, Source/ASMultiplexImageNode.mm, Source/ASNetworkImageNode.h, Source/ASNetworkImageNode.mm, Source/ASScrollNode.mm, Source/ASTextNode.h, Source/ASVideoNode.h, Source/Details/ASAbstractLayoutController.h, Source/Layout/ASLayout.h, Source/Layout/ASLayoutSpec+Subclasses.mm, Source/Layout/ASLayoutSpec.h, Source/Private/ASCollectionViewFlowLayoutInspector.h, Source/Private/ASLayoutTransition.h, Source/Private/ASMutableElementMap.h, Source/Private/ASSection.h
- Improve designated initializer attributions for `ASDisplayNode` and subclasses
- Move initializer in `ASNetworkImageNode`, `ASMultiplexImageNode` and `ASVideoNode` to unavailable
- Use `NS_UNAVAILABLE` instead of `__unavailable`
Fixes:
-  In `ASScrollView` it's now possible to overwrite `init` and call super without any crash
- In `ASTextCellNode` overwrite of `init` did crash calling `super.init`. Now it's actually prevented to overwrite `init` an otherwise it is recommended to overwrite the designated initializer `initWithAttributes:insets:` and just calling super with the passed in parameters to initialize
=> Improve designated initializer usage

Source/ASPagerFlowLayout.m
Currently rotation works because of a different code path (`nodeDidRelayout:sizeChanged:` -> `invalidateLayoutWithContext:`) but that code path requires multiple invalidations and isn't native. 
This is the native way to get flow layout to ask you for the new sizes on rotation, which we need.
=> Invalidate Pager Flow Metrics on Bounds Change

Source/ASTableView.mm
This was added in #430. Since then it's grown and grown in complexity probably due to other issues encountered along the way. 😱 
Back then we would flush the range controller (queued in the run loop), and now we synchronously flush it (if it's invalidated):
- At the end of the layout pass
- After calling endUpdates
- When we enter the window
The original rationale was that "we depend on -indexPathsForVisibleRows to be correct immediately after willDisplayCell:, but it isn't." But I don't think it's true that we depend on it being correct at that time… we depend on it being correct later, asynchronously. Could be interesting to see if `indexPathsForVisibleRows` calls `layoutIfNeeded` or equivalent.
@eanagel What are your thoughts on this? You mentioned that not having it caused issues with …
=> Remove ASTableView's pendingVisibleIndexPath System

Source/ASVideoPlayerNode.h, Source/ASVideoPlayerNode.mm, examples/ASDKTube/Sample/Models/VideoModel.m, examples/ASDKTube/Sample/Nodes/VideoContentCell.m, examples/ASDKTube/Sample/ViewController.m
This PR is building on top of the fabulous work of @nguyenhuy in #3093.
Some problems in ASVideoPlayerNode currently:
* We have two sources of truth. One is the asset within the `ASVideoPlayerNode` and the other one is within the backing `ASVideoNode`. Ideally we only want to have only one final source of truth, therefore this PR will try to use the `ASVideoNode` as final truth of source.
* `_loadAssetWhenNodeBecomesVisible` isn't turned on in the empty initializer. This causes an assertion in #3042 because it's not safe to set an asset on ASVideoNode off main.
* The flag itself is troublesome. It's enabled by default, but even so, "visible" is a bit too late. The asset can be loaded as soon as the player enters preload state, which is what ASVideoNode is doing.
This PR deprecates …
=> [ASVideoPlayerNode] Fixes and improvements

AsyncDisplayKit.xcodeproj/project.pbxproj, Source/ASCollectionView.mm, Source/ASTableView.mm, Source/Base/ASBaseDefines.h, Source/Details/ASAbstractLayoutController.mm, Source/Details/ASCollectionViewLayoutController.m, Source/Details/ASLayoutController.h, Source/Details/ASRangeController.h, Source/Details/ASRangeController.mm, Source/Details/ASTableLayoutController.m, Source/Private/ASElementMap.h, Source/Private/ASElementMap.m
This doesn't actually change any behavior, but it lays the groundwork for range controllers to deal with supplementary elements.
After this diff, we provide elements of other kinds to the range controller, but before it starts its core work it filter-maps supplementary elements into item index paths, and continues behaving as before.
We should review this and once it's landed we can change the core range controller algorithm to deal with supplementary elements and items alike.
=> Initial Work for Range Controller to Support Supplementary Elements

Source/ASCollectionView.mm
- Currently we use `node.calculatedSize` for collection view item sizes
- Assumes already measured with correct size ranges
- Currently no API to ask us invalidate the size range
- We hard-invalidate all size ranges on collection-view-bounds-change (rotation)
- Flow layout knows when item sizes are invalidated, has API for it
- After this diff, we use the latest size range and rely on `layoutThatFits:` as cache
- In the future we remove the eager remeasure pass on rotation if we convince community not to migrate away from `node.calculatedSize` in their layouts
- After we remove eager remeasure
- We have public deprecated method `calculatedSizeForItemAtIndexPath:`
- Maybe expand on that? Give custom layouts an equivalent to ask us for item sizes like …
=> Don't Cache ConstrainedSize in ASCollectionView

Source/ASCollectionNode.mm, Source/ASDisplayNode.mm
Unfortunately we had to revert #3132 as it would have broke a lot of current code as the designated and convenience initializer in ASDisplayNode are not probably defined at all.
This PR at least fixes crashes if `ASDisplayNode` is subclassed in Swift and certain initializer implemented. This especially fixes known crashes in `ASScrollNode`, `ASCollectionNode` and `ASTableNode`.
=> [Swift] Fix crashes while subclassing ASDisplayNode and subclasses in Swift

Source/ASDisplayNode.mm
`-[ASDisplayNode actionForLayer:forKey:]` should return `nil` to avoid the node being animated by CA when it's being moved from one supernode to another.
This reverts commit 1d21c0bd5545741f284e553d7ed003c69fa6897c introduced by @Adlai-Holler in #3063.
=> [ASDisplayNode] Revert #3063

Source/Layout/ASStackLayoutSpec.h, Source/Layout/ASStackLayoutSpec.mm, Source/Private/Layout/ASStackUnpositionedLayout.h, Source/Private/Layout/ASStackUnpositionedLayout.mm
- The current locking situation of `ASDisplayNode` unfortunately causes deadlocks if a stack spec is concurrent. While the concurrency has proven to be beneficial, enabling it by default is too risky.
- Once `ASDisplayNode` has a transactional layout system and/or its locking strategy has improved, we definitely should reconsider this option.
=> Add a concurrent flag to ASStackLayoutSpec that is off by default

Source/ASCollectionView.mm, Tests/ASCollectionViewTests.mm
This was added in #3017 and it's causing some issues for Pinterest, due to it triggering the initial load of data for collections that are `(0, 0)`. @nguyenhuy Do you remember the details of why this was added?
=> Don't Eagerly Trigger Relayout in Wait

Source/ASTableView.mm
This avoids a possible infinite loop.
=> When Converting Index Paths in Tables, Only Wait if Asked

Source/ASControlNode.mm
Currently the touch and tracking system of ASControlNode does not align with the system of UIControl. ASControlNode does not even consider `beginTrackingWithTouch:withEvent:` or `continueTrackingWithTouch:withEvent:`.
This commit will change the ASControlNode logic around touch event handling and tracking to align with UIControl after diving a bit into the assembly and the way UIControl is working.
This PR also uncomments the assertion that if adding a target action to an `ASControlNode` that is layer backed it will throw an assertion.
Resolves #3139
=> [ASControlNode] Align touch and tracking system in ASControlNode to UIControl

Source/ASCollectionView.mm
- `UICollectionViewFlowLayout` asks its delegate, which is `ASCollectionView`, for reference size of headers and footers. If a header or footer is unavailable, its backing collection element will be nil and a zero size should be returned immediately.
- Same deal for unknown items.
=> [ASCollectionView] Gratefully handle unavailable headers and footers

Source/ASCollectionView.mm, Source/Private/ASElementMap.m
Not sure what's causing this yet, but we're sometimes seeing visible supplementary elements reported by the collection view that don't exist in the element map.
It's possible that these are leftover from an animation that's inflight or something, so we may not want to be as strict as an assertion. Let's get the production crashes out of the way and revisit.
=> Add Production Workarounds for Missing Elements

Source/ASButtonNode.mm, Source/ASImageNode.mm, Source/ASTextNode.mm, Source/ASVideoNode.mm, Source/ASVideoPlayerNode.mm
To be able to enable asynchronous stack layout spec computation again as well as planned work around layout calculations within `ASDispayNode`, we need to improve our locking situation. This is a first small step by reviewing most of the `ASDisplayNode` subclasses and remove not needed locking.
Especially it's important to remove the lock calling superclass methods like `setNeedsLayout` and `setNeedsDisplay` etc.
=> Improve locking situation in ASDisplayNode subclasses

Source/Private/Layout/ASStackUnpositionedLayout.mm
=> flexShrinkAdjustment lambda must always return CGFloat

Source/ASButtonNode.mm
Since the title node is lazily created, we need to get it via its setter or risk having no title at all! 
Fixes #3164.
=> When update title of a button node, need to get title node via setter

Source/ASCellNode.mm
Cell nodes can be used without using it within a collection or table view. In this case if a size change happened we should call super as there is no interactionDelegate
=> [ASCellNode] Let superclass know if size change happened and it does not have an interaction delegate

Source/ASCellNode.mm, Source/ASDisplayNode.mm, Source/Private/ASDisplayNode+AsyncDisplay.mm, Source/Private/ASDisplayNode+FrameworkPrivate.h, Source/Private/ASDisplayNodeInternal.h
- Add and Remove locking where it's necessary and missing or it could cause to deadlocks
- Annotate methods that needs to be called with a lock held with `_locked_` prefix
- Cleanup code around our locking guidelines in general (scoped locking and calling `lock()` and `unlock()` directly)
- Most of the locking code around layout is not touched yet that will be in a follow up PR on top of this one, but I wanted to have this two separated to have the changes as small as possible.
=> [ASDisplayNode] Improve locking in ASDisplayNode

Source/ASCollectionNode.mm, Source/ASTableNode.mm
Because there would be no update otherwise.
This is a follow up on https://github.com/facebook/AsyncDisplayKit/pull/3120.
=> Don't load collection/table node just to wait for updates to be committed

Source/ASDisplayNode.mm
Currently creating a `view` / `layer` in `ASDisplayNode` can cause a race condition where it can happen the loading of the view / layer is in flight but e.g. `isNodeLoaded` would return NO although it would be ready. The idea from this PR is to make the creation of the layer / view as well as applying all pending states in one transaction so no race condition should happen anymore.
=> [ASDisplayNode] Add locking to view and layer in ASDisplayNode

Source/ASDisplayNode.mm, Source/Private/ASDisplayNodeInternal.h, Source/Private/ASLayoutTransition.mm
We have to check in subnode removals in a layout transition, if the supernode of the subnode is indeed still the node that executes the layout transition. It can happen that a node already did a layout transition and added this subnode, in this case the subnode would would be removed from the new node instead of the old node.
Resolves: #3019
=> [Layout] Check in layout transition if the supernode is still the node that is executing the transition

Source/ASMultiplexImageNode.mm, Source/ASNetworkImageNode.mm, Source/Details/ASBasicImageDownloader.mm, Source/Details/ASImageProtocols.h, Source/Details/ASPINRemoteImageDownloader.m
Hi guys,
Following #3112 I'm submitting this PR to solve the bridging crashes I was experiencing when implementing `ASImageCacheProtocol` in Swift.
A sample project showcasing the problem can be found here: https://github.com/flovouin/ASDK-ASImageCacheProtocolBridge
The problem is that `clearFetchedImageFromCacheWithURL` is sometimes called with a `nil` URL when it shouldn't.
So I double checked all the calls to `ASImageCacheProtocol` and `ASImageDownloaderProtocol` in the ASDK codebase and came up with the following PR.
- The first commit ensures that the image nodes never call the image protocols methods with a `nil` URL / identifier when they shouldn't. The only place where I am not entirely sure whether the URL can be `nil` is in the …
=> [ASImageProtocols] Fix nullables to avoid bridging crashes

Source/ASCollectionNode+Beta.h, Source/ASCollectionNode.mm
Although we may not want to support this property long-term, there are some usages of it
that are difficult to avoid. Specifically because the complexity it adds is both low,
and contained to a small area of the code that would be easy to remove it, it would be
great to support this.
The usage relates to apps that require the Interop protocol, and are architected to expect
a few methods / protocols being implemented on the UICollectionView class itself. It does
not directly override ASCollectionView behaviors. So hypothetically, it would also work
if it were possible to set ASCollectionView's superclass.
Instead, the app is making its own subclass descend from ASCollectionView and use the interop
APIs, even in environments where there are no ASCellNodes ever returned.
=> [ASCollectionNode] Add .collectionViewClass to ASCollectionNode+Beta.

Source/ASTextNode.mm
Current issue:
1) Set `attributedText` in `ASTextNode` with whiteColor
2) `_composedTruncationText` gets updated to take on this new color attribute
3) Set the `attributedText` with greenColor
4) The `_composedTruncationText` gets updated with the new attributes, but does NOT overwrite any existing attributes — i.e., does not overwrite the white color with green. Comment from `_locked_prepareTruncationStringForDrawing:`:
```
// Add any of the original string's attributes to the truncation string,
// but don't overwrite any of the truncation string's attributes
```
=> [ASTextNode] Reset _composedTruncationText when attributedText is updated

Source/ASTextNode.mm
- `_locked_composedTruncationText` is a lazy getter for the ivar `_composedTruncationText`
- When it changes, call `_invalidateTruncationText`
- Never access `_composedTruncationText` ivar directly.
=> Simplify composedTruncationText Logic

Source/ASCollectionView.mm, Source/ASTableView.mm, Tests/ASTableViewTests.mm
- Currently, there is a gap between the moment UICollectionView/UITableView triggers its first data load and when ASDataController finishes processing it. During this gap, the view keeps issuing "initial" loads by calling reloadData and causes its data controller to reload multiple times.
- Fix by immediately forward the first reloadData call to UICollectionView/UITableView before letting its data controller to handle it for real. During the gap, the view thinks that it loaded initial data but is empty, and thus stops triggering initial loads. Once the data controller finished loading, it will call another reloadData on the view which causes the view to swap to a correct state.
=> Avoid multiple initial data loads being issued by UICollectionView/UITableView

Source/ASRunLoopQueue.mm
Just saw this while working on another problem. Little freebie.
=> Tiny: Make the Run Loop Source Context on Stack, Not Heap

Source/ASDisplayNode.mm, Source/ASDisplayNodeExtras.mm, Source/ASRunLoopQueue.h, Source/ASRunLoopQueue.mm
- Save resources when nodes are discarded before being displayed.
- Fixes crashes when table nodes/collection nodes are laid out after their dataSource/delegate are deallocated. We could fix this at a lower level, but this is a good place to do it.
=> Add Support for the Run Loop Queue to be Weak

Source/Details/ASCollectionViewLayoutController.m
Stack-trace:
```
[Thread 0] Fatal Exception: NSInvalidArgumentException
*** -[__NSSetM addObject:]: object cannot be nil
0 CoreFoundation                 6465999288 __exceptionPreprocess + 0
1 libobjc.A.dylib                6443156828 objc_exception_throw + 0
2 CoreFoundation                 6464833564 -[__NSCFString fastestEncoding] + 0
> 3 Pinterest                      4302733028 -[ASCollectionViewLayoutController allElementsForScrolling:rangeMode:displaySet:preloadSet:map:] (ASCollectionViewLayoutController.m:89)
4 Pinterest                      4303028176 -[ASRangeController _updateVisibleNodeIndexPaths] (ASRangeController.mm:255)
5 Pinterest                      4302712760 -[ASCollectionView layoutSubviews] (ASCollectionView.mm:1424)
6 UIKit                          6565268096 …
```
=> Avoid adding nil element which represents an unsupported decoration view

Source/ASDisplayNode.mm
- It's not safe to hold the lock of a supernode and:
- Edit states of its subnodes
- Call subclass hooks
- Run completion block
- Run animation, which can trigger layout passes on subnodes. Especially dangerous if one of them is a collection view because the layout pass can cause a change set update if it's the first pass.
This should fix https://jira.pinadmin.com/browse/BUG-53093
```
[Thread 0] Crashed: com.apple.main-thread
SIGABRT ABORT 0x000000001dc1f89c
0 libsystem_kernel.dylib         499251356  semaphore_wait_trap + 8
1 libdispatch.dylib              498348313  _dispatch_group_wait_slow + 234
> 2 Pinterest                      6453191    -[ASDataController updateWithChangeSet:] (ASDataController.mm:444)
3 Pinterest                      6389189    -[ASCollectionView …
```
=> Fix locking situation of layout transition

AsyncDisplayKit.xcodeproj/project.pbxproj, Source/ASImageNode+AnimatedImage.mm, Source/ASImageNode.mm, Source/ASNetworkImageNode.mm, Source/Private/ASImageNode+AnimatedImagePrivate.h, Source/Private/ASImageNode+Private.h
`ASImageNode`, `ASNetworkImageNode` are pretty important classes where the current locking situation is kind of interesting. This diff tries to cleanup the whole situation a bit. I intentionally didn't refactor the classes too much to remove the noise that would make, especially methods like: `- (void)_lazilyLoadImageIfNecessary`.
This will happening in a follow up diff.
Resolves: #3177
=> [ASNetworkImageNode] Improve locking

ASDKListKit/Podfile, Source/Details/_ASCollectionViewCell.h, Source/Details/_ASCollectionViewCell.m
- Add a category to `_ASCollectionViewCell` that gives it an empty implementation of `bindViewModel:`. We don't need to bind view models because we have cell nodes. 
- Modernize `_ASCollectionViewCell.h` as a ridealong.
- Specify the exact commit of IGListKit in our ASDKListKit project.
=> Add Support for IGListBindingSectionController

Source/ASCollectionNode.h, Source/ASCollectionNode.mm, Source/ASDisplayNode.h, Source/ASDisplayNode.mm, Source/ASScrollNode.mm, Source/ASTableNode.h, Source/ASTableNode.mm, Source/ASTableView.mm, Source/Private/ASDisplayNodeInternal.h, examples/Swift/Sample/TailLoadingCellNode.swift
- Make `init` the designated initializer for `ASDisplayNode`.
- Add `setViewBlock:` and `setLayerBlock:` methods so that subclasses don't have to call `[super initWithNodeBlock:]` since now they are not allowed to.
- In the future we could deprecate `initWithViewBlock:` and `initWithLayerBlock:` since they now just call `setViewBlock:` and since the `didLoad:` argument can be replaced by calling `onDidLoad:` immediately after.
- Breaks anyone who calls `[super initWithViewBlock:]` but they can easily just replace with `[super init]; [self setViewBlock:]`.
=> Fix the Initialization Hierarchy

Source/ASCollectionNode.mm, Source/ASTableNode.mm, Source/Details/ASDataController.h, Source/Details/ASDataController.mm, Source/Details/ASTraitCollection.h, Tests/ASCollectionViewTests.mm
- Currently, when there is a new trait collection, we correctly propagate it to all visible elements. However, since the propagating block is executed on main thread immediately without waiting for the background editing queue of `ASDataController`, not all elements are updated.
- Then to fix that, we updated ASDataController to handle these changes inside `updateWithChangeSet` (#3200). This works, but it doesn’t address the underlying issue.
- We now delegate the propagating task to `ASDataController` which schedule a block to its main serial queue after waiting for its background editing queue.
- Unit test included.
=> [Trait collection] Correctly handle changes that occur mid-updates

Source/ASCollectionView.mm, Source/ASTableView.mm, Source/Details/ASDataController.mm, Source/Private/_ASHierarchyChangeSet.h, Source/Private/_ASHierarchyChangeSet.mm
Also, I took this opportunity to reorganize `_ASHierarchyChangeSet.h`.
=> ASDataController can bail early if a change set is empty

Source/ASSectionController.h, Source/ASSupplementaryNodeSource.h
Currently these headers refer to types that they don't define.
=> Improve the Headers for ASSectionController and ASSupplementaryNodeSource

ASDKListKit/Podfile, Source/AsyncDisplayKit-Prefix.pch, Source/IGListAdapter+AsyncDisplayKit.m, Source/Private/ASIGListAdapterBasedDataSource.m
In IGListKit <=2.1, you have to use IGListCollectionView. In later versions, you can just use plain UICollectionView 🙌 . This diff lets us support both cases pretty cleanly.
=> Add Support for IGListKit > 2.1, Without IGListCollectionView

Source/ASNetworkImageNode.mm
`_setImage` is intended to call the super version of the method,
however with the adoption of the new `_locked_ prefix`, ASImageNode's
implementation would call back into ASNetworkImageNode's implementation.
This restore the intent of the `_setImage` method.
=> _setImage wasn't calling correct implementation

Source/Base/ASAvailability.h, Source/Details/ASObjectDescriptionHelpers.m, Source/Details/ASTraitCollection.h, Source/Details/ASTraitCollection.m, Source/Details/NSIndexSet+ASHelpers.m, Source/Layout/ASDimension.mm, Source/Layout/ASLayoutElement.h, Source/Layout/ASLayoutElementExtensibility.h, Source/Layout/ASLayoutElementPrivate.h, Source/Layout/ASLayoutSpec+Subclasses.mm, Source/Layout/ASLayoutSpec.mm, Source/Private/ASInternalHelpers.h, Source/Private/ASInternalHelpers.m, Source/Private/Layout/ASLayoutSpecPrivate.h
This is causing #3244 to fail because TARGET_OS_IPHONE isn't defined when running unit tests, and rather than fix that let's remove this and focus on iOS.
=> Remove macOS Support

AsyncDisplayKit.podspec, BUCK, Source/ASCollectionView.mm, Source/ASDisplayNode+Beta.h, Source/ASDisplayNode+Yoga.mm, Source/ASMultiplexImageNode.mm, Source/ASTableView.mm, Source/ASViewController.mm, Source/AsyncDisplayKit-Prefix.pch, Source/AsyncDisplayKit.h, Source/Base/ASAvailability.h, Source/Base/ASBaseDefines.h, Source/Base/ASLog.h, Source/Details/ASObjectDescriptionHelpers.m, Source/Details/ASPhotosFrameworkImageRequest.m, Source/Details/ASTraitCollection.h, Source/Details/NSIndexSet+ASHelpers.m, Source/Layout/ASInsetLayoutSpec.h, Source/Layout/ASLayoutElement.h, Source/Layout/ASLayoutElementPrivate.h, Source/Layout/ASLayoutSpec.mm, Source/Private/Layout/ASLayoutSpecPrivate.h
We are seeing a build warning when using the IGListKit Subspec (which explicitly defines `IG_LIST_KIT` in the podspec) because that causes the `#ifndef` in the prefix header to skip defining the `IG_LIST_COLLECTION_VIEW` macro.
While I'm at it fixing that, I think we should go ahead and standardize that we always define these flags internally, by looking at which headers are available when building AsyncDisplayKit.
This diff:
- Removes the explicit define from the podspec and BUCK files.
- Removes the `#ifndef` from the prefix header.
At the end of the day, if those headers aren't available (`__has_include` would evaluate to false) then the build isn't going to work no matter what you manually define.
=> Standardize Dependency Flags for PINRemoteImage, IGListKit

Source/ASCollectionView.mm, Source/ASTableView.mm, Source/Details/ASDelegateProxy.m
This resolves issue #3056.
Some times the batch fetch is not fired, even though it is `true` on `func shouldBatchFetch(for collectionView: ASCollectionView) -> Bool`.
I noticed that this is happening because `_deceleratingVelocity` is not reset. So I made the changes based on what @Adlai-Holler said and now it is working.
=> Fix failing batch fetch in some cases.

AsyncDisplayKit.podspec, Source/ASNetworkImageNode.mm, Source/Details/ASImageProtocols.h, Source/Details/ASPINRemoteImageDownloader.m
Adds resume support support for image downloads that have exited preload range (only on ASNetworkImageNode currently).
=> Add download resume support

Source/ASDisplayNode.h
Really small fix, but the argument was stated to be `viewBlock` when it's for `layerBlock` and it was causing a warning.
=> Fix incorrect argument label in function comment

Source/Base/ASAssert.h, Source/Details/ASThread.h
Fix below warning:
> /Users/engineering/jenkins_root/workspace/AsyncDisplayKit-PRs/Source/Base/ASAssert.h:69:5: 'CHECK_LOCKING_SAFETY' is not defined, evaluates to 0 [-Wundef]
=> [ASThread] Move thread ownership assertion to ASThread

Source/ASCollectionNode.mm, Source/ASDisplayNode.h, Source/ASDisplayNode.mm, Source/ASTableNode.mm, Source/Details/UIView+ASConvenience.h, Source/Details/_ASCollectionViewCell.m, Source/Private/ASDisplayNode+UIViewBridge.mm, Source/Private/_ASPendingState.mm
This ensures all subnodes have the correct size to preload their content. This is important for image nodes, as well as collection and table nodes.
For collection node, we can take a step further by telling it load initial data during preload state. Without doing this, the node often loads when it enters display state which is too late. And its cells can't even start prefetching before the loading finishes. [Here](https://www.dropbox.com/s/neqp2juv9l2zi7z/Pin-to-pin%20swiping.mp4?dl=0) is a video on pin-to-pin swiping before (left) and after (right) this diff.
Since ASDisplayNode currently doesn't have a `layoutIfNeeded` implementation, I'd have to allocate its view/layer (or call `__layout` directly) in order to trigger a layout pass. Instead, I went ahead and implement the method. It's …
=> [ASDisplayNode] Trigger a layout pass whenever a node enters preload state
