- AsyncDisplayKit/ASTextNode.mm
- AsyncDisplayKit/Details/ASTextNodeRenderer.h
- AsyncDisplayKit/Details/ASTextNodeRenderer.mm
> Safe calls in ASTextNodeRenderer

- AsyncDisplayKit/ASNetworkImageNode.mm
> Dispatch lazy image downloaders to another thread

- AsyncDisplayKit/ASDisplayNode.mm
> Dispatch main screen scale to main once and only once

- AsyncDisplayKit/ASMultiplexImageNode.mm
- AsyncDisplayKitTests/ASMultiplexImageNodeTests.m
- examples/Multiplex/Sample/ViewController.m
> Only download images when multiplex node is displayed

- AsyncDisplayKit/ASDisplayNode.mm
Only show a placeholder if there is a place that needs holding
fixes #213
> Actual place holding

- AsyncDisplayKit/ASTextNode.mm
> Removed unintentional conversion.

- AsyncDisplayKit/ASMultiplexImageNode.h
> ASMultiplexImageNode designated initializer

- AsyncDisplayKit/ASCollectionView.mm
- AsyncDisplayKit/ASTableView.mm
- AsyncDisplayKit/Details/ASDataController.h
- AsyncDisplayKit/Details/ASDataController.mm
- AsyncDisplayKit/Details/ASRangeController.h
- AsyncDisplayKit/Details/ASRangeController.mm
Not for 1.1 release.
Add batch update and animation support for UITableView.
> Batch animation

- AsyncDisplayKit/ASCollectionView.mm
- AsyncDisplayKit/ASTableView.mm
> Default proxy object for ASTableView and ASCollectionView

- AsyncDisplayKit/Details/ASRangeController.mm
"did" should be "will" in a couple of places
> Fix ASRangeController's delegate method invocations

- AsyncDisplayKit/ASNetworkImageNode.mm
Fixes #239.  (Thanks @rnystrom!)
> Fix strong ASNetworkImageNodeDelegate reference.

- AsyncDisplayKit/ASTableView.mm
- AsyncDisplayKit/Details/ASFlowLayoutController.mm
Cleaning up some inconsistencies that I found whilst digging.
> Code format cleanup

- AsyncDisplayKit.xcodeproj/project.pbxproj
- AsyncDisplayKit/ASScrollNode.h
- AsyncDisplayKit/ASScrollNode.mm
- AsyncDisplayKit/AsyncDisplayKit.h
Closes #99.  This is a quick sketch -- room for improvement includes
considering a less-questionable class name, potentially exposing
additional UIScrollView functionality directly on the node, and using it
in a sample project.
> Simple UIScrollView wrapper node.

- AsyncDisplayKit.xcodeproj/project.pbxproj
- AsyncDisplayKit/ASDisplayNode.h
- AsyncDisplayKit/ASDisplayNode.mm
- AsyncDisplayKit/ASScrollNode.m
- examples/EditableText/Sample/ViewController.m
- examples/Multiplex/Sample/ViewController.m
- examples/Placeholders/Sample/ViewController.m
* Switch ASScrollNode to block initialiser syntax.
* -[UIView addSubnode:], -[CALayer addSubnode:].
> Miscellanea

- AsyncDisplayKit/ASImageNode.h
- AsyncDisplayKit/ASImageNode.mm
Quick addition to render tinted images for buttons and other UI components.
> Add image modification block to render template images w/ tint.

- AsyncDisplayKit/ASImageNode.mm
> Respect opacity of ASImageNode

- AsyncDisplayKit/ASCollectionView.mm
- AsyncDisplayKit/ASTableView.mm
- AsyncDisplayKit/Details/ASDataController.h
- AsyncDisplayKit/Details/ASDataController.mm
- AsyncDisplayKit/Details/ASRangeController.h
- AsyncDisplayKit/Details/ASRangeController.mm
Fix group updates/animation:
1) the group updates need to be done in single run loop: (fix it by set the pending blocks in the ASDataController)
2) Add performBatchUpdates into the ASCollectionView, and tested it with insertion and deletion in groups
> Fix group updates/animation

- AsyncDisplayKit/ASTextNode.mm
> Allow touches and long press on ASTextNode

- AsyncDisplayKit/Details/ASMultidimensionalArrayUtils.mm
Add assertion per the request in https://github.com/facebook/AsyncDisplayKit/issues/242
> Add assertion to avoid inserting elements that is out of range

- AsyncDisplayKit/ASCollectionView.h
- AsyncDisplayKit/ASCollectionView.mm
- AsyncDisplayKit/ASTableView.h
- AsyncDisplayKit/ASTableView.mm
- AsyncDisplayKit/Details/ASDataController.h
- AsyncDisplayKit/Details/ASDataController.mm
- examples/ASCollectionView/Sample/ViewController.m
- examples/Kittens/Sample/ViewController.m
Add "collectionViewLockDataSourceForDataUpdating" and "collectionViewUnlockDataSourceForDataUpdating" for enable data fetching from background thread.
> Move ASTableView & ASCollectionView data fetching to background thread

- AsyncDisplayKit/ASCollectionView.mm
> Fix wrong assertion

- AsyncDisplayKit/ASDisplayNode.h
- AsyncDisplayKit/ASDisplayNode.mm
- AsyncDisplayKit/Private/ASDisplayNodeInternal.h
- examples/Placeholders/Sample/SlowpokeImageNode.m
> Change placeholder boolean to time interval

- AsyncDisplayKit/ASCollectionView.h
- AsyncDisplayKit/ASCollectionView.mm
- AsyncDisplayKit/ASTableView.h
- AsyncDisplayKit/ASTableView.mm
> Make data locking API optional

- AsyncDisplayKit/ASDisplayNode.h
- AsyncDisplayKit/ASDisplayNode.mm
- AsyncDisplayKit/Details/ASRangeHandlerPreload.mm
> Range handlers use recursive actions

- AsyncDisplayKit.xcodeproj/project.pbxproj
- AsyncDisplayKit/ASNetworkImageNode.mm
- AsyncDisplayKit/Details/ASBasicImageDownloader.mm
- AsyncDisplayKit/Details/ASImageProtocols.h
- AsyncDisplayKit/Private/ASBasicImageDownloaderInternal.h
- AsyncDisplayKitTests/ASBasicImageDownloaderContextTests.m
> Thread safe creation and canceling of download tasks

- AsyncDisplayKit/ASImageNode.mm
Regarding tint, it actually seems like the only place we tint the image during display is [here](https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASImageNode.mm#L229) so we can actually only tint greyscale. Should we assert having a tint and a stretchable image as well if its only greyscale?
fixes #374
> Stretchy or mod block images

- AsyncDisplayKit/ASCellNode.h
- AsyncDisplayKit/ASCellNode.m
- AsyncDisplayKit/ASDisplayNode.mm
- AsyncDisplayKit/ASEditableTextNode.mm
- AsyncDisplayKit/ASImageNode.mm
- AsyncDisplayKit/ASTextNode.mm
- AsyncDisplayKit/Details/_ASDisplayView.h
- AsyncDisplayKit/Details/_ASDisplayView.mm
> Forward touches to super instead of the superview

- AsyncDisplayKit/ASDisplayNode.mm
Fixes #460, as discussed in #407.
> Create pending nodes set lazily

- AsyncDisplayKit/Private/ASDisplayNode+UIViewBridge.mm
Thanks @victormayorov for finding an issue in this code.  Here's a refactoring that reads more cleanly.  Does it still look correct?
> Clean up logic in setFrame: for clarity and compactness

- AsyncDisplayKit.xcodeproj/project.pbxproj
- AsyncDisplayKit/ASCollectionView.h
- AsyncDisplayKit/ASCollectionView.mm
- AsyncDisplayKit/Details/ASScrollDirection.h
- AsyncDisplayKit/Details/ASScrollDirection.m
- AsyncDisplayKit/Details/UICollectionViewLayout+ASConvenience.h
- AsyncDisplayKit/Details/UICollectionViewLayout+ASConvenience.m
Exposes ASCollectionView's ability to determine scroll direction. Scroll direction detection can now support 2-axis collection view layouts. ASCollectionView can now determine scrollable axes.
> ASCollectionView scrollDirection and scrollableDirections

- AsyncDisplayKit.xcodeproj/project.pbxproj
- AsyncDisplayKit.xcodeproj/xcshareddata/xcschemes/AsyncDisplayKit-iOS.xcscheme
- AsyncDisplayKit/AsyncDisplayKit-iOS.h
- AsyncDisplayKit/Info.plist
This PR adds a separate framework target so AsyncDisplayKit can be used with [Carthage](https://github.com/Carthage/Carthage)
> Added iOS framework target for Carthage support

- AsyncDisplayKit/ASCollectionView.mm
- AsyncDisplayKit/ASTableView.mm
- AsyncDisplayKit/Details/ASDataController.h
- AsyncDisplayKit/Details/ASDataController.mm
- AsyncDisplayKit/Details/ASRangeController.h
- AsyncDisplayKit/Details/ASRangeController.mm
Passes tests, optimizes respondsToSelector checks, etc.
> Clean up ASDataController for readability & API naming consistency.

- AsyncDisplayKit/Details/ASDataController.mm
Previously, methods like _insertNodes(...) were actually primarily responsible for initiating layout calculations, etc.  Methods are now grouped according to whether they represent external API entry points or are internal-only.
> Clean up organization and naming of methods internal to ASDataController.

- examples/ASTableViewStressTest/Sample/Info.plist
> Update the identifier that AsyncDisplayKit uses to label its internal queues.

- AsyncDisplayKit/ASCollectionView.h
- AsyncDisplayKit/ASControlNode.h
- AsyncDisplayKit/ASDisplayNode+Subclasses.h
- AsyncDisplayKit/ASDisplayNode.h
- AsyncDisplayKit/ASEditableTextNode.h
- AsyncDisplayKit/ASMultiplexImageNode.h
- AsyncDisplayKit/ASNetworkImageNode.h
- AsyncDisplayKit/ASTableView.h
- AsyncDisplayKit/Details/ASDataController.h
- AsyncDisplayKit/Details/ASRangeController.h
> Fix some appledoc warnings

- AsyncDisplayKit/ASCollectionView.h
- AsyncDisplayKit/ASDisplayNode.h
- AsyncDisplayKit/ASTableView.h
- AsyncDisplayKit/Layout/ASCenterLayoutSpec.h
- AsyncDisplayKit/Layout/ASDimension.h
- AsyncDisplayKit/Layout/ASLayout.h
- AsyncDisplayKit/Layout/ASLayoutable.h
- AsyncDisplayKit/Layout/ASStackLayoutDefines.h
- AsyncDisplayKit/Layout/ASStackLayoutSpec.h
- AsyncDisplayKit/Layout/ASStaticLayoutSpec.h
- docs/build.sh
> Fix all remaining docblocks

- Podfile.lock
> Update Podfile.lock to match earlier changes to Podfile.

- AsyncDisplayKit/ASDisplayNode.mm
Context of the current implementation can be found [here](https://github.com/facebook/AsyncDisplayKit/pull/594#discussion_r36050170).
Since the origin is computed from the node's bounds size, anchorPoint and position properties (see [frame setter](https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/Private/ASDisplayNode%2BUIViewBridge.mm#L131)), if the position is not adjusted, the node will have a wrong origin within its superview:
> When relayout a node, preserve its frame origin

- AsyncDisplayKit.xcodeproj/project.pbxproj
- examples/ASCollectionView/Sample.xcodeproj/project.pbxproj
- examples/ASTableViewStressTest/Sample.xcodeproj/project.pbxproj
- examples/EditableText/Sample.xcodeproj/project.pbxproj
- examples/HorizontalWithinVerticalScrolling/Sample.xcodeproj/project.pbxproj
- examples/Kittens/Sample.xcodeproj/project.pbxproj
- examples/Multiplex/Sample.xcodeproj/project.pbxproj
- examples/Placeholders/Sample.xcodeproj/project.pbxproj
- examples/Swift/Sample.xcodeproj/project.pbxproj
- smoke-tests/Life Without CocoaPods/Life Without CocoaPods.xcodeproj/project.pbxproj
Excited to start working with this framework!
> Update project indentation settings

- AsyncDisplayKit/Layout/ASLayoutOptions.h
- AsyncDisplayKit/Layout/ASLayoutOptions.mm
- AsyncDisplayKit/Layout/ASLayoutSpec.mm
I thought I already did this. I think copyFrom is a better name.
> Changed copyIntoOptions to copyFromOptions

- AsyncDisplayKit/ASCellNode.h
EDIT: The evilest pull request!
> Clarify ASCellNode docs

- .travis.yml
- AsyncDisplayKit.podspec
> Update Podspec to support Cocoapods 0.38.x

- AsyncDisplayKit/ASTableView.h
- AsyncDisplayKit/ASTableView.mm
- AsyncDisplayKit/Details/ASDataController.h
- AsyncDisplayKit/Details/ASDataController.mm
- AsyncDisplayKitTests/ASTableViewTests.m
This adds a method called indexPathForNode: to ASTableView
> Add a indexPathForNode: to ASTableView

- .travis.yml
This reverts commit 5ecc3798ad1ec73750a434405604667bfc32e9ac.
> Restoring 0.38.2 - Revert "Revert "Update Travis' Cocoapods version to 0.38.2""

- AsyncDisplayKit/ASDisplayNode.mm
- AsyncDisplayKit/Private/ASDisplayNode+UIViewBridge.mm
[Here](https://github.com/facebook/AsyncDisplayKit/pull/631/files#r38378312) is the motivation for this PR.
@garrettmoon Please also give feedback on this diff. Thanks!
> Use getters and setters while adjusting position of a node

- AsyncDisplayKit/Layout/ASLayoutOptions.mm
> wasn't copying alignSelf

- AsyncDisplayKit/ASEditableTextNode.mm
- AsyncDisplayKit/ASImageNode.mm
- AsyncDisplayKit/ASNetworkImageNode.mm
- AsyncDisplayKit/ASTextNode.mm
- AsyncDisplayKit/Details/ASTextNodeCoreTextAdditions.m
> More public API fast pathing

- AsyncDisplayKit/ASDisplayNode.mm
- AsyncDisplayKit/Private/ASDisplayNode+UIViewBridge.mm
- AsyncDisplayKit/Private/ASDisplayNodeInternal.h
> Use bounds and position to layout subnodes

- AsyncDisplayKit/ASDisplayNode.mm
> Clean up #723

- AsyncDisplayKit/ASCollectionView.mm
- AsyncDisplayKit/ASTableView.mm
This reverts commit 77745c55b084c51d57a405073a6e9b00c379f918.
Bug was found / reported in https://github.com/facebook/AsyncDisplayKit/issues/721
Attempting resolution here, but need to fix for current clients now:
https://github.com/facebook/AsyncDisplayKit/pull/724
> Revert "Properly support operating with nil asyncDelegate for Table & Collection."

- AsyncDisplayKit.xcodeproj/project.pbxproj
- AsyncDisplayKit/ASDisplayNode.h
- AsyncDisplayKit/ASDisplayNode.mm
- AsyncDisplayKit/Details/ASCollectionViewFlowLayoutInspector.m
- AsyncDisplayKit/Details/UIView+ASConvenience.h
- AsyncDisplayKit/Details/UIView+ASConvenience.m
- AsyncDisplayKit/Private/ASDisplayNode+UIViewBridge.mm
- AsyncDisplayKit/Private/_ASPendingState.m
- AsyncDisplayKitTests/ASDisplayNodeAppearanceTests.m
- AsyncDisplayKitTests/ASDisplayNodeTests.m
Unfortunately this is causing tests to fail on master, 100% of the time.  It's a bit of a weird issue and sadly I don't have time to debug it...sorry for reverting the entire stack!
> Revert "Make ASDisplayNode.name Thread Safe"

- AsyncDisplayKit/ASCellNode.m
- AsyncDisplayKit/ASCollectionView.h
- AsyncDisplayKit/ASCollectionView.mm
- AsyncDisplayKit/ASDisplayNode.h
- AsyncDisplayKit/ASTableView.h
- AsyncDisplayKit/ASTableView.mm
- examples/Kittens/Sample/KittenNode.mm
- examples/Kittens/Sample/ViewController.m
> Add relayout item/row APIs to ASTableView and ASCollectionView

- AsyncDisplayKit/Private/_ASPendingState.m
> release any CGColor's set while the node is in a pending state

- AsyncDisplayKit/ASViewController.h
- AsyncDisplayKit/ASViewController.m
This is a more tame solution to #780.
> Expose ASViewController's constrained size for subclass customization

- AsyncDisplayKit.xcodeproj/project.pbxproj
- AsyncDisplayKit/ASTableNode.h
- AsyncDisplayKit/ASTableNode.m
Should I have another initializer that drops the asyncDataFetching arg?
> Add a ASTableNode class, similar to ASCollectionNode

- AsyncDisplayKit.xcodeproj/project.pbxproj
- AsyncDisplayKit/AsyncDisplayKit.h
Carthage wouldn't be able to detect it
> ASTableNode wasn't exposed publicly.

- AsyncDisplayKit/ASCollectionView.mm
- AsyncDisplayKit/ASTableView.mm
- examples/ASCollectionView/Sample.xcodeproj/project.pbxproj
- examples/ASCollectionView/Sample/ItemNode.h
- examples/ASCollectionView/Sample/ItemNode.m
- examples/ASCollectionView/Sample/ViewController.m
- examples/Kittens/Sample/KittenNode.mm
Seems like some of the state wasn't being correctly passed through to the ASCellNode on cell population.
Fixes #807
> Fix selection inconsistency in ASTableView/ASCollectionView cell implementation

- AsyncDisplayKit/ASMultiplexImageNode.mm
> Cleanup PR 894

- index.html
Branch gh-pages is not updated automatically. So I manually regenerate the site.
> Update video links in gh-pages

- AsyncDisplayKit/ASCollectionView.mm
- AsyncDisplayKit/ASTableView.mm
- AsyncDisplayKit/Details/ASDataController.mm
- examples/ASTableViewStressTest/Sample.xcodeproj/project.pbxproj
This fixes #854.  Thanks for the detailed information in your report, @smyrgl - it was essential for me to be able to figure out this issue quickly and clearly.  visibleNodes I believe was added quite recently, and it looks like not quite finished - it's critical that this be bulletproof in its implementation.
> [ASDataController] Ensure an empty array is returned if visibleNodes is called before any nodes are complete.

- AsyncDisplayKit/ASDisplayNode.mm
- AsyncDisplayKit/Layout/ASLayout.mm
An attempt at doing https://github.com/facebook/AsyncDisplayKit/pull/937 in ASLayout
> Enforce pixels bounds for ASLayout size/position

- AsyncDisplayKit/ASDisplayNode.mm
This is a fix for https://github.com/facebook/AsyncDisplayKit/issues/928
Thanks for the report, and especially the test project, @1nput0utput  - this otherwise would have gone unnoticed for quite some time and would have been very difficult for me to fix without the test project.
> Ensure that .hierarchyState is propogated to new subnodes early enough for us to reference it as the views are added.

- AsyncDisplayKit/ASTextNode.mm
- AsyncDisplayKit/Private/ASDisplayNode+UIViewBridge.mm
- AsyncDisplayKit/Private/ASInternalHelpers.h
- AsyncDisplayKit/Private/ASInternalHelpers.mm
- AsyncDisplayKit/Private/_ASCoreAnimationExtras.mm
- AsyncDisplayKit/TextKit/ASTextKitRenderer.mm
Optimizations for ASTextNode handling of renderer allocation and deallocation.
Optimizations for ASDisplayNode handling of bridged property "contentMode", especially for layer-backed nodes.
> Optimizations for ASTextNode renderer; Optimizations for ASDisplayNode Bridge.

- AsyncDisplayKit/ASNetworkImageNode.mm
Details discussed in https://github.com/facebook/AsyncDisplayKit/pull/1003.  This PR supercedes that one.
> [ASNetworkImageNode] Improve handling of file URLs for images.

- README.md
This makes it easier to glance at for those who plan to use the project in Swift.
> [Swift] Add Readme code snippet with example usage of an ASDisplayNode.

- AsyncDisplayKit/ASCollectionView.mm
- AsyncDisplayKit/ASPagerNode.h
- AsyncDisplayKit/ASPagerNode.m
- AsyncDisplayKit/Details/ASDelegateProxy.h
- AsyncDisplayKit/Details/ASDelegateProxy.m
- AsyncDisplayKit/Details/ASLayoutRangeType.h
- AsyncDisplayKit/Details/ASRangeController.mm
- examples/VerticalWithinHorizontalScrolling/Sample/GradientTableNode.h
- examples/VerticalWithinHorizontalScrolling/Sample/GradientTableNode.mm
- examples/VerticalWithinHorizontalScrolling/Sample/RandomCoreGraphicsNode.h
- examples/VerticalWithinHorizontalScrolling/Sample/RandomCoreGraphicsNode.m
- examples/VerticalWithinHorizontalScrolling/Sample/ViewController.m
This is a fix for #1011.  @knopp, give it a try when you have a chance!  I think I'll include this in 1.9.4.
> Ensure that ASRangeController immediately removes any deleted nodes from its range state.

- AsyncDisplayKit.xcodeproj/project.pbxproj
- AsyncDisplayKit/ASCollectionNode.mm
- AsyncDisplayKit/ASCollectionView.h
- AsyncDisplayKit/ASCollectionView.mm
- AsyncDisplayKit/Details/ASAbstractLayoutController.mm
- AsyncDisplayKit/Details/ASCollectionInternal.h
- AsyncDisplayKit/Details/ASCollectionInternal.m
- AsyncDisplayKit/Details/ASRangeControllerBeta.mm
- examples/CollectionViewWithViewControllerCells/Sample.xcodeproj/project.pbxproj
- examples/Kittens/Sample.xcodeproj/project.pbxproj
- examples/Multiplex/Sample.xcodeproj/project.pbxproj
- examples/SynchronousKittens/Sample.xcodeproj/project.pbxproj
This is in preparation for a substantial refactor I have coming up, which will move much of the logic out of ASCollectionView and ASTableView into a shared ASDisplayNode superclass that then ASCollectionNode and ASTableNode will inherit from.
> Introduce ASCollectionInternal file and create always-available ASCView -> ASCNode backpointer.

- AsyncDisplayKit/ASButtonNode.h
- AsyncDisplayKit/ASButtonNode.mm
- AsyncDisplayKit/ASControlNode.h
- AsyncDisplayKit/ASControlNode.m
- examples/Multiplex/Sample/ScreenNode.m
following the UIControl design, removed ASButtonState from ASButtonNode and added ASControlState to ASControlNodes, also added a selectedState to all ASControlNodes.
@appleguy @connor
> Replace ASButtonState with ASControlState

- AsyncDisplayKit.xcodeproj/project.pbxproj
- AsyncDisplayKit/Details/ASRangeControllerBeta.mm
- AsyncDisplayKitTestHost/AppDelegate.mm
@knopp - take a look, I think this will resolve #1034.  I don't have a way to test it, as I don't have a reproduction case yet, but this did pass the unit test suite.  Beware: I have not run it with even an example app yet.  I will try it with Pinterest and some example apps tomorrow, and if you're able to try it out with good results, will certainly land it at that stage.
> [ASRangeControllerBeta] Support disjoint ranges between updates (scroll jumps, etc)

- AsyncDisplayKit.xcodeproj/project.pbxproj
- AsyncDisplayKit.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
- AsyncDisplayKit/ASDisplayNode.mm
- AsyncDisplayKit/ASDisplayNodeExtras.h
- AsyncDisplayKit/Details/ASRangeControllerBeta.mm
- AsyncDisplayKit/Details/_ASDisplayLayer.mm
- AsyncDisplayKit/Layout/ASLayoutSpec.mm
- AsyncDisplayKit/Private/ASDisplayNode+UIViewBridge.mm
- AsyncDisplayKit/Private/ASDisplayNodeInternal.h
@knopp - check this out if you are still using the Beta range controller.  To a degree, I hope not as it was indeed at least a bit slower than the old one, although Pinterest toughed it out!  The last two diffs have drastically improved performance, although I'm not sure what the Stable to Beta comparison is yet.
> Substantial optimizations for ASRangeControllerBeta & recursivelySetInterfaceState:.

- AsyncDisplayKit/ASTableView.mm
Nice and easy fix.
Details: #1077 
@appleguy
> [ASTableView] Ensure -[super layoutSubviews] is called before messaging delegate.

- AsyncDisplayKit/ASTableView.mm
@appleguy As discussed in #1078
> [ASTableView] Rename _ASTableViewCellDelegate method.

- AsyncDisplayKit.podspec
- AsyncDisplayKit/ASDisplayNode.h
- AsyncDisplayKit/ASDisplayNode.mm
- AsyncDisplayKit/ASEditableTextNode.mm
- AsyncDisplayKit/ASMapNode.h
- AsyncDisplayKit/ASMapNode.mm
- AsyncDisplayKit/ASMultiplexImageNode.h
- AsyncDisplayKit/ASMultiplexImageNode.mm
- AsyncDisplayKit/ASPagerNode.m
- AsyncDisplayKit/ASTableViewProtocols.h
- AsyncDisplayKit/Details/ASPhotosFrameworkImageRequest.h
- AsyncDisplayKit/Details/ASPhotosFrameworkImageRequest.m
- AsyncDisplayKit/Details/_ASDisplayView.mm
- AsyncDisplayKit/Private/ASDisplayNode+UIViewBridge.mm
- AsyncDisplayKit/Private/_ASPendingState.m
This adds a very small change on top of @aaronschubert0's original PR to make the dynamic framework build.
https://github.com/facebook/AsyncDisplayKit/pull/1059
> [tvOS] Initial changes to support building AsyncDisplayKit for tvOS.

- AsyncDisplayKit/ASImageNode.mm
This is a workaround necessary due to an iOS 9 bug.  I'm not gating it to iOS 9 only so as to
not exaggerate iOS version-specific behavior differences in the framework, since a majority are
on iOS 9 anyway.  If we can confirm the bug is fixed in a later iOS version, then it will be gated.
Issue tracked in greater detail here: https://github.com/facebook/AsyncDisplayKit/issues/1068
> [ASImageNode] @synchronized around UIImage draw to prevent concurrently decoding the same instance.

- AsyncDisplayKit/Details/ASRangeControllerBeta.mm
This also adopts Objective-C generics for the various collections in this class.
> [ASRangeControllerBeta] Utilize NSMutableOrderedSet to ensure visible items are prioritized.

- AsyncDisplayKit/ASCollectionView.mm
- AsyncDisplayKit/ASTableView.mm
- AsyncDisplayKit/Details/ASDataController.h
- AsyncDisplayKit/Details/ASDataController.mm
- AsyncDisplayKit/Details/ASRangeController.h
- AsyncDisplayKit/Details/ASRangeController.mm
- AsyncDisplayKit/Details/ASRangeControllerBeta.mm
Second time need to revert this diff. It's getting awkward haha.
I'm not reverting tests. They should be there anyway.
> Revert reloadData optimizations

- AsyncDisplayKit/ASDisplayNode.h
- AsyncDisplayKit/ASDisplayNode.mm
- AsyncDisplayKit/Details/Transactions/_ASAsyncTransaction.h
- AsyncDisplayKit/Details/Transactions/_ASAsyncTransaction.mm
For some reason it looks much better than NSUInteger and 128 :)
Signed-off-by: Matej Knopp <matej.knopp@gmail.com>
> [_ASAsyncTransaction] make priority a NSInteger with default to 0

- AsyncDisplayKit/ASDisplayNode.h
- AsyncDisplayKit/ASDisplayNode.mm
- AsyncDisplayKit/ASDisplayNodeExtras.h
- AsyncDisplayKit/Private/ASDisplayNodeInternal.h
- AsyncDisplayKitTests/ASDisplayNodeTests.m
Github being down is doing some funky things with this PR. Not all the commits are showing up on the website as I'm writing this. If you're only seeing one commit, this problem is still persistent. There should be about 6 commits in this PR total.
Fixes #844
> Add `setNeedsDataFetch` to trigger in-range `fetchData` calls

- AsyncDisplayKitTests/ASTextNodeTests.m
@appleguy and @yury  I tested it. All Worked! Thanks a lot for that. I try add Unit test check pls. #865
> Added additionalTruncationMessage Unit test

- AsyncDisplayKit.xcodeproj/project.pbxproj
- AsyncDisplayKit/ASVideoNode.h
- AsyncDisplayKit/ASVideoNode.mm
- AsyncDisplayKit/Private/ASDefaultPlayButton.h
- AsyncDisplayKit/Private/ASDefaultPlayButton.m
- examples/VideoTableView/Sample.xcodeproj/project.pbxproj
- examples/Videos/Sample/ViewController.m
•  Fixes format problem for some preview frames
•  Adds default play button when one isn't provied.
Discussion: Should probably add bool for disabling default play button?  It's 2am though so I'll add it laters.
> [ASVideoNode] Bug fix and default play button

- AsyncDisplayKit/ASCollectionView.mm
- AsyncDisplayKit/ASTableView.mm
We were only using the pan gesture's velocity method, which only returns a valid result when the gesture is being tracked. This new implementation identifies the general velocity of the deceleration after touch up and reports the value while the touch is not tracked in the collection/table view's scroll view.
> Observe decelerating scroll velocity for accurate direction reporting

- AsyncDisplayKit.xcodeproj/project.pbxproj
- AsyncDisplayKit/ASVideoNode.h
- AsyncDisplayKit/ASVideoNode.mm
- AsyncDisplayKit/Private/ASDefaultPlayButton.m
- AsyncDisplayKitTests/ASVideoNodeTests.m
- examples/Videos/Sample/ViewController.m
Removed unnecessary clear color and improved comment
> [ASVideoNode] Video muting, tap delegate override, general cleanup

- AsyncDisplayKit/ASCollectionNode.h
- AsyncDisplayKit/ASCollectionNode.mm
- AsyncDisplayKit/ASCollectionView.h
- AsyncDisplayKit/ASCollectionView.mm
- AsyncDisplayKit/ASDisplayNode.mm
- AsyncDisplayKit/ASTableView.h
- AsyncDisplayKit/ASTableView.mm
- AsyncDisplayKit/Details/ASAbstractLayoutController.mm
- AsyncDisplayKit/Details/ASCollectionViewLayoutController.mm
- AsyncDisplayKit/Details/ASFlowLayoutController.mm
- AsyncDisplayKit/Details/ASLayoutController.h
- AsyncDisplayKit/Details/ASLayoutRangeType.h
- AsyncDisplayKit/Details/ASRangeController.h
- AsyncDisplayKit/Details/ASRangeController.mm
- AsyncDisplayKit/Details/ASRangeControllerBeta.mm
- AsyncDisplayKit/Private/ASDisplayNodeInternal.h
Follow up on #1155: When range controller uses minimum mode, it observes to rendering engine and extends to full mode if conditions meet.
> Range controller automatically extends to full mode

- AsyncDisplayKit/ASDisplayNode.mm
Hotfix for some layout issues seen in master by @samhsiung.
> Wrap implicit hierarchy management behind beta feature flag

- AsyncDisplayKit/ASControlNode+Subclasses.h
- AsyncDisplayKit/ASControlNode.m
- AsyncDisplayKit/ASTextNode.mm
Should Address Issue #1145 by introducing a new instance variable _targetAdded that delays setting of self.userInteractionEnabled to viewDidLoad.
> [ASControlNode] optimize init method

- AsyncDisplayKit/ASDisplayNode.mm
- AsyncDisplayKit/ASPagerNode.m
- AsyncDisplayKit/Details/ASAbstractLayoutController.mm
- AsyncDisplayKit/Details/ASLayoutController.h
- AsyncDisplayKit/Details/ASLayoutRangeType.h
- AsyncDisplayKit/Details/ASRangeController.mm
- AsyncDisplayKit/Details/ASRangeControllerBeta.mm
- AsyncDisplayKit/Private/ASDisplayNodeInternal.h
Follow up on #1163
One problem/concern left: Pages are not notified when they fall outside visible range of the hosting pager node. So they don't update their range mode and don't shrink back to minimum one.
> More on range mode and range controller

- AsyncDisplayKit.xcodeproj/project.pbxproj
- AsyncDisplayKit/ASControlNode.mm
Adds locking to ASControlNode class. Addresses issue #330.
> [ASControlNode] Add locking for event dispatch table.

- LICENSE
> Update Copyright License.

- AsyncDisplayKit/Details/ASDataController.mm
@appleguy @rahul-malik @nguyenhuy
> Fix allocatedNodes Subarray to match indexPaths subarray

- AsyncDisplayKit/Details/ASPINRemoteImageDownloader.m
who the hell are these idiots?! -signed, author of PINRemoteImage
> PINRemoteImage 2.0 moved its tag

- AsyncDisplayKit.xcodeproj/project.pbxproj
- AsyncDisplayKit/ASPagerFlowLayout.h
- AsyncDisplayKit/ASPagerFlowLayout.m
- AsyncDisplayKit/ASPagerNode.h
- AsyncDisplayKit/ASPagerNode.m
- AsyncDisplayKit/AsyncDisplayKit.h
Adds a custom UICollectionViewLayout that identifies the centered item upon rotation and updates the contentOffset when the bounds change has completed. The final contentOffset will be centered horizontally.
> [ASPagerNode] Add automatic rotation support

- examples/CatDealsCollectionView/Sample/ItemNode.m
addSubnode self.soldOutOverlay twice
> remove second [self addSubnode:self.soldOutOverlay]

- AsyncDisplayKit/ASCollectionView.mm
- AsyncDisplayKit/ASTableView.mm
- AsyncDisplayKit/Details/ASDataController.mm
- AsyncDisplayKitTests/ASDisplayNodeTests.m
Also addressing some analyzer warnings as well in this commit.
> [ASDataController] Concurrent allocation of ASCellNodes

- AsyncDisplayKit.xcodeproj/project.pbxproj
- AsyncDisplayKit/ASTableView.mm
- AsyncDisplayKit/Details/ASDataController.mm
Reverts facebook/AsyncDisplayKit#1250
> Revert "fix scheduling issue that causes collectionView to not animate"

- AsyncDisplayKit/ASDisplayNode.mm
- AsyncDisplayKit/ASImageNode.mm
- AsyncDisplayKit/Private/ASDisplayNode+UIViewBridge.mm
- AsyncDisplayKit/Private/ASDisplayNodeInternal.h
- AsyncDisplayKit/Private/ASInternalHelpers.h
- AsyncDisplayKit/Private/ASPendingStateController.mm
- AsyncDisplayKit/Private/_ASPendingState.mm
- AsyncDisplayKitTests/ASBridgedPropertiesTests.mm
@appleguy Wow this feels better! Thanks for helping me get the level of quality here up :+1:
> [ASDisplayNode] Post-Review Refinements of Recent No-Affinity UIKit/CA Property Bridging

- AsyncDisplayKit/Private/ASDisplayNode+UIViewBridge.mm
A relatively modest regression from the recent thread affinity patch.
> [ASDisplayNode] Bridge should trigger display when opacity or bg color change.

- AsyncDisplayKit/Private/ASPendingStateController.mm
@appleguy pointed out a pretty common deadlock case here and suggested this solution. I think it's a winner!
> [ASPendingStateController] Relinquish Lock Before Applying Pending States

- AsyncDisplayKit/Details/ASIndexedNodeContext.h
> Follow-up on #1288

- AsyncDisplayKit/Details/ASDataController.mm
- AsyncDisplayKit/Details/ASIndexedNodeContext.h
- AsyncDisplayKit/Details/ASIndexedNodeContext.m
based on @Adlai-Holler comments in #1288
> Performance improvements in ASDataController

- AsyncDisplayKit/ASCollectionView.mm
- AsyncDisplayKit/ASTableView.mm
…llectionView becomes visible or invisible
Adresses issue: #1285
> [ASInterfaceState] Ensure cell visibility is updated if overall Table or Collection becomes invisible.

- AsyncDisplayKit/ASViewController.m
> [ASViewController] Fix crash accessing automaticallyAdjustRangeModeBasedOnViewEvents

- AsyncDisplayKit/ASNetworkImageNode.mm
Destruction of bigger images in ASNetworkImageNode on the main thread can be expensive and can take some time, so we dispatch onto a background queue to actually dealloc.
> [ASNetworkImageNode] Dispatch deallocation of UIImage in clearFetchedData: to background thread

- AsyncDisplayKit/ASDisplayNode.mm
#1311
- Fix thread affinity during implicit hierarchy management of loaded subnodes.
- Small changes.
> Follow-up on 1311

- AsyncDisplayKit/ASDisplayNode.mm
- AsyncDisplayKit/Details/_ASDisplayLayer.mm
- AsyncDisplayKit/Private/ASDisplayNode+UIViewBridge.mm
- AsyncDisplayKit/Private/ASDisplayNodeInternal.h
- Bounds change set directly to _ASDisplayLayer should also be saved to threadSafeBounds
- Remove overkill _usesDisplayView flag
> Fix threadSafeBounds

- AsyncDisplayKit/ASDisplayNode.mm
@appleguy : Putting this up for initial review and profiling. We should determine the correct heuristic and/or batch size for each run loop and ultimately if this is a meaningful change in the framework. Feedback welcome as I'm sure this might require a few iterations before we get a solution we feel is an improvement.
> [ASDisplayNode] Run loop amortization: Scheduling of view creation / hierarchy assembly across run loops for gaps to handle touches

- AsyncDisplayKit/ASDisplayNode.mm
…ore removing
the node from the renderQueue.
> [ASDisplayNode] Transfer node ownership from renderQueue to displayingNodes queue before removing it.

- AsyncDisplayKit.xcodeproj/project.pbxproj
- AsyncDisplayKit/ASDisplayNode.mm
- AsyncDisplayKit/ASRunLoopQueue.h
- AsyncDisplayKit/ASRunLoopQueue.mm
ASRunLoopQueue can process a specified number of items per run loop iteration
via a block based api.
> [ASRunLoopQueue] Refactor the run loop implementation code into a reusable queue abstraction

- AsyncDisplayKit.xcodeproj/project.pbxproj
- AsyncDisplayKit/ASImageNode.mm
- AsyncDisplayKit/AsyncDisplayKit+Debug.h
- AsyncDisplayKit/AsyncDisplayKit+Debug.m
- AsyncDisplayKit/AsyncDisplayKit.h
- shows a red text label overlay on bottom right hand corner of ASImageNodes with pixel scaling factor
- import AsyncDisplayKit+Debug.h and enable using [ASImageNode setEnableImageDebugOverlay]
> [ASImageNode] An ASImageNode debug feature showing pixel scaling amount

- AsyncDisplayKit/ASDisplayNode.mm
Replace recursive methods with ASDisplayNodePerformBlockOnEveryNode function
> [ASDisplayNode] Replace recursive methods with ASDisplayNodePerformBlockOnEveryNode

- AsyncDisplayKit/ASButtonNode.mm
- AsyncDisplayKit/ASControlNode.mm
- AsyncDisplayKit/ASDisplayNode.h
- AsyncDisplayKit/ASDisplayNode.mm
- AsyncDisplayKit/ASEqualityHashHelpers.mm
- AsyncDisplayKit/ASImageNode.h
- AsyncDisplayKit/ASImageNode.mm
- AsyncDisplayKit/ASRunLoopQueue.mm
- AsyncDisplayKit/ASTableView.mm
- AsyncDisplayKit/ASTableViewInternal.h
- AsyncDisplayKit/ASTextNode.mm
- AsyncDisplayKit/ASVideoNode.mm
- AsyncDisplayKit/Details/ASCollectionViewFlowLayoutInspector.m
- AsyncDisplayKit/Details/ASDataController.mm
- AsyncDisplayKit/Details/ASMainSerialQueue.mm
- AsyncDisplayKit/Details/ASRangeController.mm
- AsyncDisplayKit/Details/Transactions/_ASAsyncTransaction.mm
- AsyncDisplayKit/Details/Transactions/_ASAsyncTransactionContainer+Private.h
- AsyncDisplayKit/Details/Transactions/_ASAsyncTransactionContainer.h
- AsyncDisplayKit/Details/UIView+ASConvenience.h
- AsyncDisplayKit/Details/_ASDisplayView.mm
- AsyncDisplayKit/Layout/ASDimension.mm
- AsyncDisplayKit/Private/ASDisplayNodeInternal.h
- AsyncDisplayKit/TextKit/ASTextKitAttributes.h
- Base/ASEqualityHelpers.h
Minor changes. Makes the static analyzer and linter happier.
> [Refactoring] Objective-C 2.0 / Modern syntax for arrays, dictionaries, numbers; logic simplification

- AsyncDisplayKit/ASButtonNode.mm
- AsyncDisplayKit/ASDisplayNode.mm
- AsyncDisplayKit/ASEditableTextNode.mm
- AsyncDisplayKit/ASMapNode.mm
- AsyncDisplayKit/ASMultiplexImageNode.mm
- AsyncDisplayKit/ASTableView.mm
- AsyncDisplayKit/ASTextNode.mm
- AsyncDisplayKit/Details/ASBasicImageDownloader.mm
- AsyncDisplayKit/Details/ASDataController.mm
- AsyncDisplayKit/Layout/ASLayout.mm
- AsyncDisplayKit/Private/ASDisplayNode+AsyncDisplay.mm
- AsyncDisplayKit/TextKit/ASTextKitAttributes.h
> [Refactoring] Redundant function removal; Ternary formatting

- AsyncDisplayKit/ASCollectionViewLayoutFacilitatorProtocol.h
- AsyncDisplayKit/ASDisplayNode.mm
- AsyncDisplayKit/ASMultiplexImageNode.mm
- AsyncDisplayKit/Details/ASCollectionViewFlowLayoutInspector.h
- AsyncDisplayKit/Details/ASDataController+Subclasses.h
- AsyncDisplayKit/Details/ASDataController.h
- AsyncDisplayKit/Details/ASMainSerialQueue.mm
- AsyncDisplayKit/Private/ASInternalHelpers.mm
- AsyncDisplayKit/TextKit/ASTextKitAttributes.h
- AsyncDisplayKitTests/ASTableViewTests.m
- Base/ASAssert.h
Includes fix for https://github.com/facebook/AsyncDisplayKit/issues/681 (cc @Adlai-Holler)
> [AsyncDisplayKit] Adopt #pragma once, remove last remaining dispatch_sync (UIScreen scale).

- AsyncDisplayKit/ASMapNode.mm
@aaronschubert0 would love your review - if you have time!
> [ASMapNode] Reduce number of MapKit calls to -cancel by using the .isLoading property.

- AsyncDisplayKit/ASDisplayNode+Beta.h
- AsyncDisplayKit/ASDisplayNode.mm
- Also make sure a transition isn't invalidated right after it passed the validation test and before it proceeds
> [ASDisplayNode] [Async layout transition] Add method to cancel layout transitions in progress

- AsyncDisplayKit/ASPagerFlowLayout.m
> Fix PagerNode from not loading

- AsyncDisplayKit/TextKit/ASTextKitRenderer.mm
- examples/EditableText/Sample.xcodeproj/project.pbxproj
- examples/EditableText/Sample.xcworkspace/contents.xcworkspacedata
- examples/EditableText/Sample/ViewController.m
This occurred for manually hosted nodes that are lacking the expected call to -measure.
This fixes the scenario described in https://github.com/facebook/AsyncDisplayKit/issues/1295
> [ASTextNode] Fix edge case where text truncator may not run (manually hosted nodes)

- AsyncDisplayKit.xcodeproj/project.pbxproj
- AsyncDisplayKit/ASDisplayNode.mm
- AsyncDisplayKit/Layout/ASDimension.h
- AsyncDisplayKit/Layout/ASLayoutable.mm
- AsyncDisplayKit/Layout/ASLayoutablePrivate.h
- The struct is mapped to ID of the current thread and used by subnodes to decide whether they should proceed measurement.
#1387
> [ASLayoutable] Introduce ASLayoutableContext, thread-local storage for layout passes.

- .travis.yml
Travis needs to switch to 7.3 in order to build with iOS 9.3
> [AsyncDisplayKit] - Fix Travis issues

- AsyncDisplayKit/Details/ASDataController.mm
- Refactor ASDataController layout nodes methods
- Don't crash if dataSource becomes nil while layout is happening
@appleguy @nguyenhuy Could you guys take a look, it should address for now: #1181
> [ASDataController] Refactor ASDataController layout nodes methods

- AsyncDisplayKit/Private/ASDisplayNodeLayoutContext.mm
> Provide a nil check and better typing for node in layout find methods

- README.md
> Update README.md sheilds

- AsyncDisplayKit/Details/_ASDisplayView.mm
- AsyncDisplayKit/Details/_ASDisplayViewAccessiblity.mm
- AsyncDisplayKit/Private/ASDisplayNode+UIViewBridge.mm
Add accessibility support for nodes that are accessibleElements and are self in a layer backed subnode. Furthermore addresses some comments from #1476
> [ASDisplayNode] Add handling layer backed accessibility elements within layer backed nodes

- AsyncDisplayKit/TextKit/ASTextKitRenderer+Positioning.mm
> [ASTextNode] Fix deadlock calling trailingRect

- AsyncDisplayKit/TextKit/ASTextKitContext.mm
Summary: Looks like this isn't being locked when it should be.
Reviewers: ricky, levi, scottg, schneider
Reviewed By: scottg, schneider
Subscribers: jenkins
Differential Revision: https://phabricator.pinadmin.com/D84952
> [ASTextNode] Add locking around NSTextContainer's constrainedSize

- AsyncDisplayKit/Details/ASEnvironment.h
- AsyncDisplayKit/Layout/ASLayoutSpec.h
- AsyncDisplayKit/Layout/ASLayoutSpec.mm
- Added nullable for returning children
- Store default child and children as properties
- Use vector for creating final children
> [ASLayoutSpec] Improvements for ASLayoutSpec's internal implementation of child / children properties.

- AsyncDisplayKit/ASVideoNode.mm
This optimization was removed at some point. This PR brings it back.
> [ASVideoNode] Reuse existing AVPlayer when available

- AsyncDisplayKit/ASDisplayNode.mm
- AsyncDisplayKit/Private/ASDisplayNode+UIViewBridge.mm
- AsyncDisplayKit/Private/ASDisplayNodeInternal.h
- AsyncDisplayKit/Private/_ASPendingState.mm
This is a follow up PR for #1537 that should address all the comments.
> Follow up for ASCollectionNode and ASTableNode background color fix

- AsyncDisplayKit/ASVideoNode.mm
Approved in https://phabricator.pinadmin.com/D86234
> Removing an unnecessary assertion in ASVideoNode

- AsyncDisplayKit/ASDisplayNode+Subclasses.h
- AsyncDisplayKit/ASDisplayNode.h
- AsyncDisplayKit/ASDisplayNode.mm
- AsyncDisplayKitTests/ASDisplayNodeImplicitHierarchyTests.m
> [ASDisplayNode] Add layout spec block follow up

- AsyncDisplayKit/ASNetworkImageNode.mm
Calling _updateProgressImageBlockOnDownloaderIfNeeded should be called without _lock held. We will lock super to read our interface state and it's best to avoid acquiring both locks.
> [ASNetworkImage] Fix deadlock in ASNetworkImageNode

- examples/AnimatedGIF/Podfile
- Should fix warning and issue with #1581
> Specifies beta of PINRemoteImage

- .editorconfig
More infos at: http://editorconfig.org
> [Build / Xcode] Add .editorconfig for coding style

- AsyncDisplayKit/ASMapNode.mm
Just a small thing. I found that if I presented and dismissed VCs with lots of map snapshots they'd get slightly backed up.
> [ASMapNode] Remove Retain Cycle, Cancel Snapshotting on Deallocation

- AsyncDisplayKit/ASMultiplexImageNode.h
- AsyncDisplayKit/ASMultiplexImageNode.mm
- AsyncDisplayKit/ASNetworkImageNode.h
- AsyncDisplayKit/ASNetworkImageNode.mm
Differential Revision: https://phabricator.pinadmin.com/D89742
> Add support for disabling progressive image rendering

- AsyncDisplayKit/ASMultiplexImageNode.h
- AsyncDisplayKit/Details/ASImageProtocols.h
- AsyncDisplayKit/Details/ASPINRemoteImageDownloader.h
- AsyncDisplayKit/Details/ASPINRemoteImageDownloader.m
I snuck in two other small changes.
> [ASPINRemoteImageDownloader] Call Download Progress Handler

- AsyncDisplayKit/ASCollectionView.h
- AsyncDisplayKit/ASPagerNode.h
- AsyncDisplayKit/ASPagerNode.m
- AsyncDisplayKit/Details/ASDelegateProxy.m
- Change ASPagerNodeDataSource -> ASPagerDataSource
- Add ASPagerDelegate
> [ASPagerNode] Fix ASPagerNode data source and delegate inconsistencies

- AsyncDisplayKit/TextKit/ASTextKitRenderer.mm
fixes a crash introduced by https://github.com/facebook/AsyncDisplayKit/pull/1637
> Fixed a crash in ASTextNode that I made

- AsyncDisplayKit/Details/Transactions/_ASAsyncTransactionGroup.m
> [ASAsyncTransactionGroup] Create a new hash table on commit to prevent copy

- AsyncDisplayKit/ASViewController.mm
This reverts commit b34e8d78de20ea11b2b07a24df3b12d2936d1a5e.
In attempting to rebase my visibility patch, I overwrote all of Ricky's
changes to ASViewController. This puts them back in.
> Revert "ASViewController.m -> ASViewController.mm upstream"

- examples/ASDKgram/Sample.xcodeproj/project.pbxproj
This helps running the sample on a device.
> Removed DevelopmentTeam setting in sample

- AsyncDisplayKit/ASDisplayNode.mm
> May as well use the existing visibility function.

- AsyncDisplayKit/ASImageNode.mm
> [ASImageNode] Fix image sometimes appearing with black background or completely disappearing in ASImageNode

- _docs/cell-node.md
- _docs/containers-astablenode.md
- _docs/control-node.md
- _docs/display-node.md
- _docs/layout-engine.md
- _docs/synchronous-concurrency.md
- _docs/text-cell-node.md
- _includes/header.html
- static/main.css
Also tweaked styling for code blocks
> Added docs for control node, cell node, text cell node

- AsyncDisplayKit.podspec
- AsyncDisplayKit/Details/ASPINRemoteImageDownloader.h
- AsyncDisplayKit/Details/ASPINRemoteImageDownloader.m
I `pod lib lint`ed but this will need to be merged to `pod spec lint`
> Missed #def ing out the header I guess?

- AsyncDisplayKit/ASDisplayNode.h
- AsyncDisplayKit/ASDisplayNode.mm
- examples/Videos/Sample/ViewController.h
- examples/Videos/Sample/ViewController.m
This reverts commit 2e384a32e15d34ea8f963dbc4e44aaa297ca019b, reversing
changes made to b8618d3151d9714d24ccfd935b92a99b774442f1.
> Revert "Merge pull request #1673 from maicki/AddAutomaticMeasureBeforeLayout"

- AsyncDisplayKit/ASPagerFlowLayout.h
- AsyncDisplayKit/ASPagerFlowLayout.m
- AsyncDisplayKit/ASPagerNode.h
- AsyncDisplayKit/ASPagerNode.m
- AsyncDisplayKit/Details/ASDelegateProxy.m
- examples/PagerNode/Sample/ViewController.h
- examples/PagerNode/Sample/ViewController.m
Build on top of #1224 and should fix #1169
> [ASPagerNode] Add ASPagerNode rotation support

- AsyncDisplayKit/ASTextNode.mm
Moving the modifier from __unsafe_unretained to __weak for the layer we use for highlighting.
> [ASTextNode] Move modifier to __weak for the highlighted layer

- AsyncDisplayKit/ASNetworkImageNode.mm
> [ASNetworkImage] Fix not handling imageNode:didLoadImage: from ASNetworkImageNodeDelegate as optional

- AsyncDisplayKit/ASImageNode+AnimatedImage.mm
- AsyncDisplayKit/ASImageNode.h
> [ASImageNode] Update default run loop for animated images to CommonModes

- AsyncDisplayKit/ASTableView.h
- AsyncDisplayKit/ASTableView.mm
- AsyncDisplayKitTests/ASTableViewTests.m
Addresses this suggestion: #1242
> [ASTableView] Add constrainedSizeForRowAtIndexPath: to control row heights from delegate

- AsyncDisplayKit.xcodeproj/project.pbxproj
This fixes #1826. Landing immediately.
> [Framework Build] Make NSIndexSet Helpers Framework-Visible

- AsyncDisplayKit.xcodeproj/project.pbxproj
- AsyncDisplayKit/ASDisplayNode+Subclasses.h
- AsyncDisplayKit/ASDisplayNode.mm
Subclasses can override this method to react to a trait collection change
Also added NSIndexSet+ASHelpers to be part of the pod. The example wouldn't build without it.
> [ASDisplayNode] added asyncTraitCollectionDidChange method

- AsyncDisplayKit/Details/ASDataController.mm
This irritates other compilers/settings.
> [ASDataController] Remove Aggregate CGRect Initializer

- AsyncDisplayKit.xcodeproj/project.pbxproj
- AsyncDisplayKit/ASDisplayNodeExtras.mm
- AsyncDisplayKitTests/ASDisplayNodeExtrasTests.m
Collect subnodes passing the test, not the node with the subnodes passing the test.
> [ASDisplayNodeExtras] Collect subnodes passing the test

- AsyncDisplayKit/ASCollectionView.mm
> [ASCollectionView] Add return type to the shouldNotAnimateBlock

- AsyncDisplayKit/ASViewController.mm
> [ASViewController] Fix Modal presented ASViewController don't rotate on iOS 8.3

- AsyncDisplayKit/Details/ASCollectionDataController.mm
> [ASCollectionDataController] Repopulate deleted supplementary nodes if necessary

- AsyncDisplayKit/ASVideoPlayerNode.mm
Fixes these ASVideoNode retain cycles:
Pods/AsyncDisplayKit/AsyncDisplayKit/ASVideoPlayerNode.mm:361: error: RETAIN_CYCLE
Retain cycle involving the following objects:  (1) a block capturing self;  (2) an object of class ASDisplayNode  retaining another object via instance variable _viewBlock,  (3) object self retaining self._scrubberNode,   at line 361, column 3
Pods/AsyncDisplayKit/AsyncDisplayKit/ASVideoPlayerNode.mm:509: error: RETAIN_CYCLE
Retain cycle involving the following objects:  (1) a block capturing self;  (2) an object of class ASDisplayNode  retaining another object via instance variable _viewBlock,  (3) object self retaining self._spinnerNode,   at line 509, column 3
> [ASVideoPlayerNode] Use ASDisplayNode base class lock for subclass property syncrhonization, fix retain cycles

- AsyncDisplayKit/ASVideoNode.h
- AsyncDisplayKit/ASVideoNode.mm
- AsyncDisplayKit/ASVideoPlayerNode.h
- AsyncDisplayKit/ASVideoPlayerNode.mm
Hi guys,
After some discussion on Slack, we decided to add two new properties to the `ASVideoNode`: `videoComposition` and `audioMix`. For those who are not familiar with these properties, they are defined in the AVPlayerItem, and give instruction to the player as how the tracks in the asset should be combined during playback (e.g. cross-fade between video or audio tracks).
With the current implementation of the `ASVideoNode`, it is hard to access the `currentItem` as soon as possible, as the user can't be notified when the `AVPlayerItem` is first constructed. This is solved by commit 16c6698, which introduces a new delegate method in the `ASVideoNodeDelegate`. This way the user can access the `currentItem` as soon as possible, and set the `videoComposition` and `audioMix` properties if …
> [ASVideoNode, ASVideoPlayerNode] Add video composition and audio mix capabilities

- _data/nav_docs.yml
- _docs/automatic-layout-containers.md
- _docs/cell-node.md
- _docs/containers-overview.md
- _docs/corner-rounding.md
- _docs/debug-tool-hit-test-visualization.md
- _docs/faq.md
- _docs/hit-test-slop.md
- _docs/layer-backing.md
- _docs/layout-api-sizing.md
- _docs/node-overview.md
- _docs/placeholder-fade-duration.md
- _docs/subtree-rasterization.md
- _docs/synchronous-concurrency.md
- static/main.css
clean up optimization docs
rearrange sections in nav bar
add layout api sizing Q to FAQ
add corner rounding to Optimizations + check back soon tags for methods to be released in 2.0
add layoutSpecs
Containers overview -> node containers
Node overview -> node subclasses
remove ASTextCellNode
> website refactoring

- examples_extra/Multiplex/Sample/ScreenNode.m
just fix the examples image path of Multiplex
> [Examples] fix image paths in example_extra/Multiplex

- AsyncDisplayKit/ASCellNode.mm
This assertion is failing in some apps and will be enabled soon.
> [ASCellNode] Remove assert in visibleStateDidChange:

- AsyncDisplayKit/ASMapNode.h
- AsyncDisplayKit/ASMapNode.mm
- examples/ASMapNode/Podfile
- examples/ASMapNode/Sample.xcodeproj/project.pbxproj
- examples/ASMapNode/Sample.xcodeproj/xcshareddata/xcschemes/Sample.xcscheme
- examples/ASMapNode/Sample/AppDelegate.h
- examples/ASMapNode/Sample/AppDelegate.m
- examples/ASMapNode/Sample/Assets.xcassets/AppIcon.appiconset/Contents.json
- examples/ASMapNode/Sample/Base.lproj/LaunchScreen.storyboard
- examples/ASMapNode/Sample/Info.plist
- examples/ASMapNode/Sample/MapHandlerNode.h
- examples/ASMapNode/Sample/MapHandlerNode.m
- examples/ASMapNode/Sample/ViewController.h
- examples/ASMapNode/Sample/ViewController.m
- examples/ASMapNode/Sample/main.m
* Toggle user interaction when liveMap changes (#1753)
* Change map snapshot when updating it with a new region (#1754)
* Commented out code that is causing inaccurate behavior, this was wrapped with a FIXME
* Added the ability to zoom in and show annotations, similar to showAnnotations:animated: of MKMapView.
* Added a basic example for ASMapNode to try out the different changes
A minor change: Fixed typo in some comment
> [ASMapNode] bug fixes + added the ability to zoom in on the annotations + example project

- AsyncDisplayKit/ASDisplayNode.h
- AsyncDisplayKit/ASDisplayNode.mm
- examples/Videos/Sample/ViewController.h
- examples/Videos/Sample/ViewController.m
Fix original PR ( #1673 ) that was reverted (#1717)
- Layout should happen with size as large as possible
- Fix wrong logic around layout `_hasDirtyLayout` check
> [ASDisplayNode] Add automatic measurement before layout

- _docs/corner-rounding.md
Not everyone has had the pleasure of working with the notorious @appleguy, so the joke in the intro can be confusing.
> Slight introduction tweak

- AsyncDisplayKit/ASDisplayNode.mm
- AsyncDisplayKit/Details/ASDataController.mm
> [Followup] Small code improvements

- AsyncDisplayKit/ASCollectionView.mm
- AsyncDisplayKit/Details/ASEnvironment.h
This fixes rotation issues @rcancro and I have seen. It is still being tested.
> [ASCollectionView] When Resizing, Invalidate Layout After Remeasuring

- _docs/automatic-layout-examples.md
- _docs/node-overview.md
- _docs/philosophy.md
Fixes broken image links mentioned in #1926
> [AsyncDisplayKit.org] fix broken image links

- AsyncDisplayKit/ASControlNode.mm
- AsyncDisplayKit/ASRunLoopQueue.mm
- AsyncDisplayKit/ASTableView.mm
- AsyncDisplayKit/ASVideoPlayerNode.mm
- AsyncDisplayKit/Details/ASDataController.mm
- AsyncDisplayKit/Details/NSIndexSet+ASHelpers.m
- AsyncDisplayKit/Private/ASInternalHelpers.mm
- AsyncDisplayKit/Private/ASMultidimensionalArrayUtils.mm
- AsyncDisplayKit/TextKit/ASTextKitContext.mm
- inferScript.sh
[bugs.txt](https://github.com/facebook/AsyncDisplayKit/files/367547/bugs.txt)
> [Infer] Fix Infer errors/warnings

- AsyncDisplayKit/ASCollectionView.mm
- AsyncDisplayKit/ASTableView.mm
This fixes the recent regression that came with the range controller PR. Needs review @levi @maicki @appleguy
> [ASCollectionView/ASTableView] Check for Zero-Size Correctly

- AsyncDisplayKit/ASViewController.mm
Follow up fix for #1810 and #1905
> Fixes iOS 7 and iOS 8 wrong size in viewWillAppear: while a a rotation is happening

- AsyncDisplayKit/ASVideoNode.mm
This was a very very rough manual merge, so let's review this before we land it. @maicki @levi
> [Manual Merge] Cherry-Pick #1962 to 6.7

- AsyncDisplayKit/Details/NSIndexSet+ASHelpers.m
> [ASHelpers] Fix compiler warning in as_smallDescription on 32 bit

- AsyncDisplayKit/Layout/ASLayout.mm
> Add description to ASLayout

- AsyncDisplayKit/Layout/ASLayout.h
- AsyncDisplayKit/Layout/ASLayout.mm
Incredibly helpful in debugging a layout tree. I can't believe we've gone this far without this!
> Add recursive description debugging method to ASLayout

- AsyncDisplayKit/Private/ASWeakSet.h
- AsyncDisplayKit/Private/ASWeakSet.m
Supersedes #1957 @appleguy @maicki
> [ASWeakSet] Refactor to Use NSHashTable

- AsyncDisplayKitTests/ASCollectionViewTests.mm
- AsyncDisplayKitTests/ASMultiplexImageNodeTests.m
Use XCTestExpectation for asynchronous test, and remove a test method that doesn't do anything. Review? @maicki @appleguy @levi
> [Tests] Two Minor Cleanups

- AsyncDisplayKit/Private/_ASHierarchyChangeSet.mm
> Fix compiler warnings in _ASHierarchyChangeSet on 32bit

- AsyncDisplayKit/Details/ASChangeSetDataController.mm
> [ASChangeSetDataController] Enable Some Assertions

- AsyncDisplayKit/ASCellNode.h
- AsyncDisplayKit/ASCollectionView.mm
- AsyncDisplayKit/ASDisplayNode.mm
- AsyncDisplayKit/ASTableView.mm
- AsyncDisplayKit/Details/ASCollectionViewFlowLayoutInspector.h
- AsyncDisplayKit/Details/ASImageProtocols.h
@maicki @Adlai-Holler:  @johnepinterest requested that we clean up our analyzer warnings so that Jenkins can run Analyzer builds.
> Fix Xcode 7.3.1 Analyzer Warnings

- AsyncDisplayKit/ASTextNode.mm
Initial PR to open source our internal ASDK patch list from Google Inc.
> Fix ASTextNode truncation string

- AsyncDisplayKit/ASDisplayNode.mm
- AsyncDisplayKit/Details/ASEnvironment.h
- AsyncDisplayKit/Details/ASEnvironment.mm
- AsyncDisplayKit/Private/ASEnvironmentInternal.h
UIUserInterfaceIdiomUnspecified is -1 so we were actually defaulting our trait collection to UIUserInterfaceIdiomPhone (which is 0).
> [ASEnvironmentTraitCollection] default user interface idiom to UIUserInterfaceIdiomUnspecified

- AsyncDisplayKit/Details/ASCollectionViewFlowLayoutInspector.m
…plementary node layout.
Patch from iOS teams at Google Inc.
> [ASCollectionViewFlowLayoutInspector] constrainedSize typo

- AsyncDisplayKit/ASTextNode.mm
…y paragraph style in the attributed string.
Patch from Google Inc.
> [ASTextNode] Fix ascender to include line height specified in attributed string paragraph style 

- AsyncDisplayKitTests/ASSnapshotTestCase.mm
Fixed to recurse through all descendant nodes instead of just the  root node's subnodes
Patch from Google Inc.
> [Testing] Fix recursive displaysAsynchronously

- AsyncDisplayKit/ASDisplayNode.mm
Teeny tiny, resolves ship task 9
> [ASDisplayNode] Assert that User Doesn't Reuse Layout Specs

- AsyncDisplayKit/ASDisplayNode.h
Move NS_ASSUME_NONNULL_END to the end of the ASDisplayNode header
> [ASDisplayNode] Move NS_ASSUME_NONNULL_END to the end of the ASDisplayNode header

- AsyncDisplayKit/Details/ASThread.h
- AsyncDisplayKit/Private/ASLayoutTransition.mm
- AsyncDisplayKit/TextKit/ASTextKitContext.mm
This ensures that the mutex is alive at least for the lifetime of `SharedLocker` / `SharedUnlocker`.
I moved `ASLayoutTransition` to use the new `SharedLocker` as first step.
> [ASThread] Add SharedLocker and SharedUnlocker that uses a shared pointer for the mutex

- AsyncDisplayKit/ASDisplayNode.mm
Confirmed that #2047 fixes #2038 in the general case
> Revert "Fix if pending layout will be deallocated (#2038)"

- examples/ASDKgram/Sample/Utilities.m
Benchmarked RFC 3339 date time string parsing a bit and simple c parsing is around 7-8 times faster than using `NSDateFormatter`.
> [Examples] Parse RFC 3339 date time strings around 7-8 times faster in ASDKGram

- AsyncDisplayKit/ASButtonNode.mm
- AsyncDisplayKit/ASCollectionView.mm
- AsyncDisplayKit/ASDisplayNode+Beta.h
- AsyncDisplayKit/ASDisplayNode.h
- AsyncDisplayKit/ASDisplayNode.mm
- AsyncDisplayKit/ASTableView.mm
- AsyncDisplayKit/Private/ASDisplayNode+UIViewBridge.mm
- AsyncDisplayKit/Private/ASDisplayNodeInternal.h
- AsyncDisplayKit/Private/_ASHierarchyChangeSet.mm
- AsyncDisplayKitTests/ASDisplayNodeImplicitHierarchyTests.m
Will replace #2022 that was accidentally closed.
> [Automatic Hierarchy Management] Rename IHM to automatic hierarchy management and move out of beta header

- AsyncDisplayKit/ASDisplayNode.mm
- AsyncDisplayKit/Details/_ASDisplayView.h
- AsyncDisplayKit/Details/_ASDisplayView.mm
- AsyncDisplayKit/Details/_ASDisplayViewAccessiblity.mm
- Improvements for nodes that position is changing dynamically (like in ASTableView / ASCollectionView)
- Performance improvements calculating accessibility elements
- Add compiler flag: ASDK_ACCESSIBILITY_DISABLE to disable custom accessibility code
> [_ASDisplayViewAccessiblity] Improve accessibility support

- AsyncDisplayKit/ASCellNode.mm
It needs to override the new signatures as well.
> ASCellNode was overriding old deprecated methods

- AsyncDisplayKit/Details/_ASDisplayLayer.mm
- AsyncDisplayKit/Details/_ASDisplayView.mm
Found this while digging around in our drawing/CA integration. May as well yank it out! @maicki @appleguy
> [ASDisplayView] Remove Some Unused Code

- AsyncDisplayKit.xcodeproj/project.pbxproj
This keeps getting turned into (null) in our PRs. The file was removed in d5cbe33
> Remove reference to gone file ASLayoutSpec+Private.h

- AsyncDisplayKit/ASPagerNode.h
- AsyncDisplayKit/ASPagerNode.m
This brings us in line with all the other ASPagerDelegate methods.
> [ASPagerNode] Rename constrainedSizeForNodeAtIndexPath:

- AsyncDisplayKit/Details/ASCollectionDataController.mm
> Avoid Accessing itemCountsFromDataSource Off-Main

- AsyncDisplayKit/ASDisplayNode.mm
see https://github.com/facebook/AsyncDisplayKit/issues/2108
> remove non unicode char

- AsyncDisplayKit/ASImageNode.mm
See https://github.com/facebook/AsyncDisplayKit/issues/2111
> set the right attributes for block properties.

- AsyncDisplayKit/Layout/ASStackLayoutSpec.mm
`self.children` causes the creation of an NSArray, so for vertical stacks, we were creating 4. This cuts us down to 1. Per @maicki in the future we should be even more aggressive but this is a start.
Ready for review @maicki
> [ASStackLayoutSpec] Create Children NSArray Less Often

- AsyncDisplayKit.xcodeproj/project.pbxproj
- AsyncDisplayKitTests/ASDisplayLayerTests.m
- AsyncDisplayKitTests/ASDisplayNodeAppearanceTests.m
- AsyncDisplayKitTests/ASDisplayNodeTests.m
- AsyncDisplayKitTests/ASMultiplexImageNodeTests.m
- AsyncDisplayKitTests/ASUICollectionViewTests.m
- AsyncDisplayKitTests/ASViewControllerTests.m
- AsyncDisplayKitTests/ASWeakMapTests.m
I'm about to start testing the issues we've been having with deallocation, and in order to mimic real conditions in an app I want it to be ARC. So I figured let's get this chore out the way.
Ready for review @maicki @garrettmoon @appleguy @levi
> [Testing] Migrate Unit Tests to ARC

- AsyncDisplayKit.xcodeproj/project.pbxproj
- AsyncDisplayKitTests/ASDisplayNodeLayoutTests.mm
- AsyncDisplayKitTests/ASXCTExtensions.h
In preparation for a fix that is coming to `ASDisplayNode` layout mechanism let's start with having tests for the layout behavior of `ASDisplayNode`
cc @Adlai-Holler @garrettmoon
> [Testing] Add ASDisplayNodeLayoutTests

- AsyncDisplayKit/ASDisplayNode+Beta.h
- AsyncDisplayKit/ASDisplayNode.mm
> [ASDataController] Turn Update Validation Exceptions ON by Default

- AsyncDisplayKit/ASDisplayNode.h
- AsyncDisplayKit/ASDisplayNode.mm
- AsyncDisplayKit/ASDisplayNodeExtras.h
- AsyncDisplayKit/ASMapNode.mm
- AsyncDisplayKit/ASMultiplexImageNode.mm
- AsyncDisplayKit/ASNetworkImageNode.mm
- AsyncDisplayKit/ASPagerNode.m
- AsyncDisplayKit/AsyncDisplayKit+Debug.h
- AsyncDisplayKit/AsyncDisplayKit+Debug.m
- AsyncDisplayKit/Details/ASAbstractLayoutController.mm
- AsyncDisplayKit/Details/ASLayoutRangeType.h
- AsyncDisplayKit/Details/ASRangeController.mm
- AsyncDisplayKitTests/ASCollectionViewTests.mm
- AsyncDisplayKitTests/ASDisplayNodeTests.m
- AsyncDisplayKitTests/ASVideoNodeTests.m
- examples/CatDealsCollectionView/Sample/ViewController.m
This also standardizes on Preload as the name of the range.
> [ASDisplayNode] Add Convenience Interface State Accessors

- AsyncDisplayKit.xcodeproj/project.pbxproj
- AsyncDisplayKit.xcodeproj/xcshareddata/xcschemes/AsyncDisplayKit.xcscheme
- AsyncDisplayKitTests/ASCALayerTests.m
This is just for informational and forensics' sake.
> [Unit Tests] Add Tests for CALayer Behavior

- AsyncDisplayKit/ASTextNode.mm
- AsyncDisplayKit/TextKit/ASTextKitAttributes.h
- AsyncDisplayKit/TextKit/ASTextKitContext.h
- AsyncDisplayKit/TextKit/ASTextKitContext.mm
- AsyncDisplayKit/TextKit/ASTextKitRenderer.mm
- AsyncDisplayKit/TextKit/ASTextKitTailTruncater.mm
- AsyncDisplayKitTests/ASTextKitTruncationTests.mm
> [ASTextNode] Remove Unused Layout Manager Delegate Stuff

- AsyncDisplayKit/Details/Transactions/_ASAsyncTransactionContainer.m
Give us the flexibility to disable it in prod while we figure out a long term strategy.
> [ASAsyncTransactionConatiner] Add preprocessor definition for disabling state changes

- AsyncDisplayKit/ASDisplayNode.mm
To prevent confusion, e.g. #2200
> [Layout API] improve layoutSpecThatFits: assertion message

- AsyncDisplayKit/Details/ASCollectionViewFlowLayoutInspector.m
@maicki Appreciate a quick review here. Thanks!
> [ASCollectionViewFlowLayoutInspector] Fix assertion messages

- AsyncDisplayKitTests/ASDisplayNodeTests.m
We've seen this in Pinterest on rare occasions. @maicki could you take a look at this?
> Add Failing Unit Test for "Layout Should Not Be Nil" Exception

- AsyncDisplayKit/ASDisplayNode.mm
- AsyncDisplayKitTests/ASDisplayNodeLayoutTests.mm
- AsyncDisplayKitTests/ASDisplayNodeTests.m
- Fix measure pass of nodes that are range managed
- Fix measure pass for a node that is mid transition
> [Layout] Automatic measurement on layout fixes

- AsyncDisplayKit.xcodeproj/project.pbxproj
- AsyncDisplayKit/ASCellNode.mm
- AsyncDisplayKit/ASDisplayNode.mm
- AsyncDisplayKit/ASDisplayNodeExtras.h
- AsyncDisplayKit/ASTextNode.mm
- AsyncDisplayKit/Details/_ASDisplayLayer.mm
- AsyncDisplayKit/Details/_ASDisplayView.mm
- AsyncDisplayKit/Layout/ASLayout.mm
- AsyncDisplayKit/Private/ASDisplayNodeInternal.h
- AsyncDisplayKit/Private/ASObjectDescriptionHelpers.h
- AsyncDisplayKit/Private/ASObjectDescriptionHelpers.m
- AsyncDisplayKit/Private/_ASHierarchyChangeSet.mm
I went to debug some issues today and got annoyed with how off-the-mark our object descriptions are.
**Before:** `<ASTextNode 0x7ff7dc841a00 [_ASDisplayView : 0x7ff7dad37620]>`
Very little info, nonstandard format.
**After:** `<ASTextNode: 0x7fcdac01ec00; text = "Lick tail flick jump on the table stretching purr …"; frameInWindow = (106 350.5; 198 210); frame = (106 16; 198 210); cellNode = <KittenNode: 0x7fcdaae3f8c0>; interfaceState = { MeasureLayout | Preload | Display | Visible }; view = <_ASDisplayView: 0x7fcdac83fe80>>`
Way more information, including the frame onscreen, text and the nearest ASCellNode ancestor.
--- 
**Before:** `<KittenNode 0x7ff7dac12350 name = Node for kitten #144 [_ASDisplayView : 0x7ff7dad1c0a0]>`
Very little info, nonstandard format.
**After:** `<KittenNode: …
> [ASDisplayNode] Majorly Improve Descriptions

- AsyncDisplayKit/ASDisplayNode.mm
- AsyncDisplayKit/Private/ASDisplayNodeInternal.h
- AsyncDisplayKit/Private/ASLayoutTransition.mm
- AsyncDisplayKitTests/ASDisplayNodeImplicitHierarchyTests.m
Initial commit to throw an exception if manually adding / removing subnodes if node has automaticallyManagesSubnodes enabled
TODOS:
> [Layout] Throw manually adding / removing subnodes if node / supernode has automaticallySubnodeManagement enabled

- AsyncDisplayKit/ASViewController.mm
I don’t think this `setNeedsLayout` is required since we call `measure` now.
> [ASViewController] fix layout recursion

- AsyncDisplayKit/Details/_ASDisplayView.mm
> [Layout] Use `_addSubnode` / `_removeFromSupernode` methods in _ASDisplayView 2

- AsyncDisplayKit/ASCellNode.h
This documents some unexpected behavior @binl observed, per discussion with @appleguy.
> [ASCellNode] Document Cell Node Event Callback Behavior

- examples/ASDKLayoutTransition/Sample/ViewController.m
- examples/ASDKTube/Sample/Nodes/VideoContentCell.m
- examples/ASMapNode/Sample/MapHandlerNode.m
- examples/ASViewController/Sample/DetailCellNode.m
- examples/ASViewController/Sample/DetailRootNode.m
- examples/AsyncDisplayKitOverview/Sample/Node Containers/OverviewASCollectionNode.m
- examples/AsyncDisplayKitOverview/Sample/Node Containers/OverviewASPagerNode.m
- examples/AsyncDisplayKitOverview/Sample/Node Containers/OverviewASTableNode.m
- examples/AsyncDisplayKitOverview/Sample/OverviewComponentsViewController.m
- examples/CatDealsCollectionView/Sample/ItemNode.m
- examples/CatDealsCollectionView/Sample/LoadingNode.m
- examples/HorizontalWithinVerticalScrolling/Sample/HorizontalScrollCellNode.mm
- examples/Kittens/Sample/KittenNode.mm
- examples/SocialAppLayout/Sample/CommentsNode.m
- examples/SocialAppLayout/Sample/LikesNode.m
- examples/SocialAppLayout/Sample/PostNode.m
- examples/VerticalWithinHorizontalScrolling/Sample/GradientTableNode.mm
- examples/VerticalWithinHorizontalScrolling/Sample/ViewController.m
the example projects are the current cause of our Travis failures
> Fix example projects to use Layout API 2.0 style object

- AsyncDisplayKit.xcodeproj/project.pbxproj
Seen in https://github.com/facebook/AsyncDisplayKit/pull/2295
> Revert Xcode Project file to before Cocoapods or Xcode 8 changes

- AsyncDisplayKit.xcodeproj/project.pbxproj
- AsyncDisplayKit/ASVideoPlayerNode.mm
- AsyncDisplayKit/Layout/ASLayoutable.h
- AsyncDisplayKit/Layout/ASLayoutable.mm
- AsyncDisplayKitTests/ASLayoutableStyleTests.m
- examples/Videos/Sample/ViewController.m
Add a delegate to be able to get property changes.
Furthermore we move the `size` property from `readwrite`to `readonly`
> [Layout] Add delegate to ASLayoutableStyle for property changes

- AsyncDisplayKit/UIImage+ASConvenience.m
I should be enjoying time with my family, but when I see a "freebie" like this I want to get it done so I can stop thinking about it 🤓
- Use `kCGBlendModeCopy` when possible, which should be fairly often.
- Simplify path cache key generation – use `NSValue` instead of the admittedly-excellent `NSNumber` hack.
- Remove `@synchronized` around path cache access. By doing this, it is possible that the same path is generated multiple times on different threads, but it's very unlikely, and not worth adding significant overhead to all cases.
Ready for review @maicki @levi @appleguy @hannahmbanana !
> [UIImageHelpers] Refactor and Optimize Rounded Image Generation

- AsyncDisplayKit/ASCollectionNode.h
- AsyncDisplayKit/ASCollectionView.h
- AsyncDisplayKit/ASEditableTextNode.h
- AsyncDisplayKit/ASImageNode.h
- AsyncDisplayKit/ASMultiplexImageNode.h
- AsyncDisplayKit/ASNetworkImageNode.h
- AsyncDisplayKit/ASPagerNode.h
- AsyncDisplayKit/ASTableView.h
- AsyncDisplayKit/Details/ASBatchContext.h
- AsyncDisplayKit/Details/ASRangeController.h
- AsyncDisplayKit/Private/_ASHierarchyChangeSet.h
@returns is valid too, but this shows up in syntax highlighting.
> [Documentation] @return is recognized by the syntax highlighter.

- AsyncDisplayKit/ASDisplayNode.h
- AsyncDisplayKit/Details/UIView+ASConvenience.h
- AsyncDisplayKit/Private/ASDisplayNode+UIViewBridge.mm
- AsyncDisplayKit/Private/_ASPendingState.mm
- AsyncDisplayKitTests/ASDisplayNodeTests.m
Since we're disabling it in our app, provide easy access for changing the layer's behavior.
Replaces #2310
> [ASDisplayNode] Add allowsGroupOpacity property to ASDisplayNode

- AsyncDisplayKit/ASCollectionView.h
- AsyncDisplayKit/ASCollectionView.mm
- AsyncDisplayKit/ASDisplayNode+Deprecated.h
- AsyncDisplayKit/ASDisplayNode.mm
- AsyncDisplayKit/ASMultiplexImageNode.mm
- AsyncDisplayKit/ASNetworkImageNode.mm
- AsyncDisplayKit/ASTableView.h
- AsyncDisplayKit/ASTableView.mm
- AsyncDisplayKit/ASVideoNode.h
- AsyncDisplayKit/ASVideoNode.mm
- AsyncDisplayKit/Details/ASBasicImageDownloader.h
- AsyncDisplayKit/Details/ASBasicImageDownloader.mm
- AsyncDisplayKit/Details/ASImageProtocols.h
- AsyncDisplayKitTests/ASBasicImageDownloaderTests.m
- examples/Kittens/Sample/ViewController.m
I'll be going through and marking when each method was deprecated. Please hold off on reviewing until I say I'm ready.
> [API] Remove old deprecated methods.

- AsyncDisplayKit/ASTableView.h
@Adlai-Holler please take a look and suggest improvements :)
> [Documentation] Improve ASTableView docs.

- AsyncDisplayKit.xcodeproj/project.pbxproj
- AsyncDisplayKit/ASDisplayNode.mm
- AsyncDisplayKit/AsyncDisplayKit.h
- AsyncDisplayKit/Private/ASDisplayNode+AsyncDisplay.mm
- build.sh
- examples_extra/ASTableViewStressTest/Sample/ViewController.m
- examples_extra/ASTraitCollection/Sample/KittenNode.m
- examples_extra/BackgroundPropertySetting/Sample.xcodeproj/project.pbxproj
- examples_extra/BackgroundPropertySetting/Sample/DemoCellNode.swift
- examples_extra/CarthageBuildTest/CarthageExample/ViewController.m
- examples_extra/SynchronousKittens/Sample/ViewController.m
- examples_extra/VideoTableView/Sample/ViewController.m
> [Examples] Fix extra examples

- AsyncDisplayKit/Details/Transactions/_ASAsyncTransaction.mm
To be able to extract our powerful async transaction system with it's own tests and example usage patterns this PR removes the ASDK dependencies.
- Move to C++ 11 mutex
- Replace ASDK assert defines
> [ASAsyncTransaction] Remove dependencies for ASAssert and ASThread in the async transaction system

- AsyncDisplayKit/Details/_ASDisplayLayer.h
Good ideas from @appleguy and @Adlai-Holler turned into sweet, sweet code.
> Implement ivar on _ASDisplayLayer to speed up getting node from layer.

- AsyncDisplayKit/ASCollectionView.h
@Adlai-Holler Please take a look when you get a moment.
> [Documentation] Improve ASCollectionView docs.

- AsyncDisplayKit/ASTextNode.h
This is the documentation from NSTextContainer
> [Documentation] Add docs for exclusionPaths

- AsyncDisplayKit/ASNavigationController.h
- AsyncDisplayKit/ASTabBarController.h
- AsyncDisplayKit/ASVisibilityProtocols.h
And ASNavigationController, ASTabBarController
> [Documentation] Improve ASVisibility protocol documentation

- AsyncDisplayKit/ASCollectionNode.h
@Adlai-Holler Please take a look when you get a chance.
> [Documentation] Improve ASCollectionNode docs.

- AsyncDisplayKit/ASCollectionView.mm
Under iOS 10+, cells may be removed/re-added to the collection view without receiving prepareForReuse/applyLayoutAttributes, as an optimization for e.g. if the user is scrolling back and forth across a small set of items.
In this case, we have to fetch the layout attributes manually.
This may be possible under iOS < 10 but it has not been observed yet.
Tests pass locally for iPhone 6 9.3 and iPhone 7 10.0. 
I decided to stick with the basic policy that `ASCellNode.layoutAttributes` is nil for cells that are not onscreen. It's simple, and if we try to track layout attributes for offscreen cells we cannot do it reliably. We could only do it under iOS 10, and with no guarantee that the layout attributes for offscreen items will be reapplied by the system if the layout is invalidated.
> [ASCollectionView] Adjust layoutAttributes Logic for iOS 10

- AsyncDisplayKit/Layout/ASAbsoluteLayoutSpec.h
> [Layout] Fix ASAbsoluteLayoutSpec creation

- AsyncDisplayKit/Layout/ASDimension.h
- AsyncDisplayKit/Layout/ASDimension.mm
- AsyncDisplayKit/Layout/ASLayoutElement.h
- AsyncDisplayKit/Layout/ASLayoutElement.mm
- AsyncDisplayKitTests/ASLayoutElementStyleTests.m
We decided to rename `ASRelativeSize` to `ASLayoutSize`
> [Layout] Rename ASRelativeSize to ASLayoutSize

- AsyncDisplayKit/ASRunLoopQueue.mm
- AsyncDisplayKit/Details/ASDataController.mm
- AsyncDisplayKit/Details/ASRangeController.mm
- AsyncDisplayKit/Details/Transactions/_ASAsyncTransaction.mm
- Base/ASBaseDefines.h
- Base/ASLog.h
> [ASLog] Add new ASProfilingSignpost defines for System Trace flags.

- AsyncDisplayKit/ASCollectionView.mm
Please take a look @Adlai-Holler
> Scrollable direction is invalid until a relayout.

- AsyncDisplayKitTests/ASLayoutElementStyleTests.m
> Fix Test Method Name

- AsyncDisplayKit/ASVideoNode.mm
- AsyncDisplayKit/Details/Transactions/_ASAsyncTransaction.mm
@appleguy -  other uses of true in the code
> [Code Cleanup] Replace `true` values with `YES`

- AsyncDisplayKit/Layout/ASAbsoluteLayoutSpec.h
- AsyncDisplayKit/Layout/ASAbsoluteLayoutSpec.mm
Add ability for ASAbsoluteLayoutSpec to grow as far as possible or shrink to fit it's children
> [ASAbsoluteLayoutSpec] Add ASAbsoluteLayoutSpecSizing

- AsyncDisplayKit/ASCollectionView.mm
- AsyncDisplayKit/Details/ASCollectionViewFlowLayoutInspector.m
- AsyncDisplayKitTests/ASCollectionViewFlowLayoutInspectorTests.m
> Fix Uncalled Collection Delegate Methods

- AsyncDisplayKit/ASCollectionNode+Beta.h
- AsyncDisplayKit/ASCollectionNode.h
- AsyncDisplayKit/ASCollectionNode.mm
- AsyncDisplayKit/ASCollectionView.h
- AsyncDisplayKit/ASCollectionViewProtocols.h
- AsyncDisplayKit/ASDisplayNode+Deprecated.h
- AsyncDisplayKit/ASDisplayNode.h
- AsyncDisplayKit/ASTableNode.h
- AsyncDisplayKit/ASTableNode.mm
- AsyncDisplayKit/ASTableView.h
- AsyncDisplayKit/ASTableViewProtocols.h
- AsyncDisplayKit/ASTextNode.h
- AsyncDisplayKit/Details/ASCollectionViewFlowLayoutInspector.h
- AsyncDisplayKit/Details/ASIndexPath.m
- AsyncDisplayKit/Layout/ASDimension.h
- AsyncDisplayKit/Layout/ASLayoutElement.h
- AsyncDisplayKit/Layout/ASLayoutSpec.h
- AsyncDisplayKit/Layout/ASLayoutSpec.mm
- AsyncDisplayKit/Private/_AS-objc-internal.h
- Base/ASBaseDefines.h
> [2.0] add helpful deprecation messages

- AsyncDisplayKitTests/ASCollectionViewFlowLayoutInspectorTests.m
> Update Flow Layout Inspector Delegate Assertion Test for New Selector

- AsyncDisplayKit/ASLayoutElementInspectorCell.m
- AsyncDisplayKit/ASLayoutElementInspectorNode.h
- AsyncDisplayKit/ASLayoutElementInspectorNode.m
- AsyncDisplayKit/Layout/ASAbsoluteLayoutSpec.h
- examples/ASLayoutSpecPlayground/Sample/LayoutExampleNodes.m
- examples/ASLayoutSpecPlayground/Sample/PhotoPostNode.m
- examples/ASLayoutSpecPlayground/Sample/PlaygroundContainerNode.m
* Fixed crash when tapping descender.
* Fixed setting the item to inspect.
* Fixed button states in inspector node.
* Added sliders for spacingBefore, spacingAfter, ascender.
> [ASLayoutPlayground] Some fixes

- AsyncDisplayKitTests/ASTableViewTests.m
> [Testing] disable flaky table test

- AsyncDisplayKit/ASCollectionNode.h
- AsyncDisplayKit/ASPagerNode.m
- AsyncDisplayKit/Details/ASDelegateProxy.m
PR #2466 won't work without this.
> [ASPagerNode] Fix ASPagerNodeProxy to use collectionNode

- AsyncDisplayKit/ASCollectionView.mm
- AsyncDisplayKit/ASTableView.mm
I don't know of this causing any issues in practice right now, but let's nip it in the bud.
> Handle nil in selectItem&RowAtIndexPath: Methods

- AsyncDisplayKit/ASDisplayNode+Beta.h
- AsyncDisplayKit/ASDisplayNode+Subclasses.h
- AsyncDisplayKit/ASDisplayNode.mm
- AsyncDisplayKit/Details/ASEnvironment.h
- AsyncDisplayKit/Layout/ASAbsoluteLayoutSpec.mm
- AsyncDisplayKit/Layout/ASLayoutSpec+Subclasses.mm
- AsyncDisplayKit/Layout/ASLayoutSpec.mm
- AsyncDisplayKit/Layout/ASStackLayoutSpec.mm
- examples/ASDKgram/Sample/CommentsNode.m
- examples/ASDKgram/Sample/PhotoCellNode.m
Includes cleanup and refactoring around `calculateLayoutThatFits:`
Replaces #2387
> [Layout] Some cleanup work and better documentation

- AsyncDisplayKit/ASCollectionView.mm
Hopefully addresses #2471 
I'm actually not sure if even this is safe as layoutInspector could
be nil'd out *after* we check it here…
> [ASCollectionView] layoutInspector can be nil'd at anytime making flags unsafe

- AsyncDisplayKit/Layout/ASDimension.h
- AsyncDisplayKit/Layout/ASDimension.mm
Add `ASLayoutSizeAuto` to easier check if the `layoutSize` of an `ASLayoutElement` is set to auto width and height.
> [ASDimension] Add ASLayoutSizeAuto

- AsyncDisplayKit/ASCellNode+Internal.h
- AsyncDisplayKit/ASCellNode.h
- AsyncDisplayKit/ASCellNode.mm
- AsyncDisplayKit/Details/ASCollectionDataController.mm
- AsyncDisplayKit/Details/ASDataController.mm
- AsyncDisplayKit/Details/ASIndexedNodeContext.h
- AsyncDisplayKit/Details/ASIndexedNodeContext.mm
- AsyncDisplayKitTests/ASCollectionViewTests.mm
- examples/VerticalWithinHorizontalScrolling/Sample/RandomCoreGraphicsNode.m
refs #2447 
[ASCellNode]:
- Added indexPath property.
- Added a test case.
> [ASCellNode] Added indexPath property.

- AsyncDisplayKit/ASDisplayNode.mm
> [ASDisplayNode] Remove thread affinity for _displaysAsynchronously

- AsyncDisplayKit/ASCollectionNode.h
- AsyncDisplayKit/ASCollectionNode.mm
- AsyncDisplayKit/ASCollectionView.h
- AsyncDisplayKit/ASCollectionView.mm
- AsyncDisplayKit/ASTableNode.h
- AsyncDisplayKit/ASTableNode.mm
- AsyncDisplayKit/ASTableView.h
- AsyncDisplayKit/Details/ASCollectionInternal.h
- AsyncDisplayKit/Private/ASCollectionView+Undeprecated.h
- AsyncDisplayKit/Private/ASTableView+Undeprecated.h
> Finish Porting indexPath-Oriented Methods to ASTableNode/ASCollectionNode

- AsyncDisplayKit/Layout/ASAbsoluteLayoutSpec.mm
- AsyncDisplayKit/Layout/ASLayoutSpec.mm
- AsyncDisplayKit/Layout/ASOverlayLayoutSpec.mm
- AsyncDisplayKit/Private/ASLayoutTransition.h
I was debugging using asciiArtString but I found some inconsistencies and a crash. This PR fixes that, if it's possible @hannahmbanana could you check if this fixes #2500 since I don't have your test case?
> [Debugging] Fixed asciiArtString.

- AsyncDisplayKit/ASDisplayNode.mm
Also took out the check for isMain because ASPerformBlockOnMainThread performs the same check.
> [ASDisplayNode] Trampoline to main to make contents check safe

- AsyncDisplayKit/ASDisplayNode+Subclasses.h
- AsyncDisplayKit/ASDisplayNode.h
Let's add a copy and paste way of an `ASLayoutSpecBlock` to the documentation.
> [ASLayoutSpecBlock] I know we love blocks but cannot remember them ever

- AsyncDisplayKit.xcodeproj/project.pbxproj
- AsyncDisplayKit/ASPagerNode.h
- AsyncDisplayKit/ASPagerNode.m
- AsyncDisplayKitTests/ASPagerNodeTests.m
Decided to knock https://github.com/facebook/AsyncDisplayKit/issues/2528 out
@hannahmbanana
> Added -indexOfPageWithNode: method to ASPagerNode

- Base/ASBaseDefines.h
Add helper function we can improve the readability and stability of the code base a bit. E.g.:
```objc
if (child.layoutElementType == ASLayoutElementTypeLayoutSpec) {
[(ASLayoutSpec *)child setShouldVisualize:self.shouldVisualize];
}
```
```objc
ASLayoutSpec *layoutSpec = ASDynamicCast(child, ASLayoutSpec);
layoutSpec.shouldVisualize = self.shouldVisualize;
> [Stability] Add ASDynamicCast

- examples/LayoutSpecExamples-Swift/Podfile
- examples/LayoutSpecExamples-Swift/Sample.xcodeproj/project.pbxproj
- examples/LayoutSpecExamples-Swift/Sample.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- examples/LayoutSpecExamples-Swift/Sample.xcodeproj/xcshareddata/xcschemes/Sample.xcscheme
- examples/LayoutSpecExamples-Swift/Sample/AppDelegate.swift
- examples/LayoutSpecExamples-Swift/Sample/Base.lproj/LaunchScreen.storyboard
- examples/LayoutSpecExamples-Swift/Sample/Info.plist
- examples/LayoutSpecExamples-Swift/Sample/LayoutExampleNode+Layouts.swift
- examples/LayoutSpecExamples-Swift/Sample/LayoutExampleNode.swift
- examples/LayoutSpecExamples-Swift/Sample/LayoutExampleViewController.swift
- examples/LayoutSpecExamples-Swift/Sample/OverviewCellNode.swift
- examples/LayoutSpecExamples-Swift/Sample/OverviewViewController.swift
- examples/LayoutSpecExamples-Swift/Sample/Utilities.swift
> [LayoutSpecExamples] Added swift counterpart.

- AsyncDisplayKit/ASViewController.mm
- examples/ASViewController/Sample/DetailCellNode.m
- examples/ASViewController/Sample/DetailRootNode.m
- examples/ASViewController/Sample/ViewController.m
Some random ASViewController example improvements while looking into some changes around that.
> [Examples] ASViewController Improvements

- examples/ASCollectionView/Sample.xcodeproj/project.pbxproj
- examples/ASCollectionView/Sample/ViewController.m
- examples/ASDKLayoutTransition/Sample.xcodeproj/project.pbxproj
- examples/ASDKTube/Sample.xcodeproj/project.pbxproj
- examples/ASDKgram/Sample.xcodeproj/project.pbxproj
- examples/ASMapNode/Sample.xcodeproj/project.pbxproj
- examples/ASMapNode/Sample.xcworkspace/contents.xcworkspacedata
Related to issue #2569.
Enabled "Overriding Deprecated Objective-C Methods" in:
- ASCollectionView
- ASDKLayoutTransition
- ASDKTube
- ASDKgram
- ASMapNode
I can continue to do the rest of these if I'm on the right track.
> Update deprecations in ASCollectionView example, enable warnings

- AsyncDisplayKit/ASCollectionView.h
- AsyncDisplayKit/ASCollectionView.mm
- AsyncDisplayKit/ASPagerNode.m
- AsyncDisplayKit/ASTableView.h
- AsyncDisplayKit/ASTableView.mm
- AsyncDisplayKit/Private/ASCollectionView+Undeprecated.h
- AsyncDisplayKit/Private/ASTableView+Undeprecated.h
- AsyncDisplayKitTests/ASCollectionViewFlowLayoutInspectorTests.m
> [ASCollectionNode, ASTableNode] Deprecate asyncDelegate & asyncDataSource Properties 

- AsyncDisplayKit/ASCellNode.h
- AsyncDisplayKit/ASCellNode.mm
> [ASCellNode] implement a .viewController property

- AsyncDisplayKit/ASDisplayNode.mm
This is a fix for https://github.com/facebook/AsyncDisplayKit/issues/2620,
which is a followup to https://github.com/facebook/AsyncDisplayKit/pull/2610
This will ensure thread affinity is respected for .contents but still run
placeholderImage off-main when possible (node isn't loaded).
> [ASDisplayNode] Create placeholders off main when possible.

- AsyncDisplayKit/ASCollectionNode.mm
- AsyncDisplayKit/ASCollectionView.mm
- AsyncDisplayKit/ASDisplayNode+Deprecated.h
- AsyncDisplayKit/ASDisplayNode+Subclasses.h
- AsyncDisplayKit/ASDisplayNode.h
- AsyncDisplayKit/ASDisplayNode.mm
- AsyncDisplayKit/ASMapNode.mm
- AsyncDisplayKit/ASMultiplexImageNode.mm
- AsyncDisplayKit/ASNetworkImageNode.mm
- AsyncDisplayKit/ASTableNode.mm
- AsyncDisplayKit/ASTableView.mm
- AsyncDisplayKit/ASVideoNode.mm
- AsyncDisplayKit/Details/ASImageProtocols.h
- AsyncDisplayKit/Details/ASLayoutRangeType.h
- AsyncDisplayKit/Details/ASRangeController.h
- AsyncDisplayKit/Details/ASRangeController.mm
- AsyncDisplayKit/Private/ASDisplayNode+FrameworkPrivate.h
- AsyncDisplayKit/Private/ASDisplayNodeInternal.h
- AsyncDisplayKitTests/ASDisplayNodeTests.m
- AsyncDisplayKitTests/ASVideoNodeTests.m
> 2611 rename fetch data

- AsyncDisplayKit.podspec
Fixes image corruption issues: https://github.com/pinterest/PINRemoteImage/releases/tag/3.0.0-beta.7
> Update to beta 7 of PINRemoteImage

- AsyncDisplayKit/ASCellNode.mm
> [Layout] Just call super to change the size of the cell node that will resize itself instead of setting the frame directly

- examples/SocialAppLayout/Sample/PostNode.m
> [Examples] Some smaller SocialAppLayout example improvements

- examples/ASDKgram/Sample/PhotoCellNode.m
Updating the layoutSpecs structure to flat structure to make it more readable.
> [PhotoCellNode]Update formatting of layoutSpec to a flat structure.

- AsyncDisplayKit/Private/ASDisplayNodeInternal.h
> [ASDisplayNode] Add nullability declarations in ASDisplayNodeInternal.h

- AsyncDisplayKit/Details/ASWeakProxy.m
> Need to forward protocol support too.

- AsyncDisplayKit/ASDisplayNode.mm
- AsyncDisplayKit/ASImageNode.mm
- Comment out template code and fix another comment in ASDisplayNode
- Release instance lock a bit sooner and fix indentation in ASImageNode
> [ASDisplayNode][ASImageNode] Small refactorings

- AsyncDisplayKit/ASImageNode.mm
- Suggested by @appleguy in #2778
> [ASImageNode] Lock and unlock __instanceLock__ directly for a minor perf win

- AsyncDisplayKit/ASScrollNode.mm
> Support visibility events in ASScrollNode

- AsyncDisplayKit/ASDisplayNode.mm
> These messages must be called on main.

- AsyncDisplayKit/Details/ASThread.h
> Annotate the code that records mutex owner and level of ownership in ASThread

- AsyncDisplayKit/ASVideoNode.h
- AsyncDisplayKit/ASVideoPlayerNode.h
- AsyncDisplayKit/Private/ASDefaultPlaybackButton.h
This improves everything, especially the Swift import.
> Use NS_ENUM for All Enums

- AsyncDisplayKit/ASDisplayNode.mm
> [Layout Transition] Reverting back _finishOrCancelTransition that was mistakingly moved in a recent PR

- AsyncDisplayKit/Details/ASFlowLayoutController.mm
- AsyncDisplayKit/Details/ASRangeController.mm
- AsyncDisplayKitTests/ASCollectionViewTests.mm
> Range Controller Uses Last Scroll Direction, Defaults to Down/Right

- AsyncDisplayKit/ASCollectionView.mm
- AsyncDisplayKit/ASTableView.mm
> Obey UIView.areAnimationsEnabled By Default For Collection/Table Updates

- AsyncDisplayKit/ASVideoNode.h
- AsyncDisplayKit/ASVideoPlayerNode.h
> [ASVideoNode] Add missing strong attributes

- AsyncDisplayKit/ASCollectionView.mm
- AsyncDisplayKit/ASTableView.mm
- AsyncDisplayKit/Details/ASDataController.mm
This fixes #2843 which @rewandy raised in a more general way.
> ASDataController: Correctly Handle Nil IndexPath in nodeForIndexPath: Methods

- AsyncDisplayKitTests/ASPagerNodeTests.m
cc #2818 Will merge after CI passes.
> Disable Flaky Pager Test

- AsyncDisplayKit/ASEditableTextNode.h
This is merge damage caused in #2867. Will merge after CI passes.
> Remove Duplicate Declarations

- AsyncDisplayKitTests/ASCollectionViewTests.mm
- AsyncDisplayKitTests/ASNetworkImageNodeTests.m
> Disable Flaky ASNetworkImageNode Test

- AsyncDisplayKit.podspec
Linking this framework strongly is weighing down our library! @garrettmoon @appleguy
> Link AssetsLibrary Framework Weakly

- AsyncDisplayKitTests/ASCollectionViewTests.mm
> Disable Animated Batch Fetching Test

- AsyncDisplayKit/ASDisplayNode.mm
- AsyncDisplayKit/Private/ASDisplayNodeInternal.h
Mainly cleanup and restructuring of `ASDisplayNode` to sections that make sense in preparation for further restructuring.
> [ASDisplayNode] Overall code cleanup and restructuring

- AsyncDisplayKit.xcodeproj/project.pbxproj
- AsyncDisplayKit/ASDisplayNode+Subclasses.h
- AsyncDisplayKit/ASDisplayNode.mm
- AsyncDisplayKit/ASNodeController.h
- AsyncDisplayKit/ASNodeController.mm
- AsyncDisplayKit/AsyncDisplayKit.h
- AsyncDisplayKit/Private/ASDisplayNode+FrameworkPrivate.h
Paired programming with @appleguy. Example project - ASDKgram modified to use a node controller:
[ASDKgram-nodeController.zip](https://github.com/facebook/AsyncDisplayKit/files/736714/ASDKgram-nodeController.zip)
> [ASNodeController] First implementation of node controller class

- examples/ASDKgram/Sample/PhotoFeedSectionController.m
Item updates have to be submitted on the main thread. The majority of the work here – the fetching and diffing – still happens off-main.
> Fix Assertion Failure in ASDKgram IGListKit Batch Fetching

- AsyncDisplayKit/ASDisplayNode.mm
> [ASLayoutTransition] Remove taking a snapshot in the default layout transition code

- AsyncDisplayKit/Details/ASDataController.mm
- AsyncDisplayKit/Layout/ASDimension.h
> Avoid Measuring Cell Nodes with Empty Size Range

- AsyncDisplayKit/ASButtonNode.h
- AsyncDisplayKit/ASButtonNode.mm
- AsyncDisplayKit/ASControlNode.h
- AsyncDisplayKit/ASVideoPlayerNode.mm
- AsyncDisplayKit/Debug/ASLayoutElementInspectorCell.m
- AsyncDisplayKit/Debug/ASLayoutElementInspectorNode.m
> Replace ASControlState with UIControlState

- examples/ASDKLayoutTransition/Sample/ViewController.m
- examples/ASDKTube/Sample/Nodes/VideoContentCell.m
- examples/ASMapNode/Sample/MapHandlerNode.m
- examples/AsyncDisplayKitOverview/Sample/OverviewComponentsViewController.m
- examples/Videos/Sample/ViewController.m
- examples_extra/ASTraitCollection/Sample/OverrideViewController.m
- examples_extra/Multiplex/Sample/ScreenNode.m
I should have done this in #3005 😅 
Will merge after CI passes
> Update Examples to Use UIControlState

- build.sh
> Improve Build Script

- AsyncDisplayKit/Details/NSArray+Diffing.m
This avoids compiler warnings when using the strictest clang settings.
It also ensures that stack overflow can't occur even with the largest datasets.
> [NSArray+Diffing] Use heap-based allocation for array diff.

- AsyncDisplayKit.xcodeproj/project.pbxproj
- AsyncDisplayKit/ASDisplayNode+Beta.h
- AsyncDisplayKit/Details/_ASDisplayViewAccessiblity.mm
- AsyncDisplayKit/Private/ASDisplayNodeInternal.h
- AsyncDisplayKitTests/ASDisplayNodeTests.mm
- AsyncDisplayKitTests/ASDisplayNodeTestsHelper.h
- AsyncDisplayKitTests/ASSnapshotTestCase.h
- examples/ASDKgram/Sample/CommentsNode.h
- examples/ASDKgram/Sample/PhotoCellNode.m
- examples/SocialAppLayout-Inverted/Sample/PostNode.m
- examples/SocialAppLayout-Inverted/Sample/ViewController.m
- examples/SocialAppLayout/Sample/PostNode.m
- examples/SocialAppLayout/Sample/ViewController.m
> Deprecate shouldRasterizeDescendants

- AsyncDisplayKit/ASCellNode.h
- AsyncDisplayKit/ASCollectionView.mm
- AsyncDisplayKit/ASTableView.mm
> [ASCellNode] "selectedBackgroundView" property

- AsyncDisplayKit/ASPagerNode.h
Is this accurate? I'd left this as a comment on your PR but not sure you saw it before it merged.
> Hopefully this makes the comment clearer

- AsyncDisplayKit/ASDisplayNode.mm
> Clean Up actionForLayer:forKey:

- AsyncDisplayKit.xcodeproj/project.pbxproj
- AsyncDisplayKit/ASDisplayNode.mm
- AsyncDisplayKit/Layout/ASLayout.h
- AsyncDisplayKit/Layout/ASLayout.mm
- AsyncDisplayKit/Private/ASRectTable.h
- AsyncDisplayKit/Private/ASRectTable.m
- AsyncDisplayKit/_ASTransitionContext.m
- AsyncDisplayKitTests/ASRectTableTests.m
- examples/ASDKLayoutTransition/Sample/ViewController.m
This should be a very useful object for layouts (both UICV and node).
> Add ASRectTable, Use It

- AsyncDisplayKit/ASCollectionNode.h
- AsyncDisplayKit/ASCollectionView.mm
- AsyncDisplayKit/ASSupplementaryNodeSource.h
- AsyncDisplayKit/Private/ASIGListAdapterBasedDataSource.m
- examples/ASDKgram/Sample/PhotoFeedSectionController.m
It's silly that we've gone this long without updating the supplementary node API to use node blocks.
> Add collectionNode:nodeBlockForSupplementaryElementOfKind:atIndexPath:

- Source/Details/ASDataController.mm
- Source/Details/ASPhotosFrameworkImageRequest.h
- Source/Private/ASMutableElementMap.h
- Source/Private/ASMutableElementMap.m
Resolves #3096 
The repopulation business is wild! We need to be careful what are old section indexes and new section indexes.
> Fix Issues Repopulating Supplementary Elements

- Source/ASCellNode.mm
> Make ASCellNode Visibility Accesses Thread-Safe

- Source/ASControlNode.mm
- Source/ASDisplayNode.h
- Source/ASDisplayNode.mm
- Source/ASMultiplexImageNode.mm
- Source/ASTableNode.h
- Source/ASVideoNode.h
- Source/ASVideoPlayerNode.h
- Source/Debug/AsyncDisplayKit+Debug.h
- Source/Details/ASImageProtocols.h
- Source/Private/ASBatchFetching.h
- Source/Private/Layout/ASStackUnpositionedLayout.mm
> [Documentation] Fix `-Wdocumentation` warnings

- Source/Details/ASAbstractLayoutController.h
- Source/Details/ASCollectionViewLayoutController.mm
- Source/Details/ASLayoutController.h
- Source/Details/ASLayoutRangeType.h
- Source/Details/ASRangeController.mm
- Source/Details/ASTableLayoutController.m
Details in https://github.com/facebook/AsyncDisplayKit/issues/3082
> [ASRangeController] Optimize calls into UICollectionViewLayout via union rect technique.

- Source/ASCollectionView.mm
- Source/ASTableView.mm
- Source/Details/ASAbstractLayoutController.mm
- Source/Details/ASLayoutController.h
- Source/Details/ASRangeController.h
- Source/Details/ASRangeController.mm
- Source/Details/ASTableLayoutController.m
This API doesn't provide any value.
> Remove ASRangeController Viewport API

- Source/Private/Layout/ASStackUnpositionedLayout.mm
This will be helpful in many use cases, such as:
- When a node needs to force a layout pass on main before a view controller transition can start.
- Relayout all nodes.
- An upcoming async collection view flow layout, backed by a multi-line multi-threaded stack, will be able to determine constrained size of all cell nodes and drive their layout measurements on multiple threads.
Before:
After:
> [ASStackLayoutSpec] Utilize multiple threads if the stack algorithm runs on main

- Source/ASControlNode.mm
> [ASControlNode] ASControlNode should not receive any touches if it is disabled

- Source/ASDisplayNode.mm
- Before this commit:
- Bridged properties are accessed to construct a recursive description without considering thread affinity.
- We have multiple methods that does the same thing: generates a debug description.
- After this commit:
- Bridged properties are accessed without triggering thread affinity assertions.
- We have only one method that provides debug description of a node. It is then used to construct a recursive description.
Fixes #2911.
> [ASDisplayNode] Fix recursive description

- Source/ASDisplayNode.mm
Stack-trace:
```
[Thread 0] Crashed: com.apple.main-thread
SIGABRT ABORT 0x00000001890b41a8
0 libsystem_kernel.dylib         6594183592 semaphore_wait_trap + 8
1 libdispatch.dylib              6593052172 _dispatch_group_wait_slow + 304
> 2 Pinterest Enterprise           4302534640 -[ASDataController relayoutAllNodes] (ASDataController.mm:663)
3 Pinterest Enterprise           4302505120 -[ASCollectionView layer:didChangeBoundsWithOldValue:newValue:] (ASCollectionView.mm:2037)
4 Pinterest Enterprise           4302360456 -[_ASDisplayLayer setBounds:] (_ASDisplayLayer.mm:100)
5 QuartzCore                     6664819292 -[CALayer setFrame:] + 476
6 UIKit                          6710188308 -[UIView(Geometry) setFrame:] + 784
7 UIKit                          6710336464 -[UIScrollView setFrame:] …
```
> Fix deadlock while laying out subnodes

- Source/Details/ASRangeController.mm
> Range Controller: Skip Scheduling Range Update After Rendering, if Already in Full Range Mode
